### ISSUE TITLE
Did #10101 break things under PHP 8?

### ISSUE THREAD

**Issue by realkinetix** [friendica/friendica#10107]
Just refreshed my friendica after https://github.com/friendica/friendica/pull/10101 on my dev system which has PHP 8 on it, getting fatal errors now:
```
[31-Mar-2021 10:54:56 America/Vancouver] PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, int given in /home/friendica/friendica/src/Util/Logger/AbstractLogger.php:118
Stack trace:
#0 /home/friendica/friendica/src/Util/Logger/AbstractLogger.php(118): method_exists()
#1 /home/friendica/friendica/src/Util/Logger/StreamLogger.php(165): Friendica\Util\Logger\AbstractLogger->jsonEncodeArray()
#2 /home/friendica/friendica/src/Util/Logger/StreamLogger.php(141): Friendica\Util\Logger\StreamLogger->formatLog()
#3 /home/friendica/friendica/src/Util/Logger/AbstractLogger.php(173): Friendica\Util\Logger\StreamLogger->addEntry()
#4 /home/friendica/friendica/src/Core/Logger.php(222): Friendica\Util\Logger\AbstractLogger->notice()
#5 /home/friendica/friendica/src/Protocol/ActivityPub/Receiver.php(189): Friendica\Core\Logger::notice()
#6 /home/friendica/friendica/src/Protocol/ActivityPub/Receiver.php(107): Friendica\Protocol\ActivityPub\Receiver::processRelayPost()
#7 /home/friendica/friendica/src/Module/Inbox.php(69): Friendica\Protocol\ActivityPub\Receiver::processInbox()
#8 [internal function]: Friendica\Module\Inbox::rawContent()
#9 /home/friendica/friendica/src/App/Module.php(289): call_user_func()
#10 /home/friendica/friendica/src/App.php(556): Friendica\App\Module->run()
#11 /home/friendica/friendica/index.php(42): Friendica\App->runFrontend()
#12 {main}
  thrown in /home/friendica/friendica/src/Util/Logger/AbstractLogger.php on line 118
```

**Comment by realkinetix** [comment]
I rolled this system back to "git reset --hard 8fc6a58" and all is happy currently.

**Comment by MrPetovan** [comment]
Yep, we should check for the type of the value before calling `method_exists` on it.
