### ISSUE TITLE
Friendica 2021.04 not installable

### ISSUE THREAD

**Issue by narcisgarcia** [friendica/friendica#10226]
I'm following documented steps at https://friendi.ca/resources/installation/
But [2021.04 release announcement](https://github.com/friendica/friendica/releases) has no clear links to download both installable core and addons packages.
Then I've downloaded `friendica-full-2021.04.tar.gz` `friendica-addons-2021.04.tar.gz` from https://files.friendi.ca/
Once I've unpacked them at my website root directory, I visit it and page redirects to `/install`
> Not Found
> The requested URL was not found on this server.

**Comment by tobiasd** [comment]
Mmh... looks like github dropped most of the release notes copied into the form. Thanks for pointing that out! I'll fix it ASAP.

Could you please check that the `rewrite` engine of your server is activated and (if you are using Apache) that the `.htaccess-dist` file was copied to `.htaccess`.

**Comment by narcisgarcia** [comment]
Package extraction puts `.htaccess-dist` not `.htaccess`
It also puts `.php_cs.dist`

**Comment by narcisgarcia** [comment]
I've tried by renaming `.htaccess-dist` to `.htaccess` but critical errors are displayed on website:

 ```
 <b>Warning</b>:  file_exists(): open_basedir restriction in effect. File(/usr/bin/php) is not within the allowed path(s): (/srv/www/testing/site.tree/) in <b>/srv/www/testing/site.tree/public/src/Core/Installer.php</b> on line <b>252</b><br />
 <br />
 <b>Fatal error</b>:  Uncaught Friendica\Network\HTTPException\InternalServerErrorException: Friendica can't display this page at the moment, please contact the administrator. in /srv/www/testing/site.tree/public/src/Render/FriendicaSmartyEngine.php:57

 Stack trace:
 #0 /srv/www/testing/site.tree/public/src/Core/Renderer.php(170): Friendica\Render\FriendicaSmartyEngine-&gt;__construct('', Array)
 #1 /srv/www/testing/site.tree/public/src/Core/Renderer.php(111): Friendica\Core\Renderer::getTemplateEngine()
 #2 /srv/www/testing/site.tree/public/src/Module/Special/HTTPException.php(116): Friendica\Core\Renderer::getMarkupTemplate('exception.tpl')
 #3 /srv/www/testing/site.tree/public/src/App/Page.php(337): Friendica\Module\Special\HTTPException::content(Object(Friendica\Network\HTTPException\InternalServerErrorException))
 #4 /srv/www/testing/site.tree/public/src/App/Page.php(390): Friendica\App\Page-&gt;initContent(Object(Friendica\App\Mod in <b>/srv/www/testing/site.tree/public/src/Render/FriendicaSmartyEngine.php</b> on line <b>57</b><br />
 ```

**Comment by tobiasd** [comment]
Yes, so that your potentially customization of the `.htaccess` file is not over-written with an update. Hence the note in the installation instruction to copy the file to the new name.

If you are not using Apache as web-server, the rewrite rules need a different setup depending on the server you are using.

**Comment by tobiasd** [comment]
These

> open_basedir restriction

are new to me. It looks like your PHP configuration is such that you cannot access the PHP executable (`/usr/bin/php`). Is the CLI package of PHP installed on the server (php-cli on Debian based systems), maybe that's the reason. Alternatively you need to check the `open_basedir` settings of your server.

**Comment by narcisgarcia** [comment]
`php-cli` is already installed at this webserver. It runs Debian 10 (buster).
I can't modify `open_basedir` to give too open access to filesystem (`/usr/bin`)

**Comment by narcisgarcia** [comment]
src/Core/Installer.php on line 252 does a file_exists('/usr/bin/php') and no CMS will find that directory (/usr/bin) accessible in a normal web hosting.
Are there Fiendica versions tagged as "stable" or "LTS" versions?

**Comment by tobiasd** [comment]
Friendica needs to call PHP directly when spawning background jobs. Maybe @annando knows a setting that would allow the installation with your special configuration.

**Comment by tobiasd** [comment]
Is the directory `view/smarty3` in your Friendica base directory write-able by the webserver (likely www-data)?

**Comment by tomchiverton** [comment]
> Is the directory view/smarty3 in your Friendica base directory write-able by the webserver (likely www-data)?

There's nothing in https://friendi.ca/resources/installation/ about setting ownership of any folders. 

Is there a list somewhere of what needs to be writable by the web server process ?

**Comment by MrPetovan** [comment]
@tomchiverton No, only the `view/smarty3` folder by default, and the path to your Friendica log that you set in the Administration, and the storage path if you switch from the database storage to the filesystem storage.

**Comment by urbalazs** [comment]
@narcisgarcia Friendica 2021.04 is not supported anymore. Do you have the same issue with the newer versions? If not, you can close this issue.
