### ISSUE TITLE
console command "autoinstall": [Error] Friendica can't display this page at the moment

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#10392]
### Bug Description

Using the `autoinstall` command of the console results in an error and the installation not being performed.

### Steps to Reproduce

1.  install the requirements of Friendica
2.  run `bin/console autoinstall -H localhost -p 3306 -d friendica -U friendica -P PASSWORD -U localhost -L de -t 'Europe/Berlin'`
3.  get error

Actual Result:

```
$> bin/console autoinstall -v -H localhost -p 3306 -d friendica -U friendica -P PASSWORD -U localhost -L de -t 'Europe/Berlin'
PHP Warning:  A non-numeric value encountered in /var/www/friendica/vendor/asika/simple-console/src/Console.php on line 413
Executable: /var/www/friendica/bin/console.php
Arguments: array (
  0 => 'autoinstall',
)
Options: array (
  'v' => 1,
  'H' => 'localhost',
  'p' => '3306',
  'd' => 'friendica',
  'U' => 'localhost',
  'P' => 'PASSWORD',
  'L' => 'de',
  't' => 'Europe/Berlin',
)
Command: autoinstall
Initializing setup...
 Complete!

Checking environment...
 NOTICE: Not checking .htaccess/URL-Rewrite during CLI installation.

 Complete!

Creating config file...
PHP Notice:  Undefined index: host in /var/www/friendica/src/App/BaseURL.php on line 239
[Error] Friendica can't display this page at the moment, please contact the administrator.
[Backtrace]:
#0 /var/www/friendica/src/Core/Renderer.php(111): Friendica\Core\Renderer::getTemplateEngine()
#1 /var/www/friendica/src/Core/Installer.php(157): Friendica\Core\Renderer::getMarkupTemplate('local.config.tp...')
#2 /var/www/friendica/src/Console/AutomaticInstallation.php(203): Friendica\Core\Installer->createConfig(Object(Friendica\Core\Config\Cache))
#3 /var/www/friendica/vendor/asika/simple-console/src/Console.php(108): Friendica\Console\AutomaticInstallation->doExecute()
#4 /var/www/friendica/src/Core/Console.php(155): Asika\SimpleConsole\Console->execute()
#5 /var/www/friendica/vendor/asika/simple-console/src/Console.php(108): Friendica\Core\Console->doExecute()
#6 /var/www/friendica/bin/console.php(36): Asika\SimpleConsole\Console->execute()
#7 {main}

```

Expected Result:

Have the `autoinstall` complete the installation of Friendica and writing the configuration file.

### Platform Info

Friendica Version: 2021.04 and 2021.06-rc

Friendica Source:  git

PHP version: PHP 7.3.27-1~deb10u1

SQL version: Ver 15.1 Distrib 10.3.27-MariaDB

**Comment by tobiasd** [comment]
Found that this error is also displayed with

> bin/console user add NAME

but the command works anyway. Only the `autoinstall` really fails ATM and does not create the configuration file.

**Comment by tobiasd** [comment]
Just tested the autoinstall, but still getting the error

```
PHP Notice:  Undefined index: host in /var/www/friendica/src/App/BaseURL.php on line 239
[Error] Friendica can't display this page at the moment, please contact the administrator.
[Backtrace]:
#0 /var/www/friendica/src/Core/Renderer.php(111): Friendica\Core\Renderer::getTemplateEngine()
#1 /var/www/friendica/src/Core/Installer.php(157): Friendica\Core\Renderer::getMarkupTemplate('local.config.tp...')
#2 /var/www/friendica/src/Console/AutomaticInstallation.php(202): Friendica\Core\Installer->createConfig(Object(Friendica\Core\Config\Cache))
#3 /var/www/friendica/vendor/asika/simple-console/src/Console.php(108): Friendica\Console\AutomaticInstallation->doExecute()
#4 /var/www/friendica/src/Core/Console.php(151): Asika\SimpleConsole\Console->execute()
#5 /var/www/friendica/vendor/asika/simple-console/src/Console.php(108): Friendica\Core\Console->doExecute()
#6 /var/www/friendica/bin/console.php(36): Asika\SimpleConsole\Console->execute()
#7 {main}
```
I'm going to verify that test and report back!

Also the `-U` parameter is doubled, but for this I'll create a PR myself. #10423

**Comment by tobiasd** [comment]
Ok, seems to have been caused by the doubled U or somehow else :-?
