### ISSUE TITLE
Regression: User's own photos not displayed in users's own posts

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#10443]
- [YES] I have searched open and closed issues for duplicates

### Bug Description

One of the latest PRs that touched the photo/image handling introduced a regression. The user's own photos have vanished from the own posts.

When I look at my own stream https://libranet.de/profile/alfred my own posts with uploaded images/photos are not showing any photos anymore.

Example: https://libranet.de/display/0b6b25a8-1760-c127-9074-377240030776 (went back to an earlier commit, so you see the photo here again)

**Browser console:**

```
Internal Server Error

Invalid photo with id .

#0 [internal function]: Friendica\Module\Photo::rawContent()
#1 /var/www/html/libranet/src/App/Module.php(333): call_user_func()
#2 /var/www/html/libranet/src/App.php(562): Friendica\App\Module->run()
#3 /var/www/html/libranet/index.php(42): Friendica\App->runFrontend()
#4 {main}
```

From Friendica's log:

```
2021-06-28T18:06:09Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"50432e","process_id":6505}
2021-06-28T18:06:09Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"985dcb","process_id":4560}
2021-06-28T18:06:38Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"4bdbbe","process_id":10274}
2021-06-28T18:06:38Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"452259","process_id":55749}
2021-06-28T18:06:46Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"2df9b3","process_id":3924345}
2021-06-28T18:06:46Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"1fe247","process_id":16246}
2021-06-28T18:06:46Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"2cd901","process_id":29490}
2021-06-28T18:06:47Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"72d65d","process_id":4183834}
2021-06-28T18:07:08Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"91e127","process_id":619}
2021-06-28T18:08:59Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"cbba59","process_id":8801}
2021-06-28T18:09:00Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"c6b824","process_id":619}
2021-06-28T18:09:01Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"1302df","process_id":4020365}
2021-06-28T18:09:02Z index [WARNING]: Invalid photo with id . [] - {"file":"Photo.php","line":103,"function":"rawContent","uid":"ff70f5","process_id":49639}
```

### Steps to Reproduce

1.  look for your own posts with uploaded photos
2.  become aware that the photos have vanished
3.  -

Actual Result:

Own uploaded photos are not displayed in your own posts anymore.

Expected Result:

The photos should be displayed.

### Screenshots

![image](https://user-images.githubusercontent.com/3656054/123682737-ab1ec780-d84b-11eb-87df-0cd821153b4e.png)
It's difficult to make a screenshot of something that isn't there. :-)

### Platform Info

Friendica Version:
2021.06-rc 

Friendica Source: 
git

PHP version:
7.4

SQL version:
10.3 MariaDB

**Comment by AlfredSK** [comment]
I had to `git checkout 005ba8c38` to get the photos back. (and then to 56812ce24 to avoid fatal errors)

![image](https://user-images.githubusercontent.com/3656054/123685905-79a7fb00-d84f-11eb-8017-2e48ea79030a.png)

**Comment by annando** [comment]
@AlfredSK don't be so impatient. :grin:

**Comment by AlfredSK** [comment]
@annando Well, I have to satisfy my users. :-) Didn't expect the fix so quickly.

**Comment by annando** [comment]
Okay, should I revert the PR or pleed @MrPetovan to not accept it to soon? :grinning:

**Comment by AlfredSK** [comment]
I can wait. I went back to an earlier commit where it is working.
