### ISSUE TITLE
Profiles broken and no posts/conversations and private messages

### ISSUE THREAD

**Issue by Stratus3D** [friendica/friendica#10510]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Sometime within the last 2-3 weeks my something on my Friendica node broke or got changed. I am not sure what happened because I wasn't active on my server during that time, and got notified by someone else that things were broken. I had been taking regular database backups so today I tried restoring to a previous backup from 3 weeks ago. The backup didn't fix the issue. Here is the stacktrace when trying to view any profile on my server:

```
Exception thrown in /home/stratus_jason/apps/friendica_kjv_online/src/Module/Profile/Status.php:57
Stack trace:
#0 ~/apps/friendica_kjv_online/src/Module/Profile/Index.php(44): Friendica\Module\Profile\Status::content()
#1 [internal function]: Friendica\Module\Profile\Index::content()
#2 ~/apps/friendica_kjv_online/src/App/Page.php(332): call_user_func()
#3 ~/apps/friendica_kjv_online/src/App/Page.php(389): Friendica\App\Page->initContent()
#4 ~/apps/friendica_kjv_online/src/App.php(562): Friendica\App\Page->run()
#5 ~/apps/friendica_kjv_online/index.php(40): Friendica\App->runFrontend()
#6 {main}
```

Note: redacted my home directory to `~` for reasons.

### Steps to Reproduce

1.  Something happened. I don't have any idea what changed. I don't believe the hosting service has changed anything. I also don't see any signs of my server being compromised, but I haven't looked closely. No manual upgrades of Friendica were done. I also verified `/usr/bin/php bin/worker.php` is being run by cron every 5 minutes.

Actual Result:

Profiles broken and no posts/conversations and private messages. Because posts/conversations and private messages aren't working notifications aren't being generated for anything either. On private messages page, old messages and conversations are visible but new ones are not.

Expected Result:

Profiles, posts/conversations and private messages should work as before.

### Screenshots

Here is a screenshot of what I see in the UI when trying to view any profile on my server:

![Screenshot from 2021-07-17 09-18-55](https://user-images.githubusercontent.com/1520926/126039581-ab835b04-a616-4a22-8ec6-b364dce0862b.png)

### Platform Info

Friendica Version:

```
This is Friendica, version 2021.01 that is running at the web location https://social.kjv.online.
The database version is 1384/1384, the post update version is 1383/1384.
...
No installed addons/apps
```

Friendica Source: 

PHP version:

```
PHP 7.3.29 (cli) (built: Jun 29 2021 09:30:31) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.29, Copyright (c) 1999-2018, by Zend Technologies
```

SQL version: `5.5.5-10.3.25-MariaDB through PHP extension MySQLi`

**Comment by annando** [comment]
The exception is thrown because the system doesn't find the requested user. So possibly most likely something in the database has got issues.

Please execute `bin/console dbstructure update -f` in the command line? Does this return something?

Then please have a look for entries with "DB Error" in the friendica log file.

**Comment by Stratus3D** [comment]
`bin/console dbstructure update -f` outputs nothing and exits with a status code of 0. I don't see any obvious DB errors int he logs. I will keep looking though.
