### ISSUE TITLE
Admin page crashed for no Storage Backend by default.

### ISSUE THREAD

**Issue by joseph-cheung** [friendica/friendica#10558]
on admin/storage

```
Fatal error: Uncaught Error: Class name must be a valid object or a string in /www/wwwroot/yourdomain/src/Module/Admin/Storage.php:119 Stack trace: #0 [internal function]: Friendica\Module\Admin\Storage::content(Array) #1 /www/wwwroot/yourdomain/src/App/Page.php(333): call_user_func(Array, Array) #2 /www/wwwroot/yourdomain/src/App/Page.php(390): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode)) #3 /www/wwwroot/yourdomain/src/App.php(662): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Util\Profiler), Object(Friendica\Core\Config\JitConfig), Object(Friendica\Core\PConfig\JitPConfig)) #4 /www/wwwroot/yourdomain/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), 1627552004.3537) #5 {main} thrown in /www/wwwroot/yourdomain/src/Module/Admin/Storage.php on line 119 
```

`				'active' => $name === $current_storage_backend::getName(),
`  
It seems that there is no default value for current_storage_backend. 
Happened on current develop version.

**Comment by joseph-cheung** [comment]
The default value is ‘storage’. Not a valid path.

**Comment by annando** [comment]
Pinging @nupplaphil
