### ISSUE TITLE
PHP Fatal error:  Uncaught ValueError: DOMDocument::loadXML(): Argument #1

### ISSUE THREAD

**Issue by Pavvlik** [friendica/friendica#10791]
```
 cd /html/friendica && sudo -u www-data
        /usr/bin/php   -f bin/worker.php

PHP Fatal error:  Uncaught ValueError: DOMDocument::loadXML(): Argument #1
+($source) must not be empty in
+/.../html/friendica/src/Protocol/Feed.php:86
Stack trace:
#0 /.../html/friendica/src/Protocol/Feed.php(86): DOMDocument->loadXML()
#1 /.../html/friendica/src/Network/Probe.php(1871):
+Friendica\Protocol\Feed::import()
#2 /html/friendica/src/Network/Probe.php(726):
+Friendica\Network\Probe::feed()
#3 /html/friendica/src/Network/Probe.php(357):
+Friendica\Network\Probe::detect()
#4 /html/friendica/src/Model/Contact.php(2046):
+Friendica\Network\Probe::uri()
#5 /html/friendica/src/Worker/UpdateContact.php(35):
```

### Platform Info

Friendica Version:
Friendica 'Siberian Iris' 2021.09 - 1434.

Friendica Source: 
zip file
PHP version:
PHP Version 7.4.24
SQL version:
Server version: 10.5.11-MariaDB-1 Debian 11

**Comment by tobiasd** [comment]
part of #10756

**Comment by MrPetovan** [comment]
@Pavvlik Please update to the latest `develop` and report back if the same errors show up.

**Comment by Pavvlik** [comment]
> @Pavvlik Please update to the latest `develop` and report back if the same errors show up.



I think the errors have disappeared ! Thanks for the quick response.
