### ISSUE TITLE
Photos uploaded with /api/friendica/photo/create result in duplicate postings

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#10990]
- [ X ] I have searched open and closed issues for duplicates

### Bug Description

About month or so some of my contacts also using Friendica started to complain about receiving duplicate posts with my photos. It turns out that when Friendica API is used to upload photos (to use them in the post), separate statuses are created for uploads. So friends receive photo status first and then the post containing the photos. Needless to say it annoys them greatly :)

### Steps to Reproduce

1.  Upload an image using `/api/friendica/photo/create`
2.  Observe photo statuses appearing in your friends' feeds

Actual Result:

See screenshot.

Expected Result:

Photo statuses shouldn't be created by default for every image. Maybe there should be opt-in parameter for API.

### Screenshots

![Screenshot from 2021-11-17 11-50-38](https://user-images.githubusercontent.com/35988439/142168427-91dff8c2-c7e8-4154-a1c0-53f35199790c.png)

### Platform Info

Friendica Version:

Latest develop but appeared earlier (roughly after the latest stable?)

**Comment by SpcCw** [comment]
Update: currently the endpoint doesn't work at all: returns code 500 and empty response.

Same is now happening with #11023

**Comment by SpcCw** [comment]
@MrPetovan - this one however still ends up with 500 code and empty response on `2021.12-rc`

Snippet from Friendica log:
```
2021-11-29T20:49:25Z index [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Factory\Api\Friendica\Activities::createFromUriId() must be of the type int, null given, called in /usr/share/nginx/friends/include/api.php on line 527" at /usr/share/nginx/friends/src/Factory/Api/Friendica/Activities.php line 53 {"exception":"TypeError: Argument 1 passed to Friendica\\Factory\\Api\\Friendica\\Activities::createFromUriId() must be of the type int, null given, called in /usr/share/nginx/friends/include/api.php on line 527 and defined in /usr/share/nginx/friends/src/Factory/Api/Friendica/Activities.php:53\nStack trace:\n#0 /usr/share/nginx/friends/include/api.php(527): Friendica\\Factory\\Api\\Friendica\\Activities->createFromUriId()\n#1 /usr/share/nginx/friends/include/api.php(388): prepare_photo_data()\n#2 /usr/share/nginx/friends/include/api.php(1376): save_media_to_database()\n#3 /usr/share/nginx/friends/include/api.php(101): api_fr_photo_create_update()\n#4 /usr/share/nginx/friends/src/Module/Api/Friendica/Index.php(47): api_call()\n#5 /usr/share/nginx/friends/src/BaseModule.php(228): Friendica\\Module\\Api\\Friendica\\Index->rawContent()\n#6 /usr/share/nginx/friends/src/App.php(706): Friendica\\BaseModule->run()\n#7 /usr/share/nginx/friends/index.php(44): Friendica\\App->runFrontend()\n#8 {main}"} - {"file":null,"line":null,"function":null,"uid":"b14307","process_id":5241}
```
Nginx error log:
```
2021/11/29 23:49:25 [error] 29987#29987: *1633217 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: uri-id in /usr/share/nginx/friends/include/api.php on line 527" while reading response header from upstream, client: [...], server: friends.deko.cloud, request: "POST /api/friendica/photo/create.json HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "friends.deko.cloud"
```
Addressed in #11048

**Comment by MrPetovan** [comment]
Thanks, this is really helpful.

**Comment by tobiasd** [comment]
During photo upload, there is an option to "not post an additional status update" (which contains the image only). I'm not sure how this option is handled by the API call, but the 2nd posting only containing the image looks like that additional status update.

**Comment by SpcCw** [comment]
@MrPetovan - thanks, now the endpoint works again and the issue with it sending "photo statuses" still remains.

@tobiasd - yes, it is that. If I upload a photo via web interface I see this checkbox and if I uncheck it then exactly the same happens. However by default I see it checked (i.e. photo statuses aren't created) and I have to explicitly clear it.

This makes sense for the web frontend but not for API - because API client might upload multiple photos to use them in the post, maybe even scheduled post which is supposed to come online later. And then your Friendica contacts are immediately bombarded with these separate "photo statuses". Imagine creating a post with a story and ten images in it :)

This wasn't the case before. In previous versions API didn't trigger creation of these statuses so it was likely introduced during current development.

**Comment by MrPetovan** [comment]
Thanks you for your tests, it should be easy to pinpoint now.

**Comment by SpcCw** [comment]
That did it! Big thanks!
