### ISSUE TITLE
API "api/friendica/photo/delete" doesn't work

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#11023]
- [ Y ] I have searched open and closed issues for duplicates

### Bug Description

`api/friendica/photo/delete` fails to delete photos.

### Steps to Reproduce

1.  Upload a photo
2.  Issue a `api/friendica/photo/delete` to delete it.

E.g. `curl -s -X POST 'https://friends.deko.cloud/api/friendica/photo/delete.json?photo_id=1461045591619d3c028bc7f129095950' -u usr:pass`

Actual Result:

The photo isn't deleted. Error "no photo id" is returned despite it was passed.
API returns HTML even if called as `api/friendica/photo/delete.json`:
```
<html>
	<head>
		<title>Bad Request</title>
	</head>
	<body>
		<h1>Bad Request</h1>
		<p>no photo_id specified</p>
		</body>
</html>
```

Expected Result:

The photo is deleted.

Friendica Version: current develop.

**Comment by SpcCw** [comment]
@MrPetovan - still doesn't work for me, now it returns code 500 and empty response..

Same started to happpen with #10990

Update: also passing some non-existent or malformed id (or passing none at all) doesn't change anything (i.e. there is no error returned).

**Comment by MrPetovan** [comment]
Thank you for the follow-up, the unit tests involving this API endpoint passed so I assumed it would work in a production setup.

**Comment by MrPetovan** [comment]
500 error means PHP left a message, do you have anything in your Friendica/Web server/PHP interpreter logs?

**Comment by SpcCw** [comment]
> 500 error means PHP left a message

It is weird, when I get code 500 on `photo/create` I get the following in the nginx error log:
```
2021/11/29 19:15:04 [error] 29987#29987: *1605501 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: uri-id in /usr/share/nginx/friends/include/api.php on line 527" while reading response header from upstream, client: [...], server: friends.deko.cloud, request: "POST /api/friendica/photo/create.json HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "friends.deko.cloud"
```
However when I try `photo/delete` I get nothing in the same log even though I get code 500.

Where else should I look? `/var/log/php7.4-fpm.log` has nothing except the usual worker start/stop stuff. Should I capture a piece of Friendica log?

**Comment by MrPetovan** [comment]
We started logging some exception errors in the Friendica log itself, please check over there if you activated it. Otherwise, please activate it with the log level Warning.

**Comment by SpcCw** [comment]
Here it is (two calls):
```
2021-11-29T16:41:28Z index [ERROR]: Uncaught Exception Error: "Call to a member function isLoggedIn() on null" at /usr/share/nginx/friends/src/Module/BaseApi.php line 94 {"exception":"Error: Call to a member function isLoggedIn() on null in /usr/share/nginx/friends/src/Module/BaseApi.php:94\nStack trace:\n#0 /usr/share/nginx/friends/src/BaseModule.php(218): Friendica\\Module\\BaseApi->post()\n#1 /usr/share/nginx/friends/src/App.php(706): Friendica\\BaseModule->run()\n#2 /usr/share/nginx/friends/index.php(44): Friendica\\App->runFrontend()\n#3 {main}"} - {"file":null,"line":null,"function":null,"uid":"a49c0a","process_id":1487}

...

2021-11-29T16:43:10Z index [ERROR]: Uncaught Exception Error: "Call to a member function isLoggedIn() on null" at /usr/share/nginx/friends/src/Module/BaseApi.php line 94 {"exception":"Error: Call to a member function isLoggedIn() on null in /usr/share/nginx/friends/src/Module/BaseApi.php:94\nStack trace:\n#0 /usr/share/nginx/friends/src/BaseModule.php(218): Friendica\\Module\\BaseApi->post()\n#1 /usr/share/nginx/friends/src/App.php(706): Friendica\\BaseModule->run()\n#2 /usr/share/nginx/friends/index.php(44): Friendica\\App->runFrontend()\n#3 {main}"} - {"file":null,"line":null,"function":null,"uid":"c7b1fe","process_id":29306}
```

**Comment by MrPetovan** [comment]
Thanks, it's a familiar error that should have been fixed with #11037 but I apparently didn't include the correct commit from #11044, I'll submit a follow-up PR.

**Comment by MrPetovan** [comment]
Ah, never mind, you need to switch to the `2021.12-rc` branch, the `develop` branch won't be updated with fixes until the upcoming release.

**Comment by SpcCw** [comment]
So it was me who got lost in the branches.

Yes, on `2021.12-rc` deletion works.
