### ISSUE TITLE
Installation problems / Hostinger / Litespeed / htacccess / php 

### ISSUE THREAD

**Issue by Andy3142** [friendica/friendica#11039]
I've never installed anything more than Wordpress and I'm struggling to install Friendica.  I couldn't do it at all with my Wordpress hosts, so now I'm trying Hostinger.  The error with Hostinger comes when I finish uploading, and put the URL into my browser for the first time. Instead of the greeting / setup page, I get the error (4) below.

Now my goal is NOT necessarily to analyse and solve this particular error. My goal is to make Friendica work. For example, I could change to a different host. So before I get to the error message at all, a few questions:

(1) Hostinger use Litespeed not Apache. Hostinger tell me that Litespeed will use .htaccess from Apache unchanged, but this page https://friendi.ca/resources/requirements/ seems to be saying that litespeed needs a different or changed config file.  What should I do (if anything) with the .htaccess in the install, or any other config file, to run Litespeed please? [The htaccess is correctly renamed!]

(2) Does anyone reading this host Friendica on Hostinger, and would be kind enough to share with me the versions of PHP , Friendica etc etc that they kinow for sure work together?

(3) Equally does anyone reading this host Friendica on a UK (best) or English-language EU hosting company and would share with me as per (2) and I'll simply change host to ensure compatibility.

(4) Finally the error I get is this. PHP version is 7.4.25   

[Hostinger PHP 7.4.25 - phpinfo().pdf](https://github.com/friendica/friendica/files/7612625/Hostinger.PHP.7.4.25.-.phpinfo.pdf)

But to repeat, my goal is not to solve this. If it's easier to change hosts, I'll do that.
```
Fatal error: Uncaught Error: Call to a member function autocommit() on null in src/Database/Database.php:1086
Stack trace:
#0 src/Core/Lock/DatabaseLock.php(64): Friendica\Database\Database->lock('locks')
#1 src/App/Router.php(309): Friendica\Core\Lock\DatabaseLock->acquire('getCachedDispat...', 0)
#2 src/App/Router.php(231): Friendica\App\Router->getCachedDispatchData()
#3 src/App/Module.php(192): Friendica\App\Router->getModuleClass('/install')
#4 src/App.php(699): Friendica\App\Module->determineClass(Object(Friendica\App\Arguments), Object(Friendica\App\Router), Object(Friendica\Core\Config\JitConfig))
#5 / in src/Database/Database.php on line 1086
```
Many thanks
Andy
Bristol UK

**Comment by Andy3142** [comment]
OK, I solved this. I started again, in the main URL not a subdomain, and telnetted in and  gitted the files instead of uploading the tarball via Windows. It still went through some convolutions. "Vendor name not found" worried me but it fixed itself beautifully and is now running OK.

For the record, Hostinger works as a host. .htaccess needs renaming, but has no compatibility issues and does not need editing.
