### ISSUE TITLE
api/friendica/photo/create fails to upload images

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#11163]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description
After very recent updates (two weeks ago max) this API endpoint no longer works throwing code 500.

### Steps to Reproduce

1.  use `api/friendica/photo/create` to upload an image.

E.g. the following Python code used to work:

```
myfile = {"media": ("filename", open('/tmp/tmpimg', "rb"))}
r = requests.post('https://friends.deko.cloud/api/friendica/photo/create', files=myfile, data={'album':'Temp'}, auth=HTTPBasicAuth(usr, pss))
```

Actual Result:

The API returns code 500 and the following response:

`b''`

Expected Result:

JSON with the details of newly uploaded image.

### Platform Info

Friendica Version:

Current RC (2022.01.17, git)

**Comment by MrPetovan** [comment]
Do you have access to server logs by any chance? A 500 error would leave a significant trace in the PHP log.

**Comment by SpcCw** [comment]
It has the following error at the moment of the upload:

```
2022-01-17T16:02:49Z index [ERROR]: Uncaught Exception TypeError: "Argument 8 passed to Friendica\Model\Photo::upload() must be of the type string, null given, called in src/Module/Api/Friendica/Photo/Create.php on line 87" at src/Model/Photo.php line 981 {"exception":"TypeError: Argument 8 passed to Friendica\\Model\\Photo::upload() must be of the type string, null given, called in src/Module/Api/Friendica/Photo/Create.php on line 87 and defined in src/Model/Photo.php:981\nStack trace:\n#0 src/Module/Api/Friendica/Photo/Create.php(87): Friendica\\Model\\Photo::upload()\n#1 src/BaseModule.php(223): Friendica\\Module\\Api\\Friendica\\Photo\\Create->post()\n#2 src/Module/BaseApi.php(99): Friendica\\BaseModule->run()\n#3 src/App.php(711): Friendica\\Module\\BaseApi->run()\n#4 index.php(44): Friendica\\App->runFrontend()\n#5 {main}"} - {"file":null,"line":null,"function":null,"uid":"d7f2da","process_id":3991052}
```

Do I need to capture it on deeper level?

**Comment by MrPetovan** [comment]
No, it should be enough, thanks!

**Comment by annando** [comment]
I guess that I'm the to blame here 😬 
This also answers my unasked question if anyone is using these endpoints at all 😁

**Comment by MrPetovan** [comment]
I have a fix ready I haven't had a chance to submit yet.
