### ISSUE TITLE
Unfollowing twitter contacts ends up in a 500 page

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11281]
Since the last gitpull on dev, unfollowing twitter contacts ends up in a 500 page

**Comment by MrPetovan** [comment]
Thanks, I'll look into it.

**Comment by MrPetovan** [comment]
Have you updated your addons as well?

**Comment by ghost** [comment]
> Have you updated your addons as well?

Im updating the addons on every gitpul

**Comment by MrPetovan** [comment]
Do you have more details of the error in your web server log?

**Comment by ghost** [comment]
```
2022-02-24T23:17:32Z index [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Model\Contact::unfollow() must be of the type int, array given, called in /friendica/mod/unfollow.php on line 142" at /friendica/src/Model/Contact.php line 2585
{"exception":"TypeError: Argument 1 passed to Friendica\\Model\\Contact::unfollow() must be of the type int, array given, called in /friendica/mod/unfollow.php on line 142 and defined in /friendica/src/Model/Contact.php:2585
Stack trace:
#0 /friendica/mod/unfollow.php(142): Friendica\\Model\\Contact::unfollow()
#1 /friendica/mod/unfollow.php(88): unfollow_process()
#2 /friendica/src/LegacyModule.php(96): unfollow_content()
#3 /friendica/src/LegacyModule.php(73): Friendica\\LegacyModule->runModuleFunction()
#4 /friendica/src/BaseModule.php(239): Friendica\\LegacyModule->content()
#5 /friendica/src/App.php(711): Friendica\\BaseModule->run()
#6 /friendica/index.php(44): Friendica\\App->runFrontend()
#7 {main}"} - {"file":null,"line":null,"function":null,"uid":"3df571","process_id":1034}
```

**Comment by MrPetovan** [comment]
Thanks!

**Comment by ghost** [comment]
I also found this, don't know if it's related.

```
2022-02-24T23:21:14Z worker [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'preview' at row 1","callstack":"Media::insert, twitter_store_attachments, twitter_createpost, twitter_fetchhometimeline, twitter_sync_run, Worker::execFunction, Worker::execute, Worker::processQueue","params":"INSERT INTO `post-media` (`uri-id`, `type`, `url`, `name`, `mimetype`, `size`, `preview`, `preview-height`, `preview-width`, `description`, `author-url`, `author-name`, `author-image`, `publisher-url`, `publisher-name`, `publisher-image`) VALUES (3690205, 17, 'https://www.theblaze.com/shows/you-are-here/cdc-hides-covid-information', 'The CDC finally admits what​​ we\\'ve known all along about COVID-19', 'text/html; charset=utf-8', 432878, 'https://assets.rebelmouse.io/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yOTQyMDUyMS9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTcwNDk1MTcyN30.kukhdhkIHMkbFrG_rsG1NovPvmbCNdJoS6cKbwWFxD8/img.jpg?width=1200&coordinates=0%2C0%2C0%2C171&height=600', 600, 1200, 'In a recent New York Times article, CDC spokeswoman Kristen Nordlund admitted that the agency \\\"has been slow\\\" to release data collected on COVID-19 — information that would have helped health officials throughout the country make better decisions in …', 'https://www.theblaze.com/u/theblazestaff', 'BlazeTV Staff', NULL, NULL, 'TheBlaze', 'https://assets.rebelmouse.io/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8xOTE0NDk2Ny9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY3OTQzNDgzOH0.zg8UMrmW3zfmSNQ7QPo0FhmiZD6JpcXApjX0k8CCK0M/img.jpg?width=210') ON DUPLICATE KEY UPDATE `uri-id` = 3690205, `type` = 17, `url` = 'https://www.theblaze.com/shows/you-are-here/cdc-hides-covid-information', `name` = 'The CDC finally admits what​​ we\\'ve known all along about COVID-19', `mimetype` = 'text/html; charset=utf-8', `size` = 432878, `preview` = 'https://assets.rebelmouse.io/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8yOTQyMDUyMS9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTcwNDk1MTcyN30.kukhdhkIHMkbFrG_rsG1NovPvmbCNdJoS6cKbwWFxD8/img.jpg?width=1200&coordinates=0%2C0%2C0%2C171&height=600', `preview-height` = 600, `preview-width` = 1200, `description` = 'In a recent New York Times article, CDC spokeswoman Kristen Nordlund admitted that the agency \\\"has been slow\\\" to release data collected on COVID-19 — information that would have helped health officials throughout the country make better decisions in …', `author-url` = 'https://www.theblaze.com/u/theblazestaff', `author-name` = 'BlazeTV Staff', `author-image` = NULL, `publisher-url` = NULL, `publisher-name` = 'TheBlaze', `publisher-image` = 'https://assets.rebelmouse.io/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbWFnZSI6Imh0dHBzOi8vYXNzZXRzLnJibC5tcy8xOTE0NDk2Ny9vcmlnaW4uanBnIiwiZXhwaXJlc19hdCI6MTY3OTQzNDgzOH0.zg8UMrmW3zfmSNQ7QPo0FhmiZD6JpcXApjX0k8CCK0M/img.jpg?width=210'"} - {"file":"Database.php","line":772,"function":"e","uid":"308cef","process_id":174189}
2022-02-24T23:21:15Z worker [ERROR]: Unable to find owner data for uid {"uid":3,"callstack":"Probe::localProbe, Probe::uri, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction, Worker::execute, Worker::processQueue"} - {"file":"Transmitter.php","line":315,"function":"getProfile","uid":"1afeba","process_id":174364}
```

**Comment by MrPetovan** [comment]
Nope, not related, thanks for the thought though!

**Comment by MrPetovan** [comment]
Possibly caused by #11270 ?

**Comment by MrPetovan** [comment]
Something isn't right with your `src/Model/Contact.php` file, you still have the previous version where `Contact::unfollow` was declared on line 2585 like in your error message, but now it's declared in line 822.

On the other hand you have the updated `mod/follow.php` file so I'm not sure what is going on.

**Comment by bkil** [comment]
I think some of the files had been shuffled around in recent versions, so this might happen if somebody updates without erasing the whole folder holding the previous installation of Friendica.

**Comment by MrPetovan** [comment]
@copiis updates his node via `git pull` on the `develop` branch, so the only way I can see this not working as a whole is if he added personal changes to the `src/Model/Contact.php` file, but it would have created a conflict with the pull and rendered the file unparseable for PHP.

So I'm a little bit flabbergasted at the moment.

**Comment by ghost** [comment]
I did not change anything, im just gitpuling

**Comment by MrPetovan** [comment]
What does `git status` say? What about `git show -1`?

**Comment by ghost** [comment]
git status
```
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    .htaccess-dist

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	etiketi.png
	media/

no changes added to commit (use "git add" and/or "git commit -a")
```


git show -1
```
commit 67eb9ae360d60f719ea6b5a4c9df9c57d90fca01 (HEAD -> develop, origin/develop)
Merge: 093dd70e7 f38888ecc
Author: Michael Vogel <icarus@dabo.de>
Date:   Thu Feb 24 21:24:39 2022 +0100

    Merge pull request #11270 from MrPetovan/task/10862-move-unfollow-worker
    
    Move unfollow/revoke follow protocol to worker tasks
```

**Comment by MrPetovan** [comment]
Thanks, it looks correct, can you check line 822 of your `src/Model/Contact.php` file? According to the repository it should be 
```php
public static function unfollow(array $contact): void
```

**Comment by ghost** [comment]
`public static function unfollow(array $contact): void`

**Comment by MrPetovan** [comment]
Thanks, and every time you try to unfollow the same contact you are getting the same error?

**Comment by ghost** [comment]
I get the error with every twitter contact

**Comment by ghost** [comment]
What I can't say is since when this has been the case, I only noticed it after this gitpul because I only now wanted to delete a Twitter contact.

**Comment by MrPetovan** [comment]
Can you please reload either Apache or php-fpm just to be sure it isn't a weird opcode cache issue?

**Comment by ghost** [comment]
Okay... now it works!

**Comment by MrPetovan** [comment]
Phew.
