### ISSUE TITLE
Uncaught Exception TypeError for return value of Email::connect()

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11299]
- [ X] I have searched open and closed issues for duplicates

### Bug Description

```
2022-03-07T17:47:02Z worker [ERROR]: Uncaught Exception TypeError: "Return value of Friendica\Protocol\Email::connect() must be an instance of IMAP\Connection, resource returned" at .../src/Protocol/Email.php line 62 {"exception":"TypeError: Return value of Friendica\\Protocol\\Email::connect() must be an instance of IMAP\\Connection, resource returned in .../src/Protocol/Email.php:62\nStack trace:\n#0 .../src/Worker/OnePoll.php(210): Friendica\\Protocol\\Email::connect()\n#1 .../src/Worker/OnePoll.php(94): Friendica\\Worker\\OnePoll::pollMail()\n#2 [internal function]: Friendica\\Worker\\OnePoll::execute()\n#3 .../src/Core/Worker.php(497): call_user_func_array()\n#4 .../src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()\n#5 .../src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()\n#6 .../bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n#7 {main}"} - {"file":null,"line":null,"function":null,"uid":"c899e2","process_id":1846433}
```

### Steps to Reproduce

1.  switch to current develop or stable 2022.03
2.  watch the logs

### Platform Info

Friendica Version:

2022.03
2022.05-dev

Friendica Source: 

git

PHP version:

7.4

SQL version:

10.6 MariaDB

**Comment by MrPetovan** [comment]
This is a PHP 8.1+ issue, the new type hints aren't valid for PHP <8.1 @annando

**Comment by annando** [comment]
@MrPetovan how can we solve this?

**Comment by MrPetovan** [comment]
We need to revert the explicit type-hint changes and take into account the two possible return value/parameter types. I was wrong to ask you to update the function declaration, but the doc blocks need to reflect this duality as well.

**Comment by annando** [comment]
I'm always unsure how to define two different parameters types?

**Comment by MrPetovan** [comment]
In the function declaration, we can't, it has to be at the DocBlock level only, like this: `Connection|resource`

**Comment by MrPetovan** [comment]
https://github.com/friendica/friendica/pull/11304 should fix this issue

**Comment by annando** [comment]
@AlfredSK I guess this is solved for you a long time ago and we can close the issue?

**Comment by AlfredSK** [comment]
Yep. I think so.
