### ISSUE TITLE
Error 500 for .../admin/queue

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11329]
- [X ] I have searched open and closed issues for duplicates

### Bug Description
When I click on the link behind the number of queued tasks in the admin panel I get an error 500 and a white page.
.../admin/queue => error 500
.../admin/queue/deferred => works

```
index [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Util\Arrays::recursiveImplode() must be of the type array, int given, called in .../src/Module/Admin/Queue.php on line 64" at .../src/Util/Arrays.php line 43 
{"exception":"TypeError: Argument 1 passed to Friendica\\Util\\Arrays::recursiveImplode() must be of the type array, int given, called in .../src/Module/Admin/Queue.php on line 64 and defined in .../src/Util/Arrays.php:43
Stack trace:
#0 .../src/Module/Admin/Queue.php(64): Friendica\\Util\\Arrays::recursiveImplode()
#1 .../src/BaseModule.php(239): Friendica\\Module\\Admin\\Queue->content()
#2 .../src/App.php(711): Friendica\\BaseModule->run()
#3 .../index.php(44): Friendica\\App->runFrontend()
#4 {main}"}
{"file":null,"line":null,"function":null,"uid":"aecf42","process_id":2292775}
```

### Steps to Reproduce

1.  go to .../admin
2.  click on the number of queued tasks
3.  you are redirected to .../admin/queue
4.  notice the white page

Actual Result:
error 500

Expected Result:
http 200 ok

### Platform Info

Friendica Version:
2022.05-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB

**Comment by AlfredSK** [comment]
Found the error message in Friendica's log and added it to the bug description.

**Comment by AlfredSK** [comment]
This was caused by some malformed queue entry. Since I dropped some jobs from the queue it works again.
