### ISSUE TITLE
Memcached key format errors

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#11343]
Memcache keys are limited to 250 characters, so we can't really put a URL in them, but we definitely can't put _these_ URLs.
```
2022-03-15T11:25:04Z worker [ERROR]: Uncaught Exception Friendica\Core\Cache\Exception\CachePersistenceException: "Cannot get cache entry with key apcontact:getByURL:https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi" at /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php line 122 {"exception":"MemcachedException: A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE in /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php:122
Stack trace:
#0 /home/friendica/friendica/friendica/src/Model/APContact.php(172): Friendica\\Core\\Cache\\Type\\MemcachedCache->get()
#1 /home/friendica/friendica/friendica/src/Protocol/ActivityPub.php(147): Friendica\\Model\\APContact::getByURL()
#2 /home/friendica/friendica/friendica/src/Network/Probe.php(353): Friendica\\Protocol\\ActivityPub::probeProfile()
#3 /home/friendica/friendica/friendica/src/Model/Contact.php(2147): Friendica\\Network\\Probe::uri()
#4 /home/friendica/friendica/friendica/src/Worker/UpdateContact.php(35): Friendica\\Model\\Contact::updateFromProbe()
#5 [internal function]: Friendica\\Worker\\UpdateContact::execute()
#6 /home/friendica/friendica/friendica/src/Core/Worker.php(497): call_user_func_array()
#7 /home/friendica/friendica/friendica/src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()
#8 /home/friendica/friendica/friendica/src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()
#9 /home/friendica/friendica/friendica/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()
#10 {main}

Next Friendica\\Core\\Cache\\Exception\\CachePersistenceException: Cannot get cache entry with key apcontact:getByURL:https://horche.demkontinuum.de/index.php/network/network/60/network/60/network/60/network/60/network/60/network/60/network/60/n/photo/profile/1.jpg/.well-known/.well-known/.well-known/photo/photo/profile/1.jpg/.well-known/host-meta/.well-known/photo/profi in /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php:122
Stack trace:
#0 /home/friendica/friendica/friendica/src/Model/APContact.php(172): Friendica\\Core\\Cache\\Type\\MemcachedCache->get()
#1 /home/friendica/friendica/friendica/src/Protocol/ActivityPub.php(147): Friendica\\Model\\APContact::getByURL()
#2 /home/friendica/friendica/friendica/src/Network/Probe.php(353): Friendica\\Protocol\\ActivityPub::probeProfile()
#3 /home/friendica/friendica/friendica/src/Model/Contact.php(2147): Friendica\\Network\\Probe::uri()
#4 /home/friendica/friendica/friendica/src/Worker/UpdateContact.php(35): Friendica\\Model\\Contact::updateFromProbe()
#5 [internal function]: Friendica\\Worker\\UpdateContact::execute()
#6 /home/friendica/friendica/friendica/src/Core/Worker.php(497): call_user_func_array()
#7 /home/friendica/friendica/friendica/src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()
#8 /home/friendica/friendica/friendica/src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()
#9 /home/friendica/friendica/friendica/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()
#10 {main}"} - {"file":null,"line":null,"function":null,"uid":"dc28dd","process_id":9046}
```

**Comment by annando** [comment]
The problem isn't the limit, the problem are these URL. Where do they come from? Can you reproduce this?

**Comment by MrPetovan** [comment]
It reproduces itself whenever my node is updating this contact, which you can guess [who it is](https://github.com/friendica/friendica/issues/6679) from the URL.

And the problem is the limit, we can't guarantee that even valid URLs won't be shorter than 250 characters (minus the cache key prefix in this case). Just like we did for the media URL cache keys, we have to hash these URLs in this cache key, regardless of the actual URL which is a separate problem.

**Comment by annando** [comment]
Without this limit we hadn't detected that there is this problem with the repeated path parts.

**Comment by MrPetovan** [comment]
Yes but it still is besides the point, this limit doesn't exist to troubleshoot potentially problematic Friendica URLs.

**Comment by MrPetovan** [comment]
Additional error that doesn't involve bad URLs, spaces aren't allowed:
```
2022-03-15T14:40:09Z index [ERROR]: Uncaught Exception Friendica\Core\Cache\Exception\CachePersistenceException: "Cannot get cache entry with key about:2022-02-24 05:35:03:http://friendica.mrpetovan.com/profile/hypolite" at /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php line 122 {"exception":"MemcachedException: A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE in /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php:122
Stack trace:
#0 /home/friendica/friendica/friendica/mod/poco.php(124): Friendica\\Core\\Cache\\Type\\MemcachedCache->get()
#1 /home/friendica/friendica/friendica/src/LegacyModule.php(96): poco_init()
#2 /home/friendica/friendica/friendica/src/LegacyModule.php(51): Friendica\\LegacyModule->runModuleFunction()
#3 [internal function]: Friendica\\LegacyModule->__construct()
#4 /home/friendica/friendica/friendica/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#5 /home/friendica/friendica/friendica/vendor/level-2/dice/Dice.php(96): Dice\\Dice->Dice\\{closure}()
#6 /home/friendica/friendica/friendica/src/App/Router.php(330): Dice\\Dice->create()
#7 /home/friendica/friendica/friendica/src/App.php(702): Friendica\\App\\Router->getModule()
#8 /home/friendica/friendica/friendica/index.php(44): Friendica\\App->runFrontend()
#9 {main}

Next Friendica\\Core\\Cache\\Exception\\CachePersistenceException: Cannot get cache entry with key about:2022-02-24 05:35:03:http://friendica.mrpetovan.com/profile/hypolite in /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php:122
Stack trace:
#0 /home/friendica/friendica/friendica/mod/poco.php(124): Friendica\\Core\\Cache\\Type\\MemcachedCache->get()
#1 /home/friendica/friendica/friendica/src/LegacyModule.php(96): poco_init()
#2 /home/friendica/friendica/friendica/src/LegacyModule.php(51): Friendica\\LegacyModule->runModuleFunction()
#3 [internal function]: Friendica\\LegacyModule->__construct()
#4 /home/friendica/friendica/friendica/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#5 /home/friendica/friendica/friendica/vendor/level-2/dice/Dice.php(96): Dice\\Dice->Dice\\{closure}()
#6 /home/friendica/friendica/friendica/src/App/Router.php(330): Dice\\Dice->create()
#7 /home/friendica/friendica/friendica/src/App.php(702): Friendica\\App\\Router->getModule()
#8 /home/friendica/friendica/friendica/index.php(44): Friendica\\App->runFrontend()
#9 {main}"} - {"file":null,"line":null,"function":null,"uid":"f237d5","process_id":22722}
```

**Comment by MrPetovan** [comment]
And another one with a short URL but with the dreaded space:
```
2022-03-15T14:35:02Z worker [ERROR]: Uncaught Exception Friendica\Core\Cache\Exception\CachePersistenceException: "Cannot get cache entry with key apcontact:getByURL:https://hub.vilarejo.pro.br/channel/danie van der merwe9464" at /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php line 122 {"exception":"MemcachedException: A BAD KEY WAS PROVIDED/CHARACTERS OUT OF RANGE in /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php:122
Stack trace:
#0 /home/friendica/friendica/friendica/src/Model/APContact.php(172): Friendica\\Core\\Cache\\Type\\MemcachedCache->get()
#1 /home/friendica/friendica/friendica/src/Protocol/ActivityPub.php(147): Friendica\\Model\\APContact::getByURL()
#2 /home/friendica/friendica/friendica/src/Network/Probe.php(353): Friendica\\Protocol\\ActivityPub::probeProfile()
#3 /home/friendica/friendica/friendica/src/Model/Contact.php(2147): Friendica\\Network\\Probe::uri()
#4 /home/friendica/friendica/friendica/src/Worker/UpdateContact.php(35): Friendica\\Model\\Contact::updateFromProbe()
#5 [internal function]: Friendica\\Worker\\UpdateContact::execute()
#6 /home/friendica/friendica/friendica/src/Core/Worker.php(497): call_user_func_array()
#7 /home/friendica/friendica/friendica/src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()
#8 /home/friendica/friendica/friendica/src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()
#9 /home/friendica/friendica/friendica/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()
#10 {main}

Next Friendica\\Core\\Cache\\Exception\\CachePersistenceException: Cannot get cache entry with key apcontact:getByURL:https://hub.vilarejo.pro.br/channel/danie van der merwe9464 in /home/friendica/friendica/friendica/src/Core/Cache/Type/MemcachedCache.php:122
Stack trace:
#0 /home/friendica/friendica/friendica/src/Model/APContact.php(172): Friendica\\Core\\Cache\\Type\\MemcachedCache->get()
#1 /home/friendica/friendica/friendica/src/Protocol/ActivityPub.php(147): Friendica\\Model\\APContact::getByURL()
#2 /home/friendica/friendica/friendica/src/Network/Probe.php(353): Friendica\\Protocol\\ActivityPub::probeProfile()
#3 /home/friendica/friendica/friendica/src/Model/Contact.php(2147): Friendica\\Network\\Probe::uri()
#4 /home/friendica/friendica/friendica/src/Worker/UpdateContact.php(35): Friendica\\Model\\Contact::updateFromProbe()
#5 [internal function]: Friendica\\Worker\\UpdateContact::execute()
#6 /home/friendica/friendica/friendica/src/Core/Worker.php(497): call_user_func_array()
#7 /home/friendica/friendica/friendica/src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()
#8 /home/friendica/friendica/friendica/src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()
#9 /home/friendica/friendica/friendica/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()
#10 {main}"} - {"file":null,"line":null,"function":null,"uid":"c2091e","process_id":21521}
```
