### ISSUE TITLE
Timeline disappeared

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11404]
Since the last GitPull earlier, the timeline has disappeared on the desktop, under Twidere it seems that it is still being loaded.

![etiketi de-20220409](https://user-images.githubusercontent.com/12480023/162555133-d39393e7-4ae2-4b31-b338-08e4fa92b0fb.png)

```
2022-04-09T03:49:21Z index [ERROR]: DB Error {"code":1054,"error":"Unknown column 'pinned' in 'field list'","callstack":"Post::selectForUser, Conversation::addChildren, Conversation::create, Network::rawContent, BaseModule::run, App::runFrontend","params":"SELECT `uid`, `id`, `parent`, `guid`, `network`, `gravity`, `uri-id`, `uri`, `thr-parent-id`, `thr-parent`, `parent-uri-id`, `parent-uri`, `commented`, `created`, `edited`, `received`, `verb`, `object-type`, `postopts`, `plink`, `wall`, `private`, `starred`, `origin`, `parent-origin`, `title`, `body`, `language`, `content-warning`, `location`, `coord`, `app`, `rendered-hash`, `rendered-html`, `object`, `allow_cid`, `allow_gid`, `deny_cid`, `deny_gid`, `mention`, `global`, `author-id`, `author-link`, `author-name`, `author-avatar`, `author-network`, `owner-id`, `owner-link`, `owner-name`, `owner-avatar`, `owner-network`, `owner-contact-type`, `causer-id`, `causer-link`, `causer-name`, `causer-avatar`, `causer-contact-type`, `causer-network`, `contact-id`, `contact-uid`, `contact-link`, `contact-name`, `contact-avatar`, `writable`, `self`, `cid`, `alias`, `event-created`, `event-edited`, `event-start`, `event-finish`, `event-summary`, `event-desc`, `event-location`, `event-type`, `event-nofinish`, `event-ignore`, `event-id`, `delivery_queue_count`, `delivery_queue_done`, `delivery_queue_failed`, `pinned`, `contact-uid`, `gravity`, `post-type`, `post-reason` FROM `post-user-view` WHERE (FALSE AND `uid` IN (0, 2) AND (`vid` != 6 OR `vid` IS NULL) AND `visible` AND NOT `deleted` AND NOT `author-blocked` AND NOT `owner-blocked` AND (NOT `causer-blocked` OR `causer-id` = 0 OR `causer-id` IS NULL) AND NOT `contact-blocked` AND ((NOT `contact-readonly` AND NOT `contact-pending` AND (`contact-rel` IN (2, 3))) OR `self` OR `gravity` != 0 OR `contact-uid` = 0) AND NOT EXISTS (SELECT `uri-id` FROM `post-user` WHERE `uid` = 2 AND `uri-id` = `post-user-view`.`uri-id` AND `hidden`) AND NOT EXISTS (SELECT `cid` FROM `user-contact` WHERE `uid` = 2 AND `cid` = `author-id` AND `blocked`) AND NOT EXISTS (SELECT `cid` FROM `user-contact` WHERE `uid` = 2 AND `cid` = `owner-id` AND `blocked`) AND NOT EXISTS (SELECT `cid` FROM `user-contact` WHERE `uid` = 2 AND `cid` = `author-id` AND `ignored` AND `gravity` = 0) AND NOT EXISTS (SELECT `cid` FROM `user-contact` WHERE `uid` = 2 AND `cid` = `owner-id` AND `ignored` AND `gravity` = 0)) ORDER BY `uri-id` DESC, `uid` DESC"} - {"file":"Database.php","line":679,"function":"p","uid":"e642a9","process_id":2257150}
```

```
2022-04-09T03:50:03Z worker [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Model\Contact::updateFromProbe() must be of the type int, null given, called in /src/Model/GServer.php on line 1353" at /src/Model/Contact.php line 2155 {"exception":"TypeError: Argument 1 passed to Friendica\\Model\\Contact::updateFromProbe() must be of the type int, null given, called in /src/Model/GServer.php on line 1353 and defined in /home/users/zsemberi/www/friendica/src/Model/Contact.php:2155\nStack trace:\n#0 /src/Model/GServer.php(1353): Friendica\\Model\\Contact::updateFromProbe()\n#1 /src/Model/GServer.php(451): Friendica\\Model\\GServer::detectFromContacts()\n#2 /src/Model/GServer.php(258): Friendica\\Model\\GServer::detect()\n# 3/src/Worker/UpdateGServer.php(59): Friendica\\Model\\GServer::check()\n#4 [internal function]: Friendica\\Worker\\UpdateGServer::execute()\n#5 /src/Core/Worker.php(497): call_user_func_array()\n#6 /src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()\n#7 /src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()\n#8 /bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n#9 {main}"} - {"file":null,"line":null,"function":null,"uid":"3c0755","process_id":2287122}
```

**Comment by ghost** [comment]
After I restart the server, the timeline is back.
