### ISSUE TITLE
Uncaught Exception TypeError for Friendica\Model\Contact::updateFromProbe()

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11407]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

I have a lot - I mean really a lot - of exceptions when the contacts are updated from probe. I have no idea if this is making any real trouble but the number of error messages is concerning.

This is one example with all lines for the same process id.

```
2022-04-11T17:08:11Z worker [NOTICE]: Load: 5.31/24 - processes: 13376/11/339 (0:0, 30:1, 40:8, 50:4) - maximum: 24/50 [] - {"file":"Worker.php","line":819,"function":"tooMuchWorkers","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: There are fewer workers as possible, fork a new worker. {"active":11,"queues":24} - {"file":"Worker.php","line":823,"function":"tooMuchWorkers","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: Executed "proc_open" {"command":"/usr/bin/php 'bin/worker.php' --no_cron","callstack":"Worker::spawnWorker, Worker::tooMuchWorkers, Worker::isReady, Worker::processQueue"} - {"file":"System.php","line":218,"function":"run","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: Connection usage (system values) {"used":20,"max":350} - {"file":"Worker.php","line":623,"function":"maxConnectionsReached","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: Priority 30 has got 1 workers out of a limit of 7 {"priority":30,"workers":1,"limit":7} - {"file":"Worker.php","line":993,"function":"nextPriority","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: Found: {"priority":30,"id":[]} - {"file":"Worker.php","line":932,"function":"nextProcess","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: Set queue entry {"pid":173843,"ids":[313082801]} - {"file":"Worker.php","line":1074,"function":"findWorkerProcesses","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: Connection usage (system values) {"used":19,"max":350} - {"file":"Worker.php","line":623,"function":"maxConnectionsReached","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: Process start. {"priority":40,"id":313082801,"worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"Worker.php","line":475,"function":"execFunction","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: Server is outdated. Start discovery. {"Server":"https://bread.upchur.ch","Force":true,"worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"GServer.php","line":253,"function":"check","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [INFO]: Detect server type {"server":"https://bread.upchur.ch","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"GServer.php","line":327,"function":"detect","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:11Z worker [NOTICE]: Curl redirect. {"url":"https://bread.upchur.ch/.well-known/nodeinfo","to":"https://upchur.ch/yunohost/sso/?r=aHR0cHM6Ly9icmVhZC51cGNodXIuY2gvLndlbGwta25vd24vbm9kZWluZm8=","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:13Z worker [NOTICE]: Curl redirect. {"url":"https://bread.upchur.ch/statistics.json","to":"https://upchur.ch/yunohost/sso/?r=aHR0cHM6Ly9icmVhZC51cGNodXIuY2gvc3RhdGlzdGljcy5qc29u","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:14Z worker [NOTICE]: Curl redirect. {"url":"https://bread.upchur.ch","to":"https://upchur.ch/yunohost/sso/?r=aHR0cHM6Ly9icmVhZC51cGNodXIuY2gv","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:14Z worker [NOTICE]: Curl redirect. {"url":"https://bread.upchur.ch/api/v1/instance","to":"https://upchur.ch/yunohost/sso/?r=aHR0cHM6Ly9icmVhZC51cGNodXIuY2gvYXBpL3YxL2luc3RhbmNl","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:15Z worker [NOTICE]: Curl redirect. {"url":"https://bread.upchur.ch/.well-known/host-meta","to":"https://upchur.ch/yunohost/sso/?r=aHR0cHM6Ly9icmVhZC51cGNodXIuY2gvLndlbGwta25vd24vaG9zdC1tZXRh","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [ERROR]: Error(s) while parsing XML string. {"callstack":"GServer::validHostMeta, GServer::detect, GServer::check, UpdateGServer::execute","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":450,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":76,"position":"35:8","message":"Opening and ending tag mismatch: meta line 34 and head\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":41,"position":"50:121","message":"Specification mandates value for attribute autofocus\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":65,"position":"50:121","message":"attributes construct error\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":73,"position":"50:121","message":"Couldn't find end of Start Tag input line 50\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":41,"position":"54:139","message":"Specification mandates value for attribute required\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":76,"position":"55:9","message":"Opening and ending tag mismatch: input line 33 and div\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":76,"position":"57:8","message":"Opening and ending tag mismatch: input line 33 and form\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":76,"position":"60:9","message":"Opening and ending tag mismatch: form line 33 and div\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":76,"position":"65:8","message":"Opening and ending tag mismatch: div line 33 and body\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":76,"position":"66:8","message":"Opening and ending tag mismatch: div line 33 and html\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [INFO]: libxml error {"code":74,"position":"68:1","message":"EndTag: '</' not found\n","worker_id":"15f854d","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [NOTICE]: E_NOTICE: Trying to access array offset on value of type bool {"code":8,"message":"Trying to access array offset on value of type bool","file":"/var/www/html/libranet/src/Model/GServer.php","line":1353} - {"file":"GServer.php","line":1353,"function":"detectFromContacts","uid":"b4c4ca","process_id":173843}
2022-04-11T17:08:20Z worker [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Model\Contact::updateFromProbe() must be of the type int, null given, called in /var/www/html/libranet/src/Model/GServer.php on line 1353" at /var/www/html/libranet/src/Model/Contact.php line 2156 {"exception":"TypeError: Argument 1 passed to Friendica\\Model\\Contact::updateFromProbe() must be of the type int, null given, called in /var/www/html/libranet/src/Model/GServer.php on line 1353 and defined in /var/www/html/libranet/src/Model/Contact.php:2156\nStack trace:\n#0 /var/www/html/libranet/src/Model/GServer.php(1353): Friendica\\Model\\Contact::updateFromProbe()\n#1 /var/www/html/libranet/src/Model/GServer.php(451): Friendica\\Model\\GServer::detectFromContacts()\n#2 /var/www/html/libranet/src/Model/GServer.php(258): Friendica\\Model\\GServer::detect()\n#3 /var/www/html/libranet/src/Worker/UpdateGServer.php(59): Friendica\\Model\\GServer::check()\n#4 [internal function]: Friendica\\Worker\\UpdateGServer::execute()\n#5 /var/www/html/libranet/src/Core/Worker.php(497): call_user_func_array()\n#6 /var/www/html/libranet/src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()\n#7 /var/www/html/libranet/src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()\n#8 /var/www/html/libranet/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n#9 {main}"} - {"file":null,"line":null,"function":null,"uid":"b4c4ca","process_id":173843}
```

### Platform Info

Friendica Version:
2022.05-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by AlfredSK** [comment]
Example 2:

```
2022-04-11T17:16:12Z worker [NOTICE]: Load: 5.81/24 - processes: 13340/17/95 (0:0, 30:5, 40:12) - maximum: 22/50 [] - {"file":"Worker.php","line":819,"function":"tooMuchWorkers","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: There are fewer workers as possible, fork a new worker. {"active":17,"queues":22} - {"file":"Worker.php","line":823,"function":"tooMuchWorkers","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: Executed "proc_open" {"command":"/usr/bin/php 'bin/worker.php' --no_cron","callstack":"Worker::spawnWorker, Worker::tooMuchWorkers, Worker::isReady, Worker::processQueue"} - {"file":"System.php","line":218,"function":"run","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: Connection usage (system values) {"used":24,"max":350} - {"file":"Worker.php","line":623,"function":"maxConnectionsReached","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: Priority 30 has got 5 workers out of a limit of 14 {"priority":30,"workers":5,"limit":14} - {"file":"Worker.php","line":993,"function":"nextPriority","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: Found: {"priority":30,"id":[]} - {"file":"Worker.php","line":932,"function":"nextProcess","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: Set queue entry {"pid":183589,"ids":[313079992]} - {"file":"Worker.php","line":1074,"function":"findWorkerProcesses","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: Connection usage (system values) {"used":24,"max":350} - {"file":"Worker.php","line":623,"function":"maxConnectionsReached","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: Process start. {"priority":40,"id":313079992,"worker_id":"12ee92d","worker_cmd":"UpdateGServer"} - {"file":"Worker.php","line":475,"function":"execFunction","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: Server is outdated. Start discovery. {"Server":"https://sky.bundsgaard.net","Force":true,"worker_id":"12ee92d","worker_cmd":"UpdateGServer"} - {"file":"GServer.php","line":253,"function":"check","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:12Z worker [INFO]: Detect server type {"server":"https://sky.bundsgaard.net","worker_id":"12ee92d","worker_cmd":"UpdateGServer"} - {"file":"GServer.php","line":327,"function":"detect","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:13Z worker [NOTICE]: Curl redirect. {"url":"https://sky.bundsgaard.net/statistics.json","to":"https://sky.bundsgaard.net/index.php/login","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:13Z worker [NOTICE]: Curl redirect. {"url":"https://sky.bundsgaard.net","to":"https://sky.bundsgaard.net/index.php/login","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:13Z worker [NOTICE]: Curl redirect. {"url":"https://sky.bundsgaard.net/api/v1/instance","to":"https://sky.bundsgaard.net/index.php/login","method":"GET"} - {"file":"HttpClient.php","line":86,"function":"Friendica\\Network\\HTTPClient\\Factory\\{closure}","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:13Z worker [NOTICE]: E_NOTICE: Trying to access array offset on value of type bool {"code":8,"message":"Trying to access array offset on value of type bool","file":"/var/www/html/libranet/src/Model/GServer.php","line":1353} - {"file":"GServer.php","line":1353,"function":"detectFromContacts","uid":"e5bb03","process_id":183589}
2022-04-11T17:16:13Z worker [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Model\Contact::updateFromProbe() must be of the type int, null given, called in /var/www/html/libranet/src/Model/GServer.php on line 1353" at /var/www/html/libranet/src/Model/Contact.php line 2156 {"exception":"TypeError: Argument 1 passed to Friendica\\Model\\Contact::updateFromProbe() must be of the type int, null given, called in /var/www/html/libranet/src/Model/GServer.php on line 1353 and defined in /var/www/html/libranet/src/Model/Contact.php:2156\nStack trace:\n#0 /var/www/html/libranet/src/Model/GServer.php(1353): Friendica\\Model\\Contact::updateFromProbe()\n#1 /var/www/html/libranet/src/Model/GServer.php(451): Friendica\\Model\\GServer::detectFromContacts()\n#2 /var/www/html/libranet/src/Model/GServer.php(258): Friendica\\Model\\GServer::detect()\n#3 /var/www/html/libranet/src/Worker/UpdateGServer.php(59): Friendica\\Model\\GServer::check()\n#4 [internal function]: Friendica\\Worker\\UpdateGServer::execute()\n#5 /var/www/html/libranet/src/Core/Worker.php(497): call_user_func_array()\n#6 /var/www/html/libranet/src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()\n#7 /var/www/html/libranet/src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()\n#8 /var/www/html/libranet/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n#9 {main}"} - {"file":null,"line":null,"function":null,"uid":"e5bb03","process_id":183589}
```

**Comment by AlfredSK** [comment]
Example 3:

```
2022-04-11T17:16:13Z worker [NOTICE]: Load: 5.81/24 - processes: 13339/18/85 (0:0, 30:5, 40:13) - maximum: 22/50 [] - {"file":"Worker.php","line":819,"function":"tooMuchWorkers","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: There are fewer workers as possible, fork a new worker. {"active":18,"queues":22} - {"file":"Worker.php","line":823,"function":"tooMuchWorkers","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: Executed "proc_open" {"command":"/usr/bin/php 'bin/worker.php' --no_cron","callstack":"Worker::spawnWorker, Worker::tooMuchWorkers, Worker::isReady, Worker::processQueue"} - {"file":"System.php","line":218,"function":"run","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: Connection usage (system values) {"used":24,"max":350} - {"file":"Worker.php","line":623,"function":"maxConnectionsReached","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: Priority 30 has got 5 workers out of a limit of 14 {"priority":30,"workers":5,"limit":14} - {"file":"Worker.php","line":993,"function":"nextPriority","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: Found: {"priority":30,"id":[]} - {"file":"Worker.php","line":932,"function":"nextProcess","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: Set queue entry {"pid":183633,"ids":[313157640]} - {"file":"Worker.php","line":1074,"function":"findWorkerProcesses","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: Connection usage (system values) {"used":24,"max":350} - {"file":"Worker.php","line":623,"function":"maxConnectionsReached","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: Process start. {"priority":40,"id":313157640,"worker_id":"de1c068","worker_cmd":"UpdateGServer"} - {"file":"Worker.php","line":475,"function":"execFunction","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: Server is outdated. Start discovery. {"Server":"https://learn.noeldemartin.social","Force":true,"worker_id":"de1c068","worker_cmd":"UpdateGServer"} - {"file":"GServer.php","line":253,"function":"check","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:13Z worker [INFO]: Detect server type {"server":"https://learn.noeldemartin.social","worker_id":"de1c068","worker_cmd":"UpdateGServer"} - {"file":"GServer.php","line":327,"function":"detect","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:14Z worker [ERROR]: Error(s) while parsing XML string. {"callstack":"GServer::validHostMeta, GServer::detect, GServer::check, UpdateGServer::execute","worker_id":"de1c068","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":450,"function":"parseString","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:14Z worker [INFO]: libxml error {"code":68,"position":"1:2","message":"StartTag: invalid element name\n","worker_id":"de1c068","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:14Z worker [INFO]: libxml error {"code":5,"position":"1:2","message":"Extra content at the end of the document\n","worker_id":"de1c068","worker_cmd":"UpdateGServer"} - {"file":"XML.php","line":452,"function":"parseString","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:14Z worker [NOTICE]: E_NOTICE: Trying to access array offset on value of type bool {"code":8,"message":"Trying to access array offset on value of type bool","file":"/var/www/html/libranet/src/Model/GServer.php","line":1353} - {"file":"GServer.php","line":1353,"function":"detectFromContacts","uid":"0d1bda","process_id":183633}
2022-04-11T17:16:14Z worker [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Model\Contact::updateFromProbe() must be of the type int, null given, called in /var/www/html/libranet/src/Model/GServer.php on line 1353" at /var/www/html/libranet/src/Model/Contact.php line 2156 {"exception":"TypeError: Argument 1 passed to Friendica\\Model\\Contact::updateFromProbe() must be of the type int, null given, called in /var/www/html/libranet/src/Model/GServer.php on line 1353 and defined in /var/www/html/libranet/src/Model/Contact.php:2156\nStack trace:\n#0 /var/www/html/libranet/src/Model/GServer.php(1353): Friendica\\Model\\Contact::updateFromProbe()\n#1 /var/www/html/libranet/src/Model/GServer.php(451): Friendica\\Model\\GServer::detectFromContacts()\n#2 /var/www/html/libranet/src/Model/GServer.php(258): Friendica\\Model\\GServer::detect()\n#3 /var/www/html/libranet/src/Worker/UpdateGServer.php(59): Friendica\\Model\\GServer::check()\n#4 [internal function]: Friendica\\Worker\\UpdateGServer::execute()\n#5 /var/www/html/libranet/src/Core/Worker.php(497): call_user_func_array()\n#6 /var/www/html/libranet/src/Core/Worker.php(387): Friendica\\Core\\Worker::execFunction()\n#7 /var/www/html/libranet/src/Core/Worker.php(112): Friendica\\Core\\Worker::execute()\n#8 /var/www/html/libranet/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n#9 {main}"} - {"file":null,"line":null,"function":null,"uid":"0d1bda","process_id":183633}
```
