### ISSUE TITLE
daemon/worker stopped working

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#11507]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Today, I pulled the latest sources from a timespan from ~1-2 weeks.
Now the daemon/worker are no more working.

I'm using a docker environment, where hundreds of process are running in parallel, but separated at applicaton level.
The daemon/worker are complaining about tooMuchWorkers

```
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 10.05322265625/20 - processes: 114/1/3165 (0:0, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"74d4bf"}               
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 10.05322265625/20 - processes: 114/1/3165 (0:0, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"74d4bf"}               
cron_1   | Friendica[5422]: worker [NOTICE]: Load: 10.05322265625/20 - processes: 114/1/3165 (0:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"dc7044"}                   
cron_1   | Friendica[5424]: worker [NOTICE]: Load: 10.05322265625/20 - processes: 114/2/3165 (0:2) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"12a067"}                   
cron_1   | Friendica[5424]: worker [NOTICE]: Active worker limit reached, quitting. [] - {"file":"Worker.php","line":198,"function":"isReady","uid":"12a067"}                                                        
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 10.05322265625/20 - processes: 114/1/3165 (0:0, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"74d4bf"}               
cron_1   | Friendica[5427]: worker [NOTICE]: Load: 10.05322265625/20 - processes: 114/2/3165 (0:1, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"66e776"}             
cron_1   | Friendica[5427]: worker [NOTICE]: Active worker limit reached, quitting. [] - {"file":"Worker.php","line":198,"function":"isReady","uid":"66e776"}                                                        
cron_1   | Friendica[5422]: worker [ERROR]: Uncaught Exception Friendica\Network\HTTPException\NotFoundException: "Invalid contact." at /var/www/html/src/Model/Group.php line 279 {"exception":"Friendica\\Network\\
HTTPException\\NotFoundException: Invalid contact. in /var/www/html/src/Model/Group.php:279\nStack trace:\n#0 /var/www/html/src/Model/Contact.php(2645): Friendica\\Model\\Group::addMember()\n#1 /var/www/html/src/W
orker/AddContact.php(43): Friendica\\Model\\Contact::createFromProbeForUser()\n#2 [internal function]: Friendica\\Worker\\AddContact::execute()\n#3 /var/www/html/src/Core/Worker.php(508): call_user_func_array()\n#
4 /var/www/html/src/Core/Worker.php(403): Friendica\\Core\\Worker::execFunction()\n#5 /var/www/html/src/Core/Worker.php(110): Friendica\\Core\\Worker::execute()\n#6 /var/www/html/bin/worker.php(86): Friendica\\Cor
e\\Worker::processQueue()\n#7 {main}"} - {"file":null,"line":null,"function":null,"uid":"dc7044"}                                                                                                                    
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 10.05322265625/20 - processes: 114/1/3165 (0:0, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"74d4bf"}               
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 10.05322265625/20 - processes: 114/1/3165 (0:0, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"74d4bf"}               
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 10.05322265625/20 - processes: 114/1/3165 (0:0, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"74d4bf"}               
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 10.05322265625/20 - processes: 114/1/3165 (0:0, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"74d4bf"}               
cron_1   | Friendica[5429]: worker [NOTICE]: Load: 10.05322265625/20 - processes: 114/1/3165 (0:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"2aefab"}                   
cron_1   | Friendica[5431]: worker [NOTICE]: Load: 10.05322265625/20 - processes: 114/2/3164 (0:1, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"bdb411"}             
cron_1   | Friendica[5431]: worker [NOTICE]: Active worker limit reached, quitting. [] - {"file":"Worker.php","line":198,"function":"isReady","uid":"bdb411"}                                                        
cron_1   | Friendica[5433]: worker [NOTICE]: Load: 10.05322265625/20 - processes: 114/2/3164 (0:1, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"b33fcb"}             
cron_1   | Friendica[5433]: worker [NOTICE]: Active worker limit reached, quitting. [] - {"file":"Worker.php","line":198,"function":"isReady","uid":"b33fcb"}                                                        
cron_1   | Friendica[5435]: worker [NOTICE]: Load: 10.05322265625/20 - processes: 114/2/3164 (0:1, 40:1) - maximum: 1/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"2de13d"}             
cron_1   | Friendica[5435]: worker [NOTICE]: Active worker limit reached, quitting. [] - {"file":"Worker.php","line":198,"function":"isReady","uid":"2de13d"}                                                        
```
### Platform Info

Friendica Version:

docker 2022.05-rc-fpm-alpine

Friendica Source: 

PHP version: 7.4.29

SQL version: Mariadb 15.1

**Comment by annando** [comment]
The function name is `tooMuchWorkers`. It just checks if there are too much workers. How have you checked that the workerqueue isn't working?

**Comment by nupplaphil** [comment]
I wiped the process table, started the cron as usual and the first time since using, the workerqueue isn't increasing and the logs are showing 90% the logoutput above, except for some cases, where I noticed about 1-2 worker executions.

Shall I look for workerqueue entries with dangeling process IDs? I thought they would get reset because of some checks before

**Comment by nupplaphil** [comment]
ok, it's now working, I'm sorry for this false-positive ..
It was a strange behavior for me, but in the end, I now see a lot of  worker-executions again..

**Comment by annando** [comment]
The worker is performing several different self healing spells from time to time.

**Comment by nupplaphil** [comment]
Something is definitly wrong :(
```
Der Hintergrundprozess (worker) wurde zuletzt um 2022-05-15 19:12:54 UTC ausgeführt. Das war vor mehr als einer Stunde. Bitte überprüfe deine crontab-Einstellungen.
```

And a lot of workerqueue entries..

I will add current logs tomorrow

**Comment by nupplaphil** [comment]
sometimes it's working, but it's now stuck here:
```console
 cron_1   | Friendica[24]: worker [NOTICE]: Pre check: maximum load reached, quitting. [] - {"file":"Worker.php","line":71,"function":"processQueue","uid":"dee6f0"}                                                  
cron_1   | Friendica[22]: daemon [WARNING]: system load for process too high. {"load":23.47119140625,"process":"backend","maxsysload":20} - {"file":"System.php","line":167,"function":"isMaxLoadReached","uid":"c8c1
57"}                                                                                                                                                                                                                 
cron_1   | Friendica[22]: daemon [WARNING]: system load for process too high. {"load":23.1142578125,"process":"backend","maxsysload":20} - {"file":"System.php","line":167,"function":"isMaxLoadReached","uid":"c8c15
7"}                                                                                                                                                                                                                  
cron_1   | Friendica[22]: daemon [WARNING]: system load for process too high. {"load":22.796875,"process":"backend","maxsysload":20} - {"file":"System.php","line":167,"function":"isMaxLoadReached","uid":"c8c157"} 
cron_1   | Friendica[22]: daemon [WARNING]: system load for process too high. {"load":22.4677734375,"process":"backend","maxsysload":20} - {"file":"System.php","line":167,"function":"isMaxLoadReached","uid":"c8c15
7"}                                                                                                                                                                                                                  
cron_1   | Friendica[22]: daemon [WARNING]: system load for process too high. {"load":22.1943359375,"process":"backend","maxsysload":20} - {"file":"System.php","line":167,"function":"isMaxLoadReached","uid":"c8c15
7"}                                                                                                                                                                                                                  
cron_1   | Friendica[22]: daemon [WARNING]: system load for process too high. {"load":21.89208984375,"process":"backend","maxsysload":20} - {"file":"System.php","line":167,"function":"isMaxLoadReached","uid":"c8c1
57"}                                                                                                                                                                                                                 
cron_1   | Friendica[22]: daemon [WARNING]: system load for process too high. {"load":21.5615234375,"process":"backend","maxsysload":20} - {"file":"System.php","line":167,"function":"isMaxLoadReached","uid":"c8c15
7"}                                                                                                                                                                                                                  
cron_1   | Friendica[22]: daemon [WARNING]: system load for process too high. {"load":21.3193359375,"process":"backend","maxsysload":20} - {"file":"System.php","line":167,"function":"isMaxLoadReached","uid":"c8c15
7"}
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 20.99853515625/20 - processes: 132/0/1401 (0:0) - maximum: 0/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"c8c157"}
cron_1   | Friendica[26]: worker [NOTICE]: Load: 20.99853515625/20 - processes: 132/1/1403 (0:1) - maximum: 0/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"86a896"}
cron_1   | Friendica[26]: worker [NOTICE]: Active worker limit reached, quitting. [] - {"file":"Worker.php","line":198,"function":"isReady","uid":"86a896"}
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 20.3232421875/20 - processes: 132/0/1403 (0:0) - maximum: 0/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"c8c157"}
cron_1   | Friendica[22]: daemon [NOTICE]: Load: 20.3232421875/20 - processes: 132/1/1403 (0:1) - maximum: 0/5 [] - {"file":"Worker.php","line":828,"function":"tooMuchWorkers","uid":"c8c157"}
cron_1   | Friendica[22]: daemon [NOTICE]: Active worker limit reached, quitting. [] - {"file":"Worker.php","line":198,"function":"isReady","uid":"c8c157"}
```
