### ISSUE TITLE
Delivery via email seems to be broken

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11661]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

A user of venera.social reported that delivery via email (built-in imap support) seems to be broken. He has the 'hourglass' as delivery indicator on those items. He thinks it stopped working around May, 27th. 

Please tell me what information do you need. I have nearly no experience with email contacts in Friendica. :-)

When I check the delivery queue I see some entries for his UID. So I checked the workerqueue table...

```
MariaDB [venera]> select * from workerqueue where parameter like '%1263%' and not done;
+----------+-----------------------------------+----------+---------------------+---------+---------------------+---------------------+---------+------+----------+
| id       | parameter                         | priority | created             | pid     | executed            | next_try            | retrial | done | command  |
+----------+-----------------------------------+----------+---------------------+---------+---------------------+---------------------+---------+------+----------+
| 76190987 | ["wall-new",21232485,925380,1263] |       20 | 2022-05-27 17:09:59 | 3422576 | 2022-06-20 17:56:01 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 76202503 | ["wall-new",21239475,925380,1263] |       20 | 2022-05-27 20:20:34 | 3422578 | 2022-06-20 17:56:02 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 76419119 | ["wall-new",21346788,648880,1263] |       20 | 2022-05-30 10:34:54 | 3422584 | 2022-06-20 17:56:02 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 76419491 | ["wall-new",21346955,635029,1263] |       20 | 2022-05-30 10:37:36 | 3422586 | 2022-06-20 17:56:02 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 76419492 | ["wall-new",21346955,648880,1263] |       20 | 2022-05-30 10:37:36 | 3422588 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 76419839 | ["wall-new",21347342,635029,1263] |       20 | 2022-05-30 10:47:01 | 3422600 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 76419840 | ["wall-new",21347342,648880,1263] |       20 | 2022-05-30 10:47:01 | 3422598 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 76420015 | ["wall-new",21347497,648880,1263] |       20 | 2022-05-30 10:51:19 | 3422597 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 77836482 | ["wall-new",22030339,648880,1263] |       20 | 2022-06-17 11:41:19 | 3422602 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 78113023 | ["wall-new",22135102,635029,1263] |       20 | 2022-06-20 09:27:30 | 3422594 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 78113024 | ["wall-new",22135102,644054,1263] |       20 | 2022-06-20 09:27:30 | 3422592 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 78113025 | ["wall-new",22135102,648880,1263] |       20 | 2022-06-20 09:27:30 | 3422634 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 78120921 | ["wall-new",22139752,635029,1263] |       20 | 2022-06-20 12:02:21 | 3422632 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
| 78120922 | ["wall-new",22139752,644054,1263] |       20 | 2022-06-20 12:02:21 | 3422636 | 2022-06-20 17:56:03 | 0001-01-01 00:00:00 |       0 |    0 | Delivery |
+----------+-----------------------------------+----------+---------------------+---------+---------------------+---------------------+---------+------+----------+
14 rows in set (0.002 sec)
```

And when I check the logs I find this exception that seems to be related to delivery via email...

```
worker [ERROR]: Uncaught Exception TypeError: "Argument 4 passed to Friendica\Model\Post\Media::splitAttachments() must be of the type bool, null given, called in /var/www/html/venera/src/Model/Item.php on line 2805" at /var/www/html/venera/src/Model/Post/Media.php line 553 {"exception":"TypeError: Argument 4 passed to Friendica\\Model\\Post\\Media::splitAttachments() must be of the type bool, null given, called in /var/www/html/venera/src/Model/Item.php on line 2805 and defined in /var/www/html/venera/src/Model/Post/Media.php:553
Stack trace:
#0 /var/www/html/venera/src/Model/Item.php(2805): Friendica\\Model\\Post\\Media::splitAttachments()
#1 /var/www/html/venera/src/Protocol/Email.php(379): Friendica\\Model\\Item::prepareBody()
#2 /var/www/html/venera/src/Worker/Delivery.php(573): Friendica\\Protocol\\Email::send()
#3 /var/www/html/venera/src/Worker/Delivery.php(232): Friendica\\Worker\\Delivery::deliverMail()
#4 [internal function]: Friendica\\Worker\\Delivery::execute()
#5 /var/www/html/venera/src/Core/Worker.php(486): call_user_func_array()
#6 /var/www/html/venera/src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()
#7 /var/www/html/venera/src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()
#8 /var/www/html/venera/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()
#9 {main}"} - {"file":null,"line":null,"function":null,"uid":"75e693","process_id":3422636}
```

### Steps to Reproduce

I don't know. I don't have any email contacts myself.

### Platform Info

Friendica Version:
2022.06 stable

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by MrPetovan** [comment]
I have a fix for it, thank you for your detailed report!

**Comment by AlfredSK** [comment]
Weird. When I put a normal Friendica contact into the TO: field and an email address into the CC: field and I hit submit the modal doesn't vanish. It stays open as if the submit button didn't work. I have hit that button 3 times and then closed the modal. Now I have three post delivered to the Friendica contact but none reached the email recipient.

But this is only an addition to what I have tested. The user has the email contacts in some privacy (contact) group and is addressing that group via the TO: field.

**Comment by AlfredSK** [comment]
> I have a fix for it, thank you for your detailed report!

Thanks! :-) Is this some plot to force me to switch to develop again (I like it to be on stable). :-D

**Comment by MrPetovan** [comment]
Always, you know us so well.

Come to the dark side 😈

**Comment by AlfredSK** [comment]
Ok. That works. Also the modal is closing automatically again after hitting 'submit'.

The subject of the received email looks weird. Is this normal/expected? 

Thunderbird UI:
`Subject: =?UTF-8?B?W0ZyaWVuZGljYV0gVmVuZXJhIE9uZSDwn42AIHBvc3RlZCBhbiB1cGRhdGUu?=`

Source text of the email:
`Subject: =?us-ascii?Q?=3D=3FUTF-8=3FB=3FW0ZyaWVuZGljYV0gVmVuZXJhIE9uZ?=  =?us-ascii?Q?SDwn42AIHBvc3RlZCBhbiB1cGRhdGUu=3F=3D?=`

**Comment by MrPetovan** [comment]
_Comment moved to https://github.com/friendica/friendica/issues/11666_
