### ISSUE TITLE
Still have a HTTP ERROR 500 WSoD

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#11704]
Still have a WSoD after the git pull just now.
These are the error messages from the Friendica log.
The first error message I get about 40 times a minute.
The second error messages I had only once.

```
2022-07-03T04:51:25Z index [ERROR]: Uncaught Exception TypeError: "Argument 2 passed to cookienotice_page_end() must be of the type array, string given, called in /src/Core/Hook.php on line 223" at /addon/cookienotice/cookienotice.php line 101 {"exception":"TypeError: Argument 2 passed to cookienotice_page_end() must be of the type array, string given, called in /src/Core/Hook.php on line 223 and defined in /addon/cookienotice/cookienotice.php:101\nStack trace:\n
#0 /src/Core/Hook.php(223): cookienotice_page_end()\n
#1 /src/Core/Hook.php(198): Friendica\\Core\\Hook::callSingle()\n
#2 /src/App/Page.php(488): Friendica\\Core\\Hook::callAll()\n
#3 /src/App.php(725): Friendica\\App\\Page->run()\n
#4 /index.php(44): Friendica\\App->runFrontend()\n
#5 {main}"} - {"file":null,"line":null,"function":null,"uid":"804ba2","process_id":1270}
```
```

2022-07-03T05:04:07Z worker [ERROR]: Unable to find owner data for uid {"uid":3,"callstack":"Probe::localProbe, Probe::uri, Contact::updateFromProbe, UpdateContact::execute, Worker::execFunction, Worker::execute, Worker::processQueue"} - {"file":"Transmitter.php","line":443,"function":"getProfile","uid":"a14ec2","process_id":9433}


2022-07-03T05:04:27Z index [ERROR]: DB Error {"code":1054,"error":"Unknown column 'posted' in 'order clause'","callstack":"Photo::selectToArray, photos_content, LegacyModule::runModuleFunction, LegacyModule::content, BaseModule::run, App::runFrontend","params":"SELECT `resource-id` FROM `photo` WHERE (`album` = 'Pinnwand-Bilder' AND `uid` = 2 AND `scale` = 0 AND (allow_cid = '' AND allow_gid = '' AND deny_cid = '' AND deny_gid = '') ) ORDER BY `posted` DESC"} - {"file":"Database.php","line":694,"function":"p","uid":"810a2f","process_id":979}

```

**Comment by MrPetovan** [comment]
I got you: https://github.com/friendica/friendica-addons/pull/1271
