### ISSUE TITLE
/api/v1/instance gives WSOD

### ISSUE THREAD

**Issue by xundeenergie** [friendica/friendica#11708]
i tried to open https://soc.schuerz.at/api/v1/instance and get an WSOD

My friendica.log says only this entry:

```
2022-07-04T22:22:09Z index [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Factory\Api\Mastodon\Account::createFromUriId() must be of the type int, null given, called in /var/www/soc.schuerz.at/src/Factory/Api/Mastodon/Account.php on line 66" at /var/www/soc.schuerz.at/src/Factory/Api/Mastodon/Account.php line 77 {"exception":"TypeError: Argument 1 passed to Friendica\\Factory\\Api\\Mastodon\\Account::createFromUriId() must be of the type int, null given, called in /var/www/soc.schuerz.at/src/Factory/Api/Mastodon/Account.php on line 66 and defined in /var/www/soc.schuerz.at/src/Factory/Api/Mastodon/Account.php:77\nStack trace:\n#0 /var/www/soc.schuerz.at/src/Factory/Api/Mastodon/Account.php(66): Friendica\\Factory\\Api\\Mastodon\\Account->createFromUriId()\n#1 /var/www/soc.schuerz.at/src/Object/Api/Mastodon/Instance.php(106): Friendica\\Factory\\Api\\Mastodon\\Account->createFromContactId()\n#2 /var/www/soc.schuerz.at/src/Module/Api/Mastodon/Instance.php(62): Friendica\\Object\\Api\\Mastodon\\Instance->__construct()\n#3 /var/www/soc.schuerz.at/src/BaseModule.php(238): Friendica\\Module\\Api\\Mastodon\\Instance->rawContent()\n#4 /var/www/soc.schuerz.at/src/Module/BaseApi.php(99): Friendica\\BaseModule->run()\n#5 /var/www/soc.schuerz.at/src/App.php(722): Friendica\\Module\\BaseApi->run()\n#6 /var/www/soc.schuerz.at/index.php(48): Friendica\\App->runFrontend()\n#7 {main}"} - {"file":null,"line":null,"function":null,"uid":"b834e6","process_id":144926}
```

activated php error-logging gives no output.

According to @annando i should report this issue

I run friendica on devel, commit c88898df9 with nginx on php7.4

I saw, that there are a lot of this ERROR-Lines in my log
For example this:
```
2022-07-04T22:41:53Z worker [ERROR]: Uncaught Exception TypeError: "Argument 2 passed to Friendica\Protocol\ActivityPub\Transmitter::sendContactReject() must be of the type int, string given, called in /var/www/
soc.schuerz.at/src/Core/Protocol.php on line 247" at /var/www/soc.schuerz.at/src/Protocol/ActivityPub/Transmitter.php line 2171 {"exception":"TypeError: Argument 2 passed to Friendica\\Protocol\\ActivityPub\\Tra
nsmitter::sendContactReject() must be of the type int, string given, called in /var/www/soc.schuerz.at/src/Core/Protocol.php on line 247 and defined in /var/www/soc.schuerz.at/src/Protocol/ActivityPub/Transmitte
r.php:2171\nStack trace:\n#0 /var/www/soc.schuerz.at/src/Core/Protocol.php(247): Friendica\\Protocol\\ActivityPub\\Transmitter::sendContactReject()\n#1 /var/www/soc.schuerz.at/src/Worker/Contact/RevokeFollow.php
(46): Friendica\\Core\\Protocol::revokeFollow()\n#2 [internal function]: Friendica\\Worker\\Contact\\RevokeFollow::execute()\n#3 /var/www/soc.schuerz.at/src/Core/Worker.php(486): call_user_func_array()\n#4 /var/
www/soc.schuerz.at/src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()\n#5 /var/www/soc.schuerz.at/src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()\n#6 /var/www/soc.schuerz.at/bin/worke
r.php(86): Friendica\\Core\\Worker::processQueue()\n#7 {main}"} - {"file":null,"line":null,"function":null,"uid":"cd1aeb","process_id":151629}
```

**Comment by MrPetovan** [comment]
Paging @quix0r

**Comment by Quix0r** [comment]
The returned record `$contact` from the line `$contact = Contact::getById($contactId, ['uri-id']);` has a NULL `uri-id` field. I don't know how to fix this with no more data available. The id here is clearly needed in line 79 what the `account-user-view` is being queried. A NULL allowed there would cause the `HTTPException\NotFoundException` be thrown. On my instance the same API call https://f.haeder.net/api/v1/instance doesn't fail. I would suggest, to prevent the `TypeError` message to come again, that I check on NULL in `$contact['uri-id']` and throw the exception before `return self::createFromUriId($contact['uri-id'], $uid);` is being invoked.

**Comment by MrPetovan** [comment]
What about the other errors they were reporting?

Cleaned below:
```
2022-07-04T22:41:53Z worker [ERROR]: Uncaught Exception TypeError: "Argument 2 passed to Friendica\Protocol\ActivityPub\Transmitter::sendContactReject() must be of the type int, string given, called in src/Core/Protocol.php on line 247" at src/Protocol/ActivityPub/Transmitter.php line 2171
{"exception":"TypeError: Argument 2 passed to Friendica\\Protocol\\ActivityPub\\Transmitter::sendContactReject() must be of the type int, string given, called in src/Core/Protocol.php on line 247 and defined in src/Protocol/ActivityPub/Transmitter.php:2171
Stack trace:
#0 src/Core/Protocol.php(247): Friendica\\Protocol\\ActivityPub\\Transmitter::sendContactReject()
#1 src/Worker/Contact/RevokeFollow.php(46): Friendica\\Core\\Protocol::revokeFollow()
#2 [internal function]: Friendica\\Worker\\Contact\\RevokeFollow::execute()\n#3 src/Core/Worker.php(486): call_user_func_array()
#4 src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()
#5 src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()
#6 bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n#7 {main}"} - {"file":null,"line":null,"function":null,"uid":"cd1aeb","process_id":151629}
```

**Comment by xundeenergie** [comment]
After the Update, it doesn't work...

But i got an error for a Profile-number.
It was my first created admin-user.

Then i go to the profile, set an Displayname, and then the /api/v1/instance-url worked magically.
