### ISSUE TITLE
Uncaught Exception: TypeError for Protocol\Email::messageGetPart()

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11724]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

I have upgraded libranet.de to current develop. Now I get a lot of the following error messages about an uncaught exception type error related to the email protocol.

```
2022-07-11T18:18:02Z worker [ERROR]: Uncaught Exception TypeError: "Argument 4 passed to Friendica\Protocol\Email::messageGetPart() must be an instance of Friendica\Protocol\in, int given, 
called in /var/www/html/libranet/src/Protocol/Email.php on line 148" 
at /var/www/html/libranet/src/Protocol/Email.php line 224 
{"exception":"TypeError: Argument 4 passed to Friendica\\Protocol\\Email::messageGetPart() must be an instance of Friendica\\Protocol\\in, int given, called in /var/www/html/libranet/src/Protocol/Email.php on line 148 and defined in /var/www/html/libranet/src/Protocol/Email.php:224
Stack trace:
#0 /var/www/html/libranet/src/Protocol/Email.php(148): Friendica\\Protocol\\Email::messageGetPart()
#1 /var/www/html/libranet/src/Worker/OnePoll.php(391): Friendica\\Protocol\\Email::getMessage()
#2 /var/www/html/libranet/src/Worker/OnePoll.php(95): Friendica\\Worker\\OnePoll::pollMail()
#3 [internal function]: Friendica\\Worker\\OnePoll::execute()\n#4 /var/www/html/libranet/src/Core/Worker.php(486): call_user_func_array()
#5 /var/www/html/libranet/src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()
#6 /var/www/html/libranet/src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()
#7 /var/www/html/libranet/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()
#8 {main}"} - 
{"file":null,"line":null,"function":null,"uid":"c8a413","process_id":3502213}
```

### Platform Info

Friendica Version:
2022.09-dev

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by MrPetovan** [comment]
There's a typo in the type-hint, I'm on it.
