### ISSUE TITLE
Never ending queries and high CPU/RAM usage on worker run

### ISSUE THREAD

**Issue by SpcCw** [friendica/friendica#11778]
Yesterday I updated to current develop, everything seemingly went fine for a while but after some hours my node became unresponsive. I noticed untypically high RAM usage by `/usr/bin/php bin/worker.php --no_cron` and things getting OOM-killed as the result. Also MariaDB used all CPU.

I have several processes of `/usr/bin/php bin/worker.php --no_cron` but only one is misbehaving, terminating it solves the problem until next cron worker run.

There are the following multiple running queries which seem to be generated by worker (if I kill one, it is created on worker next start):

```
+------+-----------+-----------+-----------+---------+------+--------------+------------------------------------------------------------------------------------------------------+----------+
| Id   | User      | Host      | db        | Command | Time | State        | Info                                                                                                 | Progress |
+------+-----------+-----------+-----------+---------+------+--------------+------------------------------------------------------------------------------------------------------+----------+
| 8284 | root      | localhost | NULL      | Query   |    0 | starting     | show  processlist                                                                                    |    0.000 |
| 8371 | friendica | localhost | friendica | Query   |  614 | Sending data | SELECT COUNT(*) AS `total` FROM `contact` INNER JOIN `photo` ON `contact`.`id` = `contact-id` WHERE  |    0.000 |
| 8496 | friendica | localhost | friendica | Query   |  413 | Sending data | SELECT COUNT(*) AS `total` FROM `contact` INNER JOIN `photo` ON `contact`.`id` = `contact-id` WHERE  |    0.000 |
| 8695 | friendica | localhost | friendica | Query   |  255 | Sending data | SELECT COUNT(*) AS `count` FROM `contact` WHERE (`id` != 0 AND `uid` = 0 AND NOT `self` AND NOT `nur |    0.000 |
```
First two queries in this example multiply over time but never complete. Over the night I had eight or so of them active, zero progress.
The third query remains one but also seems to never complete. These are reason for MariaDB to be hammering CPU.

There are the following errors in Friendica log appearing when worker starts.

This one happens periodically:

```
2022-07-27T03:21:40Z worker [ERROR]: Uncaught Exception TypeError: "Friendica\Worker\Contact\Remove::execute(): Argument #1 ($id) must be of type int, string given" at /usr/share/nginx/friends/src/Worker/Contact/Remove.php line 32 {"exception":"TypeError: Friendica\\Worker\\Contact\\Remove::execute(): Argument #1 ($id) must be of type int, string given in /usr/share/nginx/friends/src/Worker/Contact/Remove.php:32\nStack trace:\n#0 [internal function]: Friendica\\Worker\\Contact\\Remove::execute()\n#1 /usr/share/nginx/friends/src/Core/Worker.php(486): call_user_func_array()\n#2 /usr/share/nginx/friends/src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()\n#3 /usr/share/nginx/friends/src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()\n#4 /usr/share/nginx/friends/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n#5 {main}"} - {"file":null,"line":null,"function":null,"uid":"46bbb0","process_id":59803}
```

This one happens a lot:
```
2022-07-27T03:21:44Z worker [ERROR]: DB Error {"code":1062,"error":"Duplicate entry 'NowPlaying-https://gup.pe/u/nowplaying' for key 'type_name_url'","callstack":"DBA::update, Tag::store, Tag::storeByHash, Tag::storeFromBody, Processor::storeFromBody, Processor::processContent, Processor::createItem, Receiver::routeActivities","params":"UPDATE `tag` SET `name` = 'NowPlaying' WHERE (`url` = 'https://gup.pe/u/nowplaying')"} - {"file":"Database.php","line":801,"function":"e","uid":"0e53e9","process_id":59825}
2022-07-27T03:21:44Z worker [ERROR]: DB Error {"code":1062,"error":"Duplicate entry 'u/nowplaying-https://gup.pe/u/nowplaying' for key 'type_name_url'","callstack":"DBA::update, Tag::store, Processor::storeReceivers, Processor::processContent, Processor::createItem, Receiver::routeActivities, Queue::process, Queue::processAll","params":"UPDATE `tag` SET `name` = 'u/nowplaying' WHERE (`url` = 'https://gup.pe/u/nowplaying')"} - {"file":"Database.php","line":801,"function":"e","uid":"0e53e9","process_id":59825}
```
PHP 8.0.21, MariaDB 10.9.1

Please advise how to proceed further.

**Comment by MrPetovan** [comment]
@tobiasd already reproduced this behavior on his own node 😅

**Comment by tobiasd** [comment]
May be related to  #11759 at least for me the problems started after pulling in these changes.

**Comment by tobiasd** [comment]
Another case https://forum.friendi.ca/display/bf69967c-1662-e0d2-df46-265767358594

**Comment by tobiasd** [comment]
For now, I have checked out 37c3a92d2cb6bc2bd9632a8d5bf2ace371dbb89a using git in the Friendica directory, that is the last commit before #11759 

```
git checkout 37c3a92d2cb6bc2bd9632a8d5bf2ace371dbb89a
```

**Comment by annando** [comment]
With yesterday's PR and the one from today and endless loop was removed that surely affected the performance.

**Comment by tobiasd** [comment]
You mean #11782? I'll try

**Comment by annando** [comment]
You should wait for https://github.com/friendica/friendica/pull/11785

**Comment by tobiasd** [comment]
Too late, 11782 is helping a very little bit, but I reverted back to the commit mentioned before as the server LOAD is still at 120% (150% without 11782).

**Comment by SpcCw** [comment]
Updated to the latest develop. The load seems to went down (maybe it is a little early to tell but no workers maxing out RAM so far) however never ending queries seem to still be there and using up CPU.

```
SELECT COUNT(*) AS `total` FROM `contact` INNER JOIN `photo` ON `contact`.`id` = `contact-id` WHERE `contact`.`uid` = 0 AND NOT `self` AND (`photo` != '' OR `thumb` != '' OR `micro` != '') AND NOT `nurl` IN (SELECT `nurl` FROM `contact` WHERE `uid` != 0) AND NOT `contact`.`id` IN (SELECT `author-id` FROM `post-user`) AND NOT `contact`.`id` IN (SELECT `owner-id` FROM `post-user`) AND NOT `contact`.`id` IN (SELECT `causer-id` FROM `post-user`) AND NOT `contact`.`id` IN (SELECT `cid` FROM `post-tag`) AND NOT `contact`.`id` IN (SELECT `contact-id` FROM `post-user`)
```
and
```
SELECT COUNT(*) AS `count` FROM `contact` WHERE (`id` != 0 AND `uid` = 0 AND NOT `self` AND NOT `nurl` IN (SELECT `nurl` FROM `contact` WHERE `uid` != 0) AND (NOT `network` IN ('dfrn', 'dspr', 'stat', 'feed', 'mail', 'apub') OR (`archive` AND `success_update` < '2021-07-28 12:44:10')) AND NOT `id` IN (SELECT `author-id` FROM `post-user`) AND NOT `id` IN (SELECT `owner-id` FROM `post-user`) AND NOT `id` IN (SELECT `causer-id` FROM `post-user`) AND NOT `id` IN (SELECT `cid` FROM `post-tag`) AND NOT `id` IN (SELECT `contact-id` FROM `post-user`) AND NOT `id` IN (SELECT `cid` FROM `user-contact`) AND NOT `id` IN (SELECT `cid` FROM `event`) AND NOT `id` IN (SELECT `contact-id` FROM `group_member`) AND `created` < '2022-06-28 12:44:10')
```
Currently I have two cores loaded at 100% by MariaDB.

**Comment by SpcCw** [comment]
Maybe worth noting but if I manually run this it hangs:
```
SELECT COUNT(*) AS `total` FROM `contact` INNER JOIN `photo` ON `contact`.`id` = `contact-id` WHERE `contact`.`uid` = 0 AND NOT `self` AND (`photo` != '' OR `thumb` != '' OR `micro` != '') AND NOT `nurl` IN (SELECT `nurl` FROM `contact` WHERE `uid` != 0) AND NOT `contact`.`id` IN (SELECT `author-id` FROM `post-user`) AND NOT `contact`.`id` IN (SELECT `owner-id` FROM `post-user`) AND NOT `contact`.`id` IN (SELECT `causer-id` FROM `post-user`) AND NOT `contact`.`id` IN (SELECT `cid` FROM `post-tag`) AND NOT `contact`.`id` IN (SELECT `contact-id` FROM `post-user`)
```
But if I run this it gets through:
```
SELECT COUNT(*) AS `total` FROM `contact` INNER JOIN `photo` ON `contact`.`id` = `contact-id` WHERE `contact`.`uid` = 0 AND NOT `self` AND (`photo` != '' OR `thumb` != '' OR `micro` != '')
AND NOT `nurl` IN (SELECT `nurl` FROM `contact` WHERE `uid` != 0) AND NOT `contact`.`id` IN (SELECT `author-id` FROM `post-user`) AND NOT `contact`.`id` IN (SELECT `owner-id` FROM `post-user`) AND NOT `contact`.`id` IN (SELECT `cid` FROM `post-tag`) AND NOT `contact`.`id` IN (SELECT `contact-id` FROM `post-user`);
```
It is the same query but with this part removed:
```
AND NOT `contact`.`id` IN (SELECT `causer-id` FROM `post-user`)
```

**Comment by tobiasd** [comment]
With 11785 it a bearable on my system, but far worse then before. System LOAD is down to ~80% before iit was around 30%, but at least there seem to be no more endless loops and the worker processes come to an end.

**Comment by SpcCw** [comment]
I don't seem to have problem with workers anymore just with never-ending queries but it is likely separate problem: https://github.com/friendica/friendica/issues/11465 These are the same queries that misbehave, last time it somehow resolved itself for a while but now came back.

Workers seem to be fine now.

**Comment by annando** [comment]
Are there still any load/cpu/ram issues out there?

**Comment by SpcCw** [comment]
> Are there still any load/cpu/ram issues out there?

It is fine for me now. Load is back to normal and never ending queries are also gone.

Unless @tobiasd has something to add I'd consider this issue resolved.

**Comment by tobiasd** [comment]
For me the problem is solved as well. Especially with the new options the admin can set in the config file to avoid some completions the system has been really quiet lately :)
