### ISSUE TITLE
Uncaught Exception TypeError on Friendica\Model\User::getIdForURL()

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#11931]
### Bug Description
I have a lot of these errors/exceptions in my log:
```
worker [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Model\User::getIdForURL() must be of the type string, null given, called in .../src/Protocol/ActivityPub/Processor.php on line 1731" at .../src/Model/User.php line 341
{"exception":"TypeError: Argument 1 passed to Friendica\\Model\\User::getIdForURL() must be of the type string, null given, 
called in .../src/Protocol/ActivityPub/Processor.php on line 1731 and 
defined in .../src/Model/User.php:341
Stack trace:
#0 .../src/Protocol/ActivityPub/Processor.php(1731): Friendica\\Model\\User::getIdForURL()
#1 .../src/Protocol/ActivityPub/Receiver.php(855): Friendica\\Protocol\\ActivityPub\\Processor::acceptFollowUser()
#2 ---/src/Protocol/ActivityPub/Queue.php(239): Friendica\\Protocol\\ActivityPub\\Receiver::routeActivities()
#3 .../src/Worker/ProcessQueue.php(39): Friendica\\Protocol\\ActivityPub\\Queue::process()
#4 [internal function]: Friendica\\Worker\\ProcessQueue::execute()
#5 .../src/Core/Worker.php(563): call_user_func_array()
#6 .../src/Core/Worker.php(381): Friendica\\Core\\Worker::execFunction()
#7 .../src/Core/Worker.php(106): Friendica\\Core\\Worker::execute()
#8 .../bin/worker.php(86): Friendica\\Core\\Worker::processQueue()
#9 {main}"} - 
{"file":null,"line":null,"function":null,"uid":"519839","process_id":204982}
```

### Platform Info

Friendica Version:
2022.09-rc

Friendica Source: 
git

PHP version:
7.4

SQL version:
MariaDB 10.6

**Comment by MrPetovan** [comment]
@annando The `object_actor` key isn't set in `Processor::acceptFollowUser()` for the activities coming from the `inbox-entry` table. It looks like it would be set in the other case when called from `Receiver::processActivity()`. I don't know how to debug this further.

**Comment by annando** [comment]
`object_actor` is set in the receiver function `prepareObjectData`. This called by `processActivity`. After this the activity array is either stored in queue for the delayed processing or is processed directly via `routeActivities` which then calls `acceptFollowUser`.

To analyse this data we will need to have the raw data that is received.

@AlfredSK it would be interesting to see all log entries that contain this text: `"uid":"519839","process_id":204982`.

**Comment by AlfredSK** [comment]
@annando Ok. Will do that now.

**Comment by AlfredSK** [comment]
Log level debug:

```
2022-09-28T15:04:46Z worker [NOTICE]: Load: 1.6/24 - processes: 4483/5/36 - jpm: 77/137/194 (0:4, 40:1) - maximum: 25/30 [] - {"file":"Worker.php","line":808,"function":"tooMuchWorkers","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:46Z worker [INFO]: There are fewer workers as possible, fork a new worker. {"active":5,"queues":25} - {"file":"Worker.php","line":812,"function":"tooMuchWorkers","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:46Z worker [INFO]: Connection usage (system values) {"used":11,"max":512} - {"file":"Worker.php","line":693,"function":"maxConnectionsReached","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:47Z worker [INFO]: No running worker found with priority 40 - assigning it. {"priority":40} - {"file":"Worker.php","line":960,"function":"nextPriority","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:47Z worker [INFO]: Found: {"priority":40,"id":[336148635]} - {"file":"Worker.php","line":921,"function":"nextProcess","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:47Z worker [INFO]: Set queue entry {"pid":3251270,"ids":[336148635,344625230]} - {"file":"Worker.php","line":1063,"function":"findWorkerProcesses","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:47Z worker [INFO]: Connection usage (system values) {"used":13,"max":512} - {"file":"Worker.php","line":693,"function":"maxConnectionsReached","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:47Z worker [INFO]: Process start. {"priority":40,"id":336148635,"worker_id":"67a9e62","worker_cmd":"ProcessQueue"} - {"file":"Worker.php","line":553,"function":"execFunction","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:47Z worker [INFO]: Start processing queue entry {"id":531528,"worker_id":"67a9e62","worker_cmd":"ProcessQueue"} - {"file":"ProcessQueue.php","line":38,"function":"execute","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:47Z worker [DEBUG]: Processing queue entry {"id":531528,"type":"as:Accept","object-type":"as:Follow","uri":"https://libranet.de/objects/0b6b25a8-1462-eb4e-f7a9-eb9289549846","in-reply-to":null,"callstack":"ProcessQueue::execute, Worker::execFunction, Worker::execute, Worker::processQueue","worker_id":"67a9e62","worker_cmd":"ProcessQueue"} - {"file":"Queue.php","line":217,"function":"process","uid":"4b15a7","process_id":3251270}
2022-09-28T15:04:47Z worker [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Model\User::getIdForURL() must be of the type string, null given, called in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php on line 1731" at /var/www/html/libranet/src/Model/User.php line 341 {"exception":"TypeError: Argument 1 passed to Friendica\\Model\\User::getIdForURL() must be of the type string, null given, called in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php on line 1731 and defined in /var/www/html/libranet/src/Model/User.php:341\nStack trace:\n#0 /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php(1731): Friendica\\Model\\User::getIdForURL()\n#1 /var/www/html/libranet/src/Protocol/ActivityPub/Receiver.php(855): Friendica\\Protocol\\ActivityPub\\Processor::acceptFollowUser()\n#2 /var/www/html/libranet/src/Protocol/ActivityPub/Queue.php(239): Friendica\\Protocol\\ActivityPub\\Receiver::routeActivities()\n#3 /var/www/html/libranet/src/Worker/ProcessQueue.php(39): Friendica\\Protocol\\ActivityPub\\Queue::process()\n#4 [internal function]: Friendica\\Worker\\ProcessQueue::execute()\n#5 /var/www/html/libranet/src/Core/Worker.php(570): call_user_func_array()\n#6 /var/www/html/libranet/src/Core/Worker.php(388): Friendica\\Core\\Worker::execFunction()\n#7 /var/www/html/libranet/src/Core/Worker.php(113): Friendica\\Core\\Worker::execute()\n#8 /var/www/html/libranet/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n#9 {main}"} - {"file":null,"line":null,"function":null,"uid":"4b15a7","process_id":3251270}
```

**Comment by AlfredSK** [comment]
Another example with more lines :-)

```
2022-09-28T15:09:50Z worker [NOTICE]: Load: 1.91/24 - processes: 4501/2/22 - jpm: 571/244/207 (0:2) - maximum: 24/30 [] - {"file":"Worker.php","line":808,"function":"tooMuchWorkers","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: There are fewer workers as possible, fork a new worker. {"active":2,"queues":24} - {"file":"Worker.php","line":812,"function":"tooMuchWorkers","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Connection usage (system values) {"used":3,"max":512} - {"file":"Worker.php","line":693,"function":"maxConnectionsReached","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: No running worker found with priority 20 - assigning it. {"priority":20} - {"file":"Worker.php","line":960,"function":"nextPriority","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Found: {"priority":20,"id":[344626902]} - {"file":"Worker.php","line":921,"function":"nextProcess","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Set queue entry {"pid":3258323,"ids":[344626902]} - {"file":"Worker.php","line":1063,"function":"findWorkerProcesses","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Connection usage (system values) {"used":3,"max":512} - {"file":"Worker.php","line":693,"function":"maxConnectionsReached","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Process start. {"priority":20,"id":344626902,"worker_id":"f7841f2","worker_cmd":"ProcessQueue"} - {"file":"Worker.php","line":553,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Start processing queue entry {"id":2438415,"worker_id":"f7841f2","worker_cmd":"ProcessQueue"} - {"file":"ProcessQueue.php","line":38,"function":"execute","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: Processing queue entry {"id":2438415,"type":"as:Delete","object-type":"as:Tombstone","uri":"https://nuklear.family/users/andi/statuses/102672680933508474","in-reply-to":null,"callstack":"ProcessQueue::execute, Worker::execFunction, Worker::execute, Worker::processQueue","worker_id":"f7841f2","worker_cmd":"ProcessQueue"} - {"file":"Queue.php","line":217,"function":"process","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: Contact found {"url":"https://nuklear.family/users/andi","uid":0,"update":null,"cid":448210,"worker_id":"f7841f2","worker_cmd":"ProcessQueue"} - {"file":"Contact.php","line":1232,"function":"getIdForURL","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Deleting item {"object":"https://nuklear.family/users/andi/statuses/102672680933508474","owner":448210,"worker_id":"f7841f2","worker_cmd":"ProcessQueue"} - {"file":"Processor.php","line":612,"function":"deleteItem","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: DELETE FROM `inbox-entry`  WHERE (`id` = 2438415) {"callstack":"DBA::delete, Queue::remove, Processor::deleteItem, Receiver::routeActivities, Queue::process, ProcessQueue::execute"} - {"file":"Database.php","line":1282,"function":"delete","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Successfully processed queue entry {"result":true,"id":2438415,"worker_id":"f7841f2","worker_cmd":"ProcessQueue"} - {"file":"ProcessQueue.php","line":40,"function":"execute","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Performance: {"state":1,"count":0,"stat":0.01,"write":0,"lock":0,"total":0.02,"rest":0,"exec":0.02} - {"file":"Worker.php","line":595,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Process done. {"priority":20,"id":344626902,"duration":0.02} - {"file":"Worker.php","line":616,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: ID 344626902: ProcessQueue {"action":"profiling","database_read":0,"database_write":0,"cache_read":0,"cache_write":0,"network_io":0,"file_io":0,"other_io":0.02,"total":0.02} - {"file":"Worker.php","line":618,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: No running worker found with priority 20 - assigning it. {"priority":20} - {"file":"Worker.php","line":960,"function":"nextPriority","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Found: {"priority":20,"id":[344625085]} - {"file":"Worker.php","line":921,"function":"nextProcess","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Set queue entry {"pid":3258323,"ids":[344625085]} - {"file":"Worker.php","line":1063,"function":"findWorkerProcesses","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Connection usage (system values) {"used":4,"max":512} - {"file":"Worker.php","line":693,"function":"maxConnectionsReached","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Process start. {"priority":20,"id":344625085,"worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Worker.php","line":553,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Start processing queue entry {"id":2437925,"worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"ProcessQueue.php","line":38,"function":"execute","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: Processing queue entry {"id":2437925,"type":"as:Delete","object-type":"as:Tombstone","uri":"https://octodon.social/users/kingu_platypus_gidora/statuses/108042575755725713","in-reply-to":null,"callstack":"ProcessQueue::execute, Worker::execFunction, Worker::execute, Worker::processQueue","worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Queue.php","line":217,"function":"process","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: Contact found {"url":"https://octodon.social/users/kingu_platypus_gidora","uid":0,"update":null,"cid":63752,"worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Contact.php","line":1232,"function":"getIdForURL","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Deleting item {"object":"https://octodon.social/users/kingu_platypus_gidora/statuses/108042575755725713","owner":63752,"worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Processor.php","line":612,"function":"deleteItem","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Mark item for deletion by id {"id":181150948,"callstack":"Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities, Queue::process","worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Item.php","line":298,"function":"markForDeletionById","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: DELETE FROM `post-category`  WHERE (`uri-id` = 68617554 AND `uid` = 0) {"callstack":"DBA::delete, Category::deleteByURIId, Item::markForDeletionById, Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities"} - {"file":"Database.php","line":1282,"function":"delete","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Start Update {"fields":{"deleted":true,"edited":"2022-09-28 15:09:50","changed":"2022-09-28 15:09:50"},"condition":{"id":181150948},"uid":false,"callstack":"Item::markForDeletionById, Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities, Queue::process, ProcessQueue::execute, Worker::execFunction, Worker::execute, Worker::processQueue","worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Post.php","line":510,"function":"update","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Updated posts {"rows":1,"worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Post.php","line":638,"function":"update","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: DELETE FROM `post-category`  WHERE (`uri-id` = 68617554 AND `uid` = 0) {"callstack":"DBA::delete, Category::storeTextByURIId, Item::markForDeletionById, Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities"} - {"file":"Database.php","line":1282,"function":"delete","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: DELETE FROM `post-delivery-data`  WHERE (`uri-id` = 68617554) {"callstack":"DeliveryData::delete, Item::markForDeletionById, Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities, Queue::process"} - {"file":"Database.php","line":1282,"function":"delete","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Item has been marked for deletion. {"id":181150948,"worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Item.php","line":377,"function":"markForDeletionById","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Mark item for deletion by id {"id":181150950,"callstack":"Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities, Queue::process","worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Item.php","line":298,"function":"markForDeletionById","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: DELETE FROM `post-category`  WHERE (`uri-id` = 68617554 AND `uid` = 2121) {"callstack":"DBA::delete, Category::deleteByURIId, Item::markForDeletionById, Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities"} - {"file":"Database.php","line":1282,"function":"delete","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Start Update {"fields":{"deleted":true,"edited":"2022-09-28 15:09:50","changed":"2022-09-28 15:09:50"},"condition":{"id":181150950},"uid":false,"callstack":"Item::markForDeletionById, Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities, Queue::process, ProcessQueue::execute, Worker::execFunction, Worker::execute, Worker::processQueue","worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Post.php","line":510,"function":"update","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Updated posts {"rows":1,"worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Post.php","line":638,"function":"update","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: DELETE FROM `post-category`  WHERE (`uri-id` = 68617554 AND `uid` = 2121) {"callstack":"DBA::delete, Category::storeTextByURIId, Item::markForDeletionById, Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities"} - {"file":"Database.php","line":1282,"function":"delete","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: DELETE FROM `post-delivery-data`  WHERE (`uri-id` = 68617554) {"callstack":"DeliveryData::delete, Item::markForDeletionById, Item::markForDeletion, Processor::deleteItem, Receiver::routeActivities, Queue::process"} - {"file":"Database.php","line":1282,"function":"delete","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Item has been marked for deletion. {"id":181150950,"worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"Item.php","line":377,"function":"markForDeletionById","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [DEBUG]: DELETE FROM `inbox-entry`  WHERE (`id` = 2437925) {"callstack":"DBA::delete, Queue::remove, Processor::deleteItem, Receiver::routeActivities, Queue::process, ProcessQueue::execute"} - {"file":"Database.php","line":1282,"function":"delete","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Successfully processed queue entry {"result":true,"id":2437925,"worker_id":"9a9f18b","worker_cmd":"ProcessQueue"} - {"file":"ProcessQueue.php","line":40,"function":"execute","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Performance: {"state":3,"count":0,"stat":0,"write":0.01,"lock":0,"total":0.01,"rest":0,"exec":0.06} - {"file":"Worker.php","line":595,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: Process done. {"priority":20,"id":344625085,"duration":0.059} - {"file":"Worker.php","line":616,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:50Z worker [INFO]: ID 344625085: ProcessQueue {"action":"profiling","database_read":0,"database_write":0,"cache_read":0,"cache_write":0,"network_io":0,"file_io":0,"other_io":0.06,"total":0.06} - {"file":"Worker.php","line":618,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: No running worker found with priority 40 - assigning it. {"priority":40} - {"file":"Worker.php","line":960,"function":"nextPriority","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Found: {"priority":40,"id":[336148635]} - {"file":"Worker.php","line":921,"function":"nextProcess","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Set queue entry {"pid":3258323,"ids":[336148635,344626916]} - {"file":"Worker.php","line":1063,"function":"findWorkerProcesses","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Connection usage (system values) {"used":20,"max":512} - {"file":"Worker.php","line":693,"function":"maxConnectionsReached","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Process start. {"priority":20,"id":344626916,"worker_id":"6d76720","worker_cmd":"SpoolPost"} - {"file":"Worker.php","line":553,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Spool file does does not start with "item-" {"file":".","worker_id":"6d76720","worker_cmd":"SpoolPost"} - {"file":"SpoolPost.php","line":41,"function":"execute","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Spool file does does not start with "item-" {"file":"..","worker_id":"6d76720","worker_cmd":"SpoolPost"} - {"file":"SpoolPost.php","line":41,"function":"execute","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Start Update {"fields":{"global":true},"condition":{"uri-id":84092625},"uid":false,"callstack":"Item::insert, SpoolPost::execute, Worker::execFunction, Worker::execute, Worker::processQueue","worker_id":"6d76720","worker_cmd":"SpoolPost"} - {"file":"Post.php","line":510,"function":"update","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Updated posts {"rows":0,"worker_id":"6d76720","worker_cmd":"SpoolPost"} - {"file":"Post.php","line":638,"function":"update","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Got page url (link with description) {"uri-id":84092625,"url":"https://www.currenttime.tv/a/mikhailov/32055635.html","worker_id":"6d76720","worker_cmd":"SpoolPost"} - {"file":"Media.php","line":443,"function":"insertFromRelevantUrl","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Media already exists {"uri-id":84092625,"url":"https://www.currenttime.tv/a/mikhailov/32055635.html","callstack":"Item::insert, SpoolPost::execute, Worker::execFunction, Worker::execute","worker_id":"6d76720","worker_cmd":"SpoolPost"} - {"file":"Media.php","line":83,"function":"insert","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [NOTICE]: Post-User is already inserted - aborting {"uid":0,"uri-id":84092625,"worker_id":"6d76720","worker_cmd":"SpoolPost"} - {"file":"Item.php","line":1226,"function":"insert","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Spool file is stored {"file":"item-16643777460654-1997478174.msg","result":0,"worker_id":"6d76720","worker_cmd":"SpoolPost"} - {"file":"SpoolPost.php","line":75,"function":"execute","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Performance: {"state":4,"count":0,"stat":0,"write":0.09,"lock":0.82,"total":0.1,"rest":0,"exec":0.05} - {"file":"Worker.php","line":595,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Process done. {"priority":20,"id":344626916,"duration":0.052} - {"file":"Worker.php","line":616,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: ID 344626916: SpoolPost {"action":"profiling","database_read":0,"database_write":0,"cache_read":0,"cache_write":0,"network_io":0,"file_io":0,"other_io":0.05,"total":0.05} - {"file":"Worker.php","line":618,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Connection usage (system values) {"used":13,"max":512} - {"file":"Worker.php","line":693,"function":"maxConnectionsReached","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Process start. {"priority":40,"id":336148635,"worker_id":"63ff49a","worker_cmd":"ProcessQueue"} - {"file":"Worker.php","line":553,"function":"execFunction","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [INFO]: Start processing queue entry {"id":531528,"worker_id":"63ff49a","worker_cmd":"ProcessQueue"} - {"file":"ProcessQueue.php","line":38,"function":"execute","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [DEBUG]: Processing queue entry {"id":531528,"type":"as:Accept","object-type":"as:Follow","uri":"https://libranet.de/objects/0b6b25a8-1462-eb4e-f7a9-eb9289549846","in-reply-to":null,"callstack":"ProcessQueue::execute, Worker::execFunction, Worker::execute, Worker::processQueue","worker_id":"63ff49a","worker_cmd":"ProcessQueue"} - {"file":"Queue.php","line":217,"function":"process","uid":"09a096","process_id":3258323}
2022-09-28T15:09:51Z worker [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Model\User::getIdForURL() must be of the type string, null given, called in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php on line 1731" at /var/www/html/libranet/src/Model/User.php line 341 {"exception":"TypeError: Argument 1 passed to Friendica\\Model\\User::getIdForURL() must be of the type string, null given, called in /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php on line 1731 and defined in /var/www/html/libranet/src/Model/User.php:341\nStack trace:\n#0 /var/www/html/libranet/src/Protocol/ActivityPub/Processor.php(1731): Friendica\\Model\\User::getIdForURL()\n#1 /var/www/html/libranet/src/Protocol/ActivityPub/Receiver.php(855): Friendica\\Protocol\\ActivityPub\\Processor::acceptFollowUser()\n#2 /var/www/html/libranet/src/Protocol/ActivityPub/Queue.php(239): Friendica\\Protocol\\ActivityPub\\Receiver::routeActivities()\n#3 /var/www/html/libranet/src/Worker/ProcessQueue.php(39): Friendica\\Protocol\\ActivityPub\\Queue::process()\n#4 [internal function]: Friendica\\Worker\\ProcessQueue::execute()\n#5 /var/www/html/libranet/src/Core/Worker.php(570): call_user_func_array()\n#6 /var/www/html/libranet/src/Core/Worker.php(388): Friendica\\Core\\Worker::execFunction()\n#7 /var/www/html/libranet/src/Core/Worker.php(113): Friendica\\Core\\Worker::execute()\n#8 /var/www/html/libranet/bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n#9 {main}"} - {"file":null,"line":null,"function":null,"uid":"09a096","process_id":3258323}
```

**Comment by annando** [comment]
Thanks for the data. I guess I know what is happening. Under some circumstances Friendica is sending "follow" requests for posts. This is done to ensure that we receive all updates in the thread. We don't expect an answer to those messages. It seems as if some system is answering this. With PR  #11944 we now log this to see if and how we can handle this.

**Comment by MrPetovan** [comment]
The PR technically solves this issue, do you want to keep it open to find a way to handle the unexpected messages?

**Comment by annando** [comment]
It would be great if @AlfredSK could have a look for the log message `Unhandled "accept follow" message.` and then report it here. Then I can have a look where it originates. Then we can decide what to do.

**Comment by AlfredSK** [comment]
I guess log level 'notice' is sufficient, right?

**Comment by annando** [comment]
Yes

**Comment by AlfredSK** [comment]
Hmm. I don't find any message with `Unhandled "accept follow" message` in my log file. I'm on log level 'notice'.

I'll try again later.

**Comment by AlfredSK** [comment]
Still nothing.

**Comment by annando** [comment]
Then we can define this as some hiccup of some other system and possibly can close this issue?

**Comment by AlfredSK** [comment]
Sure, if it's nothing serious.
