### ISSUE TITLE
Setting up RSS feeds no longer works

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#12090]
After I want to add this RSS feed

`https://wtf.roflcopter.fr/rss-bridge/?action=display&bridge=TwitterBridge&context=By+username&u=QuarkDDR&norep=on&noretweet=on&nopinned=on&nopic=on&format=Atom`

 I get the following.

```
Exception thrown in /src/Module/HTTPException/PageNotFound.php:49
Stack trace:
#0 /src/BaseModule.php(244): Friendica\Module\HTTPException\PageNotFound->content()
#1 /src/Module/HTTPException/PageNotFound.php(80): Friendica\BaseModule->run()
#2 /src/App.php(736): Friendica\Module\HTTPException\PageNotFound->run()
#3 /index.php(44): Friendica\App->runFrontend()
#4 {main}
```
<details>
<summary>Moved</summary>

to https://github.com/friendica/friendica/issues/11992#issuecomment-1298614361

```
worker [ERROR]: Uncaught Exception TypeError: "Friendica\Worker\UpdateContact::execute(): Argument 
#1 ($contact_id) must be of type int, null given" at /src/Worker/UpdateContact.php line 35 {"exception":"TypeError: Friendica\\Worker\\UpdateContact::execute(): Argument 
#1 ($contact_id) must be of type int, null given in /www/meld/src/Worker/UpdateContact.php:35\nStack trace:\n#0 [internal function]: Friendica\\Worker\\UpdateContact::execute()\n
#1 /src/Core/Worker.php(571): call_user_func_array()\n
#2 /src/Core/Worker.php(386): Friendica\\Core\\Worker::execFunction()\n
#3 /src/Core/Worker.php(121): Friendica\\Core\\Worker::execute()\n
#4 /bin/worker.php(86): Friendica\\Core\\Worker::processQueue()\n
#5 {main}"} - {"file":null,"line":null,"function":null,"uid":"447900","process_id":127573}
```

</details>

**Comment by MrPetovan** [comment]
Thank you for your report, the worker error is different from the web frontend error you're getting. I have the feeling it has to do with #12077 by @nupplaphil
