### ISSUE TITLE
Add new WordPress Contact Failed

### ISSUE THREAD

**Issue by chefblogger** [friendica/friendica#12101]
i tried to add my blog as a contact to my friendica.

when i use the search field - top right - i get a undefined error msg:
![Bildschirmfoto 2022-11-04 um 09 54 28](https://user-images.githubusercontent.com/70014924/199934246-26aa8265-e162-486b-a6f3-d5fbfb29c698.png)

then i tried it with the add contact form field - now my blog is recognized correctly and the data displayed is correct
![Bildschirmfoto 2022-11-04 um 10 00 17](https://user-images.githubusercontent.com/70014924/199934233-3cdd75d3-992f-44a2-bf1f-39957865494e.png)

but after i clicked on the button "add contact" i got this error msg
![Bildschirmfoto 2022-11-04 um 09 58 47](https://user-images.githubusercontent.com/70014924/199934241-118a9232-c1e3-435a-a252-64ad8ac042d0.png)

unfortunately this errormessage is unclear to me

i dont know is this a error because i did something wrong with my friendica installation or if it a bug.

i connected my wordpress blog with the activitypub plugin https://wordpress.org/plugins/activitypub/
and btw on my mastodon instance there was no error when i added my blog into this feed.

in any case I hope that should it be a bug you take this up and should it be a faulty installation that you give me a tip on how I can patch the error

**Comment by MrPetovan** [comment]
Hi, thank you for your report. are you running your node on the `stable` branch or on the `develop` branch? Also can you please share the URL you tried to add?

**Comment by chefblogger** [comment]
@MrPetovan  - i use 
"Friendica 'Giant Rhubarb' 2022.10 - 1484"

and my new contact was `@Eric@www.chefblogger.me` - it is a wordpress blog.

**Comment by MrPetovan** [comment]
Using `@Eric@www.chefblogger.me` in the top search field I'm able to find your contact:
<img width="957" alt="Screen Shot 2022-11-04 at 11 10 15" src="https://user-images.githubusercontent.com/925415/200009271-d80d2be0-2bbc-4068-b0f7-1eb26b038bf6.png">

But I'm on the 2022.12-dev version so I'm not sure it's something that was broken in the stable version that we already fixed in the develop branch or particular to your own case.

**Comment by foss-** [comment]
Confirming `The network type couldn't be detected. Contact can't be added.` when trying to add `@Eric@www.chefblogger.me` when trying to add contact from left panel add contact option (which differs from the initial report) on
Friendica, version 2022.09-rc that is running at the web location https://squeet.me. The database version is 1484/1484, the post update version is 1484/1484.

**Comment by MrPetovan** [comment]
`2022.09-rc` huh, please try to update to at least stable first?

**Comment by foss-** [comment]
Ping @annando can I haz `stable` on squeet me?

<img src="https://user-images.githubusercontent.com/5708172/200052658-1d922f8b-fe5c-4276-95fb-f714fd1392cb.jpg" data-canonical-src="https://user-images.githubusercontent.com/5708172/200052658-1d922f8b-fe5c-4276-95fb-f714fd1392cb.jpg" width="300" />

**Comment by annando** [comment]
I applied some manual changes there, so that updating to "stable" is kind of problematic. I wanted to update when "develop" is mostly stable.

**Comment by informapirata** [comment]
> please try to update to at least stable first?

Unfortunately I too have the same error and my instance runs the rel. 2023.01... 😩

**Comment by MrPetovan** [comment]
Can you share the profile URL you're trying to follow that gives the same error?

**Comment by foss-** [comment]
Retested with `@Eric@www.chefblogger.me` on pirati ca and it now works fine also using the top right search field.

**Comment by informapirata** [comment]
> Ritestato con `@Eric@www.chefblogger.me`su pirate ca e ora funziona benissimo anche utilizzando il campo di ricerca in alto a destra.

I'm sorry, but Friendica doesn't make it possible for me to follow that contact. In practice, the contact is identified, but I am not able to follow him.
I made several tests from different instances, with the rel. 2023.01.

I believe that in Friendica there is some kind of interference between the priority ability to follow the rss feed of the wordpress user (or site) and the ability to follow the user as if he were an ActivityPub object.

The fact is that today Friendica is unable to follow that type of user

**Comment by MrPetovan** [comment]
Can you please test with `https://www.chefblogger.me/author/eric/` ?

**Comment by foss-** [comment]
@chefblogger could you retry this with with 2023.01 and report back if this is persisting for you.

**Comment by informapirata** [comment]
> Can you please test with `https://www.chefblogger.me/author/eric/` ?

I can easily find the contact by pasting the link in the search box, but when I try to follow him I get this warning:

Not found
Invalid contact
```
Exception thrown in /var/www/friendica/src/Model/Group.php:293
Stack trace:
#0 /var/www/friendica/src/Model/Contact.php(3018): Friendica\Model\Group::addMember(2, 476049)
#1 /var/www/friendica/src/Module/Contact/Follow.php(206): Friendica\Model\Contact::createFromProbeForUser(3, 'https://www.che...')
#2 /var/www/friendica/src/Module/Contact/Follow.php(152): Friendica\Module\Contact\Follow->process('https://www.che...')
#3 /var/www/friendica/src/BaseModule.php(244): Friendica\Module\Contact\Follow->content(Array)
#4 /var/www/friendica/src/App.php(746): Friendica\BaseModule->run(Array)
#5 /var/www/friendica/index.php(44): Friendica\App->runFrontend(Object(Friendica\App\Router), Object(Friendica\Core\PConfig\Type\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), Object(Friendica\Util\HTTPInputData), 1675921443.2612)
#6 {main}
```

**Comment by foss-** [comment]
Following from the search result form the top search bar works fine on pirati ca.

squeet me results in "Not Found. Contact not found. Request: 63e4b05d5d340".

So while the error message differs for me on squeet me, following does indeed work from pirati ca.

@informapirata it would be interesting to learn, if this problem is also resolved when you re-try from latest development version.

**Comment by informapirata** [comment]
> @informapirata it would be interesting to learn, if this problem is also resolved when you re-try from latest development version.

It's great news that the Release candidate allows you to follow the contact.
You have verified that the contact is followed with the DRFN protocol and not with the RSS protocol?

We actually never install the Release candidate but we always try to install the latest release within 10 days of the release to prevent those who use the system for semi-professional purposes from finding themselves with problems.

In any case, I really believe that the compatibility between Friendica and the WordPress plugin (plugin unfortunately still a bit immature...) can seal Friendica's primacy as reference software in the fediverse for integrated content publication
