### ISSUE TITLE
A relative URI must not have a path beginning with a segment containing a colon

### ISSUE THREAD

**Issue by bkil** [friendica/friendica#12113]
Unfortunately, I don't have access to the input as it's not my log.

```
2022-11-05T19:46:14Z worker [ERROR]: Uncaught
 Exception InvalidArgumentException: "A relative URI must not have a path beginning with a segment containing a colon"
 at /var/www/html/example.com/vendor/guzzlehttp/psr7/src/Uri.php line 798
 {"exception":"InvalidArgumentException: A relative URI must not have a path beginning with a segment containing a colon
 in /var/www/html/example.com/vendor/guzzlehttp/psr7/src/Uri.php:798\n
 Stack trace:\n
 #0 /var/www/html/example.com/vendor/guzzlehttp/psr7/src/Uri.php(418): GuzzleHttp\\Psr7\\Uri->validateState()\n
 #1 /var/www/html/example.com/src/Model/Item.php(3051): GuzzleHttp\\Psr7\\Uri::fromParts(Array)\n
 #2 /var/www/html/example.com/src/Model/Post/Media.php(405): Friendica\\Model\\Item::containsLink('[img]\\r\\nhttps://...', '\\r\\nhttps://reisu...', 1)\n
 #3 /var/www/html/example.com/src/Model/Item.php(1119): Friendica\\Model\\Post\\Media::insertFromBody(3500627, '#[url=https://f...')\n
 #4 /var/www/html/example.com/src/Model/Item.php(1718): Friendica\\Model\\Item::insert(Array, 0)\n
 #5 /var/www/html/example.com/src/Model/Item.php(1584): Friendica\\Model\\Item::storeForUser(Array, 8)\n
 #6 /var/www/html/example.com/src/Worker/Notifier.php(801): Friendica\\Model\\Item::storeForUserByUriId(3500627, 8, Array, 1)\n
 #7 /var/www/html/example.com/src/Worker/Notifier.php(185): Friendica\\Worker\\Notifier::activityPubDelivery('wall-new', Array, Array, Array, 20, '2022-11-04 00:5...', Array)\n
 #8 [internal function]: Friendica\\Worker\\Notifier::execute('wall-new', 3500627, 1)\n
 #9 /var/www/html/example.com/src/Core/Worker.php(578): call_user_func_array('Friendica\\\\Worke...', Array)\n
 #10 /var/www/html/example.com/src/Core/Worker.php(388): Friendica\\Core\\Worker::execFunction(Array, 'Notifier', Array, true)\n
 #11 /var/www/html/example.com/src/Core/Worker.php(113): Friendica\\Core\\Worker::execute(Array)\n
 #12 /var/www/html/example.com/bin/worker.php(86): Friendica\\Core\\Worker::processQueue(true, Object(Friendica\\Core\\Worker\\Entity\\Process))\n
 #13 {main}"}
  - {"file":null,"line":null,"function":null,"uid":"eb52fa","process_id":19206}
```

* https://github.com/guzzle/psr7/blob/1.x/src/Uri.php#L798
* https://github.com/friendica/friendica/blob/stable/src/Model/Item.php#L3051
* https://github.com/friendica/friendica/blob/stable/src/Model/Post/Media.php#L405
* https://github.com/friendica/friendica/blob/stable/src/Worker/Notifier.php#L801

**Comment by MrPetovan** [comment]
Hrm, thanks for the report, without the original post content, we can only vaguely address the problem, mainly sweep the error under the rug.

**Comment by bkil** [comment]
I've already asked the admin to find out the exact post content for us. I'll post an update if he succeeds.

**Comment by MrPetovan** [comment]
I suggested a PR that includes logging in this particular case.
