### ISSUE TITLE
Activating Piwik Addon crashed friendica completely

### ISSUE THREAD

**Issue by matthiasmoritz** [friendica/friendica#12199]
Instantly after activating the piwik plugin friendica was complete creashed (Internal Server Error 500)
I tried to delete the registered hook directly in the db and removed the piwik column in the addon table. But it's still the same. Can someone help?

```
2022-11-17T19:21:40Z index [ERROR]: Uncaught Exception TypeError: "piwik_analytics(): Argument #2 ($b) must be of type array, string given, called in /var/www/virtual/punkrock/friendica/src/Core/Hook.php on line 223" at /var/www/virtual/punkrock/friendica/addon/piwik/piwik.php line 53 {"exception":"TypeError: piwik_analytics(): Argument #2 ($b) must be of type array, string given, called in /var/www/virtual/punkrock/friendica/src/Core/Hook.php on line 223 and defined in /var/www/virtual/punkrock/friendica/addon/piwik/piwik.php:53\nStack trace:
#0 /var/www/virtual/punkrock/friendica/src/Core/Hook.php(223): piwik_analytics(Object(Friendica\\App), '<div class=\"gen...')
#1 /var/www/virtual/punkrock/friendica/src/Core/Hook.php(198): Friendica\\Core\\Hook::callSingle(Object(Friendica\\App), 'page_end', Array, '<div class=\"gen...')
#2 /var/www/virtual/punkrock/friendica/src/App/Page.php(493): Friendica\\Core\\Hook::callAll('page_end', '<div class=\"gen...'
n#3 /var/www/virtual/punkrock/friendica/src/App.php(722): Friendica\\App\\Page->run(Object(Friendica\\App), Object(Friendica\\App\\BaseURL), Object(Friendica\\App\\Arguments), Object(Friendica\\App\\Mode), Object(GuzzleHttp\\Psr7\\Response), Object(Friendica\\Core\\L10n), Object(Friendica\\Util\\Profiler), Object(Friendica\\Core\\Config\\Type\\JitConfig), Object(Friendica\\Core\\PConfig\\Type\\JitPConfig))
#4 /var/www/virtual/punkrock/friendica/index.php(44): Friendica\\App->runFrontend(Object(Friendica\\App\\Router), Object(Friendica\\Core\\PConfig\\Type\\JitPConfig), Object(Friendica\\Security\\Authentication), Object(Friendica\\App\\Page), Object(Friendica\\Util\\HTTPInputData), 1668712900.3974
n#5 {main}"} - {"file":null,"line":null,"function":null,"uid":"e2bc7f","process_id":31147}```

**Comment by matthiasmoritz** [comment]
ok, i have overseen one of the hooks (page end). After deleting this on the db the application is accessible again. 
anyway... this should be fixed

**Comment by Schnoop** [comment]
This one has been fixed some days ago (https://github.com/friendica/friendica-addons/commit/b9207f7e48e2fd16be00eecb9830815133b4a868). Try to update the addon code using this repo:

https://github.com/friendica/friendica-addons

**Comment by matthiasmoritz** [comment]
This is only fixed in the dev branch (I'm on stable). But fixed anyway. Let's close this ticket than
