### ISSUE TITLE
Invalid contact with user already in DB with a mirror.

### ISSUE THREAD

**Issue by Shnoulle** [friendica/friendica#12230]
- [x] I have searched open and closed issues for duplicates

### Bug Description

get an invalid contact when contact already connected via GnuSocial bridge.

### Steps to Reproduce

1.  Activate GnuSocial bridge
2.  Get a contact on GnuSocial
3.  Find this contact on Friendica
4. contact are shown as "Gnu social connector"
5. Unconnecet with user on GnuSocial
6. Disable GnuSocial conector
7. Open contact on Friendica
8. Click on Send request

Actual Result:

get a 404 error
```
Not Found

Invalid contact.

#0 /home/social.example.net/www/src/Model/Contact.php(2945): Friendica\Model\Group::addMember()
#1 /home/social.example.net/www/mod/follow.php(177): Friendica\Model\Contact::createFromProbeForUser()
#2 /home/social.example.net/www/mod/follow.php(48): follow_process()
#3 /home/social.example.net/www/src/LegacyModule.php(96): follow_post()
#4 /home/social.example.net/www/src/LegacyModule.php(80): Friendica\LegacyModule->runModuleFunction()
#5 /home/social.example.net/www/src/BaseModule.php(228): Friendica\LegacyModule->post()
#6 /home/social.example.net/www/src/App.php(719): Friendica\BaseModule->run()
#7 /home/social.example.net/www/index.php(44): Friendica\App->runFrontend()
#8 {main}
```

Expected Result:

Allowed to move contact to local Friendica contact

### Screenshots

![Capture d’écran du 2022-11-21 09-52-37](https://user-images.githubusercontent.com/1439428/203007000-75505339-8450-408f-aa6c-9b20415284af.png)

### Platform Info

Friendica Version :Friendica 'Giant Rhubarb' 2022.10 - 1484

Friendica Source: github (here)

PHP version: 7.4

SQL version: mariadb

**Comment by Shnoulle** [comment]
Result of probe (anonymized)


```
Array
(
    [name] => Anonymized
    [nick] => anonymized
    [guid] => 
    [url] => https://pouet.example.org/users/anonymized
    [addr] => anonymized@pouet.example.org
    [alias] => https://pouet.example.org/@anonymized
    [photo] => https://paul.pouet.example.org/pouet-eu-central/accounts/avatars/000/000/001/original/XXXXXXXX.png
    [header] => https://paul.pouet.example.org/pouet-eu-central/accounts/headers/000/000/001/original/XXXXXXXXX.png
    [account-type] => 0
    [community] => 
    [keywords] => 
    [location] => 
    [about] => Etc etc etc (valid one)
    [xmpp] => 
    [matrix] => 
    [hide] => 1
    [batch] => https://pouet.example.org/inbox
    [notify] => https://pouet.example.org/users/anonymized/inbox
    [poll] => https://pouet.example.org/users/anonymized/outbox
    [request] => 
    [confirm] => 
    [subscribe] => https://pouet.example.org/authorize_interaction?uri={uri}
    [poco] => 
    [following] => https://pouet.example.org/users/anonymized/following
    [followers] => https://pouet.example.org/users/anonymized/followers
    [inbox] => https://pouet.example.org/users/anonymized/inbox
    [outbox] => https://pouet.example.org/users/anonymized/outbox
    [sharedinbox] => https://pouet.example.org/inbox
    [priority] => 0
    [network] => apub
    [pubkey] => -----BEGIN PUBLIC KEY-----
VALIDPUBKEY
EQIDAQAB
-----END PUBLIC KEY-----
    [manually-approve] => 0
    [baseurl] => https://pouet.example.org
    [gsid] => 337
)
```
