### ISSUE TITLE
404 error when making a search

### ISSUE THREAD

**Issue by villisek** [friendica/friendica#12274]
Hello, 

I'm a new Friendica user and I set up my own Friendica instance. However, after setup, I'm encountering an issue when I'm trying to find an user (i.e., my old profile on Mastodon). Whatever I type in the search box, when submitting I get a 404 error page with this error:

```
Exception produite dans /var/www/html/src/Module/HTTPException/PageNotFound.php:49
Stack trace:
#0 /var/www/html/src/BaseModule.php(244): Friendica\Module\HTTPException\PageNotFound->content()
#1 /var/www/html/src/Module/HTTPException/PageNotFound.php(80): Friendica\BaseModule->run()
#2 /var/www/html/src/App.php(719): Friendica\Module\HTTPException\PageNotFound->run()
#3 /var/www/html/index.php(44): Friendica\App->runFrontend()
#4 {main}
```

And the URL of the search page is (redacted host): `/search?q=%40cvillisek89%40noc.social`

I'm not sure whether it is a bug or an issue related to my set-up... 
I'm using Nginx on Debian, with the rewrite rules provided in the config example on Github. I also disabled cgi fixpath in the PHP FPM config. I don't know where it comes from, as I'm not seeing this error in neither nginx nor php-fpm logs. 

Is it a bug?

**Comment by MrPetovan** [comment]
Hi, please make sure your nginx rewrite blocks look like this:
```
  location / {
    try_files $uri /index.php?pagename=$uri&$args;
  }

  location ^~ /.well-known/ {
    allow all;
    rewrite ^ /index.php?pagename=$uri;
  }
```
The important part is that `q=` shouldn't be used for rewriting as it conflicts with the search parameter.

**Comment by miiichael** [comment]
FWIW I had this problem and it helped me! I had originally configured my instance using hints from [here](https://github.com/filipesaraiva/friendica/blob/master/mods/sample-nginx.config), though I now see that the main friendica repo has something different. 😅

**Comment by annando** [comment]
@miiichael that repo is really ancient 😀 

BTW: I guess we can close this issue.

**Comment by miiichael** [comment]
Yeah, I feel that the wiki (which I probably ignored at the time because I wanted friendica at the top level instead of a subpath) ought to mention that there are configuration examples _right there_ in the repo... 😅

**Comment by annando** [comment]
Sadly we are lacking people who want to contribute in the Wiki.
