### ISSUE TITLE
Getting now this in the Friendica logs

### ISSUE THREAD

**Issue by ghost** [friendica/friendica#12343]
Has anything been changed?
The Friendica log now looks like this.

```
 thrown {"code":1,"message":"Uncaught Error: Class \"Friendica\\Util\\DateTimeFormat\" not found in /src/Core/Logger/Type/StreamLogger.php:169\nStack trace:\n#0 /src/Core/Logger/Type/StreamLogger.php(148): Friendica\\Core\\Logger\\Type\\StreamLogger->formatLog()\n#1 /src/Core/Logger/Type/AbstractLogger.php(204): Friendica\\Core\\Logger\\Type\\StreamLogger->addEntry()\n#2 /src/Core/Logger/Handler/ErrorHandler.php(272): Friendica\\Core\\Logger\\Type\\AbstractLogger->log()\n#3 /vendor/composer/ClassLoader.php(444): Friendica\\Core\\Logger\\Handler\\ErrorHandler->handleError()\n#4 /vendor/composer/ClassLoader.php(444): include('...')\n#5 /vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile()\n#6 /src/Core/Logger/Type/StreamLogger.php(169): Composer\\Autoload\\ClassLoader->loadClass()\n#7 /src/Core/Logger/Type/StreamLogger.php(148): Friendica\\Core\\Logger\\Type\\StreamLogger->formatLog()\n#8 /src/Core/Logger/Type/AbstractLogger.php(204): Friendica\\Core\\Logger\\Type\\StreamLogger->addEntry()\n#9 /src/Core/Logger/Handler/ErrorHandler.php(236): Friendica\\Core\\Logger\\Type\\AbstractLogger->log()\n#10 /src/Core/Logger/Handler/ErrorHandler.php(128): Friendica\\Core\\Logger\\Handler\\ErrorHandler->handleException()\n#11 [internal function]: Friendica\\Core\\Logger\\Handler\\ErrorHandler->Friendica\\Core\\Logger\\Handler\\{closure}()\n#12 {main}\n  thrown","file":"/src/Core/Logger/Type/StreamLogger.php","line":169,"trace":null} - {"file":null,"line":null,"function":null,"uid":"ae3d20","process_id":1057608}
2022-12-06T10:42:59Z worker [ALERT]: Fatal Error (E_ERROR): Uncaught Error: Class "Friendica\Util\DateTimeFormat" not found in /src/Core/Logger/Type/StreamLogger.php:169
Stack trace:
#0 /src/Core/Logger/Type/StreamLogger.php(148): Friendica\Core\Logger\Type\StreamLogger->formatLog()
#1 /src/Core/Logger/Type/AbstractLogger.php(204): Friendica\Core\Logger\Type\StreamLogger->addEntry()
#2 /src/Core/Logger/Handler/ErrorHandler.php(272): Friendica\Core\Logger\Type\AbstractLogger->log()
#3 /vendor/composer/ClassLoader.php(444): Friendica\Core\Logger\Handler\ErrorHandler->handleError()
#4 /vendor/composer/ClassLoader.php(444): include('...')
#5 /vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#6 /src/Core/Logger/Type/StreamLogger.php(169): Composer\Autoload\ClassLoader->loadClass()
#7 /src/Core/Logger/Type/StreamLogger.php(148): Friendica\Core\Logger\Type\StreamLogger->formatLog()
#8 /src/Core/Logger/Type/AbstractLogger.php(204): Friendica\Core\Logger\Type\StreamLogger->addEntry()
#9 /src/Core/Logger/Handler/ErrorHandler.php(236): Friendica\Core\Logger\Type\AbstractLogger->log()
#10 /src/Core/Logger/Handler/ErrorHandler.php(128): Friendica\Core\Logger\Handler\ErrorHandler->handleException()
#11 [internal function]: Friendica\Core\Logger\Handler\ErrorHandler->Friendica\Core\Logger\Handler\{closure}()
#12 {main}
```

**Comment by MrPetovan** [comment]
Please run `bin/composer.phar dumpautoload`
