### ISSUE TITLE
Profiles no longer accessible

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#12476]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description
All profile pages according to the patterns https://domain/profile/user are no longer accessible.
https://loma.ml/display/373ebf56-7963-a02f-f476-24c859179147

https://anonsys.net/display/bf69967c-4763-a028-97ce-f46927945968
https://mecp.de/atagajigir.php

### Platform Info

Friendica Version: 2022.12-rc

Friendica Source: git

PHP version: 7.4

SQL version: 10.4

**Comment by AlfredSK** [comment]
```
index [ERROR]: Uncaught Exception TypeError: "Argument 1 passed to Friendica\Module\Profile\Profile::__construct() must be an instance of Friendica\Profile\ProfileField\Repository\ProfileField, instance of Friendica\Core\L10n given, called in /var/www/html/libranet/src/Module/Profile/Index.php on line 40" at /var/www/html/libranet/src/Module/Profile/Profile.php line 69 
{"exception":"TypeError: Argument 1 passed to Friendica\\Module\\Profile\\Profile::__construct() must be an instance of Friendica\\Profile\\ProfileField\\Repository\\ProfileField, instance of Friendica\\Core\\L10n given, called in /var/www/html/libranet/src/Module/Profile/Index.php on line 40 and defined in /var/www/html/libranet/src/Module/Profile/Profile.php:69
Stack trace:
#0 /var/www/html/libranet/src/Module/Profile/Index.php(40): Friendica\\Module\\Profile\\Profile->__construct()
#1 /var/www/html/libranet/src/BaseModule.php(238): Friendica\\Module\\Profile\\Index->rawContent()
#2 /var/www/html/libranet/src/App.php(746): Friendica\\BaseModule->run()
#3 /var/www/html/libranet/index.php(44): Friendica\\App->runFrontend()
#4 {main}"} - {"file":null,"line":null,"function":null,"uid":"254d37","process_id":1822543}
```

**Comment by kr428** [comment]
Seems to work again. Thanks all.
