### ISSUE TITLE
Error retrieving notifications and clicking on the Friendica icon 

### ISSUE THREAD

**Issue by sekretaerbaer** [friendica/friendica#12537]
- [x] I have searched open and closed issues for duplicates

### Bug Description

after today's git pull I have the problem that when I also click a notification I get the following error message

```
Exception thrown in /var/www/html/src/Core/System.php:502
Stack trace:
#0 /var/www/html/src/Module/Notifications/Notification.php(197): Friendica\Core\System::externalRedirect()
#1 /var/www/html/src/Module/Notifications/Notification.php(142): Friendica\Module\Notifications\Notification->handleNotification()
#2 /var/www/html/src/BaseModule.php(244): Friendica\Module\Notifications\Notification->content()
#3 /var/www/html/src/App.php(719): Friendica\BaseModule->run()
#4 /var/www/html/index.php(44): Friendica\App->runFrontend()
#5 {main}
```

also I get an error message when I click on the Friendica icon 

```
Exception thrown in /var/www/html/src/Core/System.php:502
Stack trace:
#0 /var/www/html/src/App/BaseURL.php(460): Friendica\Core\System::externalRedirect()
#1 /var/www/html/src/Module/Home.php(46): Friendica\App\BaseURL->redirect()
#2 /var/www/html/src/BaseModule.php(244): Friendica\Module\Home->content()
#3 /var/www/html/src/App.php(719): Friendica\BaseModule->run()
#4 /var/www/html/index.php(44): Friendica\App->runFrontend()
#5 {main}
```

with a 
`git checkout fa579c234 `
I could reset the source so far that the error is gone. So I assume that the reason for the error is in commit 
_"5c332af84 (origin/develop, origin/HEAD, develop) Merge pull request #12527 from nupplaphil/feat/request_id"._ 

### Platform Info

Friendica Version: Friendica 'Giant Rhubarb' 2023.03-dev - 1504

Friendica Source: 

PHP version: PHP 7.4.3

SQL version: Ver 10.3.37-MariaDB-0ubuntu0.20.04.1 for debian-linux-gnu on x86_64 (Ubuntu 20.04)

**Comment by nupplaphil** [comment]
I'm not able to reproduce it :-/ .. I now use the current  develop branch for opensocial.at and friendica.me with a few hundred users, but no such error .. can you retry it?

**Comment by haheute** [comment]
i think i have the same errors:

```
Exception thrown in /var/www/localhost/friendica/src/Core/System.php:502
Stack trace:
#0 /var/www/localhost/friendica/src/Module/Notifications/Notification.php(197): Friendica\Core\System::externalRedirect()
#1 /var/www/localhost/friendica/src/Module/Notifications/Notification.php(142): Friendica\Module\Notifications\Notification->handleNotification()
#2 /var/www/localhost/friendica/src/BaseModule.php(244): Friendica\Module\Notifications\Notification->content()
#3 /var/www/localhost/friendica/src/App.php(719): Friendica\BaseModule->run()
#4 /var/www/localhost/friendica/index.php(44): Friendica\App->runFrontend()
#5 {main}
```

```
Exception thrown in /var/www/localhost/friendica/src/Core/System.php:502
Stack trace:
#0 /var/www/localhost/friendica/src/App/BaseURL.php(460): Friendica\Core\System::externalRedirect()
#1 /var/www/localhost/friendica/src/Module/Home.php(46): Friendica\App\BaseURL->redirect()
#2 /var/www/localhost/friendica/src/BaseModule.php(244): Friendica\Module\Home->content()
#3 /var/www/localhost/friendica/src/App.php(719): Friendica\BaseModule->run()
#4 /var/www/localhost/friendica/index.php(44): Friendica\App->runFrontend()
#5 {main}
```
Diese Friendica-Instanz verwendet die Version 2023.03-dev, sie ist unter der folgenden Adresse im Web zu finden https://amical.info. Die Datenbankversion ist 1504/1504 und die Post-Update-Version 1484/1484.

PHP 8.1.13
mysql  Ver 15.1 Distrib 10.6.11-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by nupplaphil** [comment]
got it .. :)
