### ISSUE TITLE
Error when trying to follow via API

### ISSUE THREAD

**Issue by olemara** [friendica/friendica#12798]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Doing a request for the path /api/v1/accounts/69/follow gives me the error:

```
Fatal error: Uncaught TypeError: Argument 1 passed to Friendica\Object\Api\Mastodon\Relationship::__construct()
must be of the type int, null given, called in /var/www/html/src/Factory/Api/Mastodon/Relationship.php on line 47 and
defined in /var/www/html/src/Object/Api/Mastodon/Relationship.php:80
Stack trace:
#0 src/Factory/Api/Mastodon/Relationship.php(47): Friendica\Object\Api\Mastodon\Relationship->__construct(NULL, false, false, false)
#1 src/Module/Api/Mastodon/Accounts/Follow.php(45): Friendica\Factory\Api\Mastodon\Relationship->createFromContactId(-1, 41)
#2 [internal function]: Friendica\Module\Api\Mastodon\Accounts\Follow::post(Array)
#3 src/App/Module.php(320): call_user_func(Array, Array)
#4 src/App.php(703): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\VoidLogger), Object(Friendica\Util\Profiler), Array, Array)
#5 index.php(42): Friendica\App->runFrontend(Object(Friendica in /var/www/html/src/Object/Api/Mastodon/Relationship.php on line 80
```
I am using the ID after searching the endpoint: /api/users/search?q=testouput2

Expected Result:

Using basic authorization, the user should follow the user with the abovementioned id.

### Platform Info

Friendica Version:
friendica: 2021.09-apache

**Comment by foss-** [comment]
There was some work on the API in the past year. Is this problem persisting with the current stable release?
