### ISSUE TITLE
Display pages won't load (but admin will) after some server changes

### ISSUE THREAD

**Issue by jakedfw** [friendica/friendica#12794]
Here's the error I'm getting: 
![image](https://user-images.githubusercontent.com/38843638/218770287-b93f1268-505d-4467-9470-cfdb4eceba17.png)

Any ideas what might cause this?

**Comment by MrPetovan** [comment]
What PHP version are you running?

**Comment by jakedfw** [comment]
8.7.1

**Comment by MrPetovan** [comment]
The current latest stable PHP version is 8.2.3, how did you get this version number?

**Comment by jakedfw** [comment]
I'm using Ubuntu 22.10 via Digital Ocean. The repositories don't have the latest php version yet (will have to wait until Ubuntu releases version 23, I think). 

Here's the PHP version (from Ubuntu command line):

`PHP 8.1.7-1ubuntu3.2 (cli) (built: Jan 16 2023 15:18:41) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.7, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.7-1ubuntu3.2, Copyright (c), by Zend Technologies`

**Comment by jakedfw** [comment]
(and sorry, I wrote 8.7.1. I meant 8.1.7!!)

**Comment by jakedfw** [comment]
Here's the full error:

```
Error: Typed property DOMAttr::$name must not be accessed before initialization in /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php:267
Stack trace:
#0 /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php(222): HTMLPurifier_Lexer_DOMLex->transformAttrToAssoc()
#1 /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php(118): HTMLPurifier_Lexer_DOMLex->createStartNode()
#2 /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Lexer/DOMLex.php(90): HTMLPurifier_Lexer_DOMLex->tokenizeDOM()
#3 /var/www/html/vendor/ezyang/htmlpurifier/library/HTMLPurifier.php(213): HTMLPurifier_Lexer_DOMLex->tokenizeHTML()
#4 /var/www/html/src/Content/Text/HTML.php(1001): HTMLPurifier->purify()
#5 /var/www/html/src/Content/Text/BBCode.php(2182): Friendica\Content\Text\HTML::purify()
#6 /var/www/html/src/Content/Text/BBCode.php(474): Friendica\Content\Text\BBCode::convert()
#7 /var/www/html/src/Navigation/Notifications/Factory/Notification.php(196): Friendica\Content\Text\BBCode::toPlaintext()
#8 /var/www/html/src/Navigation/Notifications/Factory/FormattedNavNotification.php(124): Friendica\Navigation\Notifications\Factory\Notification->getMessageFromNotification()
#9 /var/www/html/src/Module/Notifications/Ping.php(220): Friendica\Navigation\Notifications\Factory\FormattedNavNotification->createFromNotification()
#10 [internal function]: Friendica\Module\Notifications\Ping->Friendica\Module\Notifications\{closure}()
#11 /var/www/html/src/Module/Notifications/Ping.php(224): array_map()
#12 /var/www/html/src/BaseModule.php(238): Friendica\Module\Notifications\Ping->rawContent()
#13 /var/www/html/src/App.php(746): Friendica\BaseModule->run()
#14 /var/www/html/index.php(44): Friendica\App->runFrontend()
#15 {main}
```

**Comment by MrPetovan** [comment]
I tracked the error in the library's issue tracker: https://github.com/ezyang/htmlpurifier/issues/365

The cause is the PHP version used, and the original reporter solved it by jumping straight to PHP 8.2. Would you be able to downgrade to PHP 8.0 or upgrade to PHP 8.2?

**Comment by jakedfw** [comment]
Unfortunately I went with Ubuntu 22.10, which doesn't have an upgrade path to 8.2. I'll need to wait until the next release in April. 

The other solution is to do a total re-install of my OS. Don't want to do that!

**Comment by sekretaerbaer** [comment]
Unfortunately, it looks like Ubuntu 23.04 lunar will still be released with PHP 8.1. 
Package php

    lunar (php): server-side, HTML-embedded scripting language (default)
    2:8.1+92ubuntu1: all
    also provided by: php8.1, uwsgi-plugin-php

for php 8.2 under Ubuntu 22.10 the only possibility would be to use an external ppa. 


https://php.watch/articles/install-php82-ubuntu-debian

**Comment by annando** [comment]
Don't we have got a config option to deactivate the purifier?

**Comment by jakedfw** [comment]
> Unfortunately, it looks like Ubuntu 23.04 lunar will still be released with PHP 8.1. Package php
> 
> ```
> lunar (php): server-side, HTML-embedded scripting language (default)
> 2:8.1+92ubuntu1: all
> also provided by: php8.1, uwsgi-plugin-php
> ```
> 
> for php 8.2 under Ubuntu 22.10 the only possibility would be to use an external ppa.
> 
> https://php.watch/articles/install-php82-ubuntu-debian

Unfortunately, the PPA maintainer has said he will not support non-LTS Ubuntu releases, so 22.10 and the others after that will not be able to get the incremental packages from him or elsewhere (from what I've found).

**Comment by jakedfw** [comment]
I was able to use my Digital Ocean backups to roll back to a previous snapshot. That has this version of php which works fine. Somewhere in there I did an update that overwrote this. So the previous version above is problematic.
<img width="437" alt="image" src="https://user-images.githubusercontent.com/38843638/219277412-a805cffd-e8d3-4ac4-ae9e-781b8f8bb7f3.png">

**Comment by MrPetovan** [comment]
April came and went, and we did another release, can you please retry to upgrade Friendica, Ubuntu and PHP?
