### ISSUE TITLE
Error when adding user via console.php

### ISSUE THREAD

**Issue by olemara** [friendica/friendica#12800]
- [x] I have searched open and closed issues for duplicates

### Bug Description

I am trying to add a user via console.php with the following command:

```
root@2073d0613a08:/var/www/html# php bin/console.php user add test3 test3 testing@testing.com en -y -v
Executable: bin/console.php
Arguments: array (
  0 => 'user',
  1 => 'add',
  2 => 'test3',
  3 => 'test3',
  4 => 'testing@testing.com',
  5 => 'en',
)
Options: array (
  'y' => 1,
  'v' => 1,
)
Command: user
Class: Friendica\Console\User
Arguments: array (
  0 => 'add',
  1 => 'test3',
  2 => 'test3',
  3 => 'testing@testing.com',
  4 => 'en',
)
Options: array (
  'y' => 1,
  'v' => 1,
)
[Error] Call to a member function setFirstIterator() on null
[Backtrace]:
#0 /var/www/html/src/Object/Image.php(545): Friendica\Object\Image->scale(300, 300)
#1 /var/www/html/src/Model/User.php(1214): Friendica\Object\Image->scaleToSquare(300)
#2 /var/www/html/src/Model/User.php(1408): Friendica\Model\User::create(Array)
#3 /var/www/html/src/Console/User.php(268): Friendica\Model\User::createMinimal('test3', 'testing@testing...', 'test3', 'en')
#4 /var/www/html/src/Console/User.php(123): Friendica\Console\User->addUser()
#5 /var/www/html/vendor/asika/simple-console/src/Console.php(108): Friendica\Console\User->doExecute()
#6 /var/www/html/src/Core/Console.php(163): Asika\SimpleConsole\Console->execute()
#7 /var/www/html/vendor/asika/simple-console/src/Console.php(108): Friendica\Core\Console->doExecute()
#8 /var/www/html/bin/console.php(41): Asika\SimpleConsole\Console->execute()
#9 {main}
```

Looking at the code, an image should be present for the code to reach that point. But there is no check of the iterator, nor is the exception caught. This means the logic that adds a use do not fully finish. But, the user is present when listing users via the console application.

### Steps to Reproduce
Run the above mentioned command.

1.  step one
2.  step two
3.  step three

Actual Result:

Expected Result:
No error message

### Platform Info

Friendica Version:
Friendica Console version 2023.01

Friendica Source: 

PHP version:

SQL version:

**Comment by MrPetovan** [comment]
Do you have by any chance any avatar addon loaded? In the `createMinimal` scenario, the only way there can be a photo at this point is if an addon provides it based on the email address.
