### ISSUE TITLE
[flaw] Table 'addon' gets recreated on each update

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#12828]
- [x] I have searched open and closed issues for duplicates

### Bug Description

The said table gets here recreated each time I run the update procedure. So this is what [my script](https://f.haeder.net/deploy.sh) does:

### Steps to Reproduce

1. After the usual steps of stopping daemon and updating files, including addons, run `./bin/console dbstructure update`
2. `./bin/console postupdate` (this step creates the table `addon`)
3. `./bin/console dbstructure drop -e` (this step removes it again)

Actual Result:

````
./deploy.sh: post-update ...
Check for pending update actions.
CREATE TABLE IF NOT EXISTS `addon` (
        `id` int unsigned NOT NULL auto_increment COMMENT '',
        `name` varchar(50) NOT NULL DEFAULT '' COMMENT 'addon base (file)name',
        `version` varchar(50) NOT NULL DEFAULT '' COMMENT 'currently unused',
        `installed` boolean NOT NULL DEFAULT '0' COMMENT 'currently always 1',
        `hidden` boolean NOT NULL DEFAULT '0' COMMENT 'currently unused',
        `timestamp` int unsigned NOT NULL DEFAULT 0 COMMENT 'file timestamp to check for reloads',
        `plugin_admin` boolean NOT NULL DEFAULT '0' COMMENT '1 = has admin config, 0 = has no admin config',
         PRIMARY KEY(`id`),
         INDEX `installed_name` (`installed`,`name`),
         UNIQUE INDEX `name` (`name`)
) DEFAULT COLLATE utf8mb4_general_ci COMMENT='registered addons';

Done.
Execute pending post updates.

All pending post updates are done.
./deploy.sh: db drop ...
DROP TABLE `addon`;
````

Expected Result:

The table isn't recreated each update being applied

### Platform Info

Friendica Version: `2023.03-dev`

Friendica Source: `git`

PHP version: 7.4.30

SQL version: 10.5.15-mariadb

**Comment by MrPetovan** [comment]
While fixing this issue (the `addon` table is still references in the `static/dbstructure.config.php` file even though we don't use it anymore, I encountered the following error running `bin/console dbstructure dumpsql`on my Windows machine:
```
[Error] Argument 4 passed to Friendica\App::__construct() must be an instance of Friendica\App\BaseURL, instance of Psr\Log\NullLogger given
[Backtrace]:
#0 [internal function]: Friendica\App->__construct(Object(Friendica\Database\Database), Object(Friendica\Core\Config\Model\DatabaseConfig), Object(Friendica\App\Mode), Object(Psr\Log\NullLogger), Object(Friendica\Util\Profiler), Object(Friendica\Core\L10n), Object(Friendica\App\Arguments), Object(Friendica\Core\PConfig\Type\PreloadPConfig), Object(Friendica\Core\Session\Model\UserSession), Object(Friendica\Database\Definition\DbaDefinition), Object(Friendica\Database\Definition\ViewDefinition))
#1 D:\Projects\Friendica\MrPetovan\friendica\vendor\level-2\dice\Dice.php(132): ReflectionMethod->invokeArgs(Object(Friendica\App), Array)
#2 D:\Projects\Friendica\MrPetovan\friendica\vendor\level-2\dice\Dice.php(96): Dice\Dice->Dice\{closure}(Array, Array)
#3 D:\Projects\Friendica\MrPetovan\friendica\src\DI.php(90): Dice\Dice->create('Friendica\\App')
#4 D:\Projects\Friendica\MrPetovan\friendica\src\Core\Renderer.php(169): Friendica\DI::app()
#5 D:\Projects\Friendica\MrPetovan\friendica\src\Core\Renderer.php(110): Friendica\Core\Renderer::getTemplateEngine()
#6 D:\Projects\Friendica\MrPetovan\friendica\src\Util\Writer\DocWriter.php(128): Friendica\Core\Renderer::getMarkupTemplate('structure.tpl')
#7 D:\Projects\Friendica\MrPetovan\friendica\src\Console\DatabaseStructure.php(138): Friendica\Util\Writer\DocWriter::writeDbDefinition(Array, 'D:\\Projects\\Fri...')
#8 D:\Projects\Friendica\MrPetovan\friendica\vendor\asika\simple-console\src\Console.php(108): Friendica\Console\DatabaseStructure->doExecute()
#9 D:\Projects\Friendica\MrPetovan\friendica\src\Core\Console.php(163): Asika\SimpleConsole\Console->execute()
#10 D:\Projects\Friendica\MrPetovan\friendica\vendor\asika\simple-console\src\Console.php(108): Friendica\Core\Console->doExecute()
#11 D:\Projects\Friendica\MrPetovan\friendica\bin\console.php(41): Asika\SimpleConsole\Console->execute()
#12 {main}
```
Any idea why DI gets confused about the arguments @nupplaphil ?

**Comment by MrPetovan** [comment]
Caused by cd11088cc408de3bcf1081b2ecb9850b39563b28 in https://github.com/friendica/friendica/pull/12605
