### ISSUE TITLE
update fix 2023.04

### ISSUE THREAD

**Issue by mama21mama** [friendica/friendica#13032]
https://friendicarg.nsupdate.info/admin/dbsync/check

Service Unavailable
```
RecursiveDirectoryIterator::__construct(/var/www/html/friendicarg.nsupdate.info/view/smarty3/compiled/aa/97/a1): failed to open dir: No such file or directory

#0 /var/www/html/friendicarg.nsupdate.info/src/Module/Special/HTTPException.php(145): Friendica\Core\Renderer::replaceMacros('file:/var/www/h...', Array)
#1 /var/www/html/friendicarg.nsupdate.info/src/BaseModule.php(254): Friendica\Module\Special\HTTPException->content(Object(Friendica\Network\HTTPException\ServiceUnavailableException))
#2 /var/www/html/friendicarg.nsupdate.info/src/App.php(700): Friendica\BaseModule->run(Object(Friendica\Module\Special\HTTPException), Array)
#3 /var/www/html/friendicarg.nsupdate.info/index.php(52): Friendica\App->runFrontend(Object(Friendica\App\Router), Object(Friendica\Core\PConfig\Type\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), Object(Friendica\Content\Nav), Object(Friendica\Module\Special\HTTPException), Object(Friendica\Util\HTTPInputData), 1682362522.8753, Array)
#4 {main}
```
Request: 6446d09b0427d

https://friendicarg.nsupdate.info/community

Service Unavailable
```
RecursiveDirectoryIterator::__construct(/var/www/html/friendicarg.nsupdate.info/view/smarty3/compiled/4c/f2/36): failed to open dir: No such file or directory

#0 /var/www/html/friendicarg.nsupdate.info/src/Module/Special/HTTPException.php(145): Friendica\Core\Renderer::replaceMacros('file:/var/www/h...', Array)
#1 /var/www/html/friendicarg.nsupdate.info/src/BaseModule.php(254): Friendica\Module\Special\HTTPException->content(Object(Friendica\Network\HTTPException\ServiceUnavailableException))
#2 /var/www/html/friendicarg.nsupdate.info/src/App.php(700): Friendica\BaseModule->run(Object(Friendica\Module\Special\HTTPException), Array)
#3 /var/www/html/friendicarg.nsupdate.info/index.php(52): Friendica\App->runFrontend(Object(Friendica\App\Router), Object(Friendica\Core\PConfig\Type\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), Object(Friendica\Content\Nav), Object(Friendica\Module\Special\HTTPException), Object(Friendica\Util\HTTPInputData), 1682362539.8551, Array)
#4 {main}
```
Request: 6446d0ac46eef

https://reisub.nsupdate.info/paste/paste.php?raw&id=75

**Comment by MrPetovan** [comment]
Please delete your `/var/www/html/friendicarg.nsupdate.info/view/smarty3/compiled` folder, it will be recreated with the correct files.

**Comment by mama21mama** [comment]
no work. White screen

edit:

```
root@reisub-pc /v/w/h/friendicarg.nsupdate.info# bin/console maintenance 1 https://github.com/friendica/friendica/issues/13032
System set in maintenance mode
Maintenance reason: https://github.com/friendica/friendica/issues/13032
root@reisub-pc /v/w/h/friendicarg.nsupdate.info# bin/console dbstructure update
ALTER IGNORE TABLE `post-user` MODIFY `notification-type` smallint unsigned NOT NULL DEFAULT 0 COMMENT ''; 
```
seems to update now. I wait for it to end
