### ISSUE TITLE
“/notifications/system?show=all” Page Error 500

### ISSUE THREAD

**Issue by Tslmuun** [friendica/friendica#13043]
Unable to access the "/notifications/system?show=all" page.

[x] I have searched open and closed issues for duplicates

### Steps to Reproduce

1.Click on "Notifications" in the right-hand menu.
2.Click on "Show all".
3.error 500 The page cannot be accessed.

**This error is not persistent and only occurs occasionally. After a couple of days,The page can be accessed normally.
 I'm not sure what triggers this issue under what conditions.**

```
Uncaught Exception TypeError: "Friendica\Content\Text\BBCode::toPlaintext(): Argument #1 ($text) must be of type string, null given, called in /src/Navigation/Notifications/Factory/FormattedNotify.php on line 225" at /src/Content/Text/BBCode.php line 227
```

```
TypeError: Friendica\Content\Text\BBCode::toPlaintext(): Argument #1 ($text) must be of type string, null given, called in /src/Navigation/Notifications/Factory/FormattedNotify.php on line 225 and defined in /src/Content/Text/BBCode.php:227
Stack trace:

#0 /src/Navigation/Notifications/Factory/FormattedNotify.php(225): Friendica\Content\Text\BBCode::toPlaintext()
#1 /src/Module/Notifications/Notifications.php(75): Friendica\Navigation\Notifications\Factory\FormattedNotify->getSystemList()
#2 /src/Module/Notifications/Notifications.php(106): Friendica\Module\Notifications\Notifications->getNotifications()
#3 /src/BaseModule.php(244): Friendica\Module\Notifications\Notifications->content()
#4 /src/App.php(700): Friendica\BaseModule->run()
#5 /index.php(52): Friendica\App->runFrontend()
#6 {main}
```

nginx log:
```
"GET /notifications/system?show=all HTTP/2.0" 500 0 "https:///notifications/system" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
```

Friendica Version: 2023.01 ,2023.4 ,2023.04-1
PHP version: 8.0.28
SQL version: 10.3.38-MariaDB

**Comment by MrPetovan** [comment]
Thank you for the detailed report!
