### ISSUE TITLE
Friendica\Object\Image->scale() - imagecreatetruecolor parameter error

### ISSUE THREAD

**Issue by Maeglin73** [friendica/friendica#13191]
I checked my Friendica 2023.05 instance this evening to find a white screen, 500 error coming from the server, and this exception trace in the log:

```
ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0 in /var/www/friendica/current/src/Object/Image.php:543
Stack trace:
#0 /var/www/friendica/current/src/Object/Image.php(543): imagecreatetruecolor()
#1 /var/www/friendica/current/src/Object/Image.php(290): Friendica\Object\Image->scale()
#2 /var/www/friendica/current/src/Object/Image.php(705): Friendica\Object\Image->scaleDown()
#3 /var/www/friendica/current/src/Model/Post/Link.php(145): Friendica\Object\Image->getBlurHash()
#4 /var/www/friendica/current/src/Model/Post/Link.php(79): Friendica\Model\Post\Link::fetchMimeType()
#5 /var/www/friendica/current/src/Content/Text/BBCode.php(249): Friendica\Model\Post\Link::getByLink()
#6 /var/www/friendica/current/src/Content/Text/BBCode.php(1613): Friendica\Content\Text\BBCode::proxyUrl()
#7 [internal function]: Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}()
#8 /var/www/friendica/current/src/Content/Text/BBCode.php(1607): preg_replace_callback()
#9 /var/www/friendica/current/src/Util/Strings.php(517): Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}()
#10 /var/www/friendica/current/src/Content/Text/BBCode.php(2244): Friendica\Util\Strings::performWithEscapedBlocks()
#11 /var/www/friendica/current/src/Content/Text/BBCode.php(1922): Friendica\Content\Text\BBCode::performWithEscapedTags()
#12 /var/www/friendica/current/src/Util/Strings.php(517): Friendica\Content\Text\BBCode::Friendica\Content\Text\{closure}()
#13 /var/www/friendica/current/src/Content/Text/BBCode.php(2244): Friendica\Util\Strings::performWithEscapedBlocks()
#14 /var/www/friendica/current/src/Content/Text/BBCode.php(1935): Friendica\Content\Text\BBCode::performWithEscapedTags()
#15 /var/www/friendica/current/src/Content/Text/BBCode.php(1206): Friendica\Content\Text\BBCode::convert()
#16 /var/www/friendica/current/src/Model/Item.php(2962): Friendica\Content\Text\BBCode::convertForUriId()
#17 /var/www/friendica/current/src/Model/Item.php(3093): Friendica\Model\Item::putInCache()
#18 /var/www/friendica/current/src/Object/Post.php(414): Friendica\Model\Item::prepareBody()
#19 /var/www/friendica/current/src/Object/Thread.php(208): Friendica\Object\Post->getTemplateData()
#20 /var/www/friendica/current/src/Content/Conversation.php(785): Friendica\Object\Thread->getTemplateData()
#21 /var/www/friendica/current/src/Module/Conversation/Network.php(204): Friendica\Content\Conversation->create()
#22 /var/www/friendica/current/src/BaseModule.php(244): Friendica\Module\Conversation\Network->content()
#23 /var/www/friendica/current/src/App.php(703): Friendica\BaseModule->run()
#24 /var/www/friendica/current/index.php(52): Friendica\App->runFrontend()
#25 {main}
```

The image dimensions being fed into that function come from Util/Images:getScalingDimensions(), and it's apparently possible for them to be (0,0). Looking back at previous logs, it looks like the post triggering the problem came from Tumblr (based on a worker error), and the images are animated GIFs.

I put a parameter check at the beginning of Friendica\Object\Image->scale() that returns false if either parameter is equal to or less than zero, and that got the site working again, but I don't know what side effects might come of that. I don't see anything wrong with what I'm guessing is the problem post after making the change.

**Comment by MrPetovan** [comment]
Thank you for this detailed report!

**Comment by Maeglin73** [comment]
Looks like this has been fixed (PR #14075).
