### ISSUE TITLE
Uncaught Exception Error: "Cannot access private property UniqueNamer::$order"

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#13265]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

Since today I see a lot of these uncaught exception errors.

```
index [ERROR]: Uncaught Exception Error: "Cannot access private property UniqueNamer::$order" at /var/www/html/libranet/vendor/friendica/json-ld/jsonld.php line 2850 
{"exception":"Error: Cannot access private property UniqueNamer::$order in /var/www/html/libranet/vendor/friendica/json-ld/jsonld.php:2850
Stack trace:
#0 /var/www/html/libranet/vendor/friendica/json-ld/jsonld.php(1299): JsonLdProcessor->_normalize()
#1 /var/www/html/libranet/vendor/friendica/json-ld/jsonld.php(159): JsonLdProcessor->normalize()
#2 /var/www/html/libranet/src/Util/JsonLD.php(115): jsonld_normalize()
#3 /var/www/html/libranet/src/Util/LDSignature.php(141): Friendica\\Util\\JsonLD::normalize()
#4 /var/www/html/libranet/src/Util/LDSignature.php(69): Friendica\\Util\\LDSignature::hash()
#5 /var/www/html/libranet/src/Protocol/ActivityPub/Receiver.php(141): Friendica\\Util\\LDSignature::getSigner()
#6 /var/www/html/libranet/src/Module/ActivityPub/Inbox.php(101): Friendica\\Protocol\\ActivityPub\\Receiver::processInbox()
#7 /var/www/html/libranet/src/BaseModule.php(228): Friendica\\Module\\ActivityPub\\Inbox->post()
#8 /var/www/html/libranet/src/Module/BaseApi.php(105): Friendica\\BaseModule->run()
#9 /var/www/html/libranet/src/Module/ActivityPub/Inbox.php(43): Friendica\\Module\\BaseApi->run()
#10 /var/www/html/libranet/src/App.php(704): Friendica\\Module\\ActivityPub\\Inbox->run()
#11 /var/www/html/libranet/index.php(52): Friendica\\App->runFrontend()
#12 {main}"} - {"file":null,"line":null,"function":null,"request-id":"64aa9cd23ada8","uid":"a222a4","process_id":3941608}
```

### Platform Info

Friendica Version:
2023.09-dev

Friendica Source: 
git

PHP version:
8.1

SQL version:
10.6 MariaDB

**Comment by MrPetovan** [comment]
I'm on it, expect a new json-ld library version to drop soon. Future issues with the library can also be posted in its repository: https://git.friendi.ca/friendica/php-json-ld/issues

**Comment by MrPetovan** [comment]
Addressed in https://git.friendi.ca/friendica/php-json-ld/pulls/4
