### ISSUE TITLE
WSOD after sending a moderation report

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13365]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

WSOD after sending a report

Create a new report
![grafik](https://github.com/friendica/friendica/assets/44441246/e026e2fa-560b-4b4c-a2b2-ac3a7a69128f)
Send report without Forward report 
![grafik](https://github.com/friendica/friendica/assets/44441246/301df486-a656-4523-94a9-7eabbbd21def)
Submit Report leads to a WSOD
![grafik](https://github.com/friendica/friendica/assets/44441246/9d2e2a70-8787-44cb-86d3-e4a3e853df34)

Context:
After updating https://github.com/friendica/friendica/pull/13364 the following message is displayed with each new post update

```
Überprüfe ausstehende Update-Aktionen
ALTER IGNORE TABLE `user-gserver` MODIFY `uid` mediumint unsigned NOT NULL DEFAULT 0 COMMENT 'Owner User id', MODIFY `gsid` int unsigned NOT NULL DEFAULT 0 COMMENT 'Gserver id'; 
ALTER IGNORE TABLE `report` MODIFY `category-id` int unsigned NOT NULL DEFAULT 1 COMMENT 'Report category, one of Entity\Report::CATEGORY_*', MODIFY `status` tinyint unsigned NOT NULL COMMENT 'Status of the report, one of Entity\Report::STATUS_*', MODIFY `resolution` tinyint unsigned COMMENT 'Resolution of the report, one of Entity\Report::RESOLUTION_*', MODIFY `created` datetime(6) NOT NULL DEFAULT '0001-01-01 00:00:00' COMMENT ''; 
Erledigt.
Ausstehende Post-Updates ausführen
```

### Platform Info

Friendica Version: Dev

Friendica Source:  git

PHP version: 8.0

SQL version: 10.5

**Comment by MrPetovan** [comment]
A WSOD should leave a trace in your Friendica and/or webserver log, please check them for related information.

**Comment by loma-one** [comment]
```
2023-08-21T14:12:38Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Moderation\Entity\Report\Post::__construct(): Argument #1 ($uriId) must be of type int, null given, called in /var/www/html/friend/src/Moderation/Factory/Report/Post.php on line 32" at /var/www/html/friend/src/Moderation/Entity/Report/Post.php line 39 
{"exception":"TypeError: Friendica\\Moderation\\Entity\\Report\\Post::__construct(): Argument #1 ($uriId) must be of type int, null given, called in /var/www/html/friend/src/Moderation/Factory/Report/Post.php on line 32 and defined in /var/www/html/friend/src/Moderation/Entity/Report/Post.php:39
Stack trace:
#0 /var/www/html/friend/src/Moderation/Factory/Report/Post.php(32): Friendica\\Moderation\\Entity\\Report\\Post->__construct()
#1 [internal function]: Friendica\\Moderation\\Factory\\Report\\Post->createFromTableRow()
#2 /var/www/html/friend/src/Moderation/Repository/Report.php(112): array_map()
#3 /var/www/html/friend/src/Moderation/Repository/Report.php(56): Friendica\\Moderation\\Repository\\Report->_selectOne()
#4 /var/www/html/friend/src/Moderation/Repository/Report.php(98): Friendica\\Moderation\\Repository\\Report->selectOneById()
#5 /var/www/html/friend/src/Module/Moderation/Report/Create.php(115): Friendica\\Moderation\\Repository\\Report->save()
#6 /var/www/html/friend/src/BaseModule.php(228): Friendica\\Module\\Moderation\\Report\\Create->post()
#7 /var/www/html/friend/src/App.php(707): Friendica\\BaseModule->run()
#8 /var/www/html/friend/index.php(55): Friendica\\App->runFrontend()
#9 {main}"} - {"file":null,"line":null,"function":null,"request-id":"64e370d6e5884","uid":"ffc965","process_id":20564}
```

**Comment by MrPetovan** [comment]
> `2023-08-21T04:53:09Z`

This timestamp was before https://github.com/friendica/friendica/pull/13364 was merged, please disregard.

**Comment by loma-one** [comment]
I was still looking for the errors and didn't see that they were already on the error 😯

**Comment by MrPetovan** [comment]
Can you please show the result of the following query on your system:
```sql
SELECT * FROM `report-post` WHERE `uri-id` IS NULL;
```
And
```sql
SELECT * FROM `post-user-view` WHERE `uri-id` IS NULL;
```

**Comment by loma-one** [comment]
MariaDB [friendica]> SELECT * FROM `report-post` WHERE `uri-id` IS NULL;
Empty set (0,001 sec)

MariaDB [friendica]> SELECT * FROM `post-user-view` WHERE `uri-id` IS NULL;
Empty set (0,007 sec)

**Comment by MrPetovan** [comment]
Thanks, I'm a little puzzled at the moment.

**Comment by MrPetovan** [comment]
Found the issue.
