### ISSUE TITLE
WSOD after importing pull request #13463

### ISSUE THREAD

**Issue by sekretaerbaer** [friendica/friendica#13467]
Some time after git pull from https://github.com/friendica/friendica/commit/dd7bea4bd146acf52086d303fce34a83d52f2516 I have a WSOD and the following error message in the log.

```
2023-09-24T14:34:31Z ERROR app Uncaught Exception DivisionByZeroError: "Division by zero" at /var/www/html/src/Model/Post/Media.php line 1181

DivisionByZeroError: Division by zero at /var/www/html/src/Model/Post/Media.php:1181
Stack trace:
#0 /var/www/html/src/Model/Item.php(3539): Friendica\Model\Post\Media::getAllocatedHeightByMedia()
#1 /var/www/html/src/Model/Item.php(3246): Friendica\Model\Item::addVisualAttachments().
#2 /var/www/html/src/Object/Post.php(431): Friendica\Model\Item::prepareBody()
#3 /var/www/html/src/Object/Thread.php(204): Friendica\Object\Post->getTemplateData().
#4 /var/www/html/src/Content/Conversation.php(685): Friendica\Object\Post->getTemplateData()
#5 /var/www/html/src/Content/Conversation.php(583): Friendica\Object\Conversation->getThreadList()
#6 /var/www/html/src/Module/Conversation/Network.php(239): Friendica\Content\Conversation->render()
#7 /var/www/html/src/BaseModule.php(244): Friendica\Module\Conversation\Network->content().
#8 /var/www/html/src/App.php(710): Friendica\BaseModule->run()
#9 /var/www/html/index.php(59): Friendica\App->runFrontend()
#10 {main}
```

by a 
`git checkout ce16cd12ec46413581f5ade6487387f56723e3`
I was able to fix the WSOD 

### Platform Info

Friendica Version:

Friendica Source: 2023.09-dev - 1534

PHP version: 8.1.2

SQL version: 10.6.12

**Comment by tobiasd** [comment]
part of #13156

**Comment by MrPetovan** [comment]
@sekretaerbaer Can you please provide the result of running this SQL query on your system:
```
SELECT * FROM `post-media` WHERE `width` = 0;
```
