### ISSUE TITLE
[Support] Lost connection to other instances after server crash

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13595]
This was preceded by a crash of the entire instance. The server was only set up, a new database was created and the backup was imported. After successful import of the backup the instance is available again.

Problem:
Comments from Friendica users to e.g. to Mastodon users are not distributed. The worker says that the delivery is completed. Jobs like _APDelivery | "0: https://pixelfed.social/f/inbox: 0_ and others are in the delayed worker queue.

In the log files I get messages like: 

```
2023-11-02T06:55:07Z app [NOTICE]: Unable to retrieve AP contact for actor - message is discarded {"actor":"https://xscape.top/users/xscape"} - {"file":"Receiver.php","line":109,"function":"processInbox","request-id":"654347cbdd0e1","stack":"Receiver::processInbox (101), Inbox::post (233), BaseModule::run (109), BaseApi::run (43), Inbox::run (711), App::runFrontend (55)","uid":"45d5d6","process_id":1805575}
```

```
2023-11-02T06:55:01Z app [NOTICE]: Post has got no receivers {"fetch_unlisted":true,"actor":"https://lemmy.world/c/lemmybewholesome","id":"https://lemmy.world/activities/like/caf930ab-7410-409c-ae2e-5feb584d1317","type":"as:Like"} - {"file":"Receiver.php","line":1238,"function":"getReceivers","request-id":"654347c59422b","stack":"Receiver::getReceivers (1894), Receiver::processObject (441), Receiver::prepareObjectData (627), Receiver::processActivity (169), Receiver::processInbox (101), Inbox::post (233), BaseModule::run (109), BaseApi::run (43), Inbox::run (711), App::runFrontend (55)","uid":"e94065","process_id":1808865}
```

```
2023-11-02T04:20:13Z app [ERROR]: Uncaught Exception Friendica\Contact\Introduction\Exception\IntroductionNotFoundException: "There is no Introduction with the ID 3606 for the user 1154" at /var/www/html/friendica/src/Contact/Introduction/Repository/Introduction.php line 94 {"exception":"Friendica\\Network\\HTTPException\\NotFoundException in /var/www/html/friendica/src/BaseRepository.php:156\nStack trace:\n#0 /var/www/html/friendica/src/Contact/Introduction/Repository/Introduction.php(57): Friendica\\BaseRepository->_selectOne()\n#1 /var/www/html/friendica/src/Contact/Introduction/Repository/Introduction.php(92): Friendica\\Contact\\Introduction\\Repository\\Introduction->selectOne()\n#2 /var/www/html/friendica/src/Module/FollowConfirm.php(46): Friendica\\Contact\\Introduction\\Repository\\Introduction->selectOneById()\n#3 /var/www/html/friendica/src/BaseModule.php(233): Friendica\\Module\\FollowConfirm->post()\n#4 /var/www/html/friendica/src/App.php(711): Friendica\\BaseModule->run()\n#5 /var/www/html/friendica/index.php(55): Friendica\\App->runFrontend()\n#6 {main}\n\nNext Friendica\\Contact\\Introduction\\Exception\\IntroductionNotFoundException: There is no Introduction with the ID 3606 for the user 1154 in /var/www/html/friendica/src/Contact/Introduction/Repository/Introduction.php:94\nStack trace:\n#0 /var/www/html/friendica/src/Module/FollowConfirm.php(46): Friendica\\Contact\\Introduction\\Repository\\Introduction->selectOneById()\n#1 /var/www/html/friendica/src/BaseModule.php(233): Friendica\\Module\\FollowConfirm->post()\n#2 /var/www/html/friendica/src/App.php(711): Friendica\\BaseModule->run()\n#3 /var/www/html/friendica/index.php(55): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"6543237d20d9c","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"206bb9","process_id":1794411}
```

```
[Thu Nov 02 08:13:51.266772 2023] [proxy_fcgi:error] [pid 2070653:tid 139795124901632] [remote 2a03:4000:5f:c2d:5428:3dff:fe25:9ed3:47136] AH01071: Got error 'PHP message: PHP Warning:  Undefined array key "type" in /var/www/html/friendica/src/Model/APContact.php on line 590PHP message: PHP Warning:  Undefined array key "type" in /var/www/html/friendica/src/Model/APContact.php on line 594'
```

How can I re-establish the connections to the other instances?

Version: 2023.09-RC
Quelle: git
SQL: 10.5
PHP: 8.1

**Comment by annando** [comment]
Have a look for log entries with `APDelivery.php` or `Delivery.php` in it. Best way is to execute `tail -f friendica.log | grep -a Delivery.php` in the shell and then to write some test posts. Please set the log level to "debug" prior.

**Comment by loma-one** [comment]
The problem was incorrect access rights to the DB
