### ISSUE TITLE
[S3 Storage] SignatureDoesNotMatch, so can´t use s3 storage

### ISSUE THREAD

**Issue by scarlet-tobar** [friendica/friendica#13760]
- [X] I have searched open and closed issues for duplicates

### Bug Description

I can´t use S3 Storage because there's a SignatureDoesNotMatch error, tried with both v2 and v4. If I roll back to 9daa11eb108ff8e82e63816d371939d0415c1247 addon commit it works again. I suspect it is because Akeeba S3 Connector was updated and caused changes.

Thank you for your work.

### Steps to Reproduce

1.  Update to latest stable (2023.12, friendica itself and addons)
2.  Check logs

Actual Result:.

It's full of these errors. Also, can´t access or upload multimedia in the S3 Storage since update.

Expected Result:

S3 Storage works as normal, allows to upload and download multimedia.

### Platform Info

Friendica Version: 2023.12

Friendica Source: GIT

PHP version: PHP 8.1.2-1ubuntu2.14
SQL version: nmariadb  Ver 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64)

**Comment by Tslmuun** [comment]
+1

**Comment by MrPetovan** [comment]
Can you please report the full error so that I can forward it upstream?

**Comment by Tslmuun** [comment]
> Can you please report the full error so that I can forward it upstream?
```
Uncaught Exception Friendica\Core\Storage\Exception\StorageException: "Cannot put data for reference 6e20c847806569877e01306cd884b0be47292dbf059be105cbce272e65c95f05" at /s3_storage/src/S3Client.php line 88

Akeeba\S3\Exception\CannotPutFile: Akeeba\S3\Connector::putObject(): [500] SignatureDoesNotMatch:The request signature we calculated does not match the signature you provided. Check your key and signing method.

Debug info:
SimpleXMLElement Object
(
    [Code] => SignatureDoesNotMatch
    [Message] => The request signature we calculated does not match the signature you provided. Check your key and signing method.
    [Key] => 6e/20
    [BucketName] => 
    [Resource] => /6e/20/c847806569877e01306cd884b0be47292dbf059be105cbce272e65c95f05
    [RequestId] => 17A3F499D8B38E7E
    [HostId] => d766ec9d-ed08-47e8-bb7c-f968dbd4f006
)
 in /addon/s3_storage/vendor/akeeba/s3/src/Connector.php:149
Stack trace:
#0 /addon/s3_storage/src/S3Client.php(85): Akeeba\S3\Connector->putObject()
#1 /src/Model/Photo.php(454): Friendica\Addon\s3_storage\src\S3Client->put()
#2 /src/Model/Photo.php(641): Friendica\Model\Photo::store()
#3 /src/Model/Contact.php(2395): Friendica\Model\Photo::importProfilePhoto()
#4 /src/Model/Contact.php(1799): Friendica\Model\Contact::updateAvatar()
#5 /src/Model/Item.php(1018): Friendica\Model\Contact::checkAvatarCache()
#6 /src/Protocol/ActivityPub/Processor.php(1172): Friendica\Model\Item::insert()
#7 /src/Protocol/ActivityPub/Receiver.php(783): Friendica\Protocol\ActivityPub\Processor::postItem()
#8 /src/Protocol/ActivityPub/Receiver.php(747): Friendica\Protocol\ActivityPub\Receiver::routeActivities()
#9 /src/Protocol/ActivityPub/Processor.php(1686): Friendica\Protocol\ActivityPub\Receiver::processActivity()
#10 /src/Protocol/ActivityPub/Receiver.php(819): Friendica\Protocol\ActivityPub\Processor::fetchMissingActivity()
#11 /src/Protocol/ActivityPub/Receiver.php(747): Friendica\Protocol\ActivityPub\Receiver::routeActivities()
#12 /src/Protocol/ActivityPub/Receiver.php(169): Friendica\Protocol\ActivityPub\Receiver::processActivity()
#13 /src/Module/ActivityPub/Inbox.php(101): Friendica\Protocol\ActivityPub\Receiver::processInbox()
#14 /src/BaseModule.php(233): Friendica\Module\ActivityPub\Inbox->post()
#15 /src/Module/BaseApi.php(109): Friendica\BaseModule->run()
#16 /src/Module/ActivityPub/Inbox.php(43): Friendica\Module\BaseApi->run()
#17 /src/App.php(711): Friendica\Module\ActivityPub\Inbox->run()
#18 /index.php(46): Friendica\App->runFrontend()
#19 {main}

Next Friendica\Core\Storage\Exception\StorageException: Cannot put data for reference 6e20c847806569877e01306cd884b0be47292dbf059be105cbce272e65c95f05 in /addon/s3_storage/src/S3Client.php:88
Stack trace:
#0 /src/Model/Photo.php(454): Friendica\Addon\s3_storage\src\S3Client->put()
#1 /src/Model/Photo.php(641): Friendica\Model\Photo::store()
#2 /src/Model/Contact.php(2395): Friendica\Model\Photo::importProfilePhoto()
#3 /src/Model/Contact.php(1799): Friendica\Model\Contact::updateAvatar()
#4 /src/Model/Item.php(1018): Friendica\Model\Contact::checkAvatarCache()
#5 /src/Protocol/ActivityPub/Processor.php(1172): Friendica\Model\Item::insert()
#6 /src/Protocol/ActivityPub/Receiver.php(783): Friendica\Protocol\ActivityPub\Processor::postItem()
#7 /src/Protocol/ActivityPub/Receiver.php(747): Friendica\Protocol\ActivityPub\Receiver::routeActivities()
#8 /src/Protocol/ActivityPub/Processor.php(1686): Friendica\Protocol\ActivityPub\Receiver::processActivity()
#9 /src/Protocol/ActivityPub/Receiver.php(819): Friendica\Protocol\ActivityPub\Processor::fetchMissingActivity()
#10 /src/Protocol/ActivityPub/Receiver.php(747): Friendica\Protocol\ActivityPub\Receiver::routeActivities()
#11 /src/Protocol/ActivityPub/Receiver.php(169): Friendica\Protocol\ActivityPub\Receiver::processActivity()
#12 /src/Module/ActivityPub/Inbox.php(101): Friendica\Protocol\ActivityPub\Receiver::processInbox()
#13 /src/BaseModule.php(233): Friendica\Module\ActivityPub\Inbox->post()
#14 /src/Module/BaseApi.php(109): Friendica\BaseModule->run()
#15 /src/Module/ActivityPub/Inbox.php(43): Friendica\Module\BaseApi->run()
#16 /src/App.php(711): Friendica\Module\ActivityPub\Inbox->run()
#17 /index.php(46): Friendica\App->runFrontend()
#18 {main}
```

**Comment by GidiKroon** [comment]
As extra datapoint, triggered by the remark in the upstream issue: I'm using Amazon AWS S3 itself rather than a compatible service and have just upgraded a server to 2023.12. I use the addon for S3 storage on that server. Signature is set to v4. Existing photos are still available and a new photo upload also succeeded. I am not using S3 for avatar storage however (I think).

**Comment by MrPetovan** [comment]
From @nikosdion in https://github.com/akeeba/s3/issues/33#issuecomment-1868855305

> Are you using Amazon S3 proper, or a third party (non-Amazon) storage service? In the latter case, please remember that you need to explicitly set the v2 signature method and whether to use paths or subdomains.
> 
> Beyond that, version 2.3 is fully tested against Amazon S3 with actual integration tests, as you can see. You can try them from your end to make sure that you can connect to Amazon S3.

**Comment by scarlet-tobar** [comment]
I'm using Wasabi S3 but doesn´t work with v2 either.

**Comment by MrPetovan** [comment]
Can you please share your configuration without the secrets?

**Comment by scarlet-tobar** [comment]
Im right now on the old addon commit that still works, but:
![Screenshot_20231225-153600_Firefox.jpg](https://github.com/friendica/friendica/assets/44346895/b77404ae-c406-4a5d-95c5-bf2997c4aa27)

**Comment by MrPetovan** [comment]
Does it work better with the legacy, path-style access enabled?

**Comment by scarlet-tobar** [comment]
In the lastest version, no different configuration works, at least for me.

I don't know if it is better or if it would change something in the version i have right now.

**Comment by Tslmuun** [comment]
I'm using idrive e2 .
 now rolled back to 9daa11eb108ff8e82e63816d371939d0415c1247 addon commit. Both V2 and V4 signatures are working fine.

![Screenshot_20231226-063316](https://github.com/friendica/friendica/assets/50679343/dee5c261-a3bd-4fad-8c4d-b7e29ce9cb5b)

**Comment by nikosdion** [comment]
Hi! I cannot talk about this software, but I can tell you about the S3 library it uses as I am its author, and I was at-mentioned.

Regarding Wasabi, the Akeeba S3 library does work with it and it is one of the environments we test it with. I recommend you use it with v4 signatures, though, not v2. First, check https://docs.wasabi.com/docs/what-are-the-service-urls-for-wasabis-different-storage-regions for the correct endpoint for your bucket's region. For example, if you have a bucket in Frankfurt you need to use `s3.eu-central-2.wasabisys.com`. Moreover, you need to set up a custom Amazon S3 region for this to work. The name of the region is the stuff between `s3.` and `.wasabisys.com` in the endpoint domain name, i.e. `eu-central-2` in this case.

In all cases of using a **non-Amazon** storage service, you **must** disable dual–stack URLs.

So, why these changes? In older versions of the library the presence of a custom endpoint set the signing version to v2, disabled dual-stack URLs, and enabled legacy path-style access _regardless of your other settings_. This worked with a lot of use cases, but started causing problems with some third party storage providers who migrated away from v2 signatures. The newer versions of the library follow your configuration, even if it makes no sense.

@MrPetovan I believe you need to change the language string indicating that v2 will be used with an endpoint as it's no longer the case, and warn people to disable dual-stack URLs when using custom endpoints.

**Comment by Tslmuun** [comment]
![image](https://github.com/friendica/friendica/assets/50679343/b08ca15f-c2be-4684-bc2e-0af7ee541c81)
I want to know the meaning of this sentence. Does it mean that setting V4 has no effect if Amazon S3 is not used?

**Comment by nikosdion** [comment]
@Tslmuun You should ignore this sentence, as it no longer applies. This was only true in older versions of the S3 library.

**Comment by MrPetovan** [comment]
@nikosdion Thank you kindly for your time answering here!

**Comment by oculos** [comment]
I am having the same trouble. I switched from V2 to v4, and stopped getting error messages on the console. But the logs still show this: 

```
2023-12-27T12:58:32Z app [INFO]: File upload: {"src":"/tmp/phpELZqGZ","filename":"02ad2da8c24744e6.png","filesize":256859,"filetype":"image/png"} - {"file":"Upload.php","line":144,"function":"post","request-id":"317952e256602aa9c26dd33d520d223e","stack":"Upload::post (233), BaseModule::run (711), App::runFrontend (55)","uid":"3a86a4","process_id":63}
2023-12-27T12:58:33Z app [ERROR]: Uncaught Exception Friendica\Core\Storage\Exception\StorageException: "Cannot put data for reference 7ab55664b34f6780e64b4a40dae1c51b55baec495ba78fa6b4d5dabd3fb0a269" at /var/www/html/addon/s3_storage/src/S3Client.php line 88 {"exception":"Akeeba\\S3\\Exception\\CannotPutFile: Akeeba\\S3\\Connector::putObject(): [500] SignatureDoesNotMatch:The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.\n\nDebug info:\nSimpleXMLElement Object\n(\n    [Code] => SignatureDoesNotMatch\n    [Message] => The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.\n

```

**Comment by nikosdion** [comment]
@oculos What is the name of your bucket, which region is it in, what is the endpoint you are using, and what is the region you have selected?

**Comment by oculos** [comment]
> @oculos What is the name of your bucket, which region is it in, what is the endpoint you are using, and what is the region you have selected?

it's s3-oslo.educloud.no.
The bucket is 1003-francis-friendica and the region is oslo.

**Comment by nupplaphil** [comment]
Fixed with https://git.friendi.ca/friendica/friendica-addons/pulls/1680 :)

**Comment by nupplaphil** [comment]
Fixed :)
