### ISSUE TITLE
Blank network page and DB errors in the log

### ISSUE THREAD

**Issue by zedascouves** [friendica/friendica#13814]
- [X] I have searched open and closed issues for duplicates

### Bug Description

I'm getting a blank network page, and I see the following DB error in the logs:

```
2024-01-08T09:36:36Z app [ERROR]: DB Error {"code":3144,"error":"Cannot create a JSON value from a string with CHARACTER SET 'binary'.","params":"SELECT `activities` FROM `post-engagement` WHERE (`contact-type` != 3 AND `activities` > 0 AND NOT `restricted` AND (`language` IS NULL OR JSON_EXTRACT(JSON_KEYS(language), '$[0]') = 'en' OR JSON_EXTRACT(JSON_KEYS(language), '$[0]') = 'pt')) ORDER BY `activities` DESC LIMIT 0, 1"} - {"file":"Database.php","line":702,"function":"p","request-id":"659bc218de0f0","stack":"Database::p (1521), Database::select (1430), Database::selectToArray (477), Timeline::getMedianActivities (280), Timeline::getRawChannelItems (207), Timeline::getChannelItems (241), Network::content (250), BaseModule::run (711), App::runFrontend (46)","uid":"cd755e","process_id":10701}
```

I get the same message if I try to run the query manually, but if I change it to...

```
SELECT
	`activities`
FROM
	`post-engagement`
WHERE
	(`contact-type` != 3
		AND `activities` > 0
		AND NOT `restricted`
		AND (`language` IS NULL
			OR JSON_EXTRACT(JSON_KEYS(CAST(`language` AS JSON)), '$[0]') = 'en'
				OR JSON_EXTRACT(JSON_KEYS(CAST(`language` AS JSON)), '$[0]') = 'pt'))
ORDER BY
	`activities` DESC
LIMIT 0,
1;
```

... It's executed without any issue.

### Steps to Reproduce

1.  Login to my instance
2.  Click on the Network page link
3.  Get a blank page

Actual Result: a blank page.

Expected Result: A page with posts.

### Platform Info

Friendica Version: Friendica 'Yellow Archangel' 2023.12 - 1542

Friendica Source: archive

PHP version: 8.2.12

SQL version: 8.0.28-0ubuntu0.20.04.3

**Comment by annando** [comment]
It looks like you are using MySQL and not MariaDB, is that right? This seems to be some incompatibility. However, this shouldn't cause a blank page. You should have something else in the log with `[ERROR]` or with an exception.

**Comment by zedascouves** [comment]
Yes, I'm using MySQL, and not MariaDB.

I do have another error/exception:
```
2024-01-08T14:17:56Z app [ERROR]: Uncaught Exception TypeError: "count(): Argument #1 ($value) must be of type Countable|array, null given" at src/Module/Conversation/Network.php line 260
{"exception":"TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in src/Module/Conversation/Network.php:260
Stack trace:
#0 src/Module/Conversation/Network.php(260): count(NULL)
#1 src/BaseModule.php(250): Friendica\\Module\\Conversation\\Network->content(Array)
#2 src/App.php(711): Friendica\\BaseModule->run(Object(Friendica\\Module\\Special\\HTTPException), Array)
#3 index.php(46): Friendica\\App->runFrontend(Object(Friendica\\App\\Router), Object(Friendica\\Core\\PConfig\\Type\\JitPConfig), Object(Friendica\\Security\\Authentication), Object(Friendica\\App\\Page), Object(Friendica\\Content\\Nav), Object(Friendica\\Module\\Special\\HTTPException), Object(Friendica\\Util\\HTTPInputData), 1704723464.8444, Array)
#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"659c0408d282d","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"24dd25","process_id":86903}
```

**Comment by annando** [comment]
Hmm, I don't find a `count` in line 260 in the file `Network.php`.

**Comment by zedascouves** [comment]
I do, actually:

`$items[count($items) - 1][$this->order] ?? null,`

in src/Module/Conversation/Network.php

And the full piece of code:

```
if ($this->pConfig->get($this->session->getLocalUserId(), 'system', 'infinite_scroll')) {
			$o .= HTML::scrollLoader();
		} else {
			$pager = new BoundariesPager(
				$this->l10n,
				$this->args->getQueryString(),
				$items[0][$this->order] ?? null,
				$items[count($items) - 1][$this->order] ?? null,
				$this->itemsPerPage
			);

			$o .= $pager->renderMinimal(count($items));
		}
```

**Comment by MrPetovan** [comment]
@annando This is the `stable` version of the file.

**Comment by annando** [comment]
Ah yeah. For a start you can change the field type of "language" in "post-engagement" to "varchar".

**Comment by zedascouves** [comment]
Ah, cool! The network page is back! :-D Thanks!

**Comment by MrPetovan** [comment]
This should be documented somewhere in the Known Issues.

**Comment by annando** [comment]
Since this change will automatically be reverted at the next update, we have to change this on our side.
