### ISSUE TITLE
[Bluesky] Undefined properties and a TypeError exception

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#13925]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

I see a lot of warnings and errors related to the Bluesky addon in my server's log. I don't use the Bluesky addon myself. So, I cannot say if this is a real bug in the addon or if this happens because of a configuration issue in the user's settings.

Looks like these lines appear in my log every time the worker is running.

**Actual Result:**

```
2024-02-20T15:36:03Z worker [WARNING]: E_WARNING: Undefined property: stdClass::$handle {"code":2,"message":"Undefined property: stdClass::$handle","file":".../addon/bluesky/bluesky.php","line":1558} - {"file":"bluesky.php","line":1558,"function":"bluesky_get_contact_fields","request-id":"65d4c6e0e4068","stack":"ErrorHandler::handleError (1558), bluesky_get_contact_fields (1505), bluesky_get_contact (1146), bluesky_get_header (1323), bluesky_add_media (1130), bluesky_process_post (1093), bluesky_fetch_feed (14), bluesky_feed_run (581), Worker::execFunction (428), Worker::execute (121), Worker::processQueue (87)","uid":"98e910","process_id":369590}
2024-02-20T15:36:03Z worker [WARNING]: E_WARNING: Undefined property: stdClass::$handle {"code":2,"message":"Undefined property: stdClass::$handle","file":".../addon/bluesky/bluesky.php","line":1559} - {"file":"bluesky.php","line":1559,"function":"bluesky_get_contact_fields","request-id":"65d4c6e0e4068","stack":"ErrorHandler::handleError (1559), bluesky_get_contact_fields (1505), bluesky_get_contact (1146), bluesky_get_header (1323), bluesky_add_media (1130), bluesky_process_post (1093), bluesky_fetch_feed (14), bluesky_feed_run (581), Worker::execFunction (428), Worker::execute (121), Worker::processQueue (87)","uid":"98e910","process_id":369590}
2024-02-20T15:36:03Z worker [WARNING]: E_WARNING: Undefined property: stdClass::$handle {"code":2,"message":"Undefined property: stdClass::$handle","file":".../addon/bluesky/bluesky.php","line":1560} - {"file":"bluesky.php","line":1560,"function":"bluesky_get_contact_fields","request-id":"65d4c6e0e4068","stack":"ErrorHandler::handleError (1560), bluesky_get_contact_fields (1505), bluesky_get_contact (1146), bluesky_get_header (1323), bluesky_add_media (1130), bluesky_process_post (1093), bluesky_fetch_feed (14), bluesky_feed_run (581), Worker::execFunction (428), Worker::execute (121), Worker::processQueue (87)","uid":"98e910","process_id":369590}
2024-02-20T15:36:03Z worker [WARNING]: E_WARNING: Undefined property: stdClass::$handle {"code":2,"message":"Undefined property: stdClass::$handle","file":".../addon/bluesky/bluesky.php","line":1561} - {"file":"bluesky.php","line":1561,"function":"bluesky_get_contact_fields","request-id":"65d4c6e0e4068","stack":"ErrorHandler::handleError (1561), bluesky_get_contact_fields (1505), bluesky_get_contact (1146), bluesky_get_header (1323), bluesky_add_media (1130), bluesky_process_post (1093), bluesky_fetch_feed (14), bluesky_feed_run (581), Worker::execFunction (428), Worker::execute (121), Worker::processQueue (87)","uid":"98e910","process_id":369590}
2024-02-20T15:36:03Z worker [WARNING]: E_WARNING: Undefined property: stdClass::$cid {"code":2,"message":"Undefined property: stdClass::$cid","file":".../addon/bluesky/bluesky.php","line":1152} - {"file":"bluesky.php","line":1152,"function":"bluesky_get_header","request-id":"65d4c6e0e4068","stack":"ErrorHandler::handleError (1152), bluesky_get_header (1323), bluesky_add_media (1130), bluesky_process_post (1093), bluesky_fetch_feed (14), bluesky_feed_run (581), Worker::execFunction (428), Worker::execute (121), Worker::processQueue (87)","uid":"98e910","process_id":369590}
2024-02-20T15:36:03Z worker [WARNING]: E_WARNING: Attempt to read property "rkey" on null {"code":2,"message":"Attempt to read property \"rkey\" on null","file":".../addon/bluesky/bluesky.php","line":1159} - {"file":"bluesky.php","line":1159,"function":"bluesky_get_header","request-id":"65d4c6e0e4068","stack":"ErrorHandler::handleError (1159), bluesky_get_header (1323), bluesky_add_media (1130), bluesky_process_post (1093), bluesky_fetch_feed (14), bluesky_feed_run (581), Worker::execFunction (428), Worker::execute (121), Worker::processQueue (87)","uid":"98e910","process_id":369590}
2024-02-20T15:36:03Z worker [WARNING]: E_WARNING: Undefined property: stdClass::$value {"code":2,"message":"Undefined property: stdClass::$value","file":".../addon/bluesky/bluesky.php","line":1324} - {"file":"bluesky.php","line":1324,"function":"bluesky_add_media","request-id":"65d4c6e0e4068","stack":"ErrorHandler::handleError (1324), bluesky_add_media (1130), bluesky_process_post (1093), bluesky_fetch_feed (14), bluesky_feed_run (581), Worker::execFunction (428), Worker::execute (121), Worker::processQueue (87)","uid":"98e910","process_id":369590}
2024-02-20T15:36:03Z worker [ERROR]: Uncaught Exception TypeError: "bluesky_get_content(): Argument #2 ($record) must be of type stdClass, null given, called in .../addon/bluesky/bluesky.php on line 1324" at .../addon/bluesky/bluesky.php line 1175 {"exception":"TypeError: bluesky_get_content(): Argument #2 ($record) must be of type stdClass, null given, called in .../addon/bluesky/bluesky.php on line 1324 and defined in .../addon/bluesky/bluesky.php:1175\nStack trace:\n#0 .../addon/bluesky/bluesky.php(1324): bluesky_get_content()\n#1 .../addon/bluesky/bluesky.php(1130): bluesky_add_media()\n#2 .../addon/bluesky/bluesky.php(1093): bluesky_process_post()\n#3 .../addon/bluesky/bluesky_feed.php(14): bluesky_fetch_feed()\n#4 .../src/Core/Worker.php(581): bluesky_feed_run()\n#5 .../src/Core/Worker.php(428): Friendica\\Core\\Worker::execFunction()\n#6 .../src/Core/Worker.php(121): Friendica\\Core\\Worker::execute()\n#7 .../bin/worker.php(87): Friendica\\Core\\Worker::processQueue()\n#8 {main}"} - {"file":null,"line":null,"function":null,"request-id":"65d4c6e0e4068","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"98e910","process_id":369590}
```

**Expected Result:**

No errors and warnings. :-)

### Platform Info

Friendica Version:
Friendica version is 2024.03-rc 
Database version is 1554/1554
Post update version is 1550/1550

Friendica Source: 
git

PHP version:
8.1

SQL version:
MariaDB 10.6

**Comment by annando** [comment]
This will be fixed by PR https://git.friendi.ca/friendica/friendica-addons/pulls/1467

**Comment by MrPetovan** [comment]
Fixed in https://git.friendi.ca/friendica/friendica-addons/pulls/1467
