### ISSUE TITLE
[advanced content filter] white screen of death

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#13950]
- [🥺] I have searched open and closed issues for duplicates

### Bug Description

The settings page of the advanced content filter add-on is broken. Going to https://example.com/advancedcontentfilter leads to a WSOD.

### Steps to Reproduce

1.  Update to current RC
2.  Go to settings > add-ons > advanced content filter 
3.  Notice the pure white color 

Actual Result:

WSOD with this error in log file:

```
app [ERROR]: Uncaught Exception ArgumentCountError: "Too few arguments to function advancedcontentfilter_get_rules(), 0 passed in /var/www/html/libranet/addon/advancedcontentfilter/advancedcontentfilter.php on line 256 and exactly 2 expected" at /var/www/html/libranet/addon/advancedcontentfilter/advancedcontentfilter.php line 308 
{"exception":"ArgumentCountError: Too few arguments to function advancedcontentfilter_get_rules(), 0 passed in /var/www/html/libranet/addon/advancedcontentfilter/advancedcontentfilter.php on line 256 and exactly 2 expected in /var/www/html/libranet/addon/advancedcontentfilter/advancedcontentfilter.php:308\n
Stack trace:\n
#0 /var/www/html/libranet/addon/advancedcontentfilter/advancedcontentfilter.php(256): advancedcontentfilter_get_rules()\n
#1 /var/www/html/libranet/src/LegacyModule.php(96): advancedcontentfilter_content()\n
#2 /var/www/html/libranet/src/LegacyModule.php(73): Friendica\\LegacyModule->runModuleFunction()\n
#3 /var/www/html/libranet/src/BaseModule.php(250): Friendica\\LegacyModule->content()\n
#4 /var/www/html/libranet/src/App.php(711): Friendica\\BaseModule->run()\n
#5 /var/www/html/libranet/index.php(55): Friendica\\App->runFrontend()\n
#6 {main}"} - {"file":null,"line":null,"function":null,"request-id":"65e0d8f7cb688","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"29cc42","process_id":1218997}
```

Expected Result:

No error. 

### Platform Info

Friendica Version:
2024.03-rc

Friendica Source: 
git

PHP version:
8.1

SQL version:
MariaDB 10.6

**Comment by MrPetovan** [comment]
PR created: https://git.friendi.ca/friendica/friendica-addons/pulls/1475

**Comment by tobiasd** [comment]
PR merged
