### ISSUE TITLE
[Addon] URL Replace creates a WSOD after activation of the addon

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#13968]
- [x] I have searched open and closed issues for duplicates

### Bug Description

After activating the add-on, a WSOD appears on the configuration page. 

### Platform Info

Friendica Version: RC 1555/1555 und die Post-Update-Version 1550/1550.

Friendica Source: git

PHP version: 8.2

SQL version: 10.5

**Comment by annando** [comment]
Do you have got any logs?

**Comment by loma-one** [comment]
```
2024-03-06T12:35:23Z app [ERROR]: Uncaught Exception TypeError: "implode(): Argument #1 ($array) must be of type array, string given" at /var/www/html/friend/addon/url_replace/url_replace.php line 49 {"exception":"TypeError: implode(): Argument #1 ($array) must be of type array, string given in /var/www/html/friend/addon/url_replace/url_replace.php:49\nStack trace:\n#0 /var/www/html/friend/addon/url_replace/url_replace.php(49): implode()\n#1 /var/www/html/friend/src/Module/Admin/Addons/Details.php(105): url_replace_addon_admin()\n#2 /var/www/html/friend/src/BaseModule.php(250): Friendica\\Module\\Admin\\Addons\\Details->content()\n#3 /var/www/html/friend/src/App.php(711): Friendica\\BaseModule->run()\n#4 /var/www/html/friend/index.php(46): Friendica\\App->runFrontend()\n#5 {main}"} - {"file":null,"line":null,"function":null,"request-id":"65e8630ba51f6","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"8c1562","process_id":1475}
```

**Comment by MrPetovan** [comment]
I'll take this one and the Fatal error reported in https://github.com/friendica/friendica/issues/13763#issuecomment-1980982910

**Comment by MrPetovan** [comment]
@Friendlica Can you please run `bin/console config url_replace twelvefeet_sites` in your Friendica folder and report the output?

**Comment by loma-one** [comment]
bin/console config url_replace twelvefeet_sites
url_replace.twelvefeet_sites => NULL

**Comment by MrPetovan** [comment]
Thanks, would you be able to test this patch on your system: https://git.friendi.ca/friendica/friendica-addons/commit/6a9287dc6fdd0341d2852a4d3ec844fc855502a3

**Comment by annando** [comment]
Should I merge it anyway or should we wait for the feedback?

**Comment by MrPetovan** [comment]
You can safely merge but I can't guarantee it will fix this particular issue.

**Comment by loma-one** [comment]
The patch was successful
