### ISSUE TITLE
Tumblr Addon: Invalid Contact?

### ISSUE THREAD

**Issue by shiribailem** [friendica/friendica#13979]
I'm trying to add a Tumblr user to follow, their profile comes up but I'm getting Invalid Contact when I try to follow them:

```
Exception thrown in /var/www/src/Model/Circle.php:295
Stack trace:
#0 /var/www/src/Model/Contact.php(3198): Friendica\Model\Circle::addMember()
#1 /var/www/src/Module/Contact/Follow.php(206): Friendica\Model\Contact::createFromProbeForUser()
#2 /var/www/src/Module/Contact/Follow.php(152): Friendica\Module\Contact\Follow->process()
#3 /var/www/src/BaseModule.php(250): Friendica\Module\Contact\Follow->content()
#4 /var/www/src/App.php(711): Friendica\BaseModule->run()
#5 /var/www/index.php(55): Friendica\App->runFrontend()
#6 {main}
```

**Comment by shiribailem** [comment]
Turns out my Tumblr connector needed to be re-authenticated, so they should be directed toward how to make it give a more helpful error message.

And so that others searching these keywords will find this as well.

**Comment by MrPetovan** [comment]
This is tricky because without this authentication, we can’t guess the contact is a Tumblr contact, which prevents us from showing a Tumblr-specific error message.

Maybe we can show a generic error message when we’re failing to authenticate Tumblr whenever it happens.

**Comment by shiribailem** [comment]
I'm not sure why, but this was an error caused by that rather than just a failure to find. But probably would have been addressed that way regardless. (I suspect it didn't fail the authentication in search gracefully)

I figure it could be as simple as "Here's a notification letting you know that the last time we tried the authentication failed"
