### ISSUE TITLE
Uncaught Exception in Tumblr addon "Call to undefined method CurlResult::getBody()"

### ISSUE THREAD

**Issue by Raroun** [friendica/friendica#14056]
### Bug Description

There is an uncaught Exception in the tumblr addon. It worked just fine till now. I just checked the friendica log and is was full with the same error over and over again.
I just deactivated the Addon for now :)

Error:
`Uncaught Exception Error: "Call to undefined method Friendica\Network\HTTPClient\Response\CurlResult::getBody()" at /var/www/html/addon/tumblr/tumblr.php line 1247`

Stack trace:
```
Error: Call to undefined method Friendica\Network\HTTPClient\Response\CurlResult::getBody() in /var/www/html/addon/tumblr/tumblr.php:1247
Stack trace:
#0 /var/www/html/addon/tumblr/tumblr.php(101): tumblr_get_contact_by_url()
#1 /var/www/html/src/Core/Hook.php(222): tumblr_probe_detect()
#2 /var/www/html/src/Core/Hook.php(198): Friendica\Core\Hook::callSingle()
#3 /var/www/html/src/Network/Probe.php(708): Friendica\Core\Hook::callAll()
#4 /var/www/html/src/Network/Probe.php(375): Friendica\Network\Probe::detect()
#5 /var/www/html/src/Model/Contact.php(1344): Friendica\Network\Probe::uri()
#6 /var/www/html/src/Model/Tag.php(199): Friendica\Model\Contact::getIdForURL()
#7 /var/www/html/src/Protocol/ActivityPub/Processor.php(1348): Friendica\Model\Tag::getTargetType()
#8 /var/www/html/src/Protocol/ActivityPub/Processor.php(920): Friendica\Protocol\ActivityPub\Processor::storeReceivers()
#9 /var/www/html/src/Protocol/ActivityPub/Processor.php(488): Friendica\Protocol\ActivityPub\Processor::processContent()
#10 /var/www/html/src/Protocol/ActivityPub/Processor.php(691): Friendica\Protocol\ActivityPub\Processor::createItem()
#11 /var/www/html/src/Protocol/ActivityPub/Receiver.php(852): Friendica\Protocol\ActivityPub\Processor::createActivity()
#12 /var/www/html/src/Protocol/ActivityPub/Receiver.php(756): Friendica\Protocol\ActivityPub\Receiver::routeActivities()
#13 /var/www/html/src/Protocol/ActivityPub/Receiver.php(169): Friendica\Protocol\ActivityPub\Receiver::processActivity()
#14 /var/www/html/src/Module/ActivityPub/Inbox.php(101): Friendica\Protocol\ActivityPub\Receiver::processInbox()
#15 /var/www/html/src/BaseModule.php(233): Friendica\Module\ActivityPub\Inbox->post()
#16 /var/www/html/src/Module/BaseApi.php(109): Friendica\BaseModule->run()
#17 /var/www/html/src/Module/ActivityPub/Inbox.php(43): Friendica\Module\BaseApi->run()
#18 /var/www/html/src/App.php(711): Friendica\Module\ActivityPub\Inbox->run()
#19 /var/www/html/index.php(46): Friendica\App->runFrontend()
#20 {main}
```

### Platform Info

Friendica Version: 2024.03 stable

Friendica Source: github

PHP version: 8.2.17

SQL version: MariaDB 11.3.2

**Comment by Raroun** [comment]
my bad - for wahtever reason the addon folder was not up to date o.O
