### ISSUE TITLE
[Addon] Bluesky: new accounts can be created when connecting to Bluesky

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14118]
See exchange in the support forum: https://loma.ml/display/373ebf56-1466-2cb3-f5ee-fc3716154085

```
2024-04-27T07:34:09Z worker [NOTICE]: Exception on get {"exception":"InvalidArgumentException: Unable to retrieve the host in URL: /xrpc/app.bsky.actor.getPreferences in /var/www/html/friendica/src/Network/HTTPClient/Client/HttpClient.php:73\nStack trace:\n#0 /var/www/html/friendica/src/Network/HTTPClient/Client/HttpClient.php(206): Friendica\\Network\\HTTPClient\\Client\\HttpClient->request()\n#1 /var/www/html/friendica/addon/bluesky/bluesky.php(1851): Friendica\\Network\\HTTPClient\\Client\\HttpClient->get()\n#2 /var/www/html/friendica/addon/bluesky/bluesky.php(1843): bluesky_get()\n#3 /var/www/html/friendica/addon/bluesky/bluesky.php(1660): bluesky_xrpc_get()\n#4 /var/www/html/friendica/addon/bluesky/bluesky.php(1643): bluesky_get_preferences()\n#5 /var/www/html/friendica/addon/bluesky/bluesky.php(532): bluesky_get_feeds()\n#6 /var/www/html/friendica/src/Core/Hook.php(222): bluesky_cron()\n#7 /var/www/html/friendica/src/Worker/ForkHook.php(31): Friendica\\Core\\Hook::callSingle()\n#8 [internal function]: Friendica\\Worker\\ForkHook::execute()\n#9 /var/www/html/friendica/src/Core/Worker.php(572): call_user_func_array()\n#10 /var/www/html/friendica/src/Core/Worker.php(386): Friendica\\Core\\Worker::execFunction()\n#11 /var/www/html/friendica/src/Core/Worker.php(121): Friendica\\Core\\Worker::execute()\n#12 /var/www/html/friendica/bin/worker.php(87): Friendica\\Core\\Worker::processQueue()\n#13 {main}","worker_id":"3d3d104","worker_cmd":"ForkHook"} - {"file":"bluesky.php","line":1853,"function":"bluesky_get","request-id":"662caa71575ec","stack":"bluesky_get (1843), bluesky_xrpc_get (1660), bluesky_get_preferences (1643), bluesky_get_feeds (532), bluesky_cron (222), Hook::callSingle (31), ForkHook::execute, Worker::execFunction (386), Worker::execute (121), Worker::processQueue (87)","uid":"73f16d","process_id":1948596}
```
```
2024-04-27T07:34:09Z worker [NOTICE]: Wrong worker arguments {"class":"ForkHook","argv":["cron",["addon/bluesky/bluesky.php","bluesky_cron"],null],"queue":{"id":109395505,"command":"ForkHook","parameter":"[\"cron\",[\"addon\\/bluesky\\/bluesky.php\",\"bluesky_cron\"],null]","priority":30,"created":"2024-04-27 07:34:09","pid":1948596,"executed":"2024-04-27 07:34:09","next_try":"0001-01-01 00:00:00","retrial":0,"done":0},"message":"bluesky_get_preferences(): Return value must be of type stdClass, null returned","worker_id":"3d3d104","worker_cmd":"ForkHook"} - {"file":"Worker.php","line":575,"function":"execFunction","request-id":"662caa71575ec","stack":"Worker::execFunction (386), Worker::execute (121), Worker::processQueue (87)","uid":"73f16d","process_id":1948596}
```

**Comment by annando** [comment]
With the latest changes to the Bluesky addon these problems should be solved.

**Comment by loma-one** [comment]
Confirmed 👍
