### ISSUE TITLE
Incorrect integer value: '' for column `photo`.`accessible`

### ISSUE THREAD

**Issue by SPiRiT369** [friendica/friendica#14113]
### Bug Description
I am a new friendica user and have just installed a new friendica server:
- Friendica version: 2024.03
- Mysql version: 10.11.6-MariaDB-0+deb12u1 (Debian 12).
- PHP version: 8.2 (Running as a podman container with alpine linux)

I can publish posts, but when I attach images to the post I have the following error in the log file.
The image files are uploaded and displayed under Photos with permissions just for me, but the post itself fails and the New Post window doesn't disappear.

```
mysqli_sql_exception: Incorrect integer value: '' for column `friendica`.`photo`.`accessible` at row 1 in /friendica/src/Database/Database.php:646
Stack trace:
#0 /friendica/src/Database/Database.php(646): mysqli_stmt->execute()
#1 /friendica/src/Database/Database.php(763): Friendica\Database\Database->p()
#2 /friendica/src/Database/Database.php(1365): Friendica\Database\Database->e()
#3 /friendica/src/Database/DBA.php(417): Friendica\Database\Database->update()
#4 /friendica/src/Model/Photo.php(565): Friendica\Database\DBA::update()
#5 /friendica/src/Model/Photo.php(911): Friendica\Model\Photo::update()
#6 /friendica/src/Model/Photo.php(885): Friendica\Model\Photo::setPermissionForResource()
#7 /friendica/src/Model/Item.php(1076): Friendica\Model\Photo::setPermissionFromBody()
#8 /friendica/mod/item.php(200): Friendica\Model\Item::insert()
#9 /friendica/mod/item.php(79): item_insert()
#10 /friendica/src/LegacyModule.php(96): item_post()
#11 /friendica/src/LegacyModule.php(80): Friendica\LegacyModule->runModuleFunction()
#12 /friendica/src/BaseModule.php(233): Friendica\LegacyModule->post()
#13 /friendica/src/App.php(711): Friendica\BaseModule->run()
#14 /friendica/index.php(46): Friendica\App->runFrontend()
#15 {main}
```

I tried the "Check database structure" link in the admin menu. I don't know if it's relevant, but anyway it didn't write anything, and didn't help.

**Comment by SPiRiT369** [comment]
UPDATE:
After lots of tries to find what happened, it looks like enabling this option solves the problem:

![image](https://github.com/friendica/friendica/assets/63514368/fbba472e-ad9a-4e57-b4d6-f5c4c88d9a98)

**Comment by annando** [comment]
I can imagine that it also works now when you disable the option again. It could be that we have got a problem with some default value.

**Comment by SPiRiT369** [comment]
When I toggle it off again, the problem returns.
