### ISSUE TITLE
Search: WSOD when searching with "+from"

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14116]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Searching for terms with the pattern "+from:person" leads to a WSOD. The error can be intercepted by starting the search with a colon.

```
2024-04-24T12:28:54Z app [ERROR]: Uncaught Exception InvalidArgumentException: "Unable to retrieve the host in URL: +from:z428 +nomadic +identity" at /var/www/html/friendica/src/Network/HTTPClient/Client/HttpClient.php line 73 {"exception":"InvalidArgumentException: Unable to retrieve the host in URL: +from:z428 +nomadic +identity in /var/www/html/friendica/src/Network/HTTPClient/Client/HttpClient.php:73\nStack trace:\n#0 /var/www/html/friendica/src/Network/HTTPClient/Client/HttpClient.php(195): Friendica\\Network\\HTTPClient\\Client\\HttpClient->request()\n#1 /var/www/html/friendica/src/Model/Item.php(4099): Friendica\\Network\\HTTPClient\\Client\\HttpClient->head()\n#2 /var/www/html/friendica/src/Module/Search/Index.php(298): Friendica\\Model\\Item::fetchByLink()\n#3 /var/www/html/friendica/src/Module/Search/Index.php(129): Friendica\\Module\\Search\\Index::tryRedirectToPost()\n#4 /var/www/html/friendica/src/BaseModule.php(250): Friendica\\Module\\Search\\Index->content()\n#5 /var/www/html/friendica/src/App.php(711): Friendica\\BaseModule->run()\n#6 /var/www/html/friendica/index.php(55): Friendica\\App->runFrontend()\n#7 {main}"} - {"file":null,"line":null,"function":null,"request-id":"6628fb0687d69","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"b2e520","process_id":1033}
```

https://loma.ml/display/373ebf56-3666-28f2-fdbe-25a340104779

### Platform Info

Friendica Version: stable / dev

Friendica Source: git

PHP version: 8.1/8.2

SQL version: 10.1/10.5

**Comment by annando** [comment]
You can try to enclose it in `"`.

**Comment by AlfredSK** [comment]
Hmm. I just tried it with `+from:steffen`. No error, search result ok.

MariaDB 10.6

**Comment by sekretaerbaer** [comment]
I have tested 

stable 
`"+from:oldkid" `-> works 
`+from:oldkid `-> WSOD [1]

dev
`"+from:oldkid"` -> works 
`+from:oldkid `-> works 

both 10.6.16-MariaDB

[1]
```
InvalidArgumentException: Unable to retrieve the host in URL: +from:oldkid in /var/www/html/src/Network/HTTPClient/Client/HttpClient.php:73
Stack trace:
#0 /var/www/html/src/Network/HTTPClient/Client/HttpClient.php(195): Friendica\Network\HTTPClient\Client\HttpClient->request()
#1 /var/www/html/src/Model/Item.php(4099): Friendica\Network\HTTPClient\Client\HttpClient->head()
#2 /var/www/html/src/Module/Search/Index.php(298): Friendica\Model\Item::fetchByLink()
#3 /var/www/html/src/Module/Search/Index.php(129): Friendica\Module\Search\Index::tryRedirectToPost()
#4 /var/www/html/src/BaseModule.php(250): Friendica\Module\Search\Index->content()
#5 /var/www/html/src/App.php(711): Friendica\BaseModule->run()
#6 /var/www/html/index.php(59): Friendica\App->runFrontend()
#7 {main}
```

**Comment by MrPetovan** [comment]
Fixed in https://github.com/friendica/friendica/pull/14069

**Comment by annando** [comment]
@sekretaerbaer you could ask your admin to update :-)
