### ISSUE TITLE
Lemmy subscription from remote instance not working properly over Friendica

### ISSUE THREAD

**Issue by csolisr** [friendica/friendica#14306]
- [X] I have searched open and closed issues for duplicates

### Bug Description

Attempting to use the "Subscribe" button on Lemmy instances that allow for external subscription fails when pointing towards a Friendica instance.

### Steps to Reproduce

1.  Go to any Lemmy instance running version 0.19.5 or later. Ensure that you're not currently logged in.
2.  Go to a group, click "Subscribe".
3.  On the pop-up "Subscribe to Remote Instance" field, type your Friendica instance's URL. (For this case, we will use `friendica.example.net` as our example URL.)
4. Click on "Fetch Community".

Actual Result:

The page is redirected to a URL of the form `https://friendica.example.net/activitypub/externalInteraction?uri=https%3A%2F%2Flemmy.example.com%2Fc%2Fmaingroup`, which is not recognized by Friendica. The following pop-up appears:

```
Exception thrown in /var/www/friendica/src/Module/HTTPException/PageNotFound.php:49
Stack trace:
#0 /var/www/friendica/src/BaseModule.php(250): Friendica\Module\HTTPException\PageNotFound->content()
#1 /var/www/friendica/src/Module/HTTPException/PageNotFound.php(80): Friendica\BaseModule->run()
#2 /var/www/friendica/src/App.php(677): Friendica\Module\HTTPException\PageNotFound->run()
#3 /var/www/friendica/index.php(46): Friendica\App->runFrontend()
#4 {main}
```

Expected Result:

The remote subscription should be recognized as such, and the system should then follow the standard subscription workflow.

### Screenshots

![imagen](https://github.com/user-attachments/assets/dca4ff21-9f08-4557-bc55-319b7d1f39dd)

### Platform Info

Friendica Version: 2024.06-dev (but can be also replicated on the latest stable version)

Friendica Source: Git repository, YunoHost

PHP version: 8.2

SQL version: 10.5.23-MariaDB

**Comment by annando** [comment]
It seems as if Lemmy isn't following the standard for remote subscriptions. So it is more a bug for Lemmy.
