### ISSUE TITLE
Cannot complete postupdate "[Error] Unable to retrieve the host in URL:  "

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#14307]
I am using the latest Friendica stable - https://social.trom.tf/friendica

`This is Friendica, version 2024.03 that is running at the web location https://social.trom.tf. The database version is 1557/1557, the post update version is 1544/1550.`

Since I updated Friendica a month or more ago it could not complete the post update. I tried `bin/console postupdate` but I get this error:

```
Check for pending update actions.
Done.
Execute pending post updates.
[Error] Unable to retrieve the host in URL: 
```

And no URL shown. 

I think some pages on our node do not work - like when people accept some friends' requests and get a page saying something like “Service Unavailable, Friendica can't display this page at the moment, please contact the administrator.” I wonder if these are related.

**Comment by annando** [comment]
Please execute `bin/console dbstructure update` in the command line and tell what the system returns. Also have got a look in your logfile for entries with `[ERROR]` into it.

**Comment by tio-trom** [comment]
Thanks. That command outputs nothing. As for the errors I waited a bit to see what we get. I see:

```
ERROR 	app 	Uncaught Exception Friendica\Core\Storage\Exception\StorageException: "Filesystem storage failed to save data to "/home/yunohost.app/friendica/storage/13/60/314155808ed312b7045a43ccb5cb8b78461b7e93b01a70c88352bfbf25da". Check your write permissions" at /var/www/friendica/src/Core/Storage/Type/Filesystem.php line 151

```
```
Friendica\Core\Storage\Exception\StorageException: Filesystem storage failed to save data to "/home/yunohost.app/friendica/storage/13/60/314155808ed312b7045a43ccb5cb8b78461b7e93b01a70c88352bfbf25da". Check your write permissions in /var/www/friendica/src/Core/Storage/Type/Filesystem.php:151
Stack trace:
#0 /var/www/friendica/src/Model/Photo.php(456): Friendica\Core\Storage\Type\Filesystem->put()
#1 /var/www/friendica/src/Model/Photo.php(641): Friendica\Model\Photo::store()
#2 /var/www/friendica/src/Model/Contact.php(2399): Friendica\Model\Photo::importProfilePhoto()
#3 /var/www/friendica/src/Model/Contact.php(2905): Friendica\Model\Contact::updateAvatar()
#4 /var/www/friendica/src/Model/Contact.php(2685): Friendica\Model\Contact::updateFromProbeArray()
#5 /var/www/friendica/src/Model/Contact.php(2629): Friendica\Model\Contact::updateFromProbe()
#6 /var/www/friendica/src/Model/Contact.php(2644): Friendica\Model\Contact::updateByIdIfNeeded()
#7 /var/www/friendica/src/Protocol/ActivityPub/Processor.php(1678): Friendica\Model\Contact::updateByUrlIfNeeded()
#8 /var/www/friendica/src/Protocol/ActivityPub/Receiver.php(828): Friendica\Protocol\ActivityPub\Processor::fetchMissingActivity()
#9 /var/www/friendica/src/Protocol/ActivityPub/Receiver.php(756): Friendica\Protocol\ActivityPub\Receiver::routeActivities()
#10 /var/www/friendica/src/Protocol/ActivityPub/Receiver.php(169): Friendica\Protocol\ActivityPub\Receiver::processActivity()
#11 /var/www/friendica/src/Module/ActivityPub/Inbox.php(101): Friendica\Protocol\ActivityPub\Receiver::processInbox()
#12 /var/www/friendica/src/BaseModule.php(233): Friendica\Module\ActivityPub\Inbox->post()
#13 /var/www/friendica/src/Module/BaseApi.php(109): Friendica\BaseModule->run()
#14 /var/www/friendica/src/Module/ActivityPub/Inbox.php(43): Friendica\Module\BaseApi->run()
#15 /var/www/friendica/src/App.php(711): Friendica\Module\ActivityPub\Inbox->run()
#16 /var/www/friendica/index.php(46): Friendica\App->runFrontend()
#17 {main}
```

`/home/yunohost.app/friendica/storage/` is owned by `friendica::www-data` with 750 file permission. The folders inside owned by the same byt with 0770 permission.

I also get this `CRITICAL 	app 	unable to create directory /var/www/friendica/view/smarty3/compiled/97/51/6e`

hm...

But generally our Friendica works quite well. I wonder what's the issue.

**Comment by annando** [comment]
I just see that you are on the stable version. AFAIK we had some issue in the post update. Could you switch to the RC? Warning: This includes some massive database updates that will block your system for hours.

**Comment by tio-trom** [comment]
Unfortunately I cannot update to the RC for now....but when the RC moves to stable I can try and see if these errors are fixed and I can update this issue.

**Comment by tio-trom** [comment]
I updated to version 2024.08 that is running at the web location https://social.trom.tf. The database version is 1571/1571, the post update version is 1544/1550.

Same issues...

```
bin/console postupdate
Check for pending update actions.
Done.
Execute pending post updates.
[Error] Unable to retrieve the host in URL:   
```

If you have any ideas about what I can try please let me know...

**Comment by annando** [comment]
I need a callstack to trace it down. You should have something in your log file.

**Comment by tio-trom** [comment]
I gathered the logs for the past minutes using the debug type of log file. In that time I tried those commands. A lot of logs https://paste.trom.tf/abocamopik.swift https://paste.trom.tf/wasaqiroti.swift https://paste.trom.tf/cavucevoxe.sql - maybe I can try to find something specific through them?

**Comment by annando** [comment]
Just search for `[Error] Unable to retrieve the host in URL:` in that file.

**Comment by tio-trom** [comment]
Sorry I forgot to say that I already did that and found nothing. I thought might be something else to look for...

**Comment by annando** [comment]
Please repeat the steps that lead to the "Unable to retrieve the host in URL" message and then search for that in the log. There should be an entry then.

**Comment by tio-trom** [comment]
Unfortunately that's exactly what I did before. Now I did it again. Logs setup for ERRORS, then via ssh opened the friendica folder  and did these:

```
root@server /var/www/friendica # bin/console dbstructure update

root@server /var/www/friendica # bin/console postupdate
Check for pending update actions.
Done.
Execute pending post updates.
[Error] Unable to retrieve the host in URL:    
```
I cannot find the error in the logs https://paste.trom.tf/avuyexapiq.php

**Comment by annando** [comment]
Please try the change in the PR https://github.com/friendica/friendica/pull/14396, set your loglevel at least to `notice` and then execute the post update again. You then should have a log message `Exception on storing engagement` in your log file.

**Comment by tio-trom** [comment]
I did it. Unfortunately I cannot find that... Here are the logs - https://paste.trom.tf/sefuzohoja.php

I can only see these about the postupdate

```
2024-08-25T12:53:57Z console [NOTICE]: Update starting. {"from":1571,"to":1571} - {"file":"Update.php","line":158,"function":"run","request-id":"66cb2965ab952","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"68dcf0","process_id":902921}
2024-08-25T12:53:57Z console [NOTICE]: Execute structure update [] - {"file":"Update.php","line":201,"function":"run","request-id":"66cb2965ab952","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"68dcf0","process_id":902921}
2024-08-25T12:53:57Z app [NOTICE]: no data for session {"session_id":"b2p5qbs5n6mle5eedosir3vmkk","uri":"/profile/tio/conversations?page=898&tag=Jupiter"} - {"file":"Database.php","line":78,"function":"read","request-id":"66cb2965dbbea","stack":"Database::read, session_start (54), Native::start (150), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (92), DI::app (42)","uid":"81acf4","process_id":888798}
2024-08-25T12:53:57Z console [NOTICE]: Database structure update finished. {"from":1571,"to":1571} - {"file":"Update.php","line":219,"function":"run","request-id":"66cb2965ab952","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"68dcf0","process_id":902921}
2024-08-25T12:53:57Z app [NOTICE]: no data for session {"session_id":"cc04jdm6khe8lhst325li7ietg","uri":"/receive/public"} - {"file":"Database.php","line":78,"function":"read","request-id":"66cb2965dc726","stack":"Database::read, session_start (54), Native::start (150), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (92), DI::app (42)","uid":"68bdf5","process_id":888797}
2024-08-25T12:53:57Z console [NOTICE]: Update success. {"from":1571,"to":1571} - {"file":"Update.php","line":251,"function":"run","request-id":"66cb2965ab952","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"68dcf0","process_id":902921}
```

After I did the change to that file should I have restarted any service?

**Comment by annando** [comment]
Please execute `bin/console postupdate`.

**Comment by tio-trom** [comment]
This is what I did. `Please try the change in the PR https://github.com/friendica/friendica/pull/14396, set your loglevel at least to notice and then execute the post update again.` - and no outputs about `Exception on storing engagement`

**Comment by annando** [comment]
What had been the command line output?

**Comment by tio-trom** [comment]
This:

```
root@server /var/www/friendica # bin/console postupdate
Check for pending update actions.
Done.
Execute pending post updates.
[Error] Unable to retrieve the host in URL:  
```

**Comment by tio-trom** [comment]
Should I manually do these changes and test on my instance?

**Comment by annando** [comment]
Not sure if you can do it easily since there are really many places. You could also switch to the `develop` branch (but then you can't switch back). When you apply the changes, you will have to edit them line by line, since of course the develop branch already differs from the stable one.

**Comment by tio-trom** [comment]
Ok then probably I should wait for the 09 release

**Comment by annando** [comment]
Waiting for the release can have the effect that the problem isn't solved until the release after the next release, when my changes hadn't covered the problem.

**Comment by tio-trom** [comment]
ok then I will do all of those changes manually today and test it out. I'll update it here.

**Comment by tio-trom** [comment]
Just to make sure I won't ruin our instance: is it ok to do all of the changes here manually https://github.com/friendica/friendica/pull/14398/files on my instance? How do you recommend doing this let me know please? Better ask now than create more issues later.

**Comment by annando** [comment]
Yes, but I guess you only need to do this in the files src/Model/Photo.php, src/Model/Post/Media.php and src/Model/User.php. If that doesn't work, you should try with src/Util/HTTPSignature.php and src/Util/ParseUrl.php.

**Comment by tio-trom** [comment]
Unfortunately no new result from that....I changed all files you suggested. Rebooted the server just in case. Did thr post update again:

```
bin/console postupdate
Check for pending update actions.
Done.
Execute pending post updates.
[Error] Unable to retrieve the host in URL: 
```

I cannot find anything in the logs either https://paste.trom.tf/siwesuqufo.php

:/

**Comment by annando** [comment]
Sadly the log is truncated. Please try the following: Open two terminals. In the first one you call `tail -f friendica.log | grep -a PostUpdate.php` (change `friendica.log` to the path and name of your logfile)

Keep the first terminal open, while you execute `bin/console postupdate` in the second window. Make sure that the user has got write permissions for the log file.

After you executed the command, the first window should return something. If that is not the case, then you have got a permission problem that you need to fix.

**Comment by tio-trom** [comment]
```
bin/console postupdate
Check for pending update actions.
Done.
Execute pending post updates.
[Error] Unable to retrieve the host in URL:  
```

Then I got this

```
tail -f friendica.log | grep -a PostUpdate
2024-09-01T15:43:47Z console [NOTICE]: Update starting. {"from":1571,"to":1571} - {"file":"Update.php","line":158,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}
2024-09-01T15:43:47Z console [NOTICE]: Execute structure update [] - {"file":"Update.php","line":201,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}
2024-09-01T15:43:48Z console [NOTICE]: Database structure update finished. {"from":1571,"to":1571} - {"file":"Update.php","line":219,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}
2024-09-01T15:43:48Z console [NOTICE]: Update success. {"from":1571,"to":1571} - {"file":"Update.php","line":251,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}

```

**Comment by annando** [comment]
Please do the following and report the result here:
`cat friendica.log | grep -a 66d48bb3c8c08`

**Comment by tio-trom** [comment]
```
cat friendica.log | grep -a 66d48bb3c8c08
2024-09-01T15:43:47Z console [NOTICE]: Update starting. {"from":1571,"to":1571} - {"file":"Update.php","line":158,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}
2024-09-01T15:43:47Z console [NOTICE]: Execute structure update [] - {"file":"Update.php","line":201,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}
2024-09-01T15:43:48Z console [NOTICE]: Database structure update finished. {"from":1571,"to":1571} - {"file":"Update.php","line":219,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}
2024-09-01T15:43:48Z console [NOTICE]: Update success. {"from":1571,"to":1571} - {"file":"Update.php","line":251,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}

```

**Comment by annando** [comment]
Please perform a manual change in the file `src/Network/HTTPClient/Client/HTTPClient.php` in line 64.
Replace this line:
```
throw new \InvalidArgumentException('Unable to retrieve the host in URL: ' . $url);
```
with these lines:
```
$this->logger->debug('Unable to retrieve the host in URL', ['url' => $url]);
$this->profiler->stopRecording();
return CurlResult::createErrorCurl($this->logger, $url);
```
Then try again.

**Comment by tio-trom** [comment]
OK how about now :)
```

bin/console postupdate
Check for pending update actions.
Done.
Execute pending post updates.
..
All pending post updates are done.

```

Seems to work :) ?

```
tail -f friendica.log | grep -a PostUpdate
2024-09-01T19:38:24Z console [NOTICE]: Update starting. {"from":1571,"to":1571} - {"file":"Update.php","line":158,"function":"run","request-id":"66d4c2b0c0cb3","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"36ad6c","process_id":1475708}
2024-09-01T19:38:24Z console [NOTICE]: Execute structure update [] - {"file":"Update.php","line":201,"function":"run","request-id":"66d4c2b0c0cb3","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"36ad6c","process_id":1475708}
2024-09-01T19:38:25Z console [NOTICE]: Database structure update finished. {"from":1571,"to":1571} - {"file":"Update.php","line":219,"function":"run","request-id":"66d4c2b0c0cb3","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"36ad6c","process_id":1475708}
2024-09-01T19:38:25Z console [NOTICE]: Update success. {"from":1571,"to":1571} - {"file":"Update.php","line":251,"function":"run","request-id":"66d4c2b0c0cb3","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"36ad6c","process_id":1475708}

```

```

cat friendica.log | grep -a 66d48bb3c8c08
2024-09-01T15:43:47Z console [NOTICE]: Update starting. {"from":1571,"to":1571} - {"file":"Update.php","line":158,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}
2024-09-01T15:43:47Z console [NOTICE]: Execute structure update [] - {"file":"Update.php","line":201,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}
2024-09-01T15:43:48Z console [NOTICE]: Database structure update finished. {"from":1571,"to":1571} - {"file":"Update.php","line":219,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}
2024-09-01T15:43:48Z console [NOTICE]: Update success. {"from":1571,"to":1571} - {"file":"Update.php","line":251,"function":"run","request-id":"66d48bb3c8c08","stack":"Update::run (96), PostUpdate::doExecute (108), Console::execute (165), Console::doExecute (108), Console::execute (45)","uid":"c453fe","process_id":1290416}

```

**Comment by tio-trom** [comment]
`This is Friendica, version 2024.08 that is running at the web location https://social.trom.tf. The database version is 1571/1571, the post update version is 1550/1550.`

Yuhuu!!!

Thank you so much Michael!
