### ISSUE TITLE
Uncaught Exception TypeError: "count(): Argument #1 ($value) must be of type Countable|array, null given"

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#14319]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

A user reported that the network page is completely blank. I checked it myself but my own network page is working. However, I can find exceptions in Friendica's log and error 500 messages in Apaches log. So, it must be something with the content that is loaded into the user's network feed.

❗️ I am not on the latest RC code. Current commit is  e3c782010ffe155e4b155c5a242e24ad468d1f35

### Error messages

```
app [ERROR]: Uncaught Exception TypeError: "count(): Argument #1 ($value) must be of type Countable|array, null given" at ..../src/Module/Conversation/Network.php line 249 
{"exception":"TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in .../src/Module/Conversation/Network.php:249
Stack trace:
#0 .../src/Module/Conversation/Network.php(249): count()
#1 .../src/BaseModule.php(250): Friendica\\Module\\Conversation\\Network->content()
#2 .../src/App.php(682): Friendica\\BaseModule->run()
#3 .../index.php(55): Friendica\\App->runFrontend()
#4 {main}"} - 
{"file":null,"line":null,"function":null,"request-id":"66a0b02bc7594","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"bc0092","process_id":2186453}
```

```
"GET /network HTTP/2.0" 500 65 "https://venera.social/" "Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0"
```

### Platform Info

Friendica Version:
2024.06-rc 
**database version is 1569/1569** !!!
post update version is 1550/1550

Friendica Source: 
git

PHP version:
8.1

SQL version:
10.11 MariaDB

**Comment by AlfredSK** [comment]
Looks like this issue is related to that one #14320

**Comment by AlfredSK** [comment]
Yep. Didn't happen again. Closing for now. :-)
