### ISSUE TITLE
DB error 128 - table handler out of memory

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#14320]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

I get this DB error several times a day in Friendica's log: Table handler out of memory

It looks like it is related to user defined channels.

I have searched for this error on the Internet to find out what is causing this. It looks like searching with a FT index with match() can produce huge result sets. When the `innodb-ft-result-cache-limit` is reached the query is running into an error.

The MariaDB default value for `innodb_ft_result_cache_limit` is 2 GB. I am now trying to use 3 GB. But I think it would be better if the default value would be sufficient.

### Error messages

```
2024-07-24T07:54:33Z app [ERROR]: DB Error {"code":128,"error":"Table handler out of memory","params":"SELECT `uri-id`, `owner-id`, `comments`, `activities`, `created` FROM `post-engagement` WHERE (MATCH (`searchtext`) AGAINST ('+(Kaies, (+Tunisie +\\\"network_apub\\\"), (+Tunis +\\\"network_apub\\\"), (+hammamet +\\\"network_apub\\\"), (+bizerte +\\\"network_apub\\\"), (+sousse +\\\"network_apub\\\"), (+monastir +\\\"network_apub\\\"), (+mehdia +\\\"network_apub\\\"), (+sfax +\\\"network_apub\\\"), (+djerba +\\\"network_apub\\\"), (+tozeur +\\\"network_apub\\\"), tunisia, kairouan, nabeul, beja, taberka, carthage,) +(\\\"language_fr\\\")' IN BOOLEAN MODE) AND (NOT `restricted` OR EXISTS(SELECT `id` FROM `post-user` WHERE `uid` = 3881 AND `uri-id` = `post-engagement`.`uri-id`)) AND NOT EXISTS(SELECT `cid` FROM `user-contact` WHERE `uid` = 3881 AND `cid` = `post-engagement`.`owner-id` AND (`ignored` OR `blocked` OR `collapsed` OR `is-blocked` OR `channel-frequency` = 1)) AND `created` > '2024-07-23 22:04:21') ORDER BY `created` ASC LIMIT 100"} - {"file":"Database.php","line":692,"function":"p","request-id":"66a0b338d26ae","stack":"Database::p (1508), Database::select (436), Timeline::getRawChannelItems (255), Timeline::getChannelItems (91), Network::rawContent (244), BaseModule::run (682), App::runFrontend (55)","uid":"3d7c6c","process_id":2203092}

2024-07-24T07:54:33Z app [ERROR]: Uncaught Exception Exception: "Table handler out of memory" at .../src/Module/Conversation/Timeline.php line 438 
{"exception":"Exception: Table handler out of memory in .../src/Module/Conversation/Timeline.php:438
Stack trace:
#0 .../src/Module/Conversation/Timeline.php(255): Friendica\\Module\\Conversation\\Timeline->getRawChannelItems()
#1 .../src/Module/Ping/Network.php(91): Friendica\\Module\\Conversation\\Timeline->getChannelItems()
#2 .../src/BaseModule.php(244): Friendica\\Module\\Ping\\Network->rawContent()
#3 .../src/App.php(682): Friendica\\BaseModule->run()
#4 .../index.php(55): Friendica\\App->runFrontend()
#5 {main}"} - 
{"file":null,"line":null,"function":null,"request-id":"66a0b338d26ae","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"3d7c6c","process_id":2203092}
```

### Platform Info

Friendica Version:
2024.06-rc
database version is 1569/1569 !!!
post update version is 1550/1550
commit is https://github.com/friendica/friendica/commit/e3c782010ffe155e4b155c5a242e24ad468d1f35

Friendica Source: 
git

PHP version:
8.1

SQL version:
MariaDB 10.11

**Comment by AlfredSK** [comment]
I was just thinking if this can be influenced by the channel settings in the admin panel?

**Comment by annando** [comment]
That's a good question.

**Comment by AlfredSK** [comment]
I had raised the setting 'Maximum number of channel posts' to 20.000 to get better results in low traffic channels. I have reset this to 10.000 now and will watch what happens. 

Is 10.000 the default? I think so but I'm not sure.

**Comment by AlfredSK** [comment]
Ok. Setting 'Maximum number of channel posts' to 10000 doesn't help. But raising the MariaDB config value `innodb_ft_result_cache_limit` to at least 2.5 GB seems to solve the issue.

**Comment by AlfredSK** [comment]
Since I raised the MariaDB config value `innodb_ft_result_cache_limit` to `2560000000` the error didn't happen again. Closed as completed.
