### ISSUE TITLE
Path does not exist or is not writeable

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#14386]
I am using the filesystem for storing the media. I have been for a while now. But after the update to 2024.08 I see a ton of these:
![image](https://github.com/user-attachments/assets/d6cbb59e-ebde-4cda-868c-d5c5121420d1)

` 	ERROR 	worker 	Uncaught exception in worker execution`

```
Data
class

Friendica\Core\Storage\Exception\StorageException

message

Path "/home/yunohost.app/friendica/storage" does not exist or is not writeable.

code

0

file

/var/www/friendica/src/Core/Storage/Type/Filesystem.php:60

trace

#0 /var/www/friendica/src/Core/Storage/Repository/StorageManager.php(200): Friendica\Core\Storage\Type\Filesystem->__construct()
#1 /var/www/friendica/src/Core/Storage/Repository/StorageManager.php(131): Friendica\Core\Storage\Repository\StorageManager->getByName()
#2 /var/www/friendica/src/Core/Storage/Repository/StorageManager.php(106): Friendica\Core\Storage\Repository\StorageManager->getWritableStorageByName()
#3 [internal function]: Friendica\Core\Storage\Repository\StorageManager->__construct()
#4 /var/www/friendica/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()
#5 /var/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#6 /var/www/friendica/src/DI.php(265): Dice\Dice->create()
#7 /var/www/friendica/src/Model/Photo.php(455): Friendica\DI::storageManager()
#8 /var/www/friendica/src/Model/Photo.php(646): Friendica\Model\Photo::store()
#9 /var/www/friendica/src/Model/Contact.php(2415): Friendica\Model\Photo::importProfilePhoto()
#10 /var/www/friendica/src/Model/Contact.php(2930): Friendica\Model\Contact::updateAvatar()
#11 /var/www/friendica/src/Model/Contact.php(2710): Friendica\Model\Contact::updateFromProbeArray()
#12 /var/www/friendica/src/Worker/UpdateContact.php(46): Friendica\Model\Contact::updateFromProbe()
#13 [internal function]: Friendica\Worker\UpdateContact::execute()
#14 /var/www/friendica/src/Core/Worker.php(574): call_user_func_array()
#15 /var/www/friendica/src/Core/Worker.php(388): Friendica\Core\Worker::execFunction()
#16 /var/www/friendica/src/Core/Worker.php(123): Friendica\Core\Worker::execute()
#17 /var/www/friendica/bin/worker.php(87): Friendica\Core\Worker::processQueue()
#18 {main}

previous

worker_id

2b8dd5f

worker_cmd

UpdateContact
```

_I think many files are stored as root:root in the storage system. I thought it is the daemon we have running for the workers but now I doubt that._

If the daemon runs as friendica:www-data then all files have the right ownership in the storage path. Also all file in the storage location have 0660. Things should be fine I guess?!

Thing is everything seems to be working fine....so I am not sure what is going on.

**Comment by annando** [comment]
This looks like some permission issue on your side. Please ensure that both the worker (invoked by cron or daemon) and the frontend is running with the same user/user group. Then ensure that the storage folder is owned by exactly this user/user group.

**Comment by tio-trom** [comment]
That's the weird bit. All of our friendica processes run under the user "friendica" and group "www-data".

![image](https://github.com/user-attachments/assets/fa2fdf86-aa4c-4d5b-8098-8dcc3678452c)

![image](https://github.com/user-attachments/assets/1cca390b-5d13-4606-a19a-a1197806f4ca)


The main friendica folder is owned by the same user/group:

![image](https://github.com/user-attachments/assets/221aa7c8-28fa-45e4-acb9-2b88080699c5)

Same for the storage

![image](https://github.com/user-attachments/assets/0519bb3c-9a9d-4bad-a2f0-07f34b2724fe)

And our daemon runs via a systemd service with the same user/group


```
[Unit]
Description=Friendica daemon
After=network.target mariadb.service
Requires=network.target remote-fs.target nss-lookup.target


[Service]
User=friendica
Group=www-data
WorkingDirectory=/var/www/friendica/
Type=simple
StandardOutput=append:/var/log/friendica/daemon.log
StandardError=inherit
ExecStart=/usr/bin/php8.2 /var/www/friendica/bin/daemon.php start
ExecStop=/usr/bin/php8.2 /var/www/friendica/bin/daemon.php stop
PIDFile=/var/www/friendica/daemon.pid
PrivateTmp=true
InaccessibleDirectories=/home /root /boot /opt /mnt /media
ReadOnlyDirectories=/etc /usr
Restart=always
RestartSec=10
StartLimitBurst=1

# Sandboxing options to harden security
# Depending on specificities of your service/app, you may need to tweak these 
# .. but this should be a good baseline
# Details for these options: https://www.freedesktop.org/software/systemd/man/systemd.exec.html
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 AF_NETLINK
RestrictNamespaces=yes
RestrictRealtime=yes
DevicePolicy=closed
ProtectClock=yes
ProtectHostname=yes
ProtectProc=invisible
ProtectSystem=full
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
LockPersonality=yes
SystemCallArchitectures=native
SystemCallFilter=~@clock @debug @module @mount @obsolete @reboot @setuid @swap @cpu-emulation @privileged

# Denying access to capabilities that should not be relevant for webapps
# Doc: https://man7.org/linux/man-pages/man7/capabilities.7.html
CapabilityBoundingSet=~CAP_RAWIO CAP_MKNOD
CapabilityBoundingSet=~CAP_AUDIT_CONTROL CAP_AUDIT_READ CAP_AUDIT_WRITE
CapabilityBoundingSet=~CAP_SYS_BOOT CAP_SYS_TIME CAP_SYS_MODULE CAP_SYS_PACCT
CapabilityBoundingSet=~CAP_LEASE CAP_LINUX_IMMUTABLE CAP_IPC_LOCK
CapabilityBoundingSet=~CAP_BLOCK_SUSPEND CAP_WAKE_ALARM
CapabilityBoundingSet=~CAP_SYS_TTY_CONFIG
CapabilityBoundingSet=~CAP_MAC_ADMIN CAP_MAC_OVERRIDE
CapabilityBoundingSet=~CAP_NET_ADMIN CAP_NET_BROADCAST CAP_NET_RAW
CapabilityBoundingSet=~CAP_SYS_ADMIN CAP_SYS_PTRACE CAP_SYSLOG 

[Install]
WantedBy=multi-user.target
```

I am baffled. We didn't change much from before the update. If you have any other suggestions? Strange thing is all seems to work fine...

**Comment by tio-trom** [comment]
One more thing: the storage path is for uploaded files

![image](https://github.com/user-attachments/assets/9376eaa5-35b8-4b9e-93ad-3f65123f0b07)

That means the files (probably photos) uploaded on our instance. Correct?

But then the errors I get are mostly about Update Contact:

![image](https://github.com/user-attachments/assets/b8f53ee9-4f50-4ee3-aaee-53150cfd37cd)

Why does UpdateContact tries to access the storage space? Or is it that the storage location is also for cached files from external users?

**Comment by annando** [comment]
The storage is used by both the users on your system and for the avatar cache of external contacts.

**Comment by tio-trom** [comment]
What would happen if I change the storage to the database now to test it? Will the old storage still be used for past uploads?

**Comment by annando** [comment]
Yes, you can change it at any time without any problems.

**Comment by tio-trom** [comment]
I switched to the database storage for the past 30 minutes. I even rebooted the entire server. Isn't it weird that I still get these messages about `Path "/home/yunohost.app/friendica/storage" does not exist or is not writeable.` ? Shouldn't that if it uses the database the storage path is irrelevant? Why getting these messages?

**Comment by annando** [comment]
What does `bin/console storage list` return?

**Comment by tio-trom** [comment]
```
root@server /var/www/friendica # bin/console storage list
 Sel | Name                
-----------------------
     | Filesystem          
 *   | Database 
```

**Comment by tio-trom** [comment]
I've also noticed a huge increase in message queues after changing to the database

![image](https://github.com/user-attachments/assets/01851d4e-1994-4750-8534-e33ac0b37885)
![image](https://github.com/user-attachments/assets/c20cd2f0-58d2-4fc6-8908-8a96394afe02)

**Comment by annando** [comment]
Something else: have you checked, if possibly due to some configuration changes the storage folder is now outside `open_basedir`?

We could do some drastic method. You could disable the avatar cache in total. And possibly you could even remove the storage in total (there is now  command for it).

**Comment by tio-trom** [comment]
> Something else: have you checked, if possibly due to some configuration changes the storage folder is now outside open_basedir?

Can you please tell me how to check that? Cannot find anything in the docs https://wiki.friendi.ca/docs/admin?q=open_basedir&do=search

EDIT: ah you mean to check the php.ini for it? Hold on

![image](https://github.com/user-attachments/assets/4c083a29-f39f-4294-be3f-8dee66f61758)

No. Seems ok. Also we did not modify any of these files.


> We could do some drastic method. You could disable the avatar cache in total. And possibly you could even remove the storage in total (there is now command for it).

I am very concerned to not nuke my instance. I just dont understand how come it all seems to work fine but also getting these messages about the storage while using the database for storage. What would we test if we would do this drastic approach?

**Comment by tio-trom** [comment]
By the way I also get this error often_

```
2024-08-25T21:23:22Z 	ERROR 	worker 	Uncaught exception in worker execution
File 	Line 	Function 	UID 	Process ID
Worker.php 	579 	execFunction 	eec937 	226124
Data
class

Error

message

Call to undefined method Friendica\Core\Storage\Repository\StorageManager::put()

code

0

file

/var/www/friendica/src/Model/Photo.php:459

trace

#0 /var/www/friendica/src/Model/Photo.php(646): Friendica\Model\Photo::store()
#1 /var/www/friendica/src/Model/Contact.php(2415): Friendica\Model\Photo::importProfilePhoto()
#2 /var/www/friendica/src/Model/Contact.php(2930): Friendica\Model\Contact::updateAvatar()
#3 /var/www/friendica/src/Model/Contact.php(2710): Friendica\Model\Contact::updateFromProbeArray()
#4 /var/www/friendica/src/Worker/UpdateContact.php(46): Friendica\Model\Contact::updateFromProbe()
#5 [internal function]: Friendica\Worker\UpdateContact::execute()
#6 /var/www/friendica/src/Core/Worker.php(574): call_user_func_array()
#7 /var/www/friendica/src/Core/Worker.php(388): Friendica\Core\Worker::execFunction()
#8 /var/www/friendica/src/Core/Worker.php(123): Friendica\Core\Worker::execute()
#9 /var/www/friendica/bin/worker.php(87): Friendica\Core\Worker::processQueue()
#10 {main}

previous

worker_id

9103c0c

worker_cmd

UpdateContact
```

Maybe it helps you figure it out :P

**Comment by annando** [comment]
As an interim solution I recommend to deactivate the avatar cache in the site settings. This buys us some time and should help to reduce the worker load.

**Comment by tio-trom** [comment]
Ok I did that for now. I wonder about this error `Call to undefined method Friendica\Core\Storage\Repository\StorageManager::put()` - maybe it is a clue about the issue I am having.

**Comment by trendless** [comment]
@tio-trom did you get this sorted out?

**Comment by tio-trom** [comment]
I do not think I see that error anymore. I will close this issue!

**Comment by trendless** [comment]
I'm wondering if the issue is/was having `/home` in the systemd file here:`InaccessibleDirectories=/home /root /boot /opt /mnt /media` 🤔

**Comment by tio-trom** [comment]
hmm ikd honestly...
