### ISSUE TITLE
Filesystem storage failed to save data to

### ISSUE THREAD

**Issue by tio-trom** [friendica/friendica#14384]
After updating to 2024.08 I get this error quite often:

```
Friendica\Core\Storage\Exception\StorageException: Filesystem storage failed to save data to "/home/yunohost.app/friendica/storage/94/5e/4dd67f1cdfacd5f682bbfa3918df2dfa025a15d86f452b2bb2ae06c79372". Check your write permissions in /var/www/friendica/src/Core/Storage/Type/Filesystem.php:151
Stack trace:
#0 /var/www/friendica/src/Model/Photo.php(459): Friendica\Core\Storage\Type\Filesystem->put()
#1 /var/www/friendica/src/Model/Photo.php(646): Friendica\Model\Photo::store()
#2 /var/www/friendica/src/Model/Contact.php(2415): Friendica\Model\Photo::importProfilePhoto()
#3 /var/www/friendica/src/Model/Contact.php(2930): Friendica\Model\Contact::updateAvatar()
#4 /var/www/friendica/src/Model/Contact.php(2710): Friendica\Model\Contact::updateFromProbeArray()
#5 /var/www/friendica/src/Model/Contact.php(2645): Friendica\Model\Contact::updateFromProbe()
#6 /var/www/friendica/src/Model/Contact.php(2660): Friendica\Model\Contact::updateByIdIfNeeded()
#7 /var/www/friendica/src/Protocol/ActivityPub/Processor.php(1770): Friendica\Model\Contact::updateByUrlIfNeeded()
#8 /var/www/friendica/src/Protocol/ActivityPub/Processor.php(1698): Friendica\Protocol\ActivityPub\Processor::processActivity()
#9 /var/www/friendica/src/Protocol/ActivityPub/Receiver.php(834): Friendica\Protocol\ActivityPub\Processor::fetchMissingActivity()
#10 /var/www/friendica/src/Protocol/ActivityPub/Receiver.php(762): Friendica\Protocol\ActivityPub\Receiver::routeActivities()
#11 /var/www/friendica/src/Protocol/ActivityPub/Receiver.php(170): Friendica\Protocol\ActivityPub\Receiver::processActivity()
#12 /var/www/friendica/src/Module/ActivityPub/Inbox.php(109): Friendica\Protocol\ActivityPub\Receiver::processInbox()
#13 /var/www/friendica/src/BaseModule.php(233): Friendica\Module\ActivityPub\Inbox->post()
#14 /var/www/friendica/src/Module/BaseApi.php(109): Friendica\BaseModule->run()
#15 /var/www/friendica/src/Module/ActivityPub/Inbox.php(45): Friendica\Module\BaseApi->run()
#16 /var/www/friendica/src/App.php(682): Friendica\Module\ActivityPub\Inbox->run()
#17 /var/www/friendica/index.php(46): Friendica\App->runFrontend()
#18 {main}
```
There are multiple of `/94/5e/4dd67f1cdfacd5f682bbfa3918df2dfa025a15d86f452b2bb2ae06c7937` kind - not just that one.

But everything seems to work fine. I can upload media and all that.

I see these files that are mentioned (like `dd67f1cdfacd5f682bbfa3918df2dfa025a15d86f452b2bb2ae06c7937`) are owned by `root::root` instead of `friendica::www-data`. A bunch are like that but I wonder why are they created under root? 

UPDATE: hm our friendica daemon always runs as root sine we could not fix this issue - https://github.com/YunoHost-Apps/friendica_ynh/issues/133 - but so it was before....and for months our friendica worked ok. I suspect the daemon creates these root files!?

**Comment by tio-trom** [comment]
I think we fixed it - at least I am sure it is an issue, or it was, with the ynh package. Am closing it now.
