### ISSUE TITLE
Vier Continuous Thread

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#14458]
- [x ] I have searched open and closed issues for duplicates

### Bug Description

In Vier Theme, when you select continuous thread, when you get to the end of the current set of messages and it loads the next set, rather than continue to display them below, as it does with Frio, the display overlaps and a new set overlays the existing but is shifted to the right.
### Steps to Reproduce

1.  step one Select the Vier Theme
2.  step two Scroll Down to the Bottom of the existing Thread
3.  step three When it brings in more it freaks out.

Actual Result:

In vier, when it loads more messages, it goes wonky, see attached image.
Expected Result:

Expect it to just display more below existing, as it does with Frio.
### Screenshots

![vire-continuous-thread](https://github.com/user-attachments/assets/59381db8-b14e-484b-aefb-4c41e7c8a723)

### Platform Info

Friendica Version:

Version
    Friendica 'Yellow Archangel' 2024.09-dev - 1573 
Friendica Source: 
Github
PHP version:
PHP version	8.1.30
php.ini	/etc/php/8.1/cgi/php.ini
upload_max_filesize	8G
post_max_size	8G
memory_limit	8G

     I have tried 8.0 through 8.3, 8.1 and 8.2 act the same, 8.0 and 8.3 both have additional issues.

SQL version:
mysql from 11.5.2-MariaDB, client 15.2 for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by 4nanook** [comment]
I don't think is a shortage of resources:

root@inuvik:~# uptime
 01:18:45 up 4 days, 18:18,  1 user,  load average: 2.76, 3.50, 3.88
root@inuvik:~# free -h
               total        used        free      shared  buff/cache   available
Mem:           251Gi        30Gi        35Gi        58Gi       185Gi       160Gi
Swap:          500Gi          0B       500Gi

Also Linux and Kernel Versions:PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

Linux inuvik 6.11.0 #1 SMP Wed Sep 25 21:39:12 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux

I really would like to get this operating cleanly and properly.  If there is any other information I can provide, please contact
me.

**Comment by 4nanook** [comment]
If CPU matters:
cpu-info
Packages:
        0: Intel Core i9-10980XE
Microarchitectures:
        18x Sky Lake
Cores:
        0: 2 processors (0-1), Intel Sky Lake
        1: 2 processors (2-3), Intel Sky Lake
        2: 2 processors (4-5), Intel Sky Lake
        3: 2 processors (6-7), Intel Sky Lake
        4: 2 processors (8-9), Intel Sky Lake
        5: 2 processors (10-11), Intel Sky Lake
        6: 2 processors (12-13), Intel Sky Lake
        7: 2 processors (14-15), Intel Sky Lake
        8: 2 processors (16-17), Intel Sky Lake
        9: 2 processors (18-19), Intel Sky Lake
        10: 2 processors (20-21), Intel Sky Lake
        11: 2 processors (22-23), Intel Sky Lake
        12: 2 processors (24-25), Intel Sky Lake
        13: 2 processors (26-27), Intel Sky Lake
        14: 2 processors (28-29), Intel Sky Lake
        15: 2 processors (30-31), Intel Sky Lake
        16: 2 processors (32-33), Intel Sky Lake
        17: 2 processors (34-35), Intel Sky Lake
Logical processors (System ID):
        0 (0): APIC ID 0x00000000
        1 (18): APIC ID 0x00000001
        2 (1): APIC ID 0x00000002
        3 (19): APIC ID 0x00000003
        4 (2): APIC ID 0x00000004
        5 (20): APIC ID 0x00000005
        6 (3): APIC ID 0x00000006
        7 (21): APIC ID 0x00000007
        8 (4): APIC ID 0x00000008
        9 (22): APIC ID 0x00000009
        10 (5): APIC ID 0x00000010
        11 (23): APIC ID 0x00000011
        12 (6): APIC ID 0x00000012
        13 (24): APIC ID 0x00000013
        14 (7): APIC ID 0x00000014
        15 (25): APIC ID 0x00000015
        16 (8): APIC ID 0x00000016
        17 (26): APIC ID 0x00000017
        18 (9): APIC ID 0x00000020
        19 (27): APIC ID 0x00000021
        20 (10): APIC ID 0x00000022
        21 (28): APIC ID 0x00000023
        22 (11): APIC ID 0x00000024
        23 (29): APIC ID 0x00000025
        24 (12): APIC ID 0x00000026
        25 (30): APIC ID 0x00000027
        26 (13): APIC ID 0x00000028
        27 (31): APIC ID 0x00000029
        28 (14): APIC ID 0x00000030
        29 (32): APIC ID 0x00000031
        30 (15): APIC ID 0x00000032
        31 (33): APIC ID 0x00000033
        32 (16): APIC ID 0x00000034
        33 (34): APIC ID 0x00000035
        34 (17): APIC ID 0x00000036
        35 (35): APIC ID 0x00000037

Linux calls it two processors, it really means it's 18 cores with hyperthreading so 36 threads, 18 cores.

And the disk partition Friendica is on:

Filesystem      Size  Used Avail Use% Mounted on
/dev/md1p2       13T  676G   11T   6% /space

So not a space issue either.  Please tell me anything I can do to fix.  I have reviewed the requirements and have met all the specified requirements including specified PHP configuration, though it suggests anything 8.x should be good but neither
8.0 nor 8.3 function well, 8.1 and 8.2 are best but both still show this bug.

I am seeing a lot of these PHP errors.  I don't know the PHP language so is all gibberish to me.
2024-09-09T07:07:40Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Module\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93" at /space/www/friendica/src/Module/Xrd.php line 173 {"exception":"TypeError: Friendica\\Module\\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93 and defined in /space/www/friendica/src/Module/Xrd.php:173\nStack trace:\n#0 /space/www/friendica/src/Module/Xrd.php(93): Friendica\\Module\\Xrd->printJSON()\n#1 /space/www/friendica/src/BaseModule.php(230): Friendica\\Module\\Xrd->rawContent()\n#2 /space/www/friendica/src/App.php(668): Friendica\\BaseModule->run()\n#3 /space/www/friendica/index.php(41): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"66de9ebcbebe0","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"ccb4a8","process_id":3261016}
2024-09-09T08:19:35Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Module\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93" at /space/www/friendica/src/Module/Xrd.php line 173 {"exception":"TypeError: Friendica\\Module\\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93 and defined in /space/www/friendica/src/Module/Xrd.php:173\nStack trace:\n#0 /space/www/friendica/src/Module/Xrd.php(93): Friendica\\Module\\Xrd->printJSON()\n#1 /space/www/friendica/src/BaseModule.php(230): Friendica\\Module\\Xrd->rawContent()\n#2 /space/www/friendica/src/App.php(668): Friendica\\BaseModule->run()\n#3 /space/www/friendica/index.php(41): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"66deaf97265b9","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"9a79bc","process_id":3417222}
2024-09-09T08:19:35Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Module\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93" at /space/www/friendica/src/Module/Xrd.php line 173 {"exception":"TypeError: Friendica\\Module\\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93 and defined in /space/www/friendica/src/Module/Xrd.php:173\nStack trace:\n#0 /space/www/friendica/src/Module/Xrd.php(93): Friendica\\Module\\Xrd->printJSON()\n#1 /space/www/friendica/src/BaseModule.php(230): Friendica\\Module\\Xrd->rawContent()\n#2 /space/www/friendica/src/App.php(668): Friendica\\BaseModule->run()\n#3 /space/www/friendica/index.php(41): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"66deaf97d9dea","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"4ca96c","process_id":3417239}
2024-09-09T08:26:53Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Module\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93" at /space/www/friendica/src/Module/Xrd.php line 173 {"exception":"TypeError: Friendica\\Module\\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93 and defined in /space/www/friendica/src/Module/Xrd.php:173\nStack trace:\n#0 /space/www/friendica/src/Module/Xrd.php(93): Friendica\\Module\\Xrd->printJSON()\n#1 /space/www/friendica/src/BaseModule.php(230): Friendica\\Module\\Xrd->rawContent()\n#2 /space/www/friendica/src/App.php(668): Friendica\\BaseModule->run()\n#3 /space/www/friendica/index.php(41): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"66deb14d25734","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"396118","process_id":3432926}
2024-09-09T09:21:01Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Module\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93" at /space/www/friendica/src/Module/Xrd.php line 173 {"exception":"TypeError: Friendica\\Module\\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93 and defined in /space/www/friendica/src/Module/Xrd.php:173\nStack trace:\n#0 /space/www/friendica/src/Module/Xrd.php(93): Friendica\\Module\\Xrd->printJSON()\n#1 /space/www/friendica/src/BaseModule.php(230): Friendica\\Module\\Xrd->rawContent()\n#2 /space/www/friendica/src/App.php(668): Friendica\\BaseModule->run()\n#3 /space/www/friendica/index.php(41): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"66debdfd47a35","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"f64624","process_id":3551954}
2024-09-09T09:26:44Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Module\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93" at /space/www/friendica/src/Module/Xrd.php line 173 {"exception":"TypeError: Friendica\\Module\\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93 and defined in /space/www/friendica/src/Module/Xrd.php:173\nStack trace:\n#0 /space/www/friendica/src/Module/Xrd.php(93): Friendica\\Module\\Xrd->printJSON()\n#1 /space/www/friendica/src/BaseModule.php(230): Friendica\\Module\\Xrd->rawContent()\n#2 /space/www/friendica/src/App.php(668): Friendica\\BaseModule->run()\n#3 /space/www/friendica/index.php(41): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"66debf5410e59","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"b33617","process_id":3567656}
2024-09-09T09:30:54Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Module\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93" at /space/www/friendica/src/Module/Xrd.php line 173 {"exception":"TypeError: Friendica\\Module\\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93 and defined in /space/www/friendica/src/Module/Xrd.php:173\nStack trace:\n#0 /space/www/friendica/src/Module/Xrd.php(93): Friendica\\Module\\Xrd->printJSON()\n#1 /space/www/friendica/src/BaseModule.php(230): Friendica\\Module\\Xrd->rawContent()\n#2 /space/www/friendica/src/App.php(668): Friendica\\BaseModule->run()\n#3 /space/www/friendica/index.php(41): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"66dec04e3d635","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"27e07e","process_id":3578335}
2024-09-09T09:33:21Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Module\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93" at /space/www/friendica/src/Module/Xrd.php line 173 {"exception":"TypeError: Friendica\\Module\\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93 and defined in /space/www/friendica/src/Module/Xrd.php:173\nStack trace:\n#0 /space/www/friendica/src/Module/Xrd.php(93): Friendica\\Module\\Xrd->printJSON()\n#1 /space/www/friendica/src/BaseModule.php(230): Friendica\\Module\\Xrd->rawContent()\n#2 /space/www/friendica/src/App.php(668): Friendica\\BaseModule->run()\n#3 /space/www/friendica/index.php(41): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"66dec0e0edb1a","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"2ef7e1","process_id":3583501}
2024-09-09T09:41:52Z app [ERROR]: Uncaught Exception TypeError: "Friendica\Module\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93" at /space/www/friendica/src/Module/Xrd.php line 173 {"exception":"TypeError: Friendica\\Module\\Xrd::printJSON(): Argument #1 ($alias) must be of type string, null given, called in /space/www/friendica/src/Module/Xrd.php on line 93 and defined in /space/www/friendica/src/Module/Xrd.php:173\nStack trace:\n#0 /space/www/friendica/src/Module/Xrd.php(93): Friendica\\Module\\Xrd->printJSON()\n#1 /space/www/friendica/src/BaseModule.php(230): Friendica\\Module\\Xrd->rawContent()\n#2 /space/www/friendica/src/App.php(668): Friendica\\BaseModule->run()\n#3 /space/www/friendica/index.php(41): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"66dec2e0a00a4","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"1b963a","process_id":3604489}
2024-09-17T21:37:20Z app [ALERT]: Fatal Error (E_COMPILE_ERROR): Cannot redeclare vier_init() (previously declared in /space/www/friendica/view/theme/nanook/theme.php:23) {"code":64,"message":"Cannot redeclare vier_init() (previously declared in /space/www/friendica/view/theme/nanook/theme.php:23)","file":"/space/www/friendica/view/theme/vier/theme.php","line":97,"trace":null} - {"file":null,"line":null,"function":null,"request-id":"66e9f690c33de","stack":"ErrorHandler::handleFatalError","uid":"257db3","process_id":2720023}
2024-10-05T02:50:33Z app [ALERT]: Fatal Error (E_COMPILE_ERROR): Cannot redeclare vier_init() (previously declared in /space/www/friendica/view/theme/nanook/theme.php:23) {"code":64,"message":"Cannot redeclare vier_init() (previously declared in /space/www/friendica/view/theme/nanook/theme.php:23)","file":"/space/www/friendica/view/theme/vier/theme.php","line":97,"trace":null} - {"file":null,"line":null,"function":null,"request-id":"6700a9787c8f7","stack":"ErrorHandler::handleFatalError","uid":"2ca5b5","process_id":1411932}

**Comment by 4nanook** [comment]
I found the issue myself.  When I ran composer diagnose, it told me that the uopz module was not exiting on signal.  I removed this module.  After this this bug and also another that I had not yet submitted, preview for comments not working, both resolved.  Hopefully this might help someone else encountering this error.
