### ISSUE TITLE
Upload of media (mp3/mp4) not possible

### ISSUE THREAD

**Issue by loma-one** [friendica/friendica#14460]
- [x] I have searched open and closed issues for duplicates

### Bug Description
Uploading mp3 and other media formats is not possible

### Steps to Reproduce

1. open the editor
2. switch to the Browser tab
3. open files
4. click on upload
5. select a format such as mp3 or mp4

Actual Result:

After selecting the file, the spinner runs for a short time. After one second, the upload is closed without a file having been uploaded

Expected Result:

After selecting the file, the mp3 or mp4 is uploaded and is available.

```
Uncaught Exception TypeError: "Friendica\Util\Strings::getBytesFromShorthand(): Argument #1 ($shorthand) must be of type string, null given, called in /var/www/html/friend/src/Module/Media/Attachment/Upload.php on line 74" at /var/www/html/friend/src/Util/Strings.php line 528 {"exception":"TypeError: Friendica\\Util\\Strings::getBytesFromShorthand(): Argument #1 ($shorthand) must be of type string, null given, called in /var/www/html/friend/src/Module/Media/Attachment/Upload.php on line 74 and defined in /var/www/html/friend/src/Util/Strings.php:528\nStack trace:\n#0 /var/www/html/friend/src/Module/Media/Attachment/Upload.php(74): Friendica\\Util\\Strings::getBytesFromShorthand()\n#1 /var/www/html/friend/src/BaseModule.php(219): Friendica\\Module\\Media\\Attachment\\Upload->post()\n#2 /var/www/html/friend/src/App.php(668): Friendica\\BaseModule->run()\n#3 /var/www/html/friend/index.php(32): Friendica\\App->runFrontend()\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"67095eec1b11d","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"26dd8f","process_id":77911}
```

### Platform Info

Friendica Version: Dev 1573/1573  1550/1550.

Friendica Source: git

PHP version: 8.2

SQL version: 10.5

**Comment by loma-one** [comment]
Ah
![image](https://github.com/user-attachments/assets/646e0019-f3cc-48d2-9af7-79c515595a7e)
