### ISSUE TITLE
Settings of managed account inaccessible (permission denied)

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#14476]
- [X ] I have searched open and closed issues for duplicates

### Bug Description

The settings page of a managed account is inaccessible for the parent user. If you switch to your own manged account and if you try to access the settings of that account you get a white permission denied page.

See also... https://libranet.de/display/0b6b25a8-6666-9910-4374-831710154279

### Steps to Reproduce

1.  set up a managed account (the parent user way)
2.  switch to that account
3.  try to access the settings page

Actual Result:

You get a permission denied page.

``[19/Oct/2024:11:51:39 +0000] "GET /settings HTTP/2.0" 403 389 "https://libranet.de/network" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"``

Expected Result:

You should be able to access the settings page and make changes to the settings of your managed account.

### Screenshots

See the provided link to a post with a screenshot.

### Platform Info

Friendica Version:
2024.09-rc

Friendica Source: 
git

PHP version:
8.3

SQL version:
MariaDB 10.11

**Comment by informapirata** [comment]
I'm curious: if you log in using:
- managed account userid
- parent account password
can you access the managed account? At this point, can you change the settings?

**Comment by AlfredSK** [comment]
I don't know. The bug description is based on a report of a user of my node. Other users did not confirm the behavior. I have to test this myself.

**Comment by annando** [comment]
There are two types of delegation. AFAIK It boils down to the question, if the mail address of both accounts is the same. If that isn't the case, then you don't have got admin rights.

**Comment by informapirata** [comment]
When dealing with delegated accounts, you can consider two cases, which I will arbitrarily call "alter ego" and "collaboration".

In the "alter ego" mode, the user creates a new account from their profile settings. This new account will necessarily share the same email as the parent account.

In the "collaboration" mode, on the other hand, there is an account that is created autonomously from the Friendica login screen. Once the account is created, its owner can decide to delegate its management to other accounts of the same instance. For example, the municipal library can delegate the management of its account to the two librarians who will each have their own Friendica account.

In the "alter ego" case, the delegated and delegating user share the same email and can indiscriminately access the settings of each other.

In the "collaboration" case, however, delegated users cannot access the settings of the delegating account. It is a question of guaranteeing the integrity of the delegating account and that is right

**Comment by AlfredSK** [comment]
> There are two types of delegation. AFAIK It boils down to the question, if the mail address of both accounts is the same. If that isn't the case, then you don't have got admin rights.

Yep. The "delegation" way doesn't give you access to the settings of the managed account. But you shouldn't get a blank Apache error page in that case. :-)

**Comment by AlfredSK** [comment]
I just tried to set up an additional account (parent user way) myself. 

Settings -> Manage Accounts -> Register an additional account

It doesn't work. I get a permission denied error. But nothing is logged - no error in Friendica's log and no error in Apache's log. Also, nothing related in the browser console. :-/

**Comment by scheriam** [comment]
I have a setup with docker compose for exploring Friendica, so I can do really "dumb" things and throw it away completely in the worst case. I added to the regular docker compose two items: Caddy Server as reverse proxy handling TLS and MailCatcher to handle all email stuff in private, so no emails are sent out to the "real world". I run Friendica version 2026.05

I can reproduce this error and also a situation that is really bad:
I logged in as "Admin" (the primary owner of the server) and created an account "Lobby" as _sub-account_ (called "alter-ego" previously in this thread). Then I switched to the sub-account and in addition to the parent, I added the same account ("Admin") also as delegate.
When I want to switch to another account then, I see the parent "Admin" once and the sub-account ("Lobby") twice in the account selection - ugly but "ok-ish".
But no matter which of the two instances of the sub-account I pick from there, I can never go to the settings (to remove the delegation to Admin or change any other settings). This an actually really nasty behaviour!
I had to use the database table `manager` to remove the delegation, then it worked.

And the error message I get for a delegated account when I want to go to the settings is not a blank server page but a page with a PHP stack trace:
```
Forbidden
 
Permission denied.
 
#0 [internal function]: Friendica\Module\BaseSettings->__construct()
#1 /var/www/html/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs()```
#2 /var/www/html/vendor/level-2/dice/Dice.php(96): Dice\Dice->{closure:Dice\Dice::getClosure():125}()
#3 /var/www/html/src/Core/DiceContainer.php(48): Dice\Dice->create()
#4 /var/www/html/src/App.php(627): Friendica\Core\DiceContainer->create()
#5 /var/www/html/src/App.php(575): Friendica\App->createModuleInstance()
#6 /var/www/html/src/App.php(190): Friendica\App->runFrontend()
#7 /var/www/html/index.php(22): Friendica\App->processRequest()
#8 {main}
```
Unfortunately I am not involved into Friendica development so I have no clue what the real expected behaviour is or how one could fix that.

A quick look into the code with a rough interpretation of the above stacktrace leads me to this: 

[`throw new ForbiddenException($this->t('Permission denied.'));`](https://github.com/friendica/friendica/blob/285cc571e92c92175c22ccad1902309fdb6ba4e1/src/Module/BaseSettings.php#L38)

so I would think it is intended behaviour. 

I personally would expect that menu entries that are forbidden are not even shown, or at least disabled, or that I get at the very least an error page in the style of the theme where all the navigation to the rest of the application is available and I don't have to use the browser back function.
