### ISSUE TITLE
Bluesky Bridge stopped working

### ISSUE THREAD

**Issue by wiligl** [friendica/friendica#14634]
### Bug Description

I previously had connected my Friendica account on friendica.world with by Bluesky account and it worked great, ie crossposting between both accounts. However, it stopped working I think a few days (?) ago. I have now checked Bluesky settings again in Friendica and renewed the App password, but I still cannot cross-post.  I wonder whether this is a problem of the friendica.world server, the Blueksy addon, or Bluesky (which is DevOping at a crazy speed).

### Steps to Reproduce

1.  Go to friendica.world in browser and login
2.  Write post and tick "Post to Bluesky" (Permissions)
3.  Wait for 6 hours
4.  Check whether Friendica post appears on Bluesky

Actual Result:

I do NOT see my Bluesky posts on Friendica. 
I do NOT see my Friendica posts on Bluesky.

Expected Result:

I see my Bluesky posts on Friendica.
I see my Friendica posts on Bluesky.

### Screenshots

NA

### Platform Info

Friendica Version:

This is Friendica, version 2024.08 that is running at the web location https://friendica.world. The database version is 1571/1571, the post update version is 1550/1550.

**Comment by annando** [comment]
Please have got a look at entries in the log with `ERROR` or `WARNING` in it **and additionally** the term `bluesky.php`.

**Comment by wiligl** [comment]
I am not the admin of the friendica.world instance and I do not think I can access the logs as a regulator user. I have forwarded the issue to admin (info(at)fedihosting(dot)foundation).

**Comment by ruudschilders** [comment]
I am the admin of Friendica.world and I think it might be caused by the issue we currently have with the worker. I will open a ticket for that. Let's see if that fixes this issue.

**Comment by wiligl** [comment]
@ruudschilders It seems Bluesky posts are now crossposted on Friendica again, but Friendica posts are NOT crossposted to Bluesky.

**Comment by Copiis** [comment]
I can confirm, posting to x,tumbrl and bluesky has not worked for me since 30.12. I am on develop

**Comment by JLuc** [comment]
When trying to activate the bluesky addon on a 2024-12 stable instance, i got a blank page and the following friendica repeated logs : 
```
2025-01-02T20:56:52Z app [NOTICE]: no data for session {"session_id":"2eb3a0eec72501aefedf06f66fd48028","uri":"/robots.txt"} - {"file":"Database.php","line":64,"function":"read","request-id":"6776fd9406c4d","stack":"Database::read, session_start (40), Native::start (150), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (247), Dice::Dice\\{closure} (132), Dice::Dice\\{closure} (96), Dice::create (79), DI::app (28)","uid":"62093f","process_id":4081889}

2025-01-02T21:13:39Z app [ERROR]: Uncaught Exception Error: "Call to undefined method Friendica\DI::appHelper()" at /home/s/www/friendica/addon/bluesky/bluesky.php line 76 
{"exception":"Error: Call to undefined method Friendica\\DI::appHelper() in /home/s/www/friendica/addon/bluesky/bluesky.php:76\n
Stack trace:\n
#0 /home/s/www/friendica/src/Core/Hook.php(208): bluesky_load_config(Object(Friendica\\Core\\Config\\Util\\ConfigFileManager))\n [...] "uid":"87477b", "process_id":4081884}
```
And friendica is now totaly broken : all pages, public, private or admin, are blanks. Renaming the addon folder to `bluesky.bak` sorted it.

**Comment by JLuc** [comment]
And this also seems related

```
2025-01-02T21:13:39Z app [ERROR]: Uncaught Exception Error: "Call to undefined method Friendica\DI::appHelper()" at /home/s/www/friendica/addon/bluesky/bluesky.php line 76 
{"exception":"Error: Call to undefined method Friendica\\DI::appHelper() in /home/s/www/friendica/addon/bluesky/bluesky.php:76\n
Stack trace:\n
#0 /home/s/www/friendica/src/Core/Hook.php(208): bluesky_load_config(Object(Friendica\\Core\\Config\\Util\\ConfigFileManager))\n
#1 /home/s/www/friendica/src/Core/Hook.php(184): Friendica\\Core\\Hook::callSingle('load_config', Array, Object(Friendica\\Core\\Config\\Util\\ConfigFileManager))\n
#2 /home/s/www/friendica/src/App.php(324): Friendica\\Core\\Hook::callAll('load_config', Object(Friendica\\Core\\Config\\Util\\ConfigFileManager))\n
#3 /home/s/www/friendica/src/App.php(289): Friendica\\App->load(Object(Friendica\\Database\\Definition\\DbaDefinition), Object(Friendica\\Database\\Definition\\ViewDefinition))\n
#4 [internal function]: Friendica\\App->__construct(Object(Friendica\\App\\Request), Object(Friendica\\Security\\Authentication), Object(Friendica\\Database\\Database), Object(Friendica\\Core\\Config\\Model\\DatabaseConfig), Object(Friendica\\App\\Mode), Object(Friendica\\App\\BaseURL), Object(Friendica\\Core\\Logger\\Type\\StreamLogger), Object(Friendica\\Util\\Profiler), Object(Friendica\\Core\\L10n), Object(Friendica\\App\\Arguments), Object(Friendica\\Core\\PConfig\\Type\\JitPConfig), Object(Friendica\\Core\\Session\\Model\\UserSession), Object(Friendica\\Database\\Definition\\DbaDefinition), Object(Friendica\\Database\\Definition\\ViewDefinition))\n
#5 /home/s/www/friendica/vendor/level-2/dice/Dice.php(132): ReflectionMethod->invokeArgs(Object(Friendica\\App), Array)\n
#6 /home/s/www/friendica/vendor/level-2/dice/Dice.php(96): Dice\\Dice->Dice\\{closure}(Array, Array)\n
#7 /home/s/www/friendica/src/DI.php(79): Dice\\Dice->create('Friendica\\\\App')\n
#8 /home/s/www/friendica/index.php(28): Friendica\\DI::app()\n
#9 {main}"} - {"file":null,"line":null,"function":null,"request-id":"67770183116af","stack":"ErrorHandler::handleException (114), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}",
"uid":"87477b",
"process_id":4081884}
```

**Comment by MrPetovan** [comment]
Are both your base Friendica install and the addon folder pointing to the same git branch? They should either both be on the `stable` branch or both on the `develop` branch, but mixing and matching is bound to cause this kind of unmet expectations.

**Comment by Copiis** [comment]
Now it works again.

**Comment by wiligl** [comment]
@ruudschilders On friendica.world crossposts to Bluesky still dont work, ie after 10 min the Friendica post still did not show on Bluesky ... Update base and addons of Friendica to latest commit?

**Comment by annando** [comment]
@wiligl the problem with friendica.world seems to be caused by a problem with the workers. See https://github.com/friendica/friendica/issues/14638

As long as this isn't solved, you will have got problems with (not only) Bluesky.

To @Copiis and @JLuc : your issues are most likely caused by other issues.

**Comment by JLuc** [comment]
My issue with Bluesky addon install was fixed following @MrPetovan advices to git update addon repo to the same "stable" version.
