### ISSUE TITLE
Text_Highlighter buggy with php 7.1

### ISSUE THREAD

**Issue by ddorian1** [friendica/friendica#3777]
From time to time, my system spams me with this error message:

>PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/virtual/jschwab>/friendica.jschwab.org/vendor/pear-pear.php.net/Text_Highlighter/Text/Highlighter/Renderer/Array.php:154
>Stack trace:
>#0 /var/www/virtual/jschwab/friendica.jschwab.org/vendor/pear-pear.php.net/Text_Highlighter/Text/Highlighter.php(378): Text_Highlighter_Renderer_Array->acceptToken('code', '[noparse]')
>#1 /var/www/virtual/jschwab/friendica.jschwab.org/include/text.php(2239): Text_Highlighter->highlight('[noparse]<objec...')
>#2 /var/www/virtual/jschwab/friendica.jschwab.org/include/bbcode.php(820): text_highlight('[noparse]<objec...', 'xml')
>#3 [internal function]: bb_highlight(Array)
>#4 /var/www/virtual/jschwab/friendica.jschwab.org/include/bbcode.php(903): preg_replace_callback('/\\[code=(.*?)\\]...', 'bb_highlight', '@[url=https://f...')
>#5 /var/www/virtual/jschwab/friendica.jschwab.org/include/text.php(1503): bbcode('@[url=https://f...')
>#6 /var/www/virtual/jschwab/friendica.jschwab.org/include/text.php(1284): prepare_text('@[u in /var/www/virtual/jschwab/friendica.jschwab.org/vendor/pear-pear.php.net/Text_Highlighter/Text/Highlighter/Renderer/Array.php on line 154

It seems the message comes with every run of the poller.
There is a new version of Text_Highlighter available [here](https://pear.php.net/package/Text_Highlighter/) that may solve the problem, but I don't know how to update it correctly.

**Comment by MrPetovan** [comment]
Hi @ddorian1 and thanks for submitting an issue. Unfortunately, Friendica is using the latest available version of Text_Highlighter (0.8.0), a package that hasn't been updated since March 2017.

After looking at the code, it's clear that it's a problem with the library philosophy and not just a wild bug, so the only option seems to change highlighting library.

**Comment by terkin** [comment]
just add this code before
`	
if(!is_array($this->_output)) {
			$this->_output = array();
}`

thats how my function looks now

```
    function acceptToken($class, $content)
    {

	if(!is_array($this->_output)) {
			$this->_output = array();
	}
        $theClass = $this->_getFullClassName($class);
        if ($this->_htmlspecialchars) {
            $content = htmlspecialchars($content);
        }
        if ($this->_enumerated) {
            $this->_output[] = array($class, $content);
        } else {
	        $this->_output[][$class] = $content;
	       
        }
        $this->_lastClass = $class;

    }
```

**Comment by MrPetovan** [comment]
Thanks for looking into this, please submit a PR over at the project GitHub page: https://github.com/pear/Text_Highlighter/pulls

**Comment by tobiasd** [comment]
This issue can be closed right?
