### ISSUE TITLE
After git pull twitter is broken

### ISSUE THREAD

**Issue by templis** [friendica/friendica#4818]
### Expected behavior
fetch the Timeline from Twitter and post it to network stream

### Actual behavior
no Updates from Twitter to Friendica

### Steps to reproduce the problem
create app connector on twitter and connect it with friendica
Login in as user and connect friendica with twitter

### Friendica version you encountered the problem
development branch (2018-05-dev)
see `example.com/friendica` on your Friendica node for the version information.

### Friendica source (git, zip)
git
### PHP version
7.1.15
### SQL version
5.7.21

See log 

2018-04-11T20:56:24Z@log5ace7677xxxxxx.xxxxx055 [DEBUG]:api.php:518:api_get_user        api_get_user: Fetching user data for user       
2018-04-11T20:56:24Z@log5ace7677xxxxxx.xxxxx055 [DEBUG]:api.php:596:api_get_user        api_get_user: user                              
2018-04-11T20:56:24Z@log5ace7677xxxxxx.xxxxx055 [NORMAL]:api.php:608:api_get_user       api_user: AND `contact`.`uid` = %d AND `contact`.`self` , user: 1                                                                                                                        
2018-04-11T20:56:24Z@log5ace7677xxxxxx.xxxxx055 [DEBUG]:Contact.php:750:getIdForURL     Get contact data for url https://social.opennerds.org/profile/xxxxxx and user 0 - api_get_user, api_direct_messages_box, api_direct_messages_sentbox, api_call                          
2018-04-11T20:56:24Z@log5ace7677xxxxxx.xxxxx055 [DEBUG]:api.php:311:api_call    API call duration: 0    api/direct_messages/sent.json?count=100                                                                                                                                  
2018-04-11T20:56:24Z@log5ace7678xxxxxx.xxxxx793 [NORMAL]:api.php:177:api_login  OAuthException: Invalid consumer key in /var/xxx/xxx/library/OAuth1.php:615                                                                                                                
Stack trace:                                                        
#0 /var/www/friendica/library/OAuth1.php(561): OAuthServer->get_consumer(Object(OAuthRequest))                                          
#1 /var/www/friendica/include/api.php(167): OAuthServer->verify_request(Object(OAuthRequest))                                           
#2 /var/www/friendica/include/api.php(302): api_login(Object(Friendica\App))                                                            
#3 /var/www/friendica/mod/api.php(117): api_call(Object(Friendica\App))                                                                 
#4 /var/www/friendica/index.php(371): api_content(Object(Friendica\App))                                                                
#5 {main}                                                           
2018-04-11T20:56:24Z@log5ace7678xxxxxx.xxxxx793 [NORMAL]:api.php:305:api_call   API call for Emton Sti: api/statuses/mentions_timeline.json?latest_results=true&count=20&include_blocked_by=true&since_id=12929&include_blocking=true                                            
2018-04-11T20:56:24Z@log5ace7678xxxxxx.xxxxx793 [NORMAL]:api.php:306:api_call   API parameters: Array                                   
(                                                                   
    [q] => api/statuses/mentions_timeline.json                      
    [latest_results] => true                                        
    [count] => 20                                                   
    [include_blocked_by] => true                                    
    [since_id] => 12929                                             
    [include_blocking] => true                                      
)                                                                   

2018-04-11T20:56:24Z@log5ace7678xxxxxx.xxxxx793 [DEBUG]:api.php:518:api_get_user        api_get_user: Fetching user data for user       
2018-04-11T20:56:24Z@log5ace7678xxxxxx.xxxxx793 [DEBUG]:api.php:596:api_get_user        api_get_user: user                              
2018-04-11T20:56:24Z@log5ace7678xxxxxx.xxxxx793 [NORMAL]:api.php:608:api_get_user       api_user: AND `contact`.`uid` = %d AND `contact`.`self` , user: 1                                                                                                                        
2018-04-11T20:56:25Z@log5ace7678xxxxxx.xxxxx793 [DEBUG]:Contact.php:750:getIdForURL     Get contact data for url https://social.opennerds.org/profile/xxx and user 0 - api_get_user, api_statuses_mentions, api_call, api_content                                            
2018-04-11T20:56:25Z@log5ace7678xxxxxx.xxxxx793 [DEBUG]:api.php:311:api_call    API call duration: 0.27 api/statuses/mentions_timeline.json?latest_results=true&count=20&include_blocked_by=true&since_id=12929&include_blocking=true                                            
2018-04-11T21:01:09Z@log5ace7795xxxxxx.xxxxx759 [NORMAL]:System.php:149:httpExit        http_status_exit 401                            
2018-04-11T21:01:10Z@f85cv0isxxxxxxxxxxxabkbi3 [TRACE]:DatabaseSessionHandler.php:38:read      no data for session f85cv0is7t4fc15rbb9labkbi3                                                                                                                                   
2018-04-11T21:01:10Z@tlfr4mkmjxxxxxxxxxxxn60esbl [TRACE]:DatabaseSessionHandler.php:38:read      no data for session tlfr4mkmjxxxxxxxxxxxn60esbl                                                                                                                                   
2018-04-11T21:01:10Z@tlfr4mkmjxxxxxxxxxxxn60esbl [DEBUG]:index.php:291:  index.php: page not found: /siteinfo.json ADDRESS: 127.0.0.1 QUERY: q=siteinfo.json                                                                                                                      
2018-04-11T21:01:10Z@log5ace7796bxxxxxx.xxxxx467 [NORMAL]:api.php:305:api_call   API call for : api/statusnet/config.json                
2018-04-11T21:01:10Z@log5ace7796bxxxxxx.xxxxx467 [NORMAL]:api.php:306:api_call   API parameters: Array                                   
(                                                                   
    [q] => api/statusnet/config.json                                
)                                                                   

2018-04-11T21:01:10Z@log5ace7796bxxxxxx.xxxxx467 [DEBUG]:api.php:311:api_call    API call duration: 0    api/statusnet/config.json       
2018-04-11T21:01:10Z@log5ace7796exxxxxx.xxxxx210 [NORMAL]:System.php:149:httpExit        http_status_exit 404                            
2018-04-11T21:01:11Z@log5ace77977xxxxxx.xxxxx360 [NORMAL]:System.php:149:httpExit        http_status_exit 404                            
2018-04-11T21:01:11Z@a34gmqa0xxxxxxxxxxxfff0c [TRACE]:DatabaseSessionHandler.php:38:read      no data for session a34gmqa0vehbfedroi0j1fff0c                                                                                                                                   
2018-04-11T21:01:30Z@log5ace77aaafxxxxxx.xxxxx414 [NORMAL]:System.php:149:httpExit        http_status_exit 401                            
2018-04-11T21:01:31Z@log5ace77ab40xxxxxx.xxxxx631 [NORMAL]:System.php:149:httpExit        http_status_exit 401                            
2018-04-11T21:01:31Z@ea5ehtc3xxxxxxxxxxo1ub4cv0 [TRACE]:DatabaseSessionHandler.php:38:read      no data for session ea5ehtc37d8p72mnuto1ub4cv0                                                                                                                                   
2018-04-11T21:01:31Z@6p5trufj7mxxxxxxxxxxxxxa8jg [TRACE]:DatabaseSessionHandler.php:38:read      no data for session 6p5trufj7mua9o77dbeqhia8jg                                                                                                                                   
2018-04-11T21:01:31Z@6p5trufxxxxxxxxxxxxxeqhia8jg [DEBUG]:index.php:291:  index.php: page not found: /siteinfo.json ADDRESS: 127.0.0.1 QUERY: q=siteinfo.json                                                                                                                      
2018-04-11T21:01:32Z@log5ace77ac4xxxxxx.xxxxx428 [NORMAL]:api.php:305:api_call   API call for : api/statusnet/config.json                
2018-04-11T21:01:32Z@log5ace77ac4xxxxxx.xxxxx428 [NORMAL]:api.php:306:api_call   API parameters: Array

**Comment by MrPetovan** [comment]
Thanks for the report with the log, you have a `OAuthException: Invalid consumer key` error in it, can you please double-check your Twitter connector settings? My Twitter timeline is imported alright.

**Comment by templis** [comment]
yes I've opened the twitter app and copied all the stuff again, cause i thought it lacks with database settings or so. So I thought if i set them new - it would work again. :)

Do you also did a complete git pull?
I also updated composer modules.
My twitter timeline stops working since 3 days ago

**Comment by MrPetovan** [comment]
Yes, I'm up-to-date with core and addons develo branches, and I ran `bin/composer.phar install`.

Can you grep your log for the "twitter" term?

**Comment by templis** [comment]
Okay - I'm stupid :/
I've done two things.
1st: hardocded consumerkey and secret in .htconfig.php
2nd: changed my crontab from scripts/worker.php to bin/worker.php

I think the second did the trick.
Thank you for your help and pointing me, that it lacks on my install. :)

**Comment by MrPetovan** [comment]
You're welcome, I love those self-resolving issues.
