### ISSUE TITLE
Bug: background process (worker) broken; images etc. aren't fetched

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4943]
A lot of embedded pictures are missing since yesterday evening. There are only the words 'image/photo' but not the actual pictures. Also I have an error message in my admin panel saying the worker is not running since yesterday 21:27 UTC. But crontab is okay and I can run the worker manually.

````
[28-Apr-2018 05:35:14 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function Friendica\Util\fetchUrlFull() in /var/www/html/libranet/src/Util/Network.php:39
Stack trace:
#0 /var/www/html/libranet/src/Content/OEmbed.php(84): Friendica\Util\Network::fetchUrl('http://www.tage...', false, 0, 15, 'text/*')
#1 /var/www/html/libranet/src/Util/ParseUrl.php(160): Friendica\Content\OEmbed::fetchURL('http://www.tage...')
#2 /var/www/html/libranet/src/Util/ParseUrl.php(61): Friendica\Util\ParseUrl::getSiteinfo('http://www.tage...', true, true)
#3 /var/www/html/libranet/include/items.php(96): Friendica\Util\ParseUrl::getSiteinfoCached('http://www.tage...', true)
#4 /var/www/html/libranet/include/items.php(143): query_page_info('http://www.tage...', '', false, '')
#5 /var/www/html/libranet/include/items.php(178): add_page_info('http://www.tage...', true)
#6 /var/www/html/libranet/src/Protocol/Diaspora.php(3054): add_page_info_to_body('[h3][url=http:/...', false, true)
#7 /var/www/html/libranet/src/Protocol/Diaspora.php(699): Friendica\Protocol\Diaspora::re in /var/www/html/libranet/src/Util/Network.php on line 39
````

**Comment by AlfredSK** [comment]
I think #4939 is the responsible PR.

**Comment by AlfredSK** [comment]
git checkout e261251
... solved the issue for now until the bug is fixed.

**Comment by astifter** [comment]
This should do the trick, @MrPetovan can you verify?
