### ISSUE TITLE
All cron jobs terminated

### ISSUE THREAD

**Issue by tobiasd** [friendica/friendica#5407]
### Expected behavior

Cron jobs not being terminated as it was the case before the pull.

### Actual behavior

(using the old htconfig config file)

Since pulling the code this morning, including #5295 all the worker runs seem to get terminated. Cron is sending out mails in the frequency of calling the worker process.

There are no error/warnings in the PHP logfile.

Calling the cron command from the CLI results in "Terminated" as well after 30 to 60 seconds without further output. System LOAD levels are the usual, RPi idling along.

(using the new INI config file)

Manual calling is *not* terminated. But a illegal Offset is reported.

    Undefined offset: 1 in src/App.php on line 1070

The run of the worker is done within a second.

### Friendica version you encountered the problem

Friendica 'The Tazmans Flax-lily' 2018.08-dev - 1277 5790a0c58a5d044c9c0cba8496db07fa7d0bc0b6

### PHP version

7.0

### SQL version

10.1.23-MariaDB

----

<s>As switching to the new config format seems to help I mark this as *Support Request* as I'm wondering if there is an underlying problem.</s>

Actually, the first impression was wrong. After switching over to the new format the cron jobs are terminated as well.

**Comment by annando** [comment]
Notices don't stop the system I you haven't configured the system badly (like I did).

**Comment by tobiasd** [comment]
I don't think that I have. And I've deactivated the notices again to the setting I had before for ~friendica, the jobs are still all terminated.

**Comment by annando** [comment]
**This** is related:
```
$ bin/daemon.php start
Notice: Undefined index: marktime in /path/to/friendica/src/App.php on line 947
Starting worker daemon.
Fatal error: Uncaught Error: Call to a member function query() on null in /path/to/friendica/include/dba.php:413
Stack trace:
#0 /path/to/friendica/include/dba.php(252): dba::p('SELECT 1')
#1 /path/to/friendica/src/App.php(516): dba::connected()
#2 /path/to/friendica/bin/daemon.php(132): Friendica\App->loadDatabase()
#3 {main}
  thrown in /path/to/friendica/include/dba.php on line 413
```

**Comment by tobiasd** [comment]
> Closed #5407 via #5409.

I don't think so. Please re-open the issue (github is currently timing out in the browser and I hope this mail comes through).

I'm on 36c6e35c7ed45ef6b18d48359b38f9c869f63245 and according to git log #5409 should be in my codebase but I'm still getting mails from the cron system with notes about Terminated jops in the frequency of calling the worker.

**Comment by tobiasd** [comment]
@annando suggested to test the `bin/daemon.php start --foreground` instead of using `bin/worker.php` the result is almost identical, but there is a new fatal error in the PHP log.

    PHP Fatal error:  Uncaught Error: Call to a member function quote() on null in include/dba.php:241
    Stack trace:
    #0 include/dba.php(1286): dba::escape('worker-ipc')
    #1 include/dba.php(1247): dba::select('worker-ipc', Array, Array, Array)
    #2 src/Core/Worker.php(1166): dba::selectFirst('worker-ipc', Array, Array)
    #3 bin/daemon.php(175): Friendica\Core\Worker::IPCJobsExists()
    #4 {main} thrown in include/dba.php on line 241

**Comment by ben-utzer** [comment]
Can this also cause my problems with the worker causing dozens to a few hundred httpd processes which then (don't know for what reason) send HTTP Error 500 when trying to load the frontend?

**Comment by annando** [comment]
This gcontact problem is fixed with pr https://github.com/friendica/friendica/pull/5421

**Comment by ben-utzer** [comment]
> This gcontact problem is fixed with pr #5421

OK, I guess the gcontact problem is not what causes my system to be not responding and serving 500 errors?

**Comment by annando** [comment]
Don't think so.

**Comment by MrPetovan** [comment]
@tobiasd It looks like the db connection vanishes during the `bin/daemon.php` execution between line 31 (when we check the App mode) and line 175. We are trying to opening it again in line 132 but it doesn't seem to be enough.

**Comment by tobiasd** [comment]
New error message in the logs, maybe related?

> PHP Fatal error:  Uncaught Error: Call to undefined method Friendica\Database\DBA::fetchFirst() in /.../src/Core/Worker.php:479

From the timing of the terminated cron jobs, maybe something got better over the last days. The termination mails now do not arrive anymore in the frequency of the started jobs. It is now more something like every second.

**Comment by annando** [comment]
Please kill all your worker jobs. This assures that you don't get old workers that don't know the renamed method.

Second: Please check if that method exists in src/Database/DBA.php
