### ISSUE TITLE
worker.php: Failed opening required vendor/autoload.php

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#5682]
### Expected behavior

running the worker.php like
```bash
php -f /var/www/html/bin/worker.php
```
Working like a worker has to work ;-)

### Actual behavior

Since update of today

Node `opensocial.at`:
```bash
cron_1   | Fatal error: Uncaught Error: Cannot use object of type stdClass as array in /var/www/html/src/Protocol/Diaspora.php:3659
cron_1   | Stack trace:
cron_1   | #0 /var/www/html/src/Worker/Delivery.php(367): Friendica\Protocol\Diaspora::sendStatus(Array, Array, Array, true)
cron_1   | #1 /var/www/html/src/Worker/Delivery.php(158): Friendica\Worker\Delivery::deliverDiaspora('wall-new', Array, Array, Array, Array, true, true, false)
cron_1   | #2 [internal function]: Friendica\Worker\Delivery::execute('wall-new', '27832', 429)
cron_1   | #3 /var/www/html/src/Core/Worker.php(347): call_user_func_array('Friendica\\Worke...', Array)
cron_1   | #4 /var/www/html/src/Core/Worker.php(239): Friendica\Core\Worker::execFunction(Array, 'Delivery', Array, true)
cron_1   | #5 /var/www/html/src/Core/Worker.php(101): Friendica\Core\Worker::execute(Array)
cron_1   | #6 /var/www/html/bin/worker.php(59): Friendica\Core\Worker::processQueue(false)
cron_1   | #7 {main}
cron_1   |   thrown in /var/www/html/src/Protocol/Diaspora.php on line 3659

[...]

cron_1   |
cron_1   | Warning: require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Fatal error: require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Warning: require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Fatal error: require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Warning: require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Fatal error: require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Warning: require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Fatal error: require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Warning: require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Fatal error: require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/boot.php on line 20
```

Node2 `friendica.philipp.info` (A few days before I guess):
```bash
cron_1   | Fatal error: Uncaught TypeError: Argument 1 passed to Friendica\Protocol\PortableContact::discoverServer() must be of the type array, null given, called in /var/www/html/src/Protocol/PortableContact.php on line 1664 and defined in /var/www/html/src/Protocol/PortableContact.php:1765
cron_1   | Stack trace:
cron_1   | #0 /var/www/html/src/Protocol/PortableContact.php(1664): Friendica\Protocol\PortableContact::discoverServer(NULL)
cron_1   | #1 /var/www/html/src/Worker/DiscoverPoCo.php(72): Friendica\Protocol\PortableContact::discoverSingleServer(3046)
cron_1   | #2 [internal function]: Friendica\Worker\DiscoverPoCo::execute('update_server_d...', 3046)
cron_1   | #3 /var/www/html/src/Core/Worker.php(346): call_user_func_array('Friendica\\Worke...', Array)
cron_1   | #4 /var/www/html/src/Core/Worker.php(238): Friendica\Core\Worker::execFunction(Array, 'DiscoverPoCo', Array, true)
cron_1   | #5 /var/www/html/src/Core/Worker.php(100): Friendica\Core\Worker::execute(Array)
cron_1   | #6 /var/www/html/bin/worker.php(57): Friendica\Core\Worker::processQueue(true)
cron_1   | #7 {main}
cron_1   |   thrown in /var/www/html/src/Protocol/PortableContact.php on line 1765
cron_1   |
cron_1   | Warning: require_once(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/boot.php on line 20
cron_1   |
cron_1   | Fatal error: require_once(): Failed opening required '/var/www/html/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/boot.php on line 20
```

- on both nodes, the autload.php is available
- checked ownership on both nodes (www-root:www-root)

### Steps to reproduce the problem

Starting the `worker.php`

### Friendica version you encountered the problem

develop

### Friendica source (git, zip)

git

### PHP version

```bash
PHP 7.1.16 (cli) (built: Apr  5 2018 04:48:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16, Copyright (c) 1999-2018, by Zend Technologies
```

### SQL version

```bash
mysql  Ver 15.1 Distrib 10.3.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by MrPetovan** [comment]
- Permission/ownership check?
- `bin/composer.phar install` just to be sure?

**Comment by nupplaphil** [comment]
> Permission/ownership check?

I made a complete `chown www-data:www-data -R /var/www/html`.
This seems to solve my problem, the workerqueue decreases :-)

Thanks!
