### ISSUE TITLE
[twitter] Addon crashes when 10s timeout is reached

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5707]
Extracted from #5470 

The typical error message looks like this: 
```PHP Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException: Resolving timed out after 10524 milliseconds in addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php:440
Stack trace:
#0 addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(357): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array)
#1 addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(323): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array)
#2 addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(191): Abraham\TwitterOAuth\TwitterOAuth->http('POST', 'https://api.twi...', 'statuses/update', Array)
#3 addon/twitter/twitter.php(613): Abraham\TwitterOAuth\TwitterOAuth->post('statuses/update', Array)
#4 src/Core/Addon.php(243): twitt in addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 440```

The Exception needs to be handled, either by retrying, or by cleanly exiting the process.

**Comment by MrPetovan** [comment]
If no one if taking up on this issue, I'll move it to the next milestone. My addon doesn't work anymore, so I can't really test any modification.

**Comment by annando** [comment]
Let's take some time to fix your system. Possibly this indicates some problem that other users do have as well.

**Comment by annando** [comment]
See here: https://github.com/friendica/friendica-addons/pull/730

**Comment by copiis** [comment]
PHP Fatal error: Uncaught Abraham\TwitterOAuth\TwitterOAuthException: Resolving timed out after 10544 milliseconds in /home/users/zsemberi/www/friendica/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php:440
Stack trace:
#0 /home/users/zsemberi/www/friendica/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(357): Abraham\TwitterOAuth\TwitterOAuth->request('https://api.twi...', 'POST', 'Authorization: ...', Array)
#1 /home/users/zsemberi/www/friendica/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(323): Abraham\TwitterOAuth\TwitterOAuth->oAuthRequest('https://api.twi...', 'POST', Array)
#2 /home/users/zsemberi/www/friendica/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php(191): Abraham\TwitterOAuth\TwitterOAuth->http('POST', 'https://api.twi...', 'statuses/update', Array)
#3 /home/users/zsemberi/www/friendica/addon/twitter/twitter.php(615): Abraham\TwitterOAuth\TwitterOAuth->post('statuses/update', Array)
#4 /home/users/zsemberi/www/friendica/src/Core/Addon.php(251): twitt in /home/users/zsemberi/www/friendica/addon/twitter/vendor/abraham/twitteroauth/src/TwitterOAuth.php on line 440

**Comment by MrPetovan** [comment]
Has this happened again?
