### ISSUE TITLE
Database errors

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#5787]
Branching off #5470 , this is a thread for the odd database errors.

For example, I got this one three times today, in a 4 minutes interval.
```
Warning:  Error while sending STMT_CLOSE packet. PID=2050 in src/Database/DBA.php on line 589
Stack trace:
  1. {main}() index.php:0
  2. salmon_post() index.php:355
  3. Friendica\Protocol\OStatus::import() mod/salmon.php:190
  4. Friendica\Protocol\OStatus::process() src/Protocol/OStatus.php:303
  5. Friendica\Protocol\OStatus::fetchAuthor() src/Protocol/OStatus.php:412
  6. Friendica\Model\Contact::getIdForURL() src/Protocol/OStatus.php:72
  7. Friendica\Model\Contact::updateAvatar() src/Model/Contact.php:1203
  8. Friendica\Model\Photo::importProfilePhoto() src/Model/Contact.php:1473
  9. Friendica\Model\Photo::store() src/Model/Photo.php:119
 10. Friendica\Database\DBA::insert() src/Model/Photo.php:78
 11. Friendica\Database\DBA::e() src/Database/DBA.php:843
 12. Friendica\Database\DBA::p() src/Database/DBA.php:611
```

**Comment by MrPetovan** [comment]
Other error reported by @copiis (https://github.com/friendica/friendica/issues/5470#issuecomment-423804245)
```
PHP Warning:  Error while sending STMT_PREPARE packet. PID=23872 in src/Database/DBA.php on line 449
PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in src/Database/DBA.php:449
Stack trace:
#0 src/Database/DBA.php(563): Friendica\Database\DBA::p('SELECT `nurl` F...', Array)
#1 src/Database/DBA.php(1332): Friendica\Database\DBA::p('SELECT `nurl` F...', Array)
#2 src/Database/DBA.php(674): Friendica\Database\DBA::select('gserver', Array, Array, Array)
#3 src/Protocol/PortableContact.php(1406): Friendica\Database\DBA::exists('gserver', Array)
#4 src/Worker/DiscoverPoCo.php(86): Friendica\Protocol\PortableContact::checkServer('http://ichmagdi...')
#5 [internal function]: Friendica\Worker\DiscoverPoCo::execute('server', 'https://ichmagd...')
#6 src/Core/Worker.php(348): call_user_func_array('Friendica\\Worke...', Array)
#7 src in src/Database/DBA.php on line 449
```

**Comment by annando** [comment]
This look a little bit like your database connection disappears from time to time. When you execute "mysqltuner.pl", what does "Aborted connections:" and "Highest connection usage:" tell you?

**Comment by copiis** [comment]
> This look a little bit like your database connection disappears from time to time. When you execute "mysqltuner.pl", what does "Aborted connections:" and "Highest connection usage:" tell you?

I can also often observe database connection interruptions in recent times.

**Comment by annando** [comment]
@copiis Can you have a look at mysqltuner.pl concerning this data that I mentioned?

**Comment by copiis** [comment]
Aborted connections: 0.02%  (54/339304)
Highest usage of available connections: 41% (41/100)

**Comment by MrPetovan** [comment]
```
[OK] Highest usage of available connections: 72% (109/151)
[OK] Aborted connections: 0.01%  (16/276861)
```

**Comment by annando** [comment]
Hmm, okay. I hoped that this could be the reason. Or do these 16 aborted connections fit into the number of log entries that you got?

**Comment by MrPetovan** [comment]
Hard to tell, there can be multiple messages for a single dropped connection, for example multiple warnings and a single Fatal Error. The general order of magnitude is similar though.

**Comment by MrPetovan** [comment]
I keep having this specific error related to the storage of a photo:
```
Warning:  Error while sending STMT_EXECUTE packet. PID=9009 in src/Database/DBA.php on line 476
Stack trace:
  1. {main}() bin/worker.php:0
  2. Friendica\Core\Worker::processQueue() bin/worker.php:52
  3. Friendica\Core\Worker::execute() src/Core/Worker.php:102
  4. Friendica\Core\Worker::execFunction() src/Core/Worker.php:255
  5. call_user_func_array:{src/Core/Worker.php:365}() src/Core/Worker.php:365
  6. Friendica\Worker\Notifier::execute() src/Core/Worker.php:365
  7. Friendica\Model\Contact::terminateFriendship() src/Worker/Notifier.php:103
  8. Friendica\Protocol\OStatus::salmon() src/Model/Contact.php:553
  9. Friendica\Protocol\OStatus::entry() src/Protocol/OStatus.php:2238
 10. Friendica\Protocol\OStatus::followEntry() src/Protocol/OStatus.php:1563
 11. Friendica\Network\Probe::uri() src/Protocol/OStatus.php:1806
 12. Friendica\Protocol\ActivityPub::probeProfile() src/Network/Probe.php:339
 13. Friendica\Model\APContact::getByURL() src/Protocol/ActivityPub.php:88
 14. Friendica\Model\Contact::updateAvatar() src/Model/APContact.php:189
 15. Friendica\Model\Photo::importProfilePhoto() src/Model/Contact.php:1477
 16. Friendica\Model\Photo::store() src/Model/Photo.php:120
 17. Friendica\Database\DBA::insert() src/Model/Photo.php:79
 18. Friendica\Database\DBA::e() src/Database/DBA.php:853
 19. Friendica\Database\DBA::p() src/Database/DBA.php:621
 20. PDOStatement->execute() src/Database/DBA.php:476
```

**Comment by MrPetovan** [comment]
From https://github.com/friendica/friendica/issues/5911#issuecomment-438855610
```
PHP Warning: Error while sending STMT_PREPARE packet. PID=1251 in src/Database/DBA.php on line 459
PHP Fatal error: Uncaught Error: Call to a member function prepare() on null in src/Database/DBA.php:459
Stack trace:
#0 src/Database/DBA.php(573): Friendica\Database\DBA::p('SELECT COUNT()...', Array)
#1 src/Database/DBA.php(709): Friendica\Database\DBA::p('SELECT COUNT()...', Array)
#2 src/Database/DBA.php(1374): Friendica\Database\DBA::fetchFirst('SELECT COUNT(*)...', Array)
#3 src/Protocol/PortableContact.php(1052): Friendica\Database\DBA::count('gcontact', Array)
#4 src/Worker/DiscoverPoCo.php(88): Friendica\Protocol\PortableContact::checkServer('http://http://p...')
#5 [internal function]: Friendica\Worker\DiscoverPoCo::execute('server', 'https://https:/...')
#6 src/Core/Worker.php(365): call_user_func_array('Friendica\Worke...', Array)
#7 sr in src/Database/DBA.php on line 459
```

**Comment by annando** [comment]
I found this PHP bug: https://bugs.php.net/bug.php?id=69899

**Comment by annando** [comment]
I'm asking myself if we could prevent these drops in any way.

**Comment by MrPetovan** [comment]
We can certainly stop storing whole remote avatar in the DB: https://github.com/friendica/friendica/issues/5787#issuecomment-435646732

But for others, I'm guessing it depends on the server's settings, which are tricky to debug and suggest better values.

**Comment by MrPetovan** [comment]
From @miqrogroove in #6411

> PHP Fatal error:  Call to a member function autocommit() on null in src/Database/DBA.php on line 878
> 
> version 2018.09
> 
> Line 878 is in function lock() so I assume this is an unhandled connection error.  Difficult to say if the underlying problem is mis-use of the DBA class or a failure within the DBA to actually check the connection.
> 
> Also note, DBA::disconnect() never modifies the value of self::$connected 😱

**Comment by danielbierstedt** [comment]
Another one with connection drops:

`root@DiskStation:/volume1/www/fr# /usr/local/bin/php70 bin/worker.php                                             PHP Fatal error:  Uncaught Error: Call to a member function autocommit() on null in /volume1/www/fr/src/Database/DBA.php:878
Stack trace:
#0 /volume1/www/fr/src/Core/Lock/DatabaseLockDriver.php(23): Friendica\Database\DBA::lock('locks')
#1 /volume1/www/fr/src/Core/Lock.php(118): Friendica\Core\Lock\DatabaseLockDriver->acquireLock('worker', 0)
#2 /volume1/www/fr/src/Core/Worker.php(1093): Friendica\Core\Lock::acquire('worker', 0)
#3 /volume1/www/fr/boot.php(537): Friendica\Core\Worker::add(10, 'DBUpdate')
#4 /volume1/www/fr/bin/worker.php(41): check_db(true)
#5 {main}
  thrown in /volume1/www/fr/src/Database/DBA.php on line 878

Fatal error: Uncaught Error: Call to a member function autocommit() on null in /volume1/www/fr/src/Database/DBA.php:878
Stack trace:
#0 /volume1/www/fr/src/Core/Lock/DatabaseLockDriver.php(23): Friendica\Database\DBA::lock('locks')
#1 /volume1/www/fr/src/Core/Lock.php(118): Friendica\Core\Lock\DatabaseLockDriver->acquireLock('worker', 0)
#2 /volume1/www/fr/src/Core/Worker.php(1093): Friendica\Core\Lock::acquire('worker', 0)
#3 /volume1/www/fr/boot.php(537): Friendica\Core\Worker::add(10, 'DBUpdate')
#4 /volume1/www/fr/bin/worker.php(41): check_db(true)
#5 {main}
  thrown in /volume1/www/fr/src/Database/DBA.php on line 878
`
This is about MariaDB:
`Connections	#	ø per hour	%
Max. concurrent connections	12	---	---
Failed attempts	1,107	20.69	0.57%
Aborted	5	0.09	<0.01%
Total	196 k	3,659.87	100.00%
`

So, load etc is not really an issue. Whats going on?

**Comment by annando** [comment]
Are you using PDO? if not, please switch to it.

**Comment by danielbierstedt** [comment]
<img width="493" alt="friendica-cron" src="https://user-images.githubusercontent.com/9999431/51234143-3651be80-196c-11e9-848e-14f0ef6cf318.PNG">

Not sure if this meany anything, but I have concerns... Menawhile, I try to make the cron stuff work without the error messages, but no luck until now. Good news is, that I improved the Nextcloud cronjob with the new knowledge...

**Comment by tobiasd** [comment]
It is only concerning, if the number does not decrease over time. The last number is the number of jobs the background process has to work on. So if it keeps piling up, adjustments to the background process have to be made.
