### ISSUE TITLE
PHP Warning:  syntax error, unexpected END_OF_LINE

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5799]
```
PHP Warning: syntax error, unexpected END_OF_LINE, expecting '=' in Unknown on line 42
in src/App.php on line 405
PHP Fatal error: Uncaught Exception: Error parsing config file config/local.ini.php in src/App.php:408
Stack trace:
#0 src/App.php(375): Friendica\App->loadConfigFile('/home/users/zse...', true)
#1 src/App.php(290): Friendica\App->loadConfigFiles()
#2 src/App.php(177): Friendica\App->reload()
#3 bin/worker.php(33): Friendica\App->__construct('/home/users/zse...')
#4 {main}
thrown in src/App.php on line 408
```

**Comment by MrPetovan** [comment]
It's a Config syntax error, a config value containing an equal sign needs to be enclosed in quotes.
