### ISSUE TITLE
Uncaught Error: Cannot use object of type Friendica\Network\CurlResult as array

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#5879]
### Expected behavior
Do not throw PHP fatal errors.

### Actual behavior
After pulling #5878 I get a lot of PHP fatal errors for 'Friendica\Network\CurlResult'.

````
PHP Fatal error:  Uncaught Error: Cannot use object of type Friendica\Network\CurlResult as array in /...../addon/mastodoncustomemojis/mastodoncustomemojis.php:94
Stack trace:
#0 /...../addon/mastodoncustomemojis/mastodoncustomemojis.php(78): mastodoncustomemojis_fetch_custom_emojis_for_url('https://shelter...')
#1 /...../addon/mastodoncustomemojis/mastodoncustomemojis.php(62): mastodoncustomemojis_get_custom_emojis_for_author('https://shelter...')
#2 /...../src/Core/Addon.php(309): mastodoncustomemojis_put_item_in_cache(Object(Friendica\App), Array)
#3 /...../src/Core/Addon.php(286): Friendica\Core\Addon::callSingleHook(Object(Friendica\App), 'put_item_in_cac...', Array, Array)
#4 /...../include/text.php(1080): Friendica\Core\Addon::callHooks('put_item_in_cac...', Array)
#5 /...../src/Model/Item.php(1638): put_item_in_cache(Array)
#6 /...../src/Protocol/ActivityPub/Processor.php(242): Friendica\Model in /...../addon/mastodoncustomemojis/mastodoncustomemojis.php on line 94
````
and
````
PHP Fatal error:  Uncaught Error: Cannot use object of type Friendica\Network\CurlResult as array in /...../src/Network/Probe.php:1337
Stack trace:
#0 /...../src/Network/Probe.php(692): Friendica\Network\Probe::ostatus(Array)
#1 /...../src/Network/Probe.php(333): Friendica\Network\Probe::detect('https://sealion...', '', 0)
#2 /...../src/Model/Contact.php(1088): Friendica\Network\Probe::uri('https://sealion...', '', 0)
#3 /...../src/Protocol/OStatus.php(72): Friendica\Model\Contact::getIdForURL('https://sealion...')
#4 /...../src/Protocol/OStatus.php(392): Friendica\Protocol\OStatus::fetchAuthor(Object(DOMXPath), NULL, Array, NULL, false)
#5 /...../Protocol/OStatus.php(1002): Friendica\Protocol\OStatus::process('<?xml version="...', Array, NULL, '', false, false)
#6 /...../Protocol/OStatus.php(706): Friendica\Protocol\OStatus::fetchRelated('https://sealion...', 'tag:sealion.clu...', Array)
#7 / in /...../src/Network/Probe.php on line 1337
````

### Friendica version you encountered the problem
2018.12-dev commit a066befba547c5b5a56b945883eda6bf32030697

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
15.1 Distrib 10.1.34-MariaDB

**Comment by nupplaphil** [comment]
On way.. Thanks for the report

**Comment by AlfredSK** [comment]
Seems to be ok now. No further fatal errors. Thanks!
Closing...
