### ISSUE TITLE
[Crypto] PHP Warning

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#5911]
PHP Warning:  openssl_sign(): supplied key param cannot be coerced into a private key in /home/users/zsemberi/www/friendica/src/Util/Crypto.php on line 26

**Comment by MrPetovan** [comment]
Without a full trace, this notice is unactionable.

**Comment by copiis** [comment]
> Without a full trace, this notice is unactionable.

Where can i get the full trace?

**Comment by MrPetovan** [comment]
I use XDebug myself even though it isn't recommended to use on a production site.

**Comment by copiis** [comment]
PHP Warning:  basename() expects parameter 1 to be string, array given in /home/users/zsemberi/www/friendica/src/Model/Photo.php on line 107
PHP Warning:  parse_url() expects parameter 1 to be string, array given in /home/users/zsemberi/www/friendica/src/Util/Network.php on line 96

**Comment by copiis** [comment]
PHP Warning:  Error while sending STMT_CLOSE packet. PID=20427 in /home/users/zsemberi/www/friendica/src/Database/DBA.php on line 653

**Comment by copiis** [comment]
PHP Warning: openssl_sign(): supplied key param cannot be coerced into a private key in /home/users/zsemberi/www/friendica/src/Util/Crypto.php on line 27

**Comment by copiis** [comment]
PHP Warning:  constant(): Couldn't find constant  in /home/users/zsemberi/www/friendica/src/Protocol/PortableContact.php on line 1378

**Comment by copiis** [comment]
PHP Warning:  openssl_sign(): supplied key param cannot be coerced into a private key in /home/users/zsemberi/www/friendica/src/Util/Crypto.php on line 28

**Comment by copiis** [comment]
PHP Warning:  Error while sending STMT_PREPARE packet. PID=1251 in /home/users/zsemberi/www/friendica/src/Database/DBA.php on line 459
PHP Fatal error:  Uncaught Error: Call to a member function prepare() on null in /home/users/zsemberi/www/friendica/src/Database/DBA.php:459
Stack trace:
#0 /home/users/zsemberi/www/friendica/src/Database/DBA.php(573): Friendica\Database\DBA::p('SELECT COUNT(*)...', Array)
#1 /home/users/zsemberi/www/friendica/src/Database/DBA.php(709): Friendica\Database\DBA::p('SELECT COUNT(*)...', Array)
#2 /home/users/zsemberi/www/friendica/src/Database/DBA.php(1374): Friendica\Database\DBA::fetchFirst('SELECT COUNT(*)...', Array)
#3 /home/users/zsemberi/www/friendica/src/Protocol/PortableContact.php(1052): Friendica\Database\DBA::count('gcontact', Array)
#4 /home/users/zsemberi/www/friendica/src/Worker/DiscoverPoCo.php(88): Friendica\Protocol\PortableContact::checkServer('http://http://p...')
#5 [internal function]: Friendica\Worker\DiscoverPoCo::execute('server', 'https://https:/...')
#6 /home/users/zsemberi/www/friendica/src/Core/Worker.php(365): call_user_func_array('Friendica\\Worke...', Array)
#7 /home/users/zsemberi/www/friendica/sr in /home/users/zsemberi/www/friendica/src/Database/DBA.php on line 459

**Comment by MrPetovan** [comment]
In the future, please enclose your error messages with three backticks like this:
````
```
PHP Warning: Error while sending STMT_PREPARE packet. PID=1251 in src/Database/DBA.php on line 459
PHP Fatal error: Uncaught Error: Call to a member function prepare() on null in src/Database/DBA.php:459
Stack trace:
#0 src/Database/DBA.php(573): Friendica\Database\DBA::p('SELECT COUNT()...', Array)
#1 src/Database/DBA.php(709): Friendica\Database\DBA::p('SELECT COUNT()...', Array)
#2 src/Database/DBA.php(1374): Friendica\Database\DBA::fetchFirst('SELECT COUNT(*)...', Array)
#3 src/Protocol/PortableContact.php(1052): Friendica\Database\DBA::count('gcontact', Array)
#4 src/Worker/DiscoverPoCo.php(88): Friendica\Protocol\PortableContact::checkServer('http://http://p...')
#5 [internal function]: Friendica\Worker\DiscoverPoCo::execute('server', 'https://https:/...')
#6 src/Core/Worker.php(365): call_user_func_array('Friendica\Worke...', Array)
#7 sr in src/Database/DBA.php on line 459
```
````
It makes them more readable and avoids mentioning old issues/PRs.

Additionally, you can strip the leading path to your Friendica install. I personally use a text editor to replace `/home/users/zsemberi/www/friendica/` with an empty string.

**Comment by copiis** [comment]
PHP Warning:  sem_acquire(): failed to acquire key 0x66011033: Identifier removed in /friendica/src/Core/Lock/SemaphoreLockDriver.php on line 41

**Comment by copiis** [comment]
PHP Warning:  htmlentities() expects parameter 1 to be string, array given in /friendica/src/Object/OEmbed.php on line 50

**Comment by copiis** [comment]
...
`PHP Warning:  htmlentities() expects parameter 1 to be string, array given in  /src/Object/OEmbed.php on line 50\n'
PHP Warning:  Friendica\\Content\\Text\\HTML::toPlaintext(): unterminated entity reference         Phoenix in /src/Content/Text/HTML.php on line 584\n'
PHP Warning:  proc_close() has been disabled for security reasons in /src/App.php on line 1100\n'`
...

**Comment by copiis** [comment]
---
PHP Warning:  Use of undefined constant DB_UPDATE_VERSION - assumed 'DB_UPDATE_VERSION' (this will throw an Error in a future version of PHP) in /friendica/src/Core/Update.php on line 24
PHP Warning:  A non-numeric value encountered in /friendica/src/Core/Update.php on line 24
PHP Warning:  Use of undefined constant DB_UPDATE_VERSION - assumed 'DB_UPDATE_VERSION' (this will throw an Error in a future version of PHP) in /friendica/src/Core/Update.php on line 25
PHP Warning:  A non-numeric value encountered in /friendica/src/Core/Update.php on line 25
---

**Comment by MrPetovan** [comment]
Thank you for adding the backticks!

**Comment by copiis** [comment]
`
PHP Warning: constant(): Couldn't find constant in /src/Protocol/PortableContact.php on line 1381`

**Comment by copiis** [comment]
`PHP Warning: Use of undefined constant openssl_public_encrypt - assumed 'openssl_public_encrypt' (this will throw an Error in a future version of PHP) in /addon/jappixmini/jappixmini.php on line 609
PHP Warning: Use of undefined constant openssl_public_decrypt - assumed 'openssl_public_decrypt' (this will throw an Error in a future version of PHP) in /addon/jappixmini/jappixmini.php on line 610
PHP Warning: Use of undefined constant openssl_private_encrypt - assumed 'openssl_private_encrypt' (this will throw an Error in a future version of PHP) in /addon/jappixmini/jappixmini.php on line 615
PHP Warning: Use of undefined constant openssl_private_decrypt - assumed 'openssl_private_decrypt' (this will throw an Error in a future version of PHP) in /addon/jappixmini/jappixmini.php on line 616`

**Comment by MrPetovan** [comment]
> `PHP Warning: Illegal string offset 'created' in /src/Worker/Notifier.php on line 148`

What version were you running when this showed up? I can't find anything related anywhere near line 148.

**Comment by MrPetovan** [comment]
In that case, I moved it to https://github.com/friendica/friendica/issues/6337#issuecomment-450430381

**Comment by AlfredSK** [comment]
Some warnings from today...

````
PHP Warning:  Invalid argument supplied for foreach() in mod/notifications.php on line 156
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in mod/notifications.php on line 276
PHP Warning:  Friendica\Content\Text\HTML::toPlaintext(): unterminated entity in src/Content/Text/HTML.php on line 586
````

The last one actually looks really weird in the log (I cleaned it up). The line contains some parts of the comment (item) that generates the problem.
````
PHP Warning:  Friendica\Content\Text\HTML::toPlaintext(): unterminated entity reference description=Composer+2019-0Token (hidden): in /var/www/html/libranet/src/Content/Text/HTML.php on line 586future use by Composer.
````

Unfortunately there are no stack traces in the log.

**Comment by tobiasd** [comment]
>  PHP Warning:  Use of undefined constant importer_uid - assumed 'importer_uid' (this will throw an Error in a future version of PHP) in /src/Worker/OnePoll.php on line 495

Using PHP 7.2.13-1 on my node.

**Comment by MrPetovan** [comment]
Note: This is already fixed in `develop` in #6408
