### ISSUE TITLE
Fatal error on tag search: uncaught ... in System.php

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6019]
Looks like there is a fatal PHP error on every tag search.

````
PHP Fatal error:  Uncaught Friendica\Network\HTTPException\InternalServerErrorException: '/search?tag=Facebook' is not a fully qualified URL, please use App->internalRedirect() instead in /.../src/Core/System.php:250
Stack trace:
#0 /.../mod/redir.php(39): Friendica\Core\System::externalRedirect('/search?tag=Fac...')
#1 /.../src/LegacyModule.php(68): redir_init(Object(Friendica\App))
#2 /.../src/LegacyModule.php(39): Friendica\LegacyModule::runModuleFunction('init')
#3 [internal function]: Friendica\LegacyModule::init()
#4 /.../src/App.php(1852): call_user_func(Array)
#5 /.../index.php(15): Friendica\App->runFrontend()
#6 {main}
  thrown in /var/www/html/libranet/src/Core/System.php on line 250
````

### Friendica version you encountered the problem
2018.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by AlfredSK** [comment]
Hmm. I have a lot of these error messages in PHP log. But when _I_ try to reproduce (trigger) the error by doing some tag searches myself I don't get that PHP error. :thinking:

**Comment by annando** [comment]
Please add all these error messages here: https://github.com/friendica/friendica/issues/5996
