### ISSUE TITLE
Uncaught TypeError: Argument 3 passed to conversation() must be an instance of Friendica\Content\Pager

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#6032]
````
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to conversation() must be an instance of Friendica\Content\Pager, null given, called in /var/www/html/libranet/mod/profile.php on line 348 and defined in /var/www/html/libranet/include/conversation.php:437
Stack trace:
#0 /var/www/html/libranet/mod/profile.php(348): conversation(Object(Friendica\App), Array, NULL, 'profile', 33, false, 'created', 33)
#1 /var/www/html/libranet/mod/update_profile.php(32): profile_content(Object(Friendica\App), 33)
#2 /var/www/html/libranet/src/LegacyModule.php(68): update_profile_content(Object(Friendica\App))
#3 /var/www/html/libranet/src/LegacyModule.php(44): Friendica\LegacyModule::runModuleFunction('content')
#4 [internal function]: Friendica\LegacyModule::content()
#5 /var/www/html/libranet/src/App.php(1846): call_user_func(Array)
#6 /var/www/html/libranet/index.php(15): Friendica\App->runFrontend()
#7 {main}
  thrown in /var/www/html/libranet/include/conversation.php on line 437
````

### Friendica version you encountered the problem
2018.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2.10

### SQL version
10.1.34 MariaDB

**Comment by MrPetovan** [comment]
Caused by #6017
