### ISSUE TITLE
../admin/site inaccessible 

### ISSUE THREAD

**Issue by AndyHee** [friendica/friendica#6266]
After the latest pull today on  `2018.12-rc` , I get an HTTP ERROR 500 for `../admin/site`.

```
2018/12/14 15:33:11 [error] 24486#24486: *104215 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class '' not found in /var/www/friendica/mod/admin.php:1537
Stack trace:
#0 /var/www/friendica/mod/admin.php(248): admin_page_site(Object(Friendica\App))
#1 /var/www/friendica/src/LegacyModule.php(69): admin_content(Object(Friendica\App))
#2 /var/www/friendica/src/LegacyModule.php(44): Friendica\LegacyModule::runModuleFunction('content')
#3 [internal function]: Friendica\LegacyModule::content()
#4 /var/www/friendica/src/App.php(1757): call_user_func(Array)
#5 /var/www/friendica/index.php(15): Friendica\App->runFrontend()
#6 {main}
  thrown in /var/www/friendica/mod/admin.php on line 1537" while reading response header from upstream, client: xxx.xx.xxx.x, server: friendica.hubup.pro, request: "GET /admin/site/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.1-fpm.sock:", host: "friendica.hubup.pro", referrer: "https://friendica.hubup.pro/admin/"

```

**Comment by AndyHee** [comment]
Fixed with ` git reset --hard 5a802bc`

https://forum.friendi.ca/display/39bbe52a-135c-1377-49b2-18b432859036
