### ISSUE TITLE
Editing posts 500 error

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#6405]
When attempting to edit any of my posts, I receive a 500 HTTP error.

Extract from my nginx log:

> 40 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm-www2.sock:", host: "friendica.cwiwie.org", referrer: "https://friendica.cwiwie.org/network?f=&order=post&"
> 2019/01/07 11:42:54 [error] 899#899: *575273 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Addon' not found in /var/www/friendica/mod/editpost.php:86
> Stack trace:
> #0 /var/www/friendica/src/LegacyModule.php(69): editpost_content(Object(Friendica\App))
> #1 /var/www/friendica/src/LegacyModule.php(44): Friendica\LegacyModule::runModuleFunction('content')
> #2 [internal function]: Friendica\LegacyModule::content()
> #3 /var/www/friendica/src/App.php(1784): call_user_func(Array)
> #4 /var/www/friendica/index.php(18): Friendica\App->runFrontend()
> #5 {main}
>   thrown in /var/www/friendica/mod/editpost.php on line 86" while reading response header from upstream, client: 87.58.29.205, server: friendica.cwiwie.org, request: "GET /editpost/187805?mode=none&_=1546857719249 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm-www2.sock:", host: "friendica.cwiwie.org", referrer: "https://friendica.cwiwie.org/network?f=&order=post&"

**Comment by annando** [comment]
An error 500 most likely is caused by some PHP error. Please have a look in your PHP error log. Which version are you using?

**Comment by wiwie** [comment]
I'm on develop.

**Comment by annando** [comment]
Ah okay. I currently can't check this problem by myself, since all of my systems are on RC and I cannot change that easily. Hopefully @MrPetovan can have a look at the problem.

**Comment by MrPetovan** [comment]
A fix is coming with my inspection round.
