### ISSUE TITLE
Redis cache - Redis class isn't available

### ISSUE THREAD

**Issue by ToeiRei** [friendica/friendica#6869]
### Expected behavior
I'd expect it to use redis as a caching solution

### Actual behavior
A stack-Trace

```
PHP Fatal error:  Uncaught Exception: Redis class isn't available in /home/social/friendica/src/Core/Cache/RedisCacheDriver.php:31
Stack trace:
#0 /home/social/friendica/src/Core/Cache/CacheDriverFactory.php(42): Friendica\Core\Cache\RedisCacheDriver->__construct('127.0.0.1', 6379)
#1 /home/social/friendica/src/Core/Cache.php(34): Friendica\Core\Cache\CacheDriverFactory::create('redis')
#2 /home/social/friendica/src/Core/Cache.php(46): Friendica\Core\Cache::init()
#3 /home/social/friendica/src/Core/Cache.php(81): Friendica\Core\Cache::getDriver()
#4 /home/social/friendica/src/Network/Probe.php(322): Friendica\Core\Cache::get('Probe::uri::htt...')
#5 /home/social/friendica/src/Protocol/PortableContact.php(446): Friendica\Network\Probe::uri('https://pluspor...')
#6 /home/social/friendica/src/Worker/GProbe.php(60): Friendica\Protocol\PortableContact::lastUpdated('https://pluspor...', true)
#7 [internal function]: Friendica\Worker\GProbe::execute('https://pluspor...')
#8 /home/social/friendica/src/Core/Worker.php(363): call_user_f in /home/social/friendica/src/Core/Cache/RedisCacheDriver.php on line 31

```

### Steps to reproduce the problem
Add redis config to local config.

### Friendica version you encountered the problem
commit 95a16c8017360957aea130633d2f0e335bd66245

### Friendica source (git, zip)
git

### PHP version
PHP 7.1.27

### SQL version
MariaDB 10.3

**Comment by MrPetovan** [comment]
Hi @ToeiRei and thanks for your report, did you run `bin/composer.phar install --no-dev` from your Friendica base directory?

**Comment by nupplaphil** [comment]
I guess it's a similar problem as #6814
- did you install a redis-server?
- did you install the `php-redis` package?

But I think I should mplement a "fallback" function for it, like a warning in the admin panel "sorry, you chose redis, but redis doesn't work, so we chose db as fallback for you"

**Comment by MrPetovan** [comment]
Ha, good point, Redis isn't a Composer dependency.

**Comment by ToeiRei** [comment]
I have pecl-redis on my server already running with my local redis server for other things so I didn't think of that. Would be nice if we could merrily print out a warning instead of a stacktrace?

**Comment by MrPetovan** [comment]
In this case, would you expect caching to be turned off completely or fallback to the always-available DB cache?

**Comment by ToeiRei** [comment]
I'd expect a fallback and a message like "Dear admin, your redis isn't available because php-redis isn't installed" which is a bit more userfriendly without digging too deep ;)

**Comment by MrPetovan** [comment]
Thanks for the input.
