### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by anmol26s** [friendica/friendica#6870]
After the latest upgrade on Yunohost Friendica package one of the user reported an 504 gateway time-out error. Here is the php log. Hope it gives some clue.

```
[13-Mar-2019 13:18:05] WARNING: [pool friendica] child 4375 said into stderr: "PHP Fatal error:  Uncaught Error: Class 'Friendica\Database\DBStructure' not found in /var/www/friendica/src/App.php:578"
[13-Mar-2019 13:18:05] WARNING: [pool friendica] child 4375 said into stderr: "Stack trace:"
[13-Mar-2019 13:18:05] WARNING: [pool friendica] child 4375 said into stderr: "#0 /var/www/friendica/src/App.php(312): Friendica\App->loadDatabase()"
[13-Mar-2019 13:18:05] WARNING: [pool friendica] child 4375 said into stderr: "#1 /var/www/friendica/src/App.php(189): Friendica\App->reload()"
[13-Mar-2019 13:18:05] WARNING: [pool friendica] child 4375 said into stderr: "#2 /var/www/friendica/bin/worker.php(31): Friendica\App->__construct('/var/www/friend...')"
[13-Mar-2019 13:18:05] WARNING: [pool friendica] child 4375 said into stderr: "#3 {main}"
```

**Comment by MrPetovan** [comment]
Did you run `bin/composer.phar install --no-dev`? It looks like an autoloader issue where it would be completely missing.

**Comment by anmol26s** [comment]
Here it runs without --no-dev option 

https://github.com/YunoHost-Apps/friendica_ynh/blob/master/scripts/upgrade#L144

**Comment by MrPetovan** [comment]
The `--no-dev` isn't mandatory, it just is an optimization if you won't run tests on the Friendica install.

What branch are you pulling from to update?

**Comment by anmol26s** [comment]
I am downloading it from this link. https://friendi.ca/wp-content/uploads/2019/02/friendica-full-2019.01.tar.gz

I want the source in tar.gz or zip format.

**Comment by MrPetovan** [comment]
Thanks, I checked it out, the generated autoload files look fine to me. If this error doesn't happen to all Yunohost installs, I'm not sure the problem is with the code or the archive itself.

Nonetheless, the code has heavily changed between the previous release and the upcoming one, so the next stable archive may not have the same issue.

**Comment by anmol26s** [comment]
Surprisingly the issue is gone itself.

**Comment by Kakaomonster** [comment]
Hello, I have the same problem with the version 2019.03 - but I have no logs and not a ssh access - it is only a webhosting package - Can someone help for this error? It comes permanently.
