### ISSUE TITLE
WSOD when database unavailable but local.config.php exists

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#6879]
### Expected behavior

If the DB isn't available, a clean error screen should appear.

### Actual behavior

WSOD
Log:
```console
[Thu Mar 14 09:43:56.769318 2019] [:error] [pid 16016] [client 192.168.22.1:53388] PHP Fatal error:  Uncaught Error: Call to a member function log() on null in /vagrant/src/Core/Logger.php:228
Stack trace:
#0 /vagrant/src/Database/DBA.php(564): Friendica\\Core\\Logger::log('DB Error 1146: ...')
#1 /vagrant/src/Database/DBA.php(1348): Friendica\\Database\\DBA::p('/*DBA::select, ...', Array)
#2 /vagrant/src/Core/Config/Adapter/JITConfigAdapter.php(34): Friendica\\Database\\DBA::select('config', Array, Array)
#3 /vagrant/src/Core/Config/Configuration.php(62): Friendica\\Core\\Config\\Adapter\\JITConfigAdapter->load('config')
#4 /vagrant/src/Core/Config/Configuration.php(32): Friendica\\Core\\Config\\Configuration->load()
#5 /vagrant/src/Factory/ConfigFactory.php(38): Friendica\\Core\\Config\\Configuration->__construct(Object(Friendica\\Core\\Config\\Cache\\ConfigCache), Object(Friendica\\Core\\Config\\Adapter\\JITConfigAdapter))
#6 /vagrant/src/Factory/DependencyFactory.php(31): Friendica\\Factory\\ConfigFactory::createConfig(Object(Friendica\\Core\\Config\\Cache\\ConfigCache))
#7 /vagrant/index.php(15): Friendica\\Factory\\DependencyFactory: in /vagrant/src/Core/Logger.php on line 228
```

### Steps to reproduce the problem

- Do a clean installation of Friendica
- Remove the database

### Friendica version you encountered the problem

develop

### Friendica source (git, zip)

git

### PHP version

```console
PHP 7.0.33-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.2, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

### SQL version

```console
mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64) using  EditLine wrapper
```

### Additional information

There is a dependency circle `Logger` <-> `DBA`
My first guess would be to throw an exception if `DBA` cannot connect during startup, catch this exception at the Factroy and either try to reconnect or to redirect to `500` status

**Comment by nupplaphil** [comment]
Fixed with #7005
