### ISSUE TITLE
[Duepuntozero] quirk default focus on Saved Searches textbox scrolls page down

### ISSUE THREAD

**Issue by WNYmathGuy** [friendica/friendica#6891]
### Expected behavior
Click on the tab for Network to see the latest posts.

### Actual behavior
Click on the tab for Network, then scroll back up to the top of the page, then see the latest posts.

### Steps to reproduce the problem
I'm not sure. It's happening to me all the time.

### Friendica version you encountered the problem
2019.01

### Friendica source (git, zip)
git

### PHP version
7.2.15

### SQL version
MariaDB 10.1.38

![Screenshot from 2019-03-16 10-44-32](https://user-images.githubusercontent.com/28640985/54476952-74872500-47d9-11e9-837e-0c702e900c89.png)

**Comment by MrPetovan** [comment]
Fixed via #6892 on the RC branch, can you pull and test again?

**Comment by WNYmathGuy** [comment]
@MrPetovan sorry to say I'm a git newbie and barely know what I'm doing with it. Can you give me the full command I would type to do it correctly?

**Comment by MrPetovan** [comment]
Of course. You need to change to the Friendica install directory, and run these commands:
```
$ git checkout 2019.03-RC
$ git pull
```

**Comment by tobiasd** [comment]
> @MrPetovan sorry to say I'm a git newbie and barely know what I'm
> doing with it. Can you give me the full command I would type to do it
> correctly?

When you pull the repositories with git

    $> git pull

among the updates to the current branch (in your case master), additionally the infomation about updates in other branches will be fetched. So if you do a `git pull` now; no new code will be fetched into the master branch (no release yet) but you will see an information about a new branch called `2019.03-RC`.

To switch to this branch you need to perfom a *checkout* with git

    $> git checkout 2019.03-RC

which will then apply all the changes done since the last release to the code.

Don't forget to update the composer dependencies

    $> bin/composer --no-dev

There will be an update to the database schema, that will be automatically applied so your node will go into maintenance mode in the time the database is updated. Additionally the performance of the worker process was improved. Several admins reported heacy LOAD with the old setting. They had to adjust the *Maximum Load Average* and the *Maximum number of parallel workers* settings in the admin panel.

Should the DB update got stuck, you can apply it manually from the command line with

    $> bin/console dbstructure update

The change for the autofocus quirk is really small. For testing it, you don't need the whole upgrade process. As an alternative you can copy the updated file from the 2019.03-RC branch [view/templates/searchbox.tpl](https://raw.githubusercontent.com/friendica/friendica/2019.03-RC/view/templates/searchbox.tpl) and save it into your `view/templates` directory of your Friendica installation. You will have to revert this change later, before git will perfprm the update after the release, because of the then uncommited changes to your source code.

**Comment by WNYmathGuy** [comment]
Oy Vey! and Holy Shit! Apparently, I only know enough to be dangerous.
- The good news is replacing `searchbox.tpl` fixed this issue.
- The bad news is before I did that the other instructions made my site unservicable.

```
Last login: Fri Mar  1 16:13:55 2019 from 192.168.1.167
domainAdminUser@serverMachineName:~$ cd domains/nsfw.wnymathguy.com/public_html/
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ git checkout 2019.03-RC
error: Your local changes to the following files would be overwritten by checkout:
	.gitignore
Please commit your changes or stash them before you switch branches.
Aborting
```

I thought I could just write things in the `.gitignore` file and they would get ignored. I had one png that I put in the main directory and also thought I needed to tell it to ignore the LetsEncrypt folder. I rolled back the manual changes I made manually then tried again.

```
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ git checkout 2019.03-RC
Branch '2019.03-RC' set up to track remote branch '2019.03-RC' from 'origin'.
Switched to a new branch '2019.03-RC'
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ git pull
remote: Enumerating objects: 543, done.
remote: Counting objects: 100% (543/543), done.
remote: Total 1131 (serverMachineName 543), reused 543 (serverMachineName 543), pack-reused 588
Receiving objects: 100% (1131/1131), 433.78 KiB | 1.14 MiB/s, done.
Resolving serverMachineNames: 100% (801/801), completed with 185 local objects.
From https://github.com/friendica/friendica
   c079a3539..d32105aa8  2019.03-RC -> origin/2019.03-RC
   48d84b924..39fc98f5f  develop    -> origin/develop
Updating c079a3539..d32105aa8
Fast-forward
 .codecov.yml                                          |    36 +-
 CREDITS.txt                                           |     9 +-
 config/settings.config.php                            |     4 +
 doc/api.md                                            |     4 +
 include/api.php                                       |    20 +-
 include/conversation.php                              |    14 +-
 include/enotify.php                                   |    17 +-
 include/items.php                                     |     3 +-
 mod/admin.php                                         |     4 +-
 mod/filerm.php                                        |     2 +-
 mod/follow.php                                        |    11 +-
 mod/match.php                                         |     2 +-
 mod/network.php                                       |    55 +-
 src/App.php                                           |    12 +-
 src/BaseObject.php                                    |     2 +-
 src/Content/Text/BBCode.php                           |    30 +-
 src/Content/Text/Markdown.php                         |    16 +-
 src/Content/Text/MarkdownParser.php                   |    18 +
 src/Content/Widget/ContactBlock.php                   |     4 +-
 src/Core/Cache/RedisCacheDriver.php                   |     5 +-
 src/Core/Config/Cache/ConfigCache.php                 |     2 +-
 src/Core/Config/Cache/ConfigCacheLoader.php           |    43 +-
 src/Core/Console/Storage.php                          |     6 +-
 src/Core/Lock/AbstractLockDriver.php                  |    22 +-
 src/Core/Lock/CacheLockDriver.php                     |     8 +-
 src/Core/Lock/DatabaseLockDriver.php                  |     8 +-
 src/Core/Lock/ILockDriver.php                         |     4 +-
 src/Core/StorageManager.php                           |     4 +-
 src/Core/Update.php                                   |    56 +-
 src/Core/Worker.php                                   |    49 +-
 src/Factory/DependencyFactory.php                     |     1 +
 src/Factory/LoggerFactory.php                         |     6 +
 src/Model/Contact.php                                 |    71 +-
 src/Model/Item.php                                    |    50 +-
 src/Model/Register.php                                |     2 +-
 src/Network/Probe.php                                 |    22 +-
 src/Object/Image.php                                  |     2 +-
 src/Object/Post.php                                   |     3 +-
 src/Protocol/ActivityPub/Processor.php                |   151 +-
 src/Protocol/ActivityPub/Transmitter.php              |    51 +-
 src/Protocol/DFRN.php                                 |     2 +-
 src/Protocol/Diaspora.php                             |     7 +-
 src/Protocol/Feed.php                                 |    19 +-
 src/Render/FriendicaSmartyEngine.php                  |     2 +-
 src/Util/Crypto.php                                   |     7 +
 src/Util/Network.php                                  |     1 -
 src/Util/Strings.php                                  |    29 +
 src/Worker/Delivery.php                               |    42 +-
 src/Worker/Notifier.php                               |    41 +-
 tests/datasets/config/.htconfig.test.php              |    50 +
 tests/datasets/content/text/markdown/bug-6633.html    |     9 +
 tests/datasets/content/text/markdown/bug-6633.md      |     9 +
 tests/src/Content/Text/BBCodeTest.php                 |   130 +
 tests/src/Content/Text/MarkdownTest.php               |    52 +
 tests/src/Core/Config/Cache/ConfigCacheLoaderTest.php |    11 +
 tests/src/Core/Lock/DatabaseLockDriverTest.php        |    11 +
 tests/src/Core/Lock/LockTest.php                      |    18 +-
 view/lang/cs/messages.po                              |     6 +-
 view/lang/cs/strings.php                              |     4 +-
 view/lang/en-gb/messages.po                           |  4596 ++++++++--------
 view/lang/en-gb/strings.php                           |   147 +-
 view/lang/en-us/messages.po                           |  3949 +++++++-------
 view/lang/en-us/strings.php                           |   916 ++--
 view/lang/it/messages.po                              | 11353 ++++++++++++++++++++-------------------
 view/lang/it/strings.php                              |  1487 ++---
 view/lang/pl/messages.po                              |  4519 ++++++++--------
 view/lang/pl/strings.php                              |   630 +--
 view/templates/searchbox.tpl                          |     2 +-
 view/theme/frio/css/style.css                         |     1 +
 view/theme/frio/php/default.php                       |     4 +-
 view/theme/frio/php/scheme.php                        |     2 +-
 71 files changed, 14956 insertions(+), 13929 deletions(-)
 create mode 100644 src/Content/Text/MarkdownParser.php
 create mode 100644 tests/datasets/content/text/markdown/bug-6633.html
 create mode 100644 tests/datasets/content/text/markdown/bug-6633.md
 create mode 100644 tests/src/Content/Text/BBCodeTest.php
 create mode 100644 tests/src/Content/Text/MarkdownTest.php
```

At this point I thought I was done so went to my browser to see how it was working. It turned out the whole site was non-functioning. I went back here and saw the @tobiasd post and tried the following. (_P.S. why is it we always tell people the hard way first and then at the end say the easier way?_)

```
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ bin/composer --no-dev
-bash: bin/composer: No such file or directory
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ bin/composer.phar --no-dev

                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--no-dev" option does not exist.                   
                                                          

list [--xml] [--raw] [--format FORMAT] [--] [<namespace>]

domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ bin/composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 3 installs, 1 update, 0 removals
  - Updating npm-asset/fullcalendar (3.9.0 => 3.10.0): Downloading (100%)         
  - Installing psr/log (1.1.0): Downloading (100%)         
  - Installing monolog/monolog (1.24.0): Downloading (100%)         
  - Installing psr/container (1.0.0): Downloading (100%)         
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
Generating optimized autoload files
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ git clone https://github.com/friendica/friendica-addons.git -b master addon
fatal: destination path 'addon' already exists and is not an empty directory.
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ bin/console install
PHP Fatal error:  Uncaught Error: Call to undefined method Friendica\App::loadConfigFile() in /home/domainAdminUser/domains/nsfw.wnymathguy.com/public_html/addon/geonames/geonames.php:81
Stack trace:
#0 /home/domainAdminUser/domains/nsfw.wnymathguy.com/public_html/src/Core/Hook.php(201): geonames_load_config(Object(Friendica\App), Object(Friendica\Core\Config\Cache\ConfigCacheLoader))
#1 /home/domainAdminUser/domains/nsfw.wnymathguy.com/public_html/src/Core/Hook.php(177): Friendica\Core\Hook::callSingle(Object(Friendica\App), 'load_config', Array, Object(Friendica\Core\Config\Cache\ConfigCacheLoader))
#2 /home/domainAdminUser/domains/nsfw.wnymathguy.com/public_html/src/App.php(370): Friendica\Core\Hook::callAll('load_config', Object(Friendica\Core\Config\Cache\ConfigCacheLoader))
#3 /home/domainAdminUser/domains/nsfw.wnymathguy.com/public_html/src/App.php(237): Friendica\App->reload()
#4 /home/domainAdminUser/domains/nsfw.wnymathguy.com/public_html/src/Factory/DependencyFactory.php(36): Friendica\App->__construct('/home/domainAdminUser/d...', Object(Friendica\Core\Config\Configurat in /home/domainAdminUser/domains/nsfw.wnymathguy.com/public_html/addon/geonames/geonames.php on line 81
```
So maybe obviously I don't understand a **byte** of that, but I know somethingis bad. Site still doesn't load anything. I'm now just desperately gussing what might work...

```
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ git checkout 2019.01
Note: checking out '2019.01'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 7441277e7 missed the day
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ git pull
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ git pull 2019.01
fatal: '2019.01' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
domainAdminUser@serverMachineName:~/domains/nsfw.wnymathguy.com/public_html$ 
```

It turns out that my site is working again at this point. I calm down and read to the bottom of @tobiasd 's post. I replace the `searchbox.tpl` file with the remote one and all is well. Not sure if it's valueable for anybody to debrief me on what the hell just happened so I'm not asking you to do that. I just wanted it to be available for you to see since you couldn't be here while it happened.

**Comment by tobiasd** [comment]
> At this point I thought I was done so went to my browser to see how it was working. It turned out the whole site was non-functioning

*gar* yes, ahem... you need to switch and pull the 2019.03-RC branch for the addons as well... That is most likely the reason for your non-working state. Sorry for forgetting this.

> P.S. why is it we always tell people the hard way first and then at the end say the easier way?

In this case, just because I wrote the answer for the git issue and at the very end realised the problem was initially with the searchbox only and you can just exchange that file; first-in-first-out.

> I thought I could just write things in the .gitignore file and they would get ignored.

If you do a `git status` then those files not included in the repository at the moment will be listed. If you add them to the `.gitignore` file git will ignore them with any action you perform via git. Those actions can lead to the deletion of the *alien* files if the git commands used have that side effect (e.g. a reset could lead to this). But normally you should not need to perform those commands.

You *can* add the files to the `.gitignore` and commit that to your own *working* branch of the repository. Then you would need to merge the changes we do to our branches (master, develop or the RC branches) into your *working* branch. This should be no problem, unless we change something at the `.gitignore` file, in which case you would need to resolve the conflict--which *is* possible.

**Comment by tobiasd** [comment]
> The good news is replacing searchbox.tpl fixed this issue.

That is great :) then I'll close the issue (so that the list of open issues for the release in decreased by one) but comments are still open.

**Comment by MrPetovan** [comment]
Post-mortem: There seems to have been some confusion about the actual commands to run.
```
$ bin/composer --no-dev
$ bin/composer.phar --no-dev
$ bin/console install
```
None of these commands exist or make sense. The actual correct command is
```
$ bin/composer.phar install --no-dev
```
And I edited @tobiasd 's answer to correct the mistake.

**Comment by tobiasd** [comment]
> And I edited @tobiasd 's answer to correct the mistake.

Thanks :)

**Comment by WNYmathGuy** [comment]
> _gar_ yes, ahem... you need to switch and pull the 2019.03-RC branch for the addons as well... That is most likely the reason for your non-working state. Sorry for forgetting this.

I did think of the add-ons but didn't understand how to try to get new ones and kept guessing wrong. Thanks so much for all the quick responses.
