### ISSUE TITLE
2019-06: Uncaught TypeError: Argument 2 passed to Friendica\Protocol\Diaspora::participantsForThread() must be of the type array, boolean given

### ISSUE THREAD

**Issue by kr428** [friendica/friendica#7356]
Updated my friendica installation to 2019-06 a few days ago, learnt that the worker.php cron doesn't work anymore. Exception see below. Known issue?

```
Array
(
    [0] => 
    [1] => Fatal error: Uncaught TypeError: Argument 2 passed to Friendica\Protocol\Diaspora::participantsForThread() must be of the type array, boolean given, called in /......../hub428/src/Worker/Notifier.php on line 405 and defined in /......../hub428/src/Protocol/Diaspora.php:214
    [2] => Stack trace:
    [3] => #0 /......../hub428/src/Worker/Notifier.php(405): Friendica\Protocol\Diaspora::participantsForThread('99090', false)
    [4] => #1 [internal function]: Friendica\Worker\Notifier::execute('wall-new', '99090')
    [5] => #2 /......../hub428/src/Core/Worker.php(402): call_user_func_array('Friendica\\Worke...', Array)
    [6] => #3 /......../hub428/src/Core/Worker.php(299): Friendica\Core\Worker::execFunction(Array, 'Notifier', Array, true)
    [7] => #4 /......../hub428/src/Core/Worker.php(114): Friendica\Core\Worker::execute(Array)
    [8] => #5 /......../hub428/bin/worker.php(54): Friendica\Core\Worker::processQueue(true)
    [9] => #6 {main}
    [10] =>   thrown in /......../hub428/src/Protocol/Diaspora.php on line 214
)

```

**Comment by annando** [comment]
This only should happen when a previous SQL query failed. Even with an empty result it would be an empty array. Could you have a look at your friendica log file for entries with DBA.php or Database.php in it that look like SQL errors?

**Comment by kr428** [comment]
Ok, need to see whether I can find this. I'm on a shared hosting environment and don't really see logging beyond simple apache2 access logs.

**Comment by annando** [comment]
This logging is done via Friendica itself. You can enable it in the admin frontend.

**Comment by kr428** [comment]
Ah ok, thanks. Wasn't aware of that. This is what appears there after enabling logging and trying to call worker.php once. Anything suspicious in there?

```
2019-07-09 11:34:44 worker [INFO]: Connection usage (user values): 1/25 [] - {&quot;file&quot;:&quot;Worker.php&quot;,&quot;line&quot;:501,&quot;function&quot;:&quot;maxConnectionsReached&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Connection usage (system values): 3/500 [] - {&quot;file&quot;:&quot;Worker.php&quot;,&quot;line&quot;:529,&quot;function&quot;:&quot;maxConnectionsReached&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Add cron entries [] - {&quot;file&quot;:&quot;Worker.php&quot;,&quot;line&quot;:1065,&quot;function&quot;:&quot;runCron&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: No running worker found with priority 20 - assigning it. {&quot;priority&quot;:20} - {&quot;file&quot;:&quot;Worker.php&quot;,&quot;line&quot;:847,&quot;function&quot;:&quot;nextPriority&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Found: {&quot;priority&quot;:20,&quot;id&quot;:[1060833]} - {&quot;file&quot;:&quot;Worker.php&quot;,&quot;line&quot;:806,&quot;function&quot;:&quot;nextProcess&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Connection usage (user values): 1/25 [] - {&quot;file&quot;:&quot;Worker.php&quot;,&quot;line&quot;:501,&quot;function&quot;:&quot;maxConnectionsReached&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Connection usage (system values): 3/500 [] - {&quot;file&quot;:&quot;Worker.php&quot;,&quot;line&quot;:529,&quot;function&quot;:&quot;maxConnectionsReached&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Process start. {&quot;priority&quot;:20,&quot;id&quot;:1060833,&quot;worker_id&quot;:&quot;8f874b0&quot;,&quot;worker_cmd&quot;:&quot;Notifier&quot;} - {&quot;file&quot;:&quot;Worker.php&quot;,&quot;line&quot;:384,&quot;function&quot;:&quot;execFunction&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Invoked: wall-new: 99090 {&quot;worker_id&quot;:&quot;8f874b0&quot;,&quot;worker_cmd&quot;:&quot;Notifier&quot;} - {&quot;file&quot;:&quot;Notifier.php&quot;,&quot;line&quot;:45,&quot;function&quot;:&quot;execute&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Top level post {&quot;worker_id&quot;:&quot;8f874b0&quot;,&quot;worker_cmd&quot;:&quot;Notifier&quot;} - {&quot;file&quot;:&quot;Notifier.php&quot;,&quot;line&quot;:120,&quot;function&quot;:&quot;execute&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [ERROR]: DB Error {&quot;code&quot;:1054,&quot;error&quot;:&quot;Unknown column 'updated' in 'field list'&quot;,&quot;callstack&quot;:&quot;DBA::update, Contact::updateSelfFromUserID, User::getOwnerDataById, Notifier::execute, Worker::execFunction, Worker::execute, Worker::processQueue&quot;,&quot;params&quot;:&quot;UPDATE `contact` SET `name` = 'Kristian R.', `nick` = 'kr', `avatar-date` = '2019-04-11 13:17:08', `location` = '', `about` = '&quot;Withering under words you told me: Comfort in the great machine.&quot;\\r\\n40something. Software professional. Photography hobbyist. Dissatisfied FLOSS nerd. Dresden.', `keywords` = 'linux, software, floss, metal, music', `gender` = '', `contact-type` = 0, `xmpp` = '', `photo` = 'https:\/\/hub.z428.eu\/photo\/19387512375c8a005269bf7791969412-4.jpg?ts=1554988628', `thumb` = 'https:\/\/hub.z428.eu\/photo\/19387512375c8a005269bf7791969412-5.jpg?ts=1554988628', `micro` = 'https:\/\/hub.z428.eu\/photo\/19387512375c8a005269bf7791969412-6.jpg?ts=1554988628', `avatar` = 'https:\/\/hub.z428.eu\/photo\/profile\/1.jpg', `forum` = '', `prv` = '', `url` = 'https:\/\/hub.z428.eu\/profile\/kr', `nurl` = 'http:\/\/hub.z428.eu\/profile\/kr', `addr` = 'kr@hub.z428.eu', `request` = 'https:\/\/hub.z428.eu\/dfrn_request\/kr', `notify` = 'https:\/\/hub.z428.eu\/dfrn_notify\/kr', `poll` = 'https:\/\/hub.z428.eu\/dfrn_poll\/kr', `confirm` = 'https:\/\/hub.z428.eu\/dfrn_confirm\/kr', `poco` = 'https:\/\/hub.z428.eu\/poco\/kr', `updated` = '2019-07-09 11:34:44' WHERE (`id` = 1)&quot;} - {&quot;file&quot;:&quot;DBA.php&quot;,&quot;line&quot;:699,&quot;function&quot;:&quot;e&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [ERROR]: DB Error {&quot;code&quot;:1054,&quot;error&quot;:&quot;Unknown column 'updated' in 'field list'&quot;,&quot;callstack&quot;:&quot;DBA::update, Contact::updateSelfFromUserID, User::getOwnerDataById, Notifier::execute, Worker::execFunction, Worker::execute, Worker::processQueue&quot;,&quot;params&quot;:&quot;UPDATE `contact` SET `name` = 'Kristian R.', `nick` = 'kr', `avatar-date` = '2019-04-11 13:17:08', `location` = '', `about` = '&quot;Withering under words you told me: Comfort in the great machine.&quot;\\r\\n40something. Software professional. Photography hobbyist. Dissatisfied FLOSS nerd. Dresden.', `keywords` = 'linux, software, floss, metal, music', `gender` = '', `contact-type` = 0, `xmpp` = '', `photo` = 'https:\/\/hub.z428.eu\/photo\/19387512375c8a005269bf7791969412-4.jpg?ts=1554988628', `thumb` = 'https:\/\/hub.z428.eu\/photo\/19387512375c8a005269bf7791969412-5.jpg?ts=1554988628', `micro` = 'https:\/\/hub.z428.eu\/photo\/19387512375c8a005269bf7791969412-6.jpg?ts=1554988628', `avatar` = 'https:\/\/hub.z428.eu\/photo\/profile\/1.jpg', `forum` = '', `prv` = '', `url` = 'https:\/\/hub.z428.eu\/profile\/kr', `nurl` = 'http:\/\/hub.z428.eu\/profile\/kr', `addr` = 'kr@hub.z428.eu', `request` = 'https:\/\/hub.z428.eu\/dfrn_request\/kr', `notify` = 'https:\/\/hub.z428.eu\/dfrn_notify\/kr', `poll` = 'https:\/\/hub.z428.eu\/dfrn_poll\/kr', `confirm` = 'https:\/\/hub.z428.eu\/dfrn_confirm\/kr', `poco` = 'https:\/\/hub.z428.eu\/poco\/kr', `updated` = '2019-07-09 11:34:44' WHERE (`uid` = 0 AND `nurl` = 'http:\/\/hub.z428.eu\/profile\/kr')&quot;} - {&quot;file&quot;:&quot;DBA.php&quot;,&quot;line&quot;:699,&quot;function&quot;:&quot;e&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [ERROR]: DB Error {&quot;code&quot;:1054,&quot;error&quot;:&quot;Unknown column 'protocol' in 'field list'&quot;,&quot;callstack&quot;:&quot;DBA::select, Transmitter::fetchTargetInboxesforUser, Transmitter::fetchTargetInboxes, Notifier::activityPubDelivery, Notifier::execute, Worker::execFunction, Worker::execute, Worker::processQueue&quot;,&quot;params&quot;:&quot;SELECT `url`, `network`, `protocol` FROM `contact` WHERE (`uid` = 1 AND `archive` = 0 AND `pending` = 0 AND `rel` IN (1, 3))&quot;} - {&quot;file&quot;:&quot;DBA.php&quot;,&quot;line&quot;:602,&quot;function&quot;:&quot;p&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Origin item 99090 with URL https://hub.z428.eu/objects/8022fca4-115d-2390-b0e4-f5e601185856 will be distributed. {&quot;worker_id&quot;:&quot;8f874b0&quot;,&quot;worker_cmd&quot;:&quot;Notifier&quot;} - {&quot;file&quot;:&quot;Notifier.php&quot;,&quot;line&quot;:620,&quot;function&quot;:&quot;activityPubDelivery&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: No inboxes found for item 99090 with URL https://hub.z428.eu/objects/8022fca4-115d-2390-b0e4-f5e601185856. It will not be distributed. {&quot;worker_id&quot;:&quot;8f874b0&quot;,&quot;worker_cmd&quot;:&quot;Notifier&quot;} - {&quot;file&quot;:&quot;Notifier.php&quot;,&quot;line&quot;:635,&quot;function&quot;:&quot;activityPubDelivery&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: GUID: 8022fca4-115d-2390-b0e4-f5e601185856: Parent is dfrn. Thread parent is dfrn {&quot;worker_id&quot;:&quot;8f874b0&quot;,&quot;worker_cmd&quot;:&quot;Notifier&quot;} - {&quot;file&quot;:&quot;Notifier.php&quot;,&quot;line&quot;:156,&quot;function&quot;:&quot;execute&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [INFO]: Distributing directly 8022fca4-115d-2390-b0e4-f5e601185856 {&quot;worker_id&quot;:&quot;8f874b0&quot;,&quot;worker_cmd&quot;:&quot;Notifier&quot;} - {&quot;file&quot;:&quot;Notifier.php&quot;,&quot;line&quot;:250,&quot;function&quot;:&quot;execute&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [ERROR]: DB Error {&quot;code&quot;:1054,&quot;error&quot;:&quot;Unknown column 'protocol' in 'field list'&quot;,&quot;callstack&quot;:&quot;DBA::select, Notifier::execute, Worker::execFunction, Worker::execute, Worker::processQueue&quot;,&quot;params&quot;:&quot;SELECT `id`, `url`, `network`, `protocol`, `batch` FROM `contact` WHERE (`id` IN (1) AND `self` = 0 AND `blocked` = 0 AND `pending` = 0 AND `archive` = 0 AND `network` IN ('stat', 'dfrn', 'dspr', 'mail'))&quot;} - {&quot;file&quot;:&quot;DBA.php&quot;,&quot;line&quot;:602,&quot;function&quot;:&quot;p&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493}
2019-07-09 11:34:44 worker [ERROR]: DB Error {&quot;code&quot;:1054,&quot;error&quot;:&quot;Unknown column 'protocol' in 'field list'&quot;,&quot;callstack&quot;:&quot;Notifier::execute, Worker::execFunction, Worker::execute, Worker::processQueue&quot;,&quot;params&quot;:&quot;SELECT `batch`, ANY_VALUE(`id`) AS `id`, ANY_VALUE(`name`) AS `name`, ANY_VALUE(`network`) AS `network`, ANY_VALUE(`protocol`) AS `protocol` FROM `contact` WHERE `network` = 'dspr' AND `batch` != '' AND `uid` = 1 AND `rel` != 2 AND NOT `blocked` AND NOT `pending` AND NOT `archive` GROUP BY `batch`&quot;} - {&quot;file&quot;:&quot;DBA.php&quot;,&quot;line&quot;:602,&quot;function&quot;:&quot;p&quot;,&quot;uid&quot;:&quot;3ccf52&quot;,&quot;process_id&quot;:29493})

```

**Comment by MrPetovan** [comment]
Yes, see the two last lines: `Unknown column 'protocol' in 'field list'` for the query `` SELECT `batch`, ANY_VALUE(`id`) AS `id`, ANY_VALUE(`name`) AS `name`, ANY_VALUE(`network`) AS `network`, ANY_VALUE(`protocol`) AS `protocol` FROM `contact` WHERE `network` = 'dspr' AND `batch` != '' AND `uid` = 1 AND `rel` != 2 AND NOT `blocked` AND NOT `pending` AND NOT `archive` GROUP BY `batch` ``

Can you please run `bin/console dbstructure dryrun` and paste the result here?

**Comment by kr428** [comment]
Is there any way to do so without having terminal access? I tried doing "check database structure" in the frontend which returned "Database structure update 1304 was successfully applied." but I'm unsure that's what you need.

**Comment by MrPetovan** [comment]
The `contact.protocol` field didn't exist in database version 1304, but the corresponding code wasn't making any reference to it either. Can you please tell us how you installed your Friendica files?

**Comment by kr428** [comment]
Didn't do much, can't really do much on the shared environment. Essentially downloaded the .zip files, copied over configuration, removed old files and copied "new" files into the same place/folder.

**Comment by MrPetovan** [comment]
Which version did you download? Can you check the DB_UPDATE_VERSION PHP constant value on line 37 of your `config/dbstructure.config.php` file?

**Comment by kr428** [comment]
Using friendica-full-2019.06.zip and the corresponding addons zip. DB_UPDATE_VERSION is set to 1304 it seems. Is this how it should be...?

**Comment by MrPetovan** [comment]
Unfortunately not, it should be 1313. I checked the archive integrity, the `config/dbstructure.config.php` file is at the correct version. Maybe you copied the whole `config` folder, overwriting the new version with your old?

**Comment by kr428** [comment]
Maybe yes. Indeed. I copied in the new config/dbstructure and apparently this solves at least the worker.php exception. Thanks for fixing something obvious. :)

**Comment by MrPetovan** [comment]
You're welcome, the update process has been made slightly more hazardous since we started cramming all sorts of stuff into the `config` folder, this will change in the next version.

**Comment by annando** [comment]
Without shell access you will most likely get into huge problems at some time in the future since some update processes will most likely fail. I do understand the need for having Friendica running under restricted shared hosters. But even large software projects like Nextcloud - although offering something similar like the frontend worker - do struggle massively with this situation. Means: When you do host Nextcloud without a shell based cron job, at some time in the future you will get huge performance issues and your system won't work reliably anymore. When even large projects like Nextcloud (who are having several full time programmers) can't solve this problem, then I don't have the confidence that we will be able doing so.

**Comment by kr428** [comment]
Hmmmm, that's not good. :( Though not your fault, it's bit of a pain to see that, even though we are more and more pushing for decentralization and asking people to run stuff on their own, the hurdle to actually do so is getting higher and higher. So far, "just" running a shared web hoster worked out well for friendica as well as nextcloud (which makes things *considerably* easier both in terms of maintaineance and - of course - also in terms of costs). Shell access, even more shell access with shell-based crons, in case of most hosters I've seen to date will require you to handle a root server of your own rather than even "just" having shared hosting with SSH enabled.

**Comment by annando** [comment]
I currently don't have a clue how to do it reliably without the shell. But there are shared hosters out there who do allow shell access.

**Comment by kr428** [comment]
What's the worker actually supposed to do? What happens inside this cron? (And, by the way, should this discussion better happen elsewhere outside this ticket? ;) )

**Comment by annando** [comment]
The worker is responsible for every background process. Mostly this is the delivering of messages. Without a running worker your message won't be distributed to the receivers. Additionally it fetches RSS feeds and is doing some background cleanup.

We can discuss this in the administrators forum as well, if you have unanswered questions.
