### ISSUE TITLE
Advanced Content Filter - class missing (typo?)

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7864]
### Expected behavior
When creating a rule in the Advanced Content Filter add-on there shouldn't be a "Slim Application Error".

### Actual behavior
I tried to create a rule to collapse posts with more than X images in the post's body. I always get a "Slim Application Error".

```
[24-Nov-2019 18:51:44 UTC] Slim Application Error:
Type: Error
Message: Class 'Friendica\Network\HTTPException\ServiceUnavaiableException' not found
File: /var/www/html/mordor/addon/advancedcontentfilter/advancedcontentfilter.php
Line: 342
Trace: #0 [internal function]: advancedcontentfilter_post_rules(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#1 /var/www/html/mordor/addon/advancedcontentfilter/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func('advancedcontent...', Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /var/www/html/mordor/addon/advancedcontentfilter/vendor/slim/slim/Slim/Route.php(335): Slim\Handlers\Strategies\RequestResponse->__invoke('advancedcontent...', Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /var/www/html/mordor/addon/advancedcontentfilter/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#4 /var/www/html/mordor/addon/advancedcontentfilter/vendor/slim/slim/Slim/Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /var/www/html/mordor/addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(495): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /var/www/html/mordor/addon/advancedcontentfilter/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /var/www/html/mordor/addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(388): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /var/www/html/mordor/addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(296): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /var/www/html/mordor/addon/advancedcontentfilter/advancedcontentfilter.php(177): Slim\App->run()
#10 /var/www/html/mordor/src/LegacyModule.php(71): advancedcontentfilter_init(Object(Friendica\App))
#11 /var/www/html/mordor/src/LegacyModule.php(40): Friendica\LegacyModule::runModuleFunction('init', Array)
#12 [internal function]: Friendica\LegacyModule::init(Array)
#13 /var/www/html/mordor/src/App/Module.php(252): call_user_func(Array, Array)
#14 /var/www/html/mordor/src/App.php(790): Friendica\App\Module->run(Object(Friendica\Core\L10n\L10n), Object(Friendica\App), Object(Friendica\Util\Logger\StreamLogger), Array, Array)
#15 /var/www/html/mordor/index.php(25): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\Config\PreloadPConfiguration))
#16 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
```

### Steps to reproduce the problem
Try to create a new rule. Look in your PHP error log...

Looks like a typo:
Class 'Friendica\Network\HTTPException\Service**Unavaiable**Exception'

### Friendica version you encountered the problem
2019.09 (master)
2019.12-dev

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by MrPetovan** [comment]
Fixed in https://github.com/friendica/friendica-addons/commit/b308f3bc0528b49a8ce0ccc9be21e047e6dff87d

**Comment by AlfredSK** [comment]
I created a PR https://github.com/friendica/friendica-addons/pull/912
