### ISSUE TITLE
Password change/recovery not working

### ISSUE THREAD

**Issue by ben-utzer** [friendica/friendica#7870]
### Expected behavior
Allow password change for user when logged in or as recovery

### Actual behavior
Change not processed. 

### Friendica version you encountered the problem
Latest stable release. 2019.09

### Friendica source (git, zip)
git

### PHP version
Latest stable. 

### SQL version
Can check if needed. 

Error log:
'23-Nov-2019 14:28:36 Europe/Berlin] PHP Fatal error:  Uncaught ParagonIE\Certainty\Exception\BundleException: No valid bundles were found in the data directory. in /www/srv/vendor/paragonie/certainty/src/Fetch.php:128
Stack trace:
#0 /www/srv/vendor/divineomega/password_exposed/src/PasswordExposedChecker.php(72): ParagonIE\Certainty\Fetch->getLatestBundle()
#1 /www/srv/vendor/divineomega/password_exposed/src/PasswordExposedChecker.php(45): DivineOmega\PasswordExposed\PasswordExposedChecker->getBundleFromCertainty()
#2 /www/srv/src/Model/User.php(414): DivineOmega\PasswordExposed\PasswordExposedChecker->__construct(Object(GuzzleHttp\Client), Object(DivineOmega\DOFileCachePSR6\CacheItemPool))
#3 /www/srv/src/Model/User.php(462): Friendica\Model\User::isPasswordExposed('Clixxxxg0000')
#4 /www/srv/mod/lostpass.php(131): Friendica\Model\User::updatePassword(20, 'Clixxxxg0000')
#5 /www/srv/mod/lostpass.php(107): lostpass_generate_password(Array)
#6 /www/srv/src/LegacyModule.php(71): lostpass_content(Object(Friendica\App))
#7 /www/srv/src/LegacyModule.php(45): in /www/srv/vendor/paragonie/certainty/src/Fetch.php on line 128'

**Comment by ben-utzer** [comment]
I don't agree with that, as the problem is only occurring on one server, but both servers have the same basic setup. But we can keep the fault, it is not an urgent thing for me, but it is kind of a bigger bug.

**Comment by MrPetovan** [comment]
The password change now works even in a slightly degraded form without the password exposed check. Please contribute your own use case on #7796
