### ISSUE TITLE
advancedcontentfilter: error 500 and uncaught type error - broken in RC!

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#7989]
### Expected behavior
Advanced content filter should accept new rules.
Edit: DB table must be created on installing the add-on.

### Actual behavior
Nothing happens when I click on "Add a rule" (saving the rule).
Edit: DB table isn't created.

Instead, I see two problems in my browser console:

`advancedcontentfilter/api/rules:1 Failed to load resource: the server responded with a status of 500 ()`

and...
 
```
advancedcontentfilter.js:57 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.<anonymous> (advancedcontentfilter.js:57)
    at Object.<anonymous> (jquery.min.js:2)
    at i (jquery.min.js:2)
    at Object.fireWith [as rejectWith] (jquery.min.js:2)
    at z (jquery.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery.min.js:4)
```

And in my PHP error log I have that fatal error:

```
PHP Fatal error:  Uncaught InvalidArgumentException: Invalid HTTP status code in .../addon/advancedcontentfilter/vendor/slim/slim/Slim/Http/Response.php:222
Stack trace:
#0 .../addon/advancedcontentfilter/vendor/slim/slim/Slim/Http/Response.php(191): Slim\Http\Response->filterStatus(NULL)
#1 .../addon/advancedcontentfilter/src/middlewares.php(21): Slim\Http\Response->withStatus(NULL)
#2 [internal function]: {closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Friendica\Network\HTTPException\ServiceUnavailableException))
#3 .../addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(665): call_user_func_array(Object(Closure), Array)
#4 .../addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(390): Slim\App->handleException(Object(Friendica\Network\HTTPException\ServiceUnavailableException), Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 .../addon/advancedcontentfilter/vendor/slim/slim/Slim/A in .../addon/advancedcontentfilter/vendor/slim/slim/Slim/Http/Response.php on line 222

```

...and this notice:

`PHP Notice:  Undefined property: Friendica\Network\HTTPException\ServiceUnavailableException::$httpcode in .../addon/advancedcontentfilter/src/middlewares.php on line 13`

### Steps to reproduce the problem
Go to settings -> addons -> advancedcontentfilter; click on **+** to add a new rule; type a name and a known working rule; click on button "Add a rule".

**The weird thing is this error appears on venera.social where I enabled the ACF addon today. On libranet.de where I use the addon for some weeks now, it seems to work.**
Edit: That's because the DB table already exists for libranet.de but not for venera.social. DB creation fails.

### Friendica version you encountered the problem
2019.12-rc

### Friendica source (git, zip)
git

### PHP version
7.2

### SQL version
10.1 MariaDB

**Comment by AlfredSK** [comment]
The same error appears when I paste A GUID and click on "Show Variables".

The weird thing is this error appears on venera.social that has been upgraded to RC yesterday and I enabled the ACF addon just today. 
On libranet.de where I use the addon for some weeks now, it seems to work.

I tried to disable and re-enable the addon. But it doesn't help.

**Comment by AlfredSK** [comment]
**Aha! Looks like some database stuff isn't in place!**

``` 
2019-12-22 14:33:32 index [ERROR]: DB Error {"code":1146,"error":"Table 'venera.advancedcontentfilter_rules' doesn't exist","callstack":"Database::select, DBA::select, advancedcontentfilter_prepare_body_content_filter, Hook::callSingle, Hook::callAll, Item::prepareBody, Post::getTemplateData, Post::getTemplateData","params":"SELECT `name`, `expression`, `serialized` FROM `advancedcontentfilter_rules` WHERE (`uid` = 381 AND `active` = 1)"} - {"file":"Database.php","line":614,"function":"p","uid":"644394","process_id":13094}
2019-12-22 14:33:32 index [ERROR]: DB Error {"code":1146,"error":"Table 'venera.advancedcontentfilter_rules' doesn't exist","callstack":"Database::select, DBA::select, advancedcontentfilter_prepare_body_content_filter, Hook::callSingle, Hook::callAll, Item::prepareBody, Post::getTemplateData, Post::getTemplateData","params":"SELECT `name`, `expression`, `serialized` FROM `advancedcontentfilter_rules` WHERE (`uid` = 381 AND `active` = 1)"} - {"file":"Database.php","line":614,"function":"p","uid":"cfa6bb","process_id":13083}
2019-12-22 14:45:43 index [ERROR]: DB Error {"code":1146,"error":"Table 'venera.advancedcontentfilter_rules' doesn't exist","callstack":"Database::select, DBA::select, advancedcontentfilter_get_rules, advancedcontentfilter_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func, Page::initContent","params":"SELECT * FROM `advancedcontentfilter_rules` WHERE (`uid` = 1)"} - {"file":"Database.php","line":614,"function":"p","uid":"520ae3","process_id":19324}
2019-12-22 14:46:34 index [ERROR]: DB Error {"code":1146,"error":"Table 'venera.advancedcontentfilter_rules' doesn't exist","callstack":"Database::insert, DBA::insert, advancedcontentfilter_post_rules, call_user_func, RequestResponse::__invoke, Route::__invoke, Route::callMiddlewareStack, Route::run","params":"INSERT INTO `advancedcontentfilter_rules` (`name`, `expression`, `serialized`, `active`, `uid`, `created`) VALUES ('Test', 'body matches \\\"*\\\"', 'O:52:\\\"Symfony\\\\Component\\\\ExpressionLanguage\\\\Node\\\\BinaryNode\\\":2:{s:5:\\\"nodes\\\";a:2:{s:4:\\\"left\\\";O:50:\\\"Symfony\\\\Component\\\\ExpressionLanguage\\\\Node\\\\NameNode\\\":2:{s:5:\\\"nodes\\\";a:0:{}s:10:\\\"attributes\\\";a:1:{s:4:\\\"name\\\";s:4:\\\"body\\\";}}s:5:\\\"right\\\";O:54:\\\"Symfony\\\\Component\\\\ExpressionLanguage\\\\Node\\\\ConstantNode\\\":3:{s:68:\\\"\\0Symfony\\\\Component\\\\ExpressionLanguage\\\\Node\\\\ConstantNode\\0isIdentifier\\\";b:0;s:5:\\\"nodes\\\";a:0:{}s:10:\\\"attributes\\\";a:1:{s:5:\\\"value\\\";s:1:\\\"*\\\";}}}s:10:\\\"attributes\\\";a:1:{s:8:\\\"operator\\\";s:7:\\\"matches\\\";}}', 1, 1, '2019-12-22 14:46:34')"} - {"file":"Database.php","line":713,"function":"e","uid":"b65f60","process_id":19307}
2019-12-22 14:46:43 index [ERROR]: DB Error {"code":1146,"error":"Table 'venera.advancedcontentfilter_rules' doesn't exist","callstack":"Database::insert, DBA::insert, advancedcontentfilter_post_rules, call_user_func, RequestResponse::__invoke, Route::__invoke, Route::callMiddlewareStack, Route::run","params":"INSERT INTO `advancedcontentfilter_rules` (`name`, `expression`, `serialized`, `active`, `uid`, `created`) VALUES ('Test', 'body matches \\\"\/(?:\\\\\\\\[img.*\\\\\\\\[\\\\\\\\\/img\\\\\\\\]\\\\\\\\s*){5}\/\\\"', 'O:52:\\\"Symfony\\\\Component\\\\ExpressionLanguage\\\\Node\\\\BinaryNode\\\":2:{s:5:\\\"nodes\\\";a:2:{s:4:\\\"left\\\";O:50:\\\"Symfony\\\\Component\\\\ExpressionLanguage\\\\Node\\\\NameNode\\\":2:{s:5:\\\"nodes\\\";a:0:{}s:10:\\\"attributes\\\";a:1:{s:4:\\\"name\\\";s:4:\\\"body\\\";}}s:5:\\\"right\\\";O:54:\\\"Symfony\\\\Component\\\\ExpressionLanguage\\\\Node\\\\ConstantNode\\\":3:{s:68:\\\"\\0Symfony\\\\Component\\\\ExpressionLanguage\\\\Node\\\\ConstantNode\\0isIdentifier\\\";b:0;s:5:\\\"nodes\\\";a:0:{}s:10:\\\"attributes\\\";a:1:{s:5:\\\"value\\\";s:28:\\\"\/(?:\\\\[img.*\\\\[\\\\\/img\\\\]\\\\s*){5}\/\\\";}}}s:10:\\\"attributes\\\";a:1:{s:8:\\\"operator\\\";s:7:\\\"matches\\\";}}', 1, 1, '2019-12-22 14:46:43')"} - {"file":"Database.php","line":713,"function":"e","uid":"8aa553","process_id":19319}
```

**Comment by AlfredSK** [comment]
Looks like when I enable the addon the database tables aren't created.

**Comment by MrPetovan** [comment]
Please try toggling the addon off and on?

I should add a check for the table existence but I won’t be able to do it until tomorrow at the earliest.

**Comment by AlfredSK** [comment]
> Please try toggling the addon off and on?

I tried that several times. Doesn't help.

**Comment by AlfredSK** [comment]
When I create the DB table manually it works.
So, I guess the hook that is responsible for creating the DB table isn't triggered or doesn't work.

**Comment by nupplaphil** [comment]
I found the problem:

`Hook::register()` register the `_definition` (for DB) function of the addon, but it doesn't adds it to the hooks of the current call. So the DB-definition/update call in the same `_install` function doesn't call this Hook.

Strange thing, because this part of code wasn't changed for months .. I'll try to add a fix

**Comment by nupplaphil** [comment]
Should be fixed by https://github.com/friendica/friendica-addons/pull/92

**Comment by nupplaphil** [comment]
@AlfredSK plz check and close if it works now :)

**Comment by AlfredSK** [comment]
It is working now.

I disabled the addon; deleted the table; enabled the addon -> table has been re-created.

Closing...
