### ISSUE TITLE
2019.12 - PHP fatal error trying to go to `community` page

### ISSUE THREAD

**Issue by victort** [friendica/friendica#8017]
### Expected behavior
click on `community` icon, expect to go to local community page, option to go to global.

### Actual behavior
blank screen

### Steps to reproduce the problem
upgrade(d) from 2019.9 to 2019.12

### Friendica version you encountered the problem
Friendica 'Dalmatian Bellflower' 2019.12 - 1327

### Friendica source (git, zip)
friendica docker image.

### PHP version
php7.3(?) that ships in docker image

### SQL version
MySQL 5.5.43

getting blank screen on community page, log produces this:
```
[Fri Dec 27 06:15:14.337771 2019] [php7:error] [pid 23493] [client 10.42.0.0:53210] PHP Fatal error:  Uncaught Error: Class 'Session' not found in /var/www/html/mod/community.php:24
Stack trace:
#0 /var/www/html/src/LegacyModule.php(71): community_content(Object(Friendica\\App))
#1 /var/www/html/src/LegacyModule.php(45): Friendica\\LegacyModule::runModuleFunction('content', Array)
#2 [internal function]: Friendica\\LegacyModule::content(Array)
#3 /var/www/html/src/App/Page.php(310): call_user_func(Array, Array)
#4 /var/www/html/src/App/Page.php(364): Friendica\\App\\Page->initContent(Object(Friendica\\App\\Module), Object(Friendica\\App\\Mode))
#5 /var/www/html/src/App.php(795): Friendica\\App\\Page->run(Object(Friendica\\App), Object(Friendica\\App\\BaseURL), Object(Friendica\\App\\Mode), Object(Friendica\\App\\Module), Object(Friendica\\Core\\L10n\\L10n), Object(Friendica\\Core\\Config\\JitConfiguration), Object(Friendica\\Core\\Config\\JitPConfiguration))
#6 /var/www/html/index.php(25): Friendica\\App->runFrontend(Object(Friendica\\App\\Module), Object(Friendica\\App\\Router), Object(Friendica\\Core\\Config\\JitPConfiguration))
#7 {main}
   in /var/www/html/mod/community.php on line 24, referer: https://social.ross154.net/admin/
10.42.0.0 - - [27/Dec/2019:06:15:14 +0000] "GET /community HTTP/1.1" 500 385 "https://social.ross154.net/admin/" "Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
```

**Comment by MrPetovan** [comment]
Thanks for the detailed report, in the future please submit your PHP Fatal Error with traces in #7998 to limit the number of individual issues!

**Comment by MrPetovan** [comment]
Moved to https://github.com/friendica/friendica/issues/7998#issuecomment-569265877, closing here.
