### ISSUE TITLE
advanced content filter - several exceptions

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#8396]
### Actual behavior
From my log:
```
[10-Mar-2020 04:35:16 Asia/Tokyo] Slim Application Error:
Type: TypeError
Message: Argument 2 passed to Friendica\Network\HTTPException::__construct() must be an instance of Exception or null, int given, called in /var/www/html/libranet/addon/advancedcontentfilter/advancedcontentfilter.php on line 333
File: /var/www/html/libranet/src/Network/HTTPException.php
Line: 36
Trace: #0 /var/www/html/libranet/addon/advancedcontentfilter/advancedcontentfilter.php(333): Friendica\Network\HTTPException->__construct('Variable "filte...', 0, Object(Symfony\Component\ExpressionLanguage\SyntaxError))
#1 [internal function]: advancedcontentfilter_post_rules(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func('advancedcontent...', Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/Route.php(335): Slim\Handlers\Strategies\RequestResponse->__invoke('advancedcontent...', Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(495): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(388): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(296): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /var/www/html/libranet/addon/advancedcontentfilter/advancedcontentfilter.php(179): Slim\App->run()
#11 /var/www/html/libranet/src/LegacyModule.php(90): advancedcontentfilter_init(Object(Friendica\App))
#12 /var/www/html/libranet/src/LegacyModule.php(59): Friendica\LegacyModule::runModuleFunction('init', Array)
#13 [internal function]: Friendica\LegacyModule::init(Array)
#14 /var/www/html/libranet/src/App/Module.php(271): call_user_func(Array, Array)
#15 /var/www/html/libranet/src/App.php(571): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\StreamLogger), Array, Array)
#16 /var/www/html/libranet/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\PreloadPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#17 {main}
View in rendered output by enabling the "displayErrorDetails" setting.

[10-Mar-2020 04:35:25 Asia/Tokyo] PHP Notice:  Undefined property: Friendica\Network\HTTPException\NotFoundException::$httpcode in /var/www/html/libranet/addon/advancedcontentfilter/src/middlewares.php on line 33

[10-Mar-2020 04:35:25 Asia/Tokyo] PHP Fatal error:  Uncaught InvalidArgumentException: Invalid HTTP status code in /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/Http/Response.php:222
Stack trace:
#0 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/Http/Response.php(191): Slim\Http\Response->filterStatus(NULL)
#1 /var/www/html/libranet/addon/advancedcontentfilter/src/middlewares.php(41): Slim\Http\Response->withStatus(NULL)
#2 [internal function]: {closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Friendica\Network\HTTPException\NotFoundException))
#3 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(665): call_user_func_array(Object(Closure), Array)
#4 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(390): Slim\App->handleException(Object(Friendica\Network\HTTPException\NotFoundException), Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/App.php(2 in /var/www/html/libranet/addon/advancedcontentfilter/vendor/slim/slim/Slim/Http/Response.php on line 222
```

I wasn't sure where to put this (fatal errors, notices, slim application error). So I made an issue for it.

I must admit I had run the composer update in addon/advancedcontentfilter some time ago. This updated some dependencies for the addon. I have reverted that before I switched to RC. So I'm not totally sure if everything in advancedcontentfilter is in an original state. But git status doesn't complain.

### Steps to reproduce the problem
Go to settings -> addons -> advanced content filter. Click around, open and safe a rule.

### Friendica version you encountered the problem
2020.03-rc

### Friendica source (git, zip)
git

### PHP version
7.3

### SQL version
10.3 MariaDB

**Comment by MrPetovan** [comment]
Fixed by https://github.com/friendica/friendica-addons/pull/966
