### ISSUE TITLE
Compacting error: JsonLdException when receiving response from Writefreely

### ISSUE THREAD

**Issue by wiwie** [friendica/friendica#8509]
When following the handle chris@blog.cwiwie.org located on a writefreely instance and receiving a post update, the following error is thrown:

```
2020-04-10T20:08:49Z index [WARNING]: compacting error:JsonLdException Object
(
    [message:protected] => Could not expand input before compaction.
    [string:Exception:private] =>
    [code:protected] =>
    [file:protected] => /var/www/friendica/vendor/friendica/json-ld/jsonld.php
    [line:protected] => 911
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /var/www/friendica/vendor/friendica/json-ld/jsonld.php
                    [line] => 56
                    [function] => compact
                    [class] => JsonLdProcessor
                    [type] => ->
                    [args] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [@context] => Array
                                        (
                                            [0] => https://www.w3.org/ns/activitystreams
                                            [1] => Array
                                                (
                                                )

                                            [2] => https://w3id.org/security/v1
                                        )
...

```

This is the complete JSON input:

```
{
  "@context": [
    "https://www.w3.org/ns/activitystreams"
  ],
  "type": "OrderedCollectionPage",
  "id": "https://blog.cwiwie.org/api/collections/chris/outbox?page=1",
  "totalItems": 3,
  "partOf": "https://blog.cwiwie.org/api/collections/chris/outbox",
  "next": "https://blog.cwiwie.org/api/collections/chris/outbox?page=2",
  "orderedItems": [
    {
      "@context": [
        "https://www.w3.org/ns/activitystreams",
        {}
      ],
      "type": "Create",
      "id": "https://blog.cwiwie.org/api/posts/5pfxj55e0l",
      "actor": "https://blog.cwiwie.org/api/collections/chris",
      "published": "2020-04-10T21:25:51+02:00",
      "object": {
        "type": "Article",
        "id": "https://blog.cwiwie.org/api/posts/5pfxj55e0l",
        "published": "2020-04-10T21:25:51+02:00",
        "inReplyTo": null,
        "url": "https://blog.cwiwie.org/asdasd-asdsdd-sdds",
        "attributedTo": "https://blog.cwiwie.org/api/collections/chris",
        "to": [
          "https://www.w3.org/ns/activitystreams#Public"
        ],
        "cc": [
          "https://blog.cwiwie.org/api/collections/chris/followers"
        ],
        "name": "asdasd asdsdD SDDS",
        "content": "<p><img src=\"https://wolke.cwiwie.org/s/syTTsZob3J66HW4/preview\" alt=\"Test Image\"></p>\n",
        "contentMap": {
          "en": "<p><img src=\"https://wolke.cwiwie.org/s/syTTsZob3J66HW4/preview\" alt=\"Test Image\"></p>\n"
        },
        "tag": []
      }
    },
    {
      "@context": [
        "https://www.w3.org/ns/activitystreams",
        {}
      ],
      "type": "Create",
      "id": "https://blog.cwiwie.org/api/posts/eiftt4yilf",
      "actor": "https://blog.cwiwie.org/api/collections/chris",
      "published": "2020-04-10T19:54:40+02:00",
      "object": {
        "type": "Article",
        "id": "https://blog.cwiwie.org/api/posts/eiftt4yilf",
        "published": "2020-04-10T19:54:40+02:00",
        "inReplyTo": null,
        "url": "https://blog.cwiwie.org/the-whole-screen-is-covered",
        "attributedTo": "https://blog.cwiwie.org/api/collections/chris",
        "to": [
          "https://www.w3.org/ns/activitystreams#Public"
        ],
        "cc": [
          "https://blog.cwiwie.org/api/collections/chris/followers"
        ],
        "name": "the whole screen is covered",
        "content": "<p>with the left side</p>\n",
        "contentMap": {
          "de": "<p>with the left side</p>\n"
        },
        "tag": []
      }
    },
    {
      "@context": [
        "https://www.w3.org/ns/activitystreams",
        {}
      ],
      "type": "Create",
      "id": "https://blog.cwiwie.org/api/posts/jt8lfz6mko",
      "actor": "https://blog.cwiwie.org/api/collections/chris",
      "published": "2020-04-10T19:27:58+02:00",
      "object": {
        "type": "Article",
        "id": "https://blog.cwiwie.org/api/posts/jt8lfz6mko",
        "published": "2020-04-10T19:27:58+02:00",
        "inReplyTo": null,
        "url": "https://blog.cwiwie.org/test-post",
        "attributedTo": "https://blog.cwiwie.org/api/collections/chris",
        "to": [
          "https://www.w3.org/ns/activitystreams#Public"
        ],
        "cc": [
          "https://blog.cwiwie.org/api/collections/chris/followers"
        ],
        "name": "Test Post",
        "content": "<p>bla test.</p>\n\n<p>_ Blubb _</p>\n\n<p><img src=\"https://wolke.cwiwie.org/s/syTTsZob3J66HW4/preview\" alt=\"test image\"></p>\n",
        "contentMap": {
          "de": "<p>bla test.</p>\n\n<p>_ Blubb _</p>\n\n<p><img src=\"https://wolke.cwiwie.org/s/syTTsZob3J66HW4/preview\" alt=\"test image\"></p>\n"
        },
        "tag": []
      }
    }
  ]
}
```
Is this invalid json-ld (error on writefreely side), or a problem in friendica's php-json-ld library?

**Comment by wiwie** [comment]
Ok. Just discovered one more relevant piece of debug info  in the writefreely log:

```
2020/04/10 22:51:59 Response: JsonLdException: [jsonld.SyntaxError]: Invalid JSON-LD syntax; @context must be an object.
Code: invalid local context
Details: Array
(
    [context] => Array
        (
        )

)

#0 /var/www/friendica/vendor/friendica/json-ld/jsonld.php(2340): JsonLdProcessor->_processContext(Object(stdClass), Array, Array)
#1 /var/www/friendica/vendor/friendica/json-ld/jsonld.php(1082): JsonLdProcessor->_expand(Object(stdClass), NULL, Object(stdClass), Array, false)
#2 /var/www/friendica/vendor/friendica/json-ld/jsonld.php(909): JsonLdProcessor->expand(Object(stdClass), Array)
#3 /var/www/friendica/vendor/friendica/json-ld/jsonld.php(56): JsonLdProcessor->compact(Object(stdClass), Object(stdClass), Array)
#4 /var/www/friendica/src/Util/JsonLD.php(149): jsonld_compact(Object(stdClass), Object(stdClass))
#5 /var/www/friendica/src/Protocol/ActivityPub/Receiver.php(97): Friendica\Util\JsonLD::compact(Array)
#6 /var/www/friendica/src/Module/Inbox.php(69): Friendica\Protocol\ActivityPub\Receiver::processInbox('{"@context":["h...', Array, 0)
#7 [internal function]: Friendica\Module\Inbox::rawContent(Array)
#8 /var/www/friendica/src/App/Module.php(283): call_user_func(Array, Array)
#9 /var/www/friendica/src/App.php(571): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\StreamLogger), Array, Array)
#10 /var/www/friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#11 {main}
```
I guess this has to be fixed on their side then?

**Comment by MrPetovan** [comment]
@annando is the JSON-LD pope around here.

**Comment by AlfredSK** [comment]
`@context` reminds me of.... https://github.com/friendica/friendica/issues/8475#issuecomment-606040337

**Comment by MrPetovan** [comment]
ActivityPub messages are full of these.

**Comment by wiwie** [comment]
> ActivityPub messages are full of these.

does that refer to @AlfredSK's comment or the error I'm getting?

**Comment by MrPetovan** [comment]
I was answering @AlfredSK

**Comment by wiwie** [comment]
For the record, I also created a ticket on writefreely side: https://github.com/writeas/writefreely/issues/296

**Comment by wiwie** [comment]
More debug info.

The array variable $ctxs in _processContext(...) in jsonld.php contains an empty array which causes the hickup. When skipping the empty array in the foreach loop, the problem goes away and I can receive posts from writefreely.

The code modification:
```
                foreach ($ctxs as $ctx) {
...
                        if (is_array($ctx) && count($ctx) == 0) {
                                continue;
                        }
...
                }
```

Json encoded, prettified contents of $ctxs variable:
```
[
    {
        "@vocab": "_:",
        "xsd": "http:\/\/www.w3.org\/2001\/XMLSchema#",
        "as": "https:\/\/www.w3.org\/ns\/activitystreams#",
        "ldp": "http:\/\/www.w3.org\/ns\/ldp#",
        "id": "@id",
        "type": "@type",
        "Accept": "as:Accept",
        "Activity": "as:Activity",
        "IntransitiveActivity": "as:IntransitiveActivity",
        "Add": "as:Add",
        "Announce": "as:Announce",
        "Application": "as:Application",
        "Arrive": "as:Arrive",
	"Article": "as:Article",
        "Audio": "as:Audio",
        "Block": "as:Block",
        "Collection": "as:Collection",
        "CollectionPage": "as:CollectionPage",
        "Relationship": "as:Relationship",
        "Create": "as:Create",
        "Delete": "as:Delete",
        "Dislike": "as:Dislike",
        "Document": "as:Document",
        "Event": "as:Event",
        "Follow": "as:Follow",
        "Flag": "as:Flag",
        "Group": "as:Group",
        "Ignore": "as:Ignore",
        "Image": "as:Image",
        "Invite": "as:Invite",
        "Join": "as:Join",
        "Leave": "as:Leave",
        "Like": "as:Like",
        "Link": "as:Link",
        "Mention": "as:Mention",
        "Note": "as:Note",
        "Object": "as:Object",
        "Offer": "as:Offer",
        "OrderedCollection": "as:OrderedCollection",
        "OrderedCollectionPage": "as:OrderedCollectionPage",
        "Organization": "as:Organization",
        "Page": "as:Page",
        "Person": "as:Person",
        "Place": "as:Place",
        "Profile": "as:Profile",
        "Question": "as:Question",
        "Reject": "as:Reject",
        "Remove": "as:Remove",
        "Service": "as:Service",
        "TentativeAccept": "as:TentativeAccept",
        "TentativeReject": "as:TentativeReject",
        "Tombstone": "as:Tombstone",
        "Undo": "as:Undo",
        "Update": "as:Update",
        "Video": "as:Video",
        "View": "as:View",
        "Listen": "as:Listen",
        "Read": "as:Read",
        "Move": "as:Move",
        "Travel": "as:Travel",
        "IsFollowing": "as:IsFollowing",
        "IsFollowedBy": "as:IsFollowedBy",
        "IsContact": "as:IsContact",
        "IsMember": "as:IsMember",
        "subject": {
            "@id": "as:subject",
            "@type": "@id"
	    "@id": "as:subject",
            "@type": "@id"
        },
        "relationship": {
            "@id": "as:relationship",
            "@type": "@id"
        },
        "actor": {
            "@id": "as:actor",
            "@type": "@id"
        },
        "attributedTo": {
            "@id": "as:attributedTo",
            "@type": "@id"
        },
        "attachment": {
            "@id": "as:attachment",
            "@type": "@id"
        },
        "bcc": {
            "@id": "as:bcc",
            "@type": "@id"
        },
        "bto": {
            "@id": "as:bto",
            "@type": "@id"
        },
        "cc": {
            "@id": "as:cc",
            "@type": "@id"
        },
        "context": {
            "@id": "as:context",
            "@type": "@id"
        },
        "current": {
            "@id": "as:current",
            "@type": "@id"
        },
        "first": {
            "@id": "as:first",
            "@type": "@id"
        },
        "generator": {
            "@id": "as:generator",
            "@type": "@id"
        },
        "icon": {
            "@id": "as:icon",
            "@type": "@id"
        },
        "image": {
	    "@id": "as:image",
            "@type": "@id"
        },
	"inReplyTo": {
            "@id": "as:inReplyTo",
            "@type": "@id"
        },
        "items": {
            "@id": "as:items",
            "@type": "@id"
        },
        "instrument": {
            "@id": "as:instrument",
            "@type": "@id"
        },
        "orderedItems": {
            "@id": "as:items",
            "@type": "@id",
            "@container": "@list"
        },
        "last": {
            "@id": "as:last",
            "@type": "@id"
        },
        "location": {
            "@id": "as:location",
            "@type": "@id"
        },
        "next": {
            "@id": "as:next",
            "@type": "@id"
        },
        "object": {
            "@id": "as:object",
            "@type": "@id"
        },
        "oneOf": {
            "@id": "as:oneOf",
            "@type": "@id"
        },
        "anyOf": {
            "@id": "as:anyOf",
            "@type": "@id"
        },
        "closed": {
            "@id": "as:closed",
            "@type": "xsd:dateTime"
        },
        "origin": {
            "@id": "as:origin",
            "@type": "@id"
        },
	"accuracy": {
            "@id": "as:accuracy",
            "@type": "xsd:float"
        },
        "prev": {
            "@id": "as:prev",
            "@type": "@id"
        },
        "preview": {
            "@id": "as:preview",
            "@type": "@id"
        },
        "replies": {
            "@id": "as:replies",
            "@type": "@id"
        },
        "result": {
            "@id": "as:result",
            "@type": "@id"
        },
        "audience": {
            "@id": "as:audience",
            "@type": "@id"
        },
        "partOf": {
            "@id": "as:partOf",
            "@type": "@id"
        },
        "tag": {
            "@id": "as:tag",
            "@type": "@id"
        },
        "target": {
            "@id": "as:target",
            "@type": "@id"
        },
        "to": {
            "@id": "as:to",
            "@type": "@id"
        },
        "url": {
            "@id": "as:url",
            "@type": "@id"
        },
        "altitude": {
            "@id": "as:altitude",
            "@type": "xsd:float"
        },
        "content": "as:content",
        "contentMap": {
            "@id": "as:content",
            "@container": "@language"
        },
	"name": "as:name",
        "nameMap": {
            "@id": "as:name",
            "@container": "@language"
        },
        "duration": {
            "@id": "as:duration",
            "@type": "xsd:duration"
        },
        "endTime": {
            "@id": "as:endTime",
            "@type": "xsd:dateTime"
        },
        "height": {
            "@id": "as:height",
            "@type": "xsd:nonNegativeInteger"
        },
        "href": {
            "@id": "as:href",
            "@type": "@id"
        },
        "hreflang": "as:hreflang",
        "latitude": {
            "@id": "as:latitude",
            "@type": "xsd:float"
        },
        "longitude": {
            "@id": "as:longitude",
            "@type": "xsd:float"
        },
        "mediaType": "as:mediaType",
        "published": {
            "@id": "as:published",
            "@type": "xsd:dateTime"
        },
        "radius": {
            "@id": "as:radius",
            "@type": "xsd:float"
        },
        "rel": "as:rel",
        "startIndex": {
            "@id": "as:startIndex",
            "@type": "xsd:nonNegativeInteger"
        },
        "startTime": {
            "@id": "as:startTime",
            "@type": "xsd:dateTime"
        },
        "summary": "as:summary",
        "summaryMap": {
            "@id": "as:summary",
            "@container": "@language"
        },
	"totalItems": {
            "@id": "as:totalItems",
            "@type": "xsd:nonNegativeInteger"
        },
        "units": "as:units",
        "updated": {
            "@id": "as:updated",
            "@type": "xsd:dateTime"
        },
        "width": {
            "@id": "as:width",
            "@type": "xsd:nonNegativeInteger"
        },
        "describes": {
            "@id": "as:describes",
            "@type": "@id"
        },
        "formerType": {
            "@id": "as:formerType",
            "@type": "@id"
        },
        "deleted": {
            "@id": "as:deleted",
            "@type": "xsd:dateTime"
        },
        "inbox": {
            "@id": "ldp:inbox",
            "@type": "@id"
        },
        "outbox": {
            "@id": "as:outbox",
            "@type": "@id"
        },
        "following": {
            "@id": "as:following",
            "@type": "@id"
        },
        "followers": {
            "@id": "as:followers",
            "@type": "@id"
        },
        "streams": {
            "@id": "as:streams",
            "@type": "@id"
        },
        "preferredUsername": "as:preferredUsername",
        "endpoints": {
            "@id": "as:endpoints",
            "@type": "@id"
        },
	"uploadMedia": {
            "@id": "as:uploadMedia",
            "@type": "@id"
        },
        "proxyUrl": {
            "@id": "as:proxyUrl",
            "@type": "@id"
        },
        "liked": {
            "@id": "as:liked",
            "@type": "@id"
        },
        "oauthAuthorizationEndpoint": {
            "@id": "as:oauthAuthorizationEndpoint",
            "@type": "@id"
        },
        "oauthTokenEndpoint": {
            "@id": "as:oauthTokenEndpoint",
            "@type": "@id"
        },
        "provideClientKey": {
	"@id": "as:provideClientKey",
            "@type": "@id"
        },
        "signClientKey": {
            "@id": "as:signClientKey",
            "@type": "@id"
        },
        "sharedInbox": {
            "@id": "as:sharedInbox",
            "@type": "@id"
        },
        "Public": {
            "@id": "as:Public",
            "@type": "@id"
        },
        "source": "as:source",
        "likes": {
            "@id": "as:likes",
            "@type": "@id"
        },
        "shares": {
            "@id": "as:shares",
            "@type": "@id"
        }
    },
    [],
    {
        "id": "@id",
        "type": "@type",
        "dc": "http:\/\/purl.org\/dc\/terms\/",
        "sec": "https:\/\/w3id.org\/security#",
        "xsd": "http:\/\/www.w3.org\/2001\/XMLSchema#",
        "EcdsaKoblitzSignature2016": "sec:EcdsaKoblitzSignature2016",
        "Ed25519Signature2018": "sec:Ed25519Signature2018",
        "EncryptedMessage": "sec:EncryptedMessage",
        "GraphSignature2012": "sec:GraphSignature2012",
        "LinkedDataSignature2015": "sec:LinkedDataSignature2015",
        "LinkedDataSignature2016": "sec:LinkedDataSignature2016",
        "CryptographicKey": "sec:Key",
        "authenticationTag": "sec:authenticationTag",
        "canonicalizationAlgorithm": "sec:canonicalizationAlgorithm",
        "cipherAlgorithm": "sec:cipherAlgorithm",
        "cipherData": "sec:cipherData",
        "cipherKey": "sec:cipherKey",
        "created": {
            "@id": "dc:created",
            "@type": "xsd:dateTime"
        },
        "creator": {
            "@id": "dc:creator",
            "@type": "@id"
        },

	"digestAlgorithm": "sec:digestAlgorithm",
        "digestValue": "sec:digestValue",
        "domain": "sec:domain",
        "encryptionKey": "sec:encryptionKey",
        "expiration": {
            "@id": "sec:expiration",
            "@type": "xsd:dateTime"
        },
        "expires": {
            "@id": "sec:expiration",
            "@type": "xsd:dateTime"
        },
        "initializationVector": "sec:initializationVector",
        "iterationCount": "sec:iterationCount",
        "nonce": "sec:nonce",
        "normalizationAlgorithm": "sec:normalizationAlgorithm",
        "owner": {
            "@id": "sec:owner",
            "@type": "@id"
        },
        "password": "sec:password",
        "privateKey": {
            "@id": "sec:privateKey",
            "@type": "@id"
        },
        "privateKeyPem": "sec:privateKeyPem",
        "publicKey": {
            "@id": "sec:publicKey",
            "@type": "@id"
        },
        "publicKeyBase58": "sec:publicKeyBase58",
        "publicKeyPem": "sec:publicKeyPem",
        "publicKeyWif": "sec:publicKeyWif",
        "publicKeyService": {
            "@id": "sec:publicKeyService",
            "@type": "@id"
        },
        "revoked": {
            "@id": "sec:revoked",
            "@type": "xsd:dateTime"
        },
        "salt": "sec:salt",
        "signature": "sec:signature",
        "signatureAlgorithm": "sec:signingAlgorithm",
        "signatureValue": "sec:signatureValue"
    }
]
```

**Comment by MrPetovan** [comment]
The empty array definitely looks out of place.

**Comment by wiwie** [comment]
Yea I can see that following a spec isn't that easy. Looking at how different platforms are implementing it, there is a lot of deviations being introduced. Isn't there some kind of validator tool that can be used to automatically validate requests sent by the different platforms against the spec? Kind of a gold standard system that developers can use to validate their implementation while writing it?

**Comment by MrPetovan** [comment]
Not that I know of.

**Comment by annando** [comment]
@wiwie we are using a PHP library to compact the JSON-LD data. This also can be used to validate the content. In the past we reported some JSON-LD violations to other projects and they fixed them.

Friendica is a little bit picky about this standard. But I think it pays out for the whole AP community, since it helps to improve the overall communication.

I guess we can work it out. The founder of WriteFreely seems to be a nice guy. At the FOSDEM in February this year we had some beer together in the Delirium café.

**Comment by annando** [comment]
In the linked issue he said that he already fixed it. I don't know, how often updates are published. But everything will be okay.

**Comment by wiwie** [comment]
I'll wait with closing this issue until their update is released and I verified that it indeed fixes the issue for me.

**Comment by wiwie** [comment]
Haven't had issues any longer after their update. Closing this issue.
