### ISSUE TITLE
(Re-) authentication of your tumblr page link ends on a 500 page

### ISSUE THREAD

**Issue by copiis** [friendica/friendica#8527]
### Expected behavior
Reauthentication of the Tumbrl Account
### Actual behavior
https://meld.de/tumblr/connect shows a `This page does not work meld.de cannot process this request at the moment. HTTP ERROR 500`

### Steps to reproduce the problem
Klick on reauthenticate tumblr
### Friendica version you encountered the problem
Friendica 'Red Hot Poker' 2020.03 - 1338

### Friendica source (git, zip)
git
### PHP version
PHP Version 7.3.15
### SQL version
MariaDB 10.1.44

**Comment by MrPetovan** [comment]
Can you check your PHP log file when this error occurs? It's likely a Fatal Error and we would need more info to fix it.

**Comment by copiis** [comment]
```
[Mon Apr 20 17:54:04.535469 2020] [proxy_fcgi:error] [pid 1205:tid 140691706431232] [client 37.201.193.4:52604] AH01071: Got error 'PHP message: PHP Notice:  session_start(): A session had already been started - ignoring in /friendica/addon/tumblr/tumblr.php on line 99PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to OAuthRequest::from_consumer_and_token() must be an instance of OAuthToken, null given, called in /friendica/addon/tumblr/library/tumblroauth.php on line 237 and defined in /friendica/library/OAuth1.php:361\nStack trace:\n
#0 /friendica/addon/tumblr/library/tumblroauth.php(237): OAuthRequest::from_consumer_and_token(Object(OAuthConsumer), NULL, 'GET', 'https://www.tum...', Array)\n
#1 /friendica/addon/tumblr/library/tumblroauth.php(98): TumblrOAuth->oAuthRequest('https://www.tum...', 'GET', Array)\n
#2 /friendica/addon/tumblr/tumblr.php(120): TumblrOAuth->getRequestToken('https://meld.de...')\n
#3 /home/users/meld/www/friendica/addon/tumblr/tumblr.php(55): tumblr_connect(Object(Friendica\\App))\n
#4 /friendica/src/LegacyModule.php(90): tumblr_content(Object(Friendica\\App))\n
#5 /friendica/src/LegacyModul...', referer: https://meld.de/settings/connectors
```

**Comment by annando** [comment]
I guess as if we have to redo the whole Tumblr stuff.

**Comment by MrPetovan** [comment]
Fixed by https://github.com/friendica/friendica-addons/pull/975
