### ISSUE TITLE
Proxified images don't work

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#8550]
After the view update, all the subsequent proxified image I've received are triggering 500 errors.

Sample URLs:
- https://friendica.mrpetovan.com/proxy/3d/aHR0cHM6Ly9pLmNoemJnci5jb20vb3JpZ2luYWwvOTI3MDE4OTgyNC9oQkQ3ODE3MzEv (target is https://i.chzbgr.com/original/9270189824/hBD781731/)
- https://friendica.mrpetovan.com/proxy/26/aHR0cHM6Ly9pLmNoemJnci5jb20vb3JpZ2luYWwvODk5NjY5NzM0NC9oQjQ5N0NERDMvMQ== (target is https://i.chzbgr.com/original/8996697344/hB497CDD3/1)
- https://friendica.mrpetovan.com/proxy/ff/aHR0cHM6Ly9hc3NldHMub2N0b2Rvbi5zb2NpYWwvbWVkaWFfYXR0YWNobWVudHMvZmlsZXMvMDA5LzM1NS8wMTMvb3JpZ2luYWwvNjNiMzQzN2E4Yzc5ZWYxMy5qcGc=.jpg (target is https://assets.octodon.social/media_attachments/files/009/355/013/original/63b3437a8c79ef13.jpg)

Systematic error message:
```
 PHP Fatal error:  Uncaught Error: Call to a member function getBody() on null in /home/friendica/friendica/friendica/src/Module/Proxy.php:108
Stack trace:
#0 [internal function]: Friendica\Module\Proxy::init(Array)
#1 /home/friendica/friendica/friendica/src/App/Module.php(271): call_user_func(Array, Array)
#2 /home/friendica/friendica/friendica/src/App.php(571): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\VoidLogger), Array, Array)
#3 /home/friendica/friendica/friendica/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\PreloadPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#4 {main}
  thrown in /home/friendica/friendica/friendica/src/Module/Proxy.php on line 108
```

**Comment by AlfredSK** [comment]
Weird. For me everything seems to work.

**Comment by MrPetovan** [comment]
I was able to trace the issue to a call to `DBA::selectFirst('owner-view', [], ['uid' => $uid]);` that returns `false` even though the `uid` exists.

Query:
```sql
SELECT * FROM `owner-view` WHERE (`uid` = 43) LIMIT 1
```
Error:
```
[2020-04-27 15:51:01] [42S02][1146] Table 'friendica_dev.owner-view' doesn't exist
```

**Comment by MrPetovan** [comment]
Ah wait, my dev instance doesn't have the worker enabled, I have to run it manually.

**Comment by MrPetovan** [comment]
Now the view exists, but I'm still getting an error when querying from PHP.

The query `SELECT * FROM `owner-view` WHERE (`uid` = 43) LIMIT 1` works on its own, but the query `SELECT * FROM `owner-view` WHERE (`uid` = ?) LIMIT 1` with parameter `43` executed from PHP returns `false`.

I'm using MariaDB, what do you use @AlfredSK ?

**Comment by MrPetovan** [comment]
From PHP, the error is the following:
```
[1615] Prepared statement needs to be re-prepared
```
???

**Comment by MrPetovan** [comment]
[This question about the error message](https://laracasts.com/discuss/channels/general-discussion/mysql-general-error-1615-prepared-statement-needs-to-be-re-prepared?page=1) suggests to either:
- Increase MariaDB `table_definition_cache`.
- or enable `PDO::ATTR_EMULATE_PREPARES` that we explicitly disable.

The latter may require code changes so I'm going to try the first.

**Comment by AlfredSK** [comment]
I'm using MariaDB 10.3.

What happens when you run the postupdate from the console? I noticed that it checks the views, deletes them if they already exist and re-creates them.

**Comment by AlfredSK** [comment]
Oh! table_definition_cache. I think I raised that value some weeks ago because mysqltuner suggested it.

**Comment by AlfredSK** [comment]
Also, I don't see any PHP errors in my log.

**Comment by MrPetovan** [comment]
Raising `table_definition_cache` to 500 from the default value 400 solved the issue.

**Comment by annando** [comment]
@MrPetovan see here: https://www.fromdual.com/taxonomy/term/349

Have you checked the number of tables on your system? I guess that the views are added to the tables.

**Comment by MrPetovan** [comment]
Here's an excerpt from `SHOW GLOBAL STATUS;`:

Variable_name | Value
---------------- |------
... | ...
Open_files	| 874
Open_streams	| 0
Open_table_definitions	| 844
Open_tables	| 1319
Opened_files	| 796653
Opened_plugin_libraries	| 0
Opened_table_definitions	| 2738
Opened_tables	| 1868
Opened_views	| 252024
... | ...

According to [the MySQL documentation about `table_definition_cache`](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_table_definition_cache), its value is also tied to `table_open_cache` which I didn't touch. In my case, I probably should increase both, which would prevent me from having to raise `table_definition_cache` alone so much from the default value.

**Comment by MrPetovan** [comment]
`table_definition_cache = 600` and `table_open_cache = 2500` still aren't enough to prevent `Prepared statement needs to be re-prepared` errors. 😞

**Comment by MrPetovan** [comment]
Still having the same issue with `table_definition_cache = 600` and `table_open_cache = 3000` after about 2 hours of normal Friendica use, I don't know what else to do.

**Comment by annando** [comment]
is it only the `owner-view`? I could separate this view into 2 or 3 different views that would be less wide.

**Comment by MrPetovan** [comment]
So far it's the only one I've seen triggering this error.

**Comment by annando** [comment]
Do you see a callstack? Is it always the same?

BTW: I fixed that view because of missing fields and a wrong assigned field: https://github.com/friendica/friendica/pull/8558

**Comment by MrPetovan** [comment]
The callstack for the proxy is always the same, yes. Haven't been able to check for the home status page.

**Comment by annando** [comment]
Would be great getting all callstacks, this would help.

**Comment by MrPetovan** [comment]
In a couple of hours, when I'll be able to switch back to my personal computer.

**Comment by annando** [comment]
Ugly timezones ...

**Comment by MrPetovan** [comment]
From the friendica log enabled with the Error filter:
Status page:
```
DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"Database::select, Database::selectFirst, DBA::selectFirst, Profile::getByNickname, Profile::load, Status::content, Index::content, call_user_func","params":"SELECT * FROM `owner-view` WHERE (`nickname` = 'hypolite' AND `uid` = 1) LIMIT 1"} - {"file":"Database.php","line":637,"function":"p","uid":"1ca594","process_id":7308}
```
Feed module:
```
DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataByNick, OStatus::feed, Feed::content, call_user_func","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"} - {"file":"Database.php","line":637,"function":"p","uid":"2c3076","process_id":7379}
```
Worker:
```
DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"DBA::p, Worker::nextPriority, Worker::nextProcess, Worker::findWorkerProcesses, Worker::processQueue","params":"SELECT COUNT(DISTINCT(`pid`)) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority`"} - {"file":"Database.php","line":637,"function":"p","uid":"9cf0b3","process_id":7496}
DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, HTTPSignature::transmit, APDelivery::execute, Worker::execFunction, Worker::execute","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"} - {"file":"Database.php","line":637,"function":"p","uid":"7d7716","process_id":7457}
```

**Comment by MrPetovan** [comment]
Full list of callstacks and associated queries:
```
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, Profile::getByNickname, Profile::load, Status::content, Index::content, call_user_func","params":"SELECT * FROM `owner-view` WHERE (`nickname` = 'hypolite' AND `uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, GContact::updateForUser, CronJobs::repairDatabase, CronJobs::execute, Worker::execFunction","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, HTTPSignature::transmit, APDelivery::execute, Worker::execFunction, Worker::execute","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, Item::isForumPost, Transmitter::createActivityFromItem, Transmitter::createCachedActivityFromItem, APDelivery::execute","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, OnePoll::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, Transmitter::createActivityFromItem, Transmitter::createCachedActivityFromItem, APDelivery::execute, Worker::execFunction","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, twitter_fetchhometimeline, twitter_sync_run, Worker::execFunction, Worker::execute","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, GContact::updateForUser, CronJobs::repairDatabase, CronJobs::execute","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, HTTPSignature::transmit, APDelivery::execute, Worker::execFunction","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, Item::isForumPost, Transmitter::createActivityFromItem, Transmitter::createCachedActivityFromItem","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, OnePoll::execute, Worker::execFunction, Worker::execute","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, Transmitter::createActivityFromItem, Transmitter::createCachedActivityFromItem, APDelivery::execute","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, twitter_fetchhometimeline, twitter_sync_run, Worker::execFunction","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, User::getOwnerDataByNick, Followers::rawContent, call_user_func","params":"SELECT * FROM `owner-view` WHERE (`uid` = 6) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, User::getOwnerDataByNick, OStatus::feed, Feed::content","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, User::getOwnerDataByNick, Outbox::rawContent, call_user_func","params":"SELECT * FROM `owner-view` WHERE (`uid` = 6) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataById, Xrd::rawContent, call_user_func, Module::run","params":"SELECT * FROM `owner-view` WHERE (`uid` = 6) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataByNick, Followers::rawContent, call_user_func, Module::run","params":"SELECT * FROM `owner-view` WHERE (`uid` = 6) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataByNick, OStatus::feed, Feed::content, call_user_func","params":"SELECT * FROM `owner-view` WHERE (`uid` = 1) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, User::getOwnerDataByNick, Outbox::rawContent, call_user_func, Module::run","params":"SELECT * FROM `owner-view` WHERE (`uid` = 6) LIMIT 1"
"callstack":"Database::select, Database::selectFirst, DBA::selectFirst, User::getOwnerDataById, Xrd::rawContent, call_user_func, Module::run, App::runFrontend","params":"SELECT * FROM `owner-view` WHERE (`uid` = 6) LIMIT 1"
"callstack":"Database::select, Database::selectToArray, DBA::selectToArray, poco_init, LegacyModule::runModuleFunction, LegacyModule::init, call_user_func, Module::run","params":"SELECT * FROM `owner-view` WHERE (`net-publish` = 1) LIMIT 0, 3"
"callstack":"DBA::p, Worker::nextPriority, Worker::nextProcess, Worker::findWorkerProcesses, Worker::processQueue","params":"SELECT COUNT(DISTINCT(`pid`)) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority`"
"callstack":"DBA::p, Worker::nextPriority, Worker::nextProcess, Worker::findWorkerProcesses, Worker::workerProcess, Worker::processQueue","params":"SELECT COUNT(DISTINCT(`pid`)) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, Contact::getIdForURL, Contact::getPublicAndUserContacID, Contact::isBlockedByUser, Contact::isSharing, Item::contactId","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, Contact::getIdForURL, Contact::getPublicAndUserContacID, Contact::isBlockedByUser, Item::insert, Processor::postItem","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, Contact::getIdForURL, Contact::getPublicAndUserContacID, Contact::isSharing, Item::contactId, Item::insert","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, Contact::getIdForURL, Processor::postItem, Processor::createItem, Receiver::processActivity, Receiver::processInbox","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, Cron::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, Cron::updatePublicContacts, Cron::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, Hook::fork, Cron::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, twitter_cron, Hook::callSingle, ForkHook::execute, Worker::execFunction, Worker::execute","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, UpdateGContacts::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::add, Worker::runCron, Worker::processQueue","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
"callstack":"DBA::p, Worker::tooMuchWorkers, Worker::processQueue","params":"SELECT COUNT(*) AS `running`, `priority` FROM `workerqueue-view` GROUP BY `priority` ORDER BY `priority`"
```

**Comment by MrPetovan** [comment]
`mysqltuner.pl` Recommandations:
```
-------- Recommendations ---------------------------------------------------------------------------
General recommendations:
    MySQL was started within the last 24 hours - recommendations may be inaccurate
    Reduce your overall MySQL memory footprint for system stability
    Dedicate this server to your database for highest performance.
    Configure your accounts with ip or subnets only, then update your configuration with skip-name-resolve=1
    We will suggest raising the 'join_buffer_size' until JOINs not using indexes are found.
             See https://dev.mysql.com/doc/internals/en/join-buffer-size.html
             (specially the conclusions at the bottom of the page).
    Before changing innodb_log_file_size and/or innodb_log_files_in_group read this: https://bit.ly/2TcGgtU
Variables to adjust:
  *** MySQL's maximum memory usage is dangerously high ***
  *** Add RAM before increasing MySQL buffer variables ***
    query_cache_size (=0)
    query_cache_type (=0)
    query_cache_limit (> 1M, or use smaller result sets)
    join_buffer_size (> 256.0K, or always use indexes with JOINs)
    table_definition_cache(600) > 1749 or -1 (autosizing if supported)
    innodb_buffer_pool_size (>= 28.2G) if possible.
    innodb_log_file_size should be (=672M) if possible, so InnoDB total log files size equals to 25% of buffer pool size.
    innodb_buffer_pool_instances(=5)
```

**Comment by MrPetovan** [comment]
Re-reading [the documentation for `table_definition_cache`](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_) I realize I shot myself in the foot. 400 is the **minimum** value this key can take, but not the **default_value**, which is defined dynamically as `400 + (table_open_cache / 2)`. Setting it to a fixed amount cancels the dynamic value. Since `table_open_cache`'s default is `2000`, the default value for `table_definition_cache` is actually `1400`, which I cruelly cut in half by setting it to `700`. It doesn't explain why I hit the ceiling just with the views, but it does explain why none of my tweaks have been successful.

I'm going to try to bump `table_open_cache` to `3000` and remove the explicit value of `table_definition_cache` to take advantage of the dynamic default value. Stay (mysql)tuned.

**Comment by annando** [comment]
The values on my system are these:
```
> show global variables where Variable_name like "table%cache";
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| table_definition_cache | 4096  |
| table_open_cache       | 8067  |
+------------------------+-------+
```

**Comment by MrPetovan** [comment]
With autosizing, `table_definition_cache` is set at `2097152` and, huh, it's overkill but it does the job.

**Comment by annando** [comment]
Concerning the output of `mysqltuner.pl`: It seems as if the `innodb_buffer_pool_size` is too high so that it takes more memory than your system can handle. (don't care about the message saying you should increase it) And you should adjust `innodb_log_file_size` to `innodb_buffer_pool_size / innodb_buffer_pool_instances`.

Don't care about `join_buffer_size` and `query_cache_limit` though.

My values on my machine with 16 GB are:
* innodb_buffer_pool_instances: 8
* innodb_buffer_pool_size: 8589934592
* innodb_log_file_size: 1073741824

**Comment by annando** [comment]
We could possibly treat this error message like the error `2006` as well:
https://github.com/friendica/friendica/blob/develop/src/Database/Database.php#L641

Means we could retry. But I have mixed feelings about this.

Should we possibly add some hint on the administration page when we calculate that this value is too low?

**Comment by MrPetovan** [comment]
But should we advocate `table_definition_cache = -1`? And what's the relationship between the current status value (in `SHOW GLOBAL STATUS`) and the current `table_definition_cache ` value?

> And you should adjust `innodb_log_file_size` to `innodb_buffer_pool_size / innodb_buffer_pool_instances`.

My current values with 8 GB RAM:
- innodb_buffer_pool_instances: 6
- innodb_buffer_pool_size: 5,637,144,576 (5.25 GB)
- innodb_log_file_size: 5,0331,648

What would the `innodb_log_file_size` value increase do?

**Comment by annando** [comment]
According to https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_buffer_pool_instances the default value for your database size would be 8 for `innodb_buffer_pool_instances`. But that page also says that each instance should have at least 1 GB. So possibly you reduce the `innodb_buffer_pool_size` to 5 GB, reduce the number of instances to 5 and the file size to 1 GB.

Since I'm no database administrator either, I suggest that you have a look for the suggested values in the documentation as well.

**Comment by guzzisti** [comment]
Regarding manipulation of "table_definition_cache":
Please be aware that admin whose run their instance on shared hosting (which atleast @tobiasd still advocates for Friendica should be able to run on) are not able to change MySQL/MariaDB params such as `table_definition_cache`.

**Comment by MrPetovan** [comment]
It's a valid point, however Friendica's resources needs have been steadily growing over the past 4 years that I've been hacking at it for various reasons, both internal (code refactoring) and external (compatibility with ActivityPub means increased traffic) and consequently we do not offer support for shared hosting installs anymore that I know of. I do get @tobiasd's point but unfortunately we're way past that point.

**Comment by annando** [comment]
Concerning shared hosters: Sadly the requirements for Friendica are in some range where shared haster do complain about excessive usage. Friendica is no Wordpress, it does so much more.

With the upcoming changes the database will be getting smaller and the load should decrease - but this only works by using these views that sadly do have their side effects.

**Comment by guzzisti** [comment]
From my point of view (and a bit experience) atleast a small instance with only "a few" (tbd what a few means ;) ) users can still run fine on a shared hosting nowadays. 
Most shared hosters have advanced a lot in the last years with features like shell access and cron jobs available as well.

**Comment by MrPetovan** [comment]
Oh, of course, it *can* work on shared hosting, we just don't recommend it nor provide comprehensive support for it anymore.

**Comment by annando** [comment]
Can we close this issue?

**Comment by guzzisti** [comment]
My testinstance still shows this error, but i'm currently unsure if you like to stick with the "admins need to tweak their mysql settings" advise or try to find another way to avoid this issue.
If you'd go with option 1, then i think this can be closed.

**Comment by MrPetovan** [comment]
Option 2 would mean revert a bunch of code that was already approved and built upon, it doesn’t look workable at the moment, thank you for your understanding.

**Comment by guzzisti** [comment]
Please make sure that there's a prominent hint in the release notes to adjust the values before updating.

**Comment by annando** [comment]
It's sad that views have got this side effect. On the other side, views offer a lot of potential for the future like disk space reduction, simplifying and unifying of the code and an easier path for supporting more than only MySQL.

There is this PHP configuration that deactivates the "real" prepares. But it could have ugly side effects.

**Comment by guzzisti** [comment]
Views may be useful, i've never used them on MySQL tough. 

On MS SQL views can be horrible performance killers when you try to hide complex querys and datastructures in cascaded views. Unfortunately this is something people tend to do after they started to use views...

**Comment by annando** [comment]
I'm running on of the largest Friendica servers. So when we would use views in a bad way, then I would experience it by myself. It is not the regular situation with "business software" where the developers are using small test databases but aren't using the system by themselves.

**Comment by annando** [comment]
@guzzisti In https://github.com/friendica/friendica/pull/8649 I added some experimental settings. This can be tested on your machine - but I strongly recommend that you keep an eye on the log files (PHP error log, Friendica log) for PHP errors, PHP warnings and database warnings (Friendica log entries with "DB Error" in it).

**Comment by annando** [comment]
@guzzisti we now introduced a working workaround, see PR https://github.com/friendica/friendica/pull/9599. I worked with it the whole day and it seems to work. Can we close this issue?

**Comment by john11smith** [comment]
@annando I have the same problem:
```
[ERROR]: DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"DBA::selectToArray, networkThreadedView, network_content, update_network_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func, Page::initContent","params":"SELECT * FROM `network-item-view` WHERE (`uid` = 1 AND `unseen` = 1) ORDER BY `commented` DESC LIMIT 100"} - {"file":"Database.php","line":668,"function":"p","uid":"ceb260","process_id":2262971}
```
Also notice 
```
[NOTICE]: no data for session {"session_id":"35b4301f752c09f73950a75565d21a9d","uri":"\/ping?format=json&_=1608664921627"} - {"file":"Database.php","line":72,"function":"read","uid":"0cc7f9","process_id":2268093}
2020-12-22T19:51:45Z index [NOTICE]: no data for session {"session_id":"b15ff4fb91ffdc221b0d335d4a322542","uri":"\/ping?format=json&_=1608664921628"} - {"file":"Database.php","line":72,"function":"read","uid":"b37e5b","process_id":2268093}
2020-12-22T19:52:25Z index [NOTICE]: no data for session {"session_id":"4abc411765f3fb68460aab5c14d4d6f9","uri":"\/ping?format=json&_=1608664921629"} - {"file":"Database.php","line":72,"function":"read","uid":"04dffe","process_id":2261577}
```
Also "http://domain-name/.well-known/host-meta is not reachable on your system. This is a severe configuration issue that prevents server to server communication. See the installation page for help."
Also  folder  is missing http://domain-name/profile

**Comment by annando** [comment]
@john11smith the only important message here is `Prepared statement needs to be re-prepared`. The other messages here are unimportant.

There are two solutions for the problem. One is to increase the value of `table_definition_cache` - which isn't possible on shared hosters. And the other is to use the current rc and to set `'pdo_emulate_prepares' => true,` in the `local.config.php`.

**Comment by john11smith** [comment]
@annando thank you very much for your help. I was sure `'pdo_emulate_prepares' => true,` was there already, because it is there on version 2020-09-1 `local-sample.config.php` but, apparently, this line doesn't get transferred to `local.config.php`. That is a shame. I think must be done during installation or at least should be mentioned on installation/ update procedure for Using the Archive Files. I think it must look like this:
_As many files got deleted or moved around, please upload the unpacked files to a new directory on your server (say friendica_new)._ **Edit local.config.php add line `'pdo_emulate_prepares' => true,` in database section,to look like:**
```
'database' => [
		'hostname' => 'localhost',
		'username' => 'mysqlusername',
		'password' => 'mysqlpassword',
		'database' => 'mysqldatabasename',
		'charset' => 'utf8mb4',
		'pdo_emulate_prepares' => true,
```
 _and copy over your existing configuration (config/local.config.php and config/addon.config.php) and .htaccess files. Afterwards rename your current Friendica directory (e.g. friendica) to friendica_old and friendica_new to friendica_
 
On updated web site press **Home** tab. If you get the error `User not found` go to Admin - Information - Overview. If it complains about database engine being not innodb, then on C-Panel terminal or SSH 
```
cd yoursite.files.com
php bin/console.php dbstructure toinnodb
bin/console dbstructure update
```

**Comment by annando** [comment]
This setting will only work reliable on the current RC not on the current stable version.

**Comment by john11smith** [comment]
@annando 

> This setting will only work reliable on the current RC not on the current stable version.

RC is not available for shared hosting servers, 2020.07 2020.09-1 versions don't work at all without `'pdo_emulate_prepares' => true,` I spend 10 days messing with updates. Not so many people use my node and hopefully, people's data hasn't been lost between last backup and today. But I think would be better if there was advice for those on shared hosting to not update above 2020.03 and wait for a new release or detailed instructions for troubleshooting mentioned before.

**Comment by annando** [comment]
I'm sorry for the trouble you had with this. And thanks for your effort in trying to fix it on your side!

I'm currently thinking about suggesting that this setting could be the default setting in the new version. But there is currently not so much experience with this. So possibly this will be default for the 2021.03 version.
