### ISSUE TITLE
2020.06-rc - worker is having FATAL error

### ISSUE THREAD

**Issue by valvin1** [friendica/friendica#8866]
### Expected behavior

Having worker queue near zero. 

### Actual behavior
Since I run 2020.06-rc this queue is now stabilized to 1300 but doesn't unqueue.
 
When I check logs I have the following error : 

```
Fatal error: Uncaught TypeError: Argument 3 passed to Friendica\Content\PageInfo::getTagsFromUrl() must be of the type string, null given, called in /var/www/html/include/items.php on line 46 and defined in /var/www/html/src/Content/PageInfo.php:204
Stack trace:
#0 /var/www/html/include/items.php(46): Friendica\Content\PageInfo::getTagsFromUrl('/2016/01/18/and...', '', NULL)
#1 /var/www/html/src/Protocol/Feed.php(532): get_page_keywords('/2016/01/18/and...', '', true, NULL)
#2 /var/www/html/src/Protocol/Feed.php(85): Friendica\Protocol\Feed::import('<?xml version="...', Array, Array)
#3 /var/www/html/include/items.php(73): Friendica\Protocol\Feed::consume('<?xml version="...', Array, Array, NULL)
#4 /var/www/html/src/Worker/OnePoll.php(176): consume_feed('<?xml version="...', Array, Array, NULL)
#5 [internal function]: Friendica\Worker\OnePoll::execute(101993)
#6 /var/www/html/src/Core/Worker.php(409): call_user_func_array('Friendica\\Worke...', Array)
#7 /var/www/html/src/Core/Worker.php(310): Friendica\Core\Worker::exec in /var/www/html/src/Content/PageInfo.php on line 204
```

### Steps to reproduce the problem

Nothing special. I'm wondering if this issue comes from older message than the version change. Messages in the worker queue is between 04th and 09th july, migration was on 04th july.

### Friendica version you encountered the problem
2020.06-rc

### PHP version

7.3.19

### SQL version

MariaDB 10.3.22

**Comment by valvin1** [comment]
looks like it is not yet fixed : 

```
Fatal error: Uncaught TypeError: Argument 3 passed to Friendica\Content\PageInfo::getTagsFromUrl() must be of the type string, null given, called in /var/www/html/include/items.php on line 46 and defined in /var/www/html/src/Content/PageInfo.php:204
Stack trace:
#0 /var/www/html/include/items.php(46): Friendica\Content\PageInfo::getTagsFromUrl('https://blog.va...', '', NULL)
#1 /var/www/html/src/Protocol/Feed.php(536): get_page_keywords('https://blog.va...', '', true, NULL)
#2 /var/www/html/src/Protocol/Feed.php(85): Friendica\Protocol\Feed::import('<?xml version="...', Array, Array)
#3 /var/www/html/include/items.php(73): Friendica\Protocol\Feed::consume('<?xml version="...', Array, Array, NULL)
#4 /var/www/html/src/Worker/OnePoll.php(176): consume_feed('<?xml version="...', Array, Array, NULL)
#5 [internal function]: Friendica\Worker\OnePoll::execute(101993)
#6 /var/www/html/src/Core/Worker.php(409): call_user_func_array('Friendica\\Worke...', Array)
#7 /var/www/html/src/Core/Worker.php(310): Friendica\Core\Worker::exec in /var/www/html/src/Content/PageInfo.php on line 204
```
It looks i'm well up to date because i can see `addBasePath` function in `Network.php`

**Comment by annando** [comment]
Well, in some way it improved. When you have a look at the log, you see a complete URL now. So the work was not useless :-)

I will have a look.

**Comment by annando** [comment]
The database update had got issues. I'm mostly sure that you don't have the field `ffi_keyword_denylist` but the field `ffi_keyword_blacklist` in your `contact` table. Could you check if the database update had been successful?

**Comment by valvin1** [comment]
unfortunately this column is well here : 

```
MariaDB [friendica]> SHOW COLUMNS from contact;
+---------------------------+-----------------------+------+-----+---------------------+----------------+
| Field                     | Type                  | Null | Key | Default             | Extra          |
+---------------------------+-----------------------+------+-----+---------------------+----------------+
| id                        | int(10) unsigned      | NO   | PRI | NULL                | auto_increment |
| uid                       | mediumint(8) unsigned | NO   | MUL | 0                   |                |
| created                   | datetime              | NO   |     | 0001-01-01 00:00:00 |                |
| self                      | tinyint(1)            | NO   | MUL | 0                   |                |
| remote_self               | tinyint(1)            | NO   |     | 0                   |                |
| rel                       | tinyint(3) unsigned   | NO   |     | 0                   |                |
| duplex                    | tinyint(1)            | NO   |     | 0                   |                |
| network                   | char(4)               | NO   |     |                     |                |
| name                      | varchar(255)          | NO   |     |                     |                |
| nick                      | varchar(255)          | NO   | MUL |                     |                |
| location                  | varchar(255)          | YES  |     |                     |                |
| about                     | text                  | YES  |     | NULL                |                |
| keywords                  | text                  | YES  |     | NULL                |                |
| gender                    | varchar(32)           | NO   |     |                     |                |
| xmpp                      | varchar(255)          | NO   |     |                     |                |
| attag                     | varchar(255)          | NO   |     |                     |                |
| avatar                    | varchar(255)          | NO   |     |                     |                |
| photo                     | varchar(255)          | YES  |     |                     |                |
| thumb                     | varchar(255)          | YES  |     |                     |                |
| micro                     | varchar(255)          | YES  |     |                     |                |
| site-pubkey               | text                  | YES  |     | NULL                |                |
| issued-id                 | varchar(255)          | NO   | MUL |                     |                |
| dfrn-id                   | varchar(255)          | NO   | MUL |                     |                |
| url                       | varchar(255)          | NO   |     |                     |                |
| nurl                      | varchar(255)          | NO   | MUL |                     |                |
| addr                      | varchar(255)          | NO   | MUL |                     |                |
| alias                     | varchar(255)          | NO   | MUL |                     |                |
| pubkey                    | text                  | YES  |     | NULL                |                |
| prvkey                    | text                  | YES  |     | NULL                |                |
| batch                     | varchar(255)          | NO   |     |                     |                |
| request                   | varchar(255)          | YES  |     | NULL                |                |
| notify                    | varchar(255)          | YES  |     | NULL                |                |
| poll                      | varchar(255)          | YES  |     | NULL                |                |
| confirm                   | varchar(255)          | YES  |     | NULL                |                |
| poco                      | varchar(255)          | YES  |     | NULL                |                |
| aes_allow                 | tinyint(1)            | NO   |     | 0                   |                |
| ret-aes                   | tinyint(1)            | NO   |     | 0                   |                |
| usehub                    | tinyint(1)            | NO   |     | 0                   |                |
| subhub                    | tinyint(1)            | NO   |     | 0                   |                |
| hub-verify                | varchar(255)          | NO   |     |                     |                |
| last-update               | datetime              | NO   |     | 0001-01-01 00:00:00 |                |
| success_update            | datetime              | NO   |     | 0001-01-01 00:00:00 |                |
| failure_update            | datetime              | NO   |     | 0001-01-01 00:00:00 |                |
| name-date                 | datetime              | NO   |     | 0001-01-01 00:00:00 |                |
| uri-date                  | datetime              | NO   |     | 0001-01-01 00:00:00 |                |
| avatar-date               | datetime              | NO   |     | 0001-01-01 00:00:00 |                |
| term-date                 | datetime              | NO   |     | 0001-01-01 00:00:00 |                |
| last-item                 | datetime              | NO   |     | 0001-01-01 00:00:00 |                |
| priority                  | tinyint(3) unsigned   | NO   |     | 0                   |                |
| blocked                   | tinyint(1)            | NO   | MUL | 1                   |                |
| readonly                  | tinyint(1)            | NO   |     | 0                   |                |
| writable                  | tinyint(1)            | NO   |     | 0                   |                |
| forum                     | tinyint(1)            | NO   |     | 0                   |                |
| prv                       | tinyint(1)            | NO   |     | 0                   |                |
| contact-type              | tinyint(4)            | NO   |     | 0                   |                |
| hidden                    | tinyint(1)            | NO   |     | 0                   |                |
| archive                   | tinyint(1)            | NO   |     | 0                   |                |
| pending                   | tinyint(1)            | NO   | MUL | 1                   |                |
| deleted                   | tinyint(1)            | NO   |     | 0                   |                |
| rating                    | tinyint(4)            | NO   |     | 0                   |                |
| reason                    | text                  | YES  |     | NULL                |                |
| closeness                 | tinyint(3) unsigned   | NO   |     | 99                  |                |
| info                      | mediumtext            | YES  |     | NULL                |                |
| profile-id                | int(10) unsigned      | YES  |     | NULL                |                |
| bdyear                    | varchar(4)            | NO   |     |                     |                |
| bd                        | date                  | NO   |     | 0001-01-01          |                |
| notify_new_posts          | tinyint(1)            | NO   |     | 0                   |                |
| fetch_further_information | tinyint(3) unsigned   | NO   |     | 0                   |                |
| ffi_keyword_blacklist     | text                  | YES  |     | NULL                |                |
| updated                   | datetime              | YES  |     | 0001-01-01 00:00:00 |                |
| protocol                  | char(4)               | NO   |     |                     |                |
| block_reason              | text                  | YES  |     | NULL                |                |
| unsearchable              | tinyint(1)            | NO   |     | 0                   |                |
| sensitive                 | tinyint(1)            | NO   |     | 0                   |                |
| baseurl                   | varchar(255)          | YES  |     |                     |                |
| subscribe                 | varchar(255)          | YES  |     | NULL                |                |
| gsid                      | int(10) unsigned      | YES  | MUL | NULL                |                |
| ffi_keyword_denylist      | text                  | YES  |     | NULL                |                |
+---------------------------+-----------------------+------+-----+---------------------+----------------+
78 rows in set (0.003 sec)
```

**Comment by valvin1** [comment]
just see that `ffi_keyword_blacklist` is still there. as you mention it should be removed ?

**Comment by MrPetovan** [comment]
It should be named `ffi_keyword_blocklist` now.

**Comment by valvin1** [comment]
@MrPetovan both columns are present in the table. I've played again from UI DB upgrade but nothing changes and same using command line.

**Comment by MrPetovan** [comment]
Ha, I didn't see it down there.

**Comment by AlfredSK** [comment]
When I look at the structure of my contact table there is only a `ffi_keyword_denylist` but no `ffi_keyword_blacklist`. This is how it should be. 
So, looks like the renaming of that field wasn't successful in you database. I don't remember if that change was part of a dbstructure update or part of a postupdate.

You can try to force the dbstructure update with `-f` parameter: `php bin/console.php dbstructure update -f`
And you can check if all postupdates were done: `php bin/console.php postupdate`

**Comment by valvin1** [comment]
i've upgraded in 2020.07 and get same issue as expected.

dbstructure was well up to date but postupdate wasn't. I was not aware of this step. I should check how it is done in docker installation.

It looks like postupdate is long process. I let you know the result.

**Comment by valvin1** [comment]
how postupdate should be triggered ? Is it a manual operation we should do each time ?
i'm using docker installation and i don't see this step anywhere. It runs `dbstructure update` but not `postupdate`

ping @nupplaphil :)

**Comment by MrPetovan** [comment]
It should be ran automatically, maybe it failed for some reason.

**Comment by AlfredSK** [comment]
Normally, the dbstructure update and postupdate is triggered automatically by the worker (cron). You only need to run them manually if something gets stuck. Both can run for a very long time. Especially the postupdate process(es) may run for several days.

Disclaimer: I know nothing about our Docker container.

**Comment by valvin1** [comment]
hmmm what happens if the process is stopped while running ? i've run the postupdate command in a ssh session without tmux or screen ... don't know if it'll survive when i'll disconnect.
Why it is so long process ? It looks like it is not very resource intensive if i refer to the status of app and db server.

Would it be possible to have similar warning has new version available in admin panel for dbstructure or postupdate ?

**Comment by nupplaphil** [comment]
If you pull and start the latest stable, the last step after a new start is an automatic update:
https://github.com/friendica/docker/blob/2e38177e2e53641655d78f7bbdedf134c5645198/2020.07/apache/entrypoint.sh#L143
(Its the same call for every other image)

So you should find a "upgrade finished" log entry in your normal docker log.

It's also possible to kick it manually after the start:
 ```
docker exec --user www-data %FRIENDICACONTAINER% php bin/console.php dbstructure upgrade
```

**Comment by valvin1** [comment]
@nupplaphil yes I had a look to the entrypoint and see `bin/console dbstructure update` was done automatically. It was well the case on my side. Issue was `bin/console postupdate` wasn't complete. So I had to triggers it manually. Btw this action should be triggered automatically so maybe something wrong stops the process.

It ran during night and now it is complete it looks like i'm still having issue. 

```
Fatal error: Uncaught TypeError: Argument 3 passed to Friendica\Content\PageInfo::getTagsFromUrl() must be of the type string, null given, called in /var/www/html/include/items.php on line 46 and defined in /var/www/html/src/Content/PageInfo.php:204
Stack trace:
#0 /var/www/html/include/items.php(46): Friendica\Content\PageInfo::getTagsFromUrl('https://blog.va...', '', NULL)
#1 /var/www/html/src/Protocol/Feed.php(536): get_page_keywords('https://blog.va...', '', true, NULL)
#2 /var/www/html/src/Protocol/Feed.php(85): Friendica\Protocol\Feed::import('<?xml version="...', Array, Array)
#3 /var/www/html/include/items.php(73): Friendica\Protocol\Feed::consume('<?xml version="...', Array, Array, NULL)
#4 /var/www/html/src/Worker/OnePoll.php(176): consume_feed('<?xml version="...', Array, Array, NULL)
#5 [internal function]: Friendica\Worker\OnePoll::execute(101993)
#6 /var/www/html/src/Core/Worker.php(409): call_user_func_array('Friendica\\Worke...', Array)
#7 /var/www/html/src/Core/Worker.php(310): Friendica\Core\Worker::exec in /var/www/html/src/Content/PageInfo.php on line 204
```
Now in the queue I have around 7k messages :( but if i refer to date the more recent is from July the 12th.

In database I'm still having both columns. Should I do manual actions ?

**Comment by annando** [comment]
Do you have both `ffi_keyword_blacklist` and `ffi_keyword_denylist` in your contact table? You only should have `ffi_keyword_denylist`. If you have only `ffi_keyword_blacklist` then please try to rename this column manually.

**Comment by valvin1** [comment]
@annando yes I still have both. it looks like dbstructure has not renamed column but only add new one.

So should I delete ffi_keyword_blacklist or should i update ffi_keyword_denylist with value present in ffi_keyword_blacklist and then delete blacklist column ?

**Comment by annando** [comment]
The easiest would be to copy the content and then remove the old field.

**Comment by valvin1** [comment]
both columns was null for all contacts so I dropped columns. unfortunately it doesn't change the result.

by identifying the url the message appears from RSS feed of my blog.

I'm wondering so if the issue of my message queue is only related to this error message or maybe this error blocks the process.

If I browse worker_queue table I see recent messages are `UpdateContact` messages and older `UpdateGServer` : 

```sql
select created,parameter from workerqueue where done = 0 and retrial = 0 order by created ;
```
```
| 2020-07-13 00:56:08 | ["UpdateGServer","https:\/\/pleroma.hidao.work",true]                                                                                                                                                |
| 2020-07-13 00:56:08 | ["UpdateGServer","https:\/\/mastodon.mxhdr.net",true]                                                                                                                                                |
| 2020-07-13 00:56:08 | ["UpdateGServer","https:\/\/social.glvr.io",true]                                                                                                                                                    |
| 2020-07-13 00:56:08 | ["UpdateGServer","https:\/\/words.ppl.town",true]                                                                                                                                                    |
| 2020-07-13 00:56:08 | ["UpdateGServer","https:\/\/testchamber.one",true]                                                                                                                                                   |
| 2020-07-13 00:56:08 | ["UpdateGServer","https:\/\/dravidam.net",true]                                                                                                                                                      |
| 2020-07-13 00:56:08 | ["UpdateGServer","https:\/\/note.lono.space",true]                                                                                                                                                   |
| 2020-07-13 00:56:08 | ["UpdateGServer","https:\/\/social.meawchill.xyz",true]                                                                                                                                              |
| 2020-07-13 00:56:08 | ["UpdateGServer","https:\/\/soc.vidyagam.es",true]
|
...

| 2020-07-16 09:59:31 | ["UpdateContact",38916,"force"]                                                                                                                                                                      |
| 2020-07-16 10:06:25 | ["UpdateContact",46745,"force"]                                                                                                                                                                      |
| 2020-07-16 10:23:06 | ["UpdateContact",690,"force"]                                                                                                                                                                        |
| 2020-07-16 10:23:36 | ["UpdateContact",541,""]                                                                                                                                                                             |
| 2020-07-16 10:25:25 | ["UpdateContact",22598,"force"]                                                                                                                                                                      |
| 2020-07-16 10:25:25 | ["UpdateContact",6258,"force"]                                                                                                                                                                       |
| 2020-07-16 10:45:33 | ["UpdateContact",7931,"force"]                                                                                                                                                                       |
| 2020-07-16 10:46:10 | ["UpdateContact",117805,"force"]                                                                                                                                                                     |
```

I'll try to remove my RSS contacts to check if it is better.

**Comment by valvin1** [comment]
deleting my RSS contact removes the error in worker.

After enabling log I see this error : 

```
2020-07-16T11:32:42Z worker [ALERT]: Driver 'redis' failed - Fallback to 'useAutoDriver()' {"exception":{}} - {"file":"LockFactory.php","line":103,"function":"create","uid":"793c8f","process_id":9}
```

I'm using redis as `lock_driver` don't if there was some change on this part ?

I'll clean my redis to be sure there is not a bad message in it.

**Comment by annando** [comment]
Don't mess with the data. In the current "develop" branch we already are having some coding that will help - and furtner stuff is on the way. So once that the currently open PRs are merged, I suggest to update the system.

**Comment by valvin1** [comment]
Redis lock driver was the reason of my issue. I think it has outdated message about postupdate or something similar. Queue was almost blocked because of that because after recreating containers messages starts dequeueing.
Does lock driver use lifetime message feature ?

**Comment by MrPetovan** [comment]
What is the lifetime message feature?

**Comment by valvin1** [comment]
in redis you can create a record with a limited time : 
https://redis.io/commands/expire
Don't know exactly what kind of message are present in redis lock driver so maybe it is not relevant. 
But if it manages lock to prevent so concurrent actions it could be interesting to but an expiration to 24h for example in order it solves by itself.

**Comment by MrPetovan** [comment]
That's a good suggestion.
