### ISSUE TITLE
I upgraded MariaDB to 10.5.4 and now some links re broken...

### ISSUE THREAD

**Issue by WNYmathGuy** [friendica/friendica#8949]
### Expected behavior
Click on a profile link and see the profile.

### Actual behavior
Click on a profile and get the blue rabbit page.
![Screenshot from 2020-07-30 16-29-38](https://user-images.githubusercontent.com/28640985/88971967-d63b1880-d282-11ea-83f1-411a2c7c2470.png)

### Steps to reproduce the problem
1. Have a nicely updated system working with the Friendica 2020.07 version.
1. Upgrade your MariaDB database from 10.1.44 to 10.2 & 10.3 & 10.4 & 10.5.4 immediately without testing anything till you are at 10.5. 

### Etcetera
This is the first problem I noticed, I assume there could be more oddities, but I also assume the solution to this one will probably solve all of them.

### Friendica version you encountered the problem
Version 2020.07 that is running at the web location https://social.outsourcedmath.com. The database version is 1355, the post update version is 1350.

### Friendica source (git, zip)
git

### PHP version
Using the Apache mod for 7.0.33, but also the same results on an instance using version 7.3.20 in FPM mode.

### SQL version
MariaDB 10.5.4

**Comment by MrPetovan** [comment]
Sorry about that, can you please first make sure there is a record with `nickname = "wnymathguy"` in your `user` table?

**Comment by WNYmathGuy** [comment]
> Sorry about that, can you please first make sure there is a record with `nickname = "wnymathguy"` in your `user` table?

Yes, I do have that record. 

I just started a new job and have family from out of town visiting, so I won't be too quick to respond. :wink:

**Comment by MrPetovan** [comment]
Next step is checking both your PHP log and your Friendica log for obvious SQL errors. If the latter isn't activated, please go to your admin panel to do so.

**Comment by WNYmathGuy** [comment]
With the Firendica logs set to **Error** I logged in as a normal user and tried to open that profile page.

<details>
  <summary>This is from the Friendica Logs viewer</summary>
  <details-dialog>

[FriendicaLog.txt](https://github.com/friendica/friendica/files/5022871/FriendicaLog.txt)


  </details-dialog>
</details>



<details>
  <summary>This is from the Apache Logs viewer</summary>
  <details-dialog>

```
[Tue Aug 04 10:38:25.689004 2020] [php7:warn] [pid 17858] [client 46.229.168.145:17208] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/outmathadmin/domains/social.outsourcedmath.com/public_html/src/Module/Profile/Contacts.php on line 66
```

  </details-dialog>
</details>

I hope that helps. Seems like a lot of logging to pick through so I only snipped from the time of login to a couple of minutes after the profile open attempt.

**Comment by WNYmathGuy** [comment]
I just poked around again today and found out that I cannot open the Users page successfully as the Admin. 


![Screenshot from 2020-08-19 18-31-44](https://user-images.githubusercontent.com/28640985/90696446-43bae300-e24a-11ea-9921-f088a829892b.png)

[admin-logs-view.txt](https://github.com/friendica/friendica/files/5099664/admin-logs-view.txt)

**Comment by WNYmathGuy** [comment]
All other Admin pages load normally, just the Users fails.

**Comment by WNYmathGuy** [comment]
Admin can't open their own profile page,
```
#0 [internal function]: Friendica\Module\Profile\Profile::content(Array)
#1 /home/jarhead/domains/nsfw.wnymathguy.com/public_html/src/App/Page.php(332): call_user_func(Array, Array)
#2 /home/jarhead/domains/nsfw.wnymathguy.com/public_html/src/App/Page.php(388): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#3 /home/jarhead/domains/nsfw.wnymathguy.com/public_html/src/App.php(576): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Core\Config\JitConfig), Object(Friendica\Core\PConfig\JitPConfig))
#4 /home/jarhead/domains/nsfw.wnymathguy.com/public_html/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#5 {main}
```

I know this is a low priority issue, but I figured logging the errors inches it closer to a solution, which prepares for the future.

**Comment by MrPetovan** [comment]
I finally got around to look at your log, and you're having the same issue I had in #8550 with many `Prepared statement needs to be re-prepared` errors related to views. Since users are now queried via views, it explains why none of the pages related to users are accessible.

The solution is to increase the MariaDB server config value `table_definition_cache` to at least `4096`.

**Comment by WNYmathGuy** [comment]
I hope to get on that #8550 tonight, but I just got an email from a new person making an account and apparently they cannot sign in, so that's another side effect.

**Comment by MrPetovan** [comment]
Yes, you should increase that server config value as soon as possible, don't forget to restart the database server once you do.

**Comment by WNYmathGuy** [comment]
For me the `/etc/mysql/my.cnf` is a symbolic link that points to `/etc/mysql/mariadb.cnf` and that doesn't have much in it. And yes you're right they are linked.
```
# The MariaDB configuration file
#
# The MariaDB/MySQL tools read configuration files in the following order:
# 0. "/etc/mysql/my.cnf" symlinks to this file, reason why all the rest is read.
# 1. "/etc/mysql/mariadb.cnf" (this file) to set global defaults,
# 2. "/etc/mysql/conf.d/*.cnf" to set global options.
# 3. "/etc/mysql/mariadb.conf.d/*.cnf" to set MariaDB-only options.
# 4. "~/.my.cnf" to set user-specific options.
#
# If the same option is defined multiple times, the last one will apply.
#
# One can use all long options that the program supports.
# Run program with --help to get a list of available options and with
# --print-defaults to see which it would actually understand and use.
#
# If you are new to MariaDB, check out https://mariadb.com/kb/en/basic-mariadb-articles/

#
# This group is read both by the client and the server
# use it for options that affect everything
#
[client-server]
# Port or socket location where to connect
# port = 3306
socket = /run/mysqld/mysqld.sock

# Import all .cnf files from configuration directory
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/
```

**Comment by annando** [comment]
@WNYmathGuy the current develop branch now has got a new option that might help as well, see PR https://github.com/friendica/friendica/pull/9599
