### ISSUE TITLE
Under the Find People option, Random Profile explodes

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#9080]
### Expected behavior
Expected it to show me some random persons profile.
### Actual behavior
Bad request

Bad Request.

#0 /misc/www/friendica/src/LegacyModule.php(90): redir_init()
#1 /misc/www/friendica/src/LegacyModule.php(59): Friendica\LegacyModule::runModuleFunction()
#2 [internal function]: Friendica\LegacyModule::init()
#3 /misc/www/friendica/src/App/Module.php(271): call_user_func()
#4 /misc/www/friendica/src/App.php(555): Friendica\App\Module->run()
#5 /misc/www/friendica/index.php(42): Friendica\App->runFrontend()
#6 {main}### Steps to reproduce the problem

### Friendica version you encountered the problem
see `example.com/friendica` on your Friendica node for the version information.
This is Friendica, version 2020.09-dev that is running at the web location https://friendica.eskimo.com. The database version is 1364, the post update version is 1341.
### PHP version
PHP 7.4.9 (cli) (built: Aug  7 2020 14:30:01) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

### SQL version
mysql --version
mysql  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by annando** [comment]
Have you had a look if that error possibly ocured not on your system but the remote on? This command just redirects you to some random remote Friendica profile.

**Comment by 4nanook** [comment]
I can't seem to reproduce it so probably that's what it was.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.
