### ISSUE TITLE
Clicking "Home" leads to "User not found" message

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#9395]
My profile https://f.haeder.net/profile/roland should be there as I'm registered there on my own instance for a very long time. Since the latest update, I got that message:

````
User not found.

#0 /var/www/.../src/Module/Profile/Index.php(44): Friendica\Module\Profile\Status::content(Array)
#1 [internal function]: Friendica\Module\Profile\Index::content(Array)
#2 /var/www/.../src/App/Page.php(331): call_user_func(Array, Array)
#3 /var/www/.../src/App/Page.php(387): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#4 /var/www/.../src/App.php(560): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Core\Config\PreloadConfig), Object(Friendica\Core\PConfig\PreloadPConfig))
#5 /var/www/.../index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\PreloadPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page))
#6 {main}
````

**Comment by MrPetovan** [comment]
The new database views aren't set up properly on your system, please the the command-line command to update your DB, if it still persists, add the `-v` flag to display eventual errors during the views creation.

**Comment by Quix0r** [comment]
I have already run `dbstructure update` and now I let run `postupdate`.

**Comment by annando** [comment]
Please also have a look into your Friendica log for entries with "DB Error" in it.

**Comment by Quix0r** [comment]
Nothing that could help. just "API login - failed" and `"REQUEST_URI":"\/api\/account\/verify_credentials.json?skip_status=true"`

**Comment by Quix0r** [comment]
````
SELECT *, `cat` AS `k` FROM `pconfig` WHERE `uid`=1 AND `cat`='xmpp';
````
gives me a password which is very different to the actual one. Can I somehow decode it?

**Comment by Quix0r** [comment]
Yes! Setting `v` to the same clear-text password, let me login again.

**Comment by Quix0r** [comment]
The `postupdate` hook did the fix. I had some issues during upgrading which lead to that `postupdate` has not been executed.

**Comment by mikauskas** [comment]
The same problem with a new install on shared hosting v 2021.01.
There were difficulties with installing. Had to manually enable many PHP extensions. Perhaps some more required?

![Screenshot_2021-02-08 cPanel -](https://user-images.githubusercontent.com/76782677/107211723-df5d2d00-69fd-11eb-91a8-0f77542d48a4.png)

 No errors with 

`php bin/console.php dbstructure update`

or

`php bin/console.php postupdate`

Here is debug info after pressing the home tab

`2021-02-08T10:53:12Z index [ERROR]: DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"DBA::selectFirst, User::getOwnerDataById, Profile::load, Status::content, Index::content, call_user_func, Page::initContent, Page::run","params":"SELECT * FROM `owner-view` WHERE (`uid` = 3) LIMIT 1"} - {"file":"Database.php","line":662,"function":"p","uid":"3bdced","process_id":144751}
2021-02-08T10:53:12Z index [INFO]: profile error: profile/testeris [] - {"file":"Profile.php","line":172,"function":"load","uid":"3bdced","process_id":144751}
2021-02-08T10:53:12Z index [DEBUG]: Contact found {"url":"https:\/\/friendica.online\/profile\/testeris","uid":0,"update":null,"cid":6} - {"file":"Contact.php","line":1061,"function":"getIdForURL","uid":"3bdced","process_id":144751}
2021-02-08T10:53:12Z index [INFO]: Collecting suggestions {"uid":3,"cid":6,"start":0,"limit":9} - {"file":"Relation.php","line":260,"function":"getSuggestions","uid":"3bdced","process_id":144751}
2021-02-08T10:53:12Z index [INFO]: Contacts of contacts who are followed by the given user {"uid":3,"cid":6,"count":0} - {"file":"Relation.php","line":283,"function":"getSuggestions","uid":"3bdced","process_id":144751}
2021-02-08T10:53:12Z index [INFO]: Contacts of contacts who are following the given user {"uid":3,"cid":6,"count":0} - {"file":"Relation.php","line":307,"function":"getSuggestions","uid":"3bdced","process_id":144751}
2021-02-08T10:53:12Z index [INFO]: Followers that are not followed by the given user {"uid":3,"cid":6,"count":0} - {"file":"Relation.php","line":327,"function":"getSuggestions","uid":"3bdced","process_id":144751}
2021-02-08T10:53:12Z index [INFO]: Any contact {"uid":3,"cid":6,"count":4} - {"file":"Relation.php","line":347,"function":"getSuggestions","uid":"3bdced","process_id":144751}
2021-02-08T10:53:12Z index [ERROR]: DB Error {"code":1615,"error":"Prepared statement needs to be re-prepared","callstack":"DBA::selectToArray, vier_community_info, vier_init, Page::run, App::runFrontend","params":"SELECT * FROM `owner-view` WHERE (`blocked` = 0 AND `publish` = 1) ORDER BY `register_date` DESC LIMIT 0, 9"} - {"file":"Database.php","line":662,"function":"p","uid":"3bdced","process_id":144751}`

**Comment by annando** [comment]
@mikauskas Enable `'pdo_emulate_prepares' => false,` in the `database` section of your `local.config.php` file.

**Comment by mikauskas** [comment]
> @mikauskas Enable `'pdo_emulate_prepares' => false,` in the `database` section of your `local.config.php` file.

There are two instances on the same shared hosting server, but different accounts, one working another not, so I did following:

1. Enabled other PHP extensions on the new install to match the older one.
![Screenshot_2021-02-08 cPanel -(3)](https://user-images.githubusercontent.com/76782677/107241986-6a9ce980-6a23-11eb-98d8-d79e55c6bdcd.png)
2. Enabled pdo_emulate_prepares, but true, not false `'pdo_emulate_prepares' => true,`
3. `php bin/console.php dbstructure update`
4. `php bin/console.php postupdate`
5. `/usr/local/bin/php bin/worker.php`

And it is working now. Thanks for your help.

**Comment by annando** [comment]
@mikauskas the error message `"Prepared statement needs to be re-prepared"` can be solved by either changing the database server configuration or by setting this `pdo_emulate_prepares` value. it may not happen all the time, especially on systems where many different applications and customers are using the same database, tjhis can also be time depending.

The PHP extensions have nothing to do with this issue - except possibly not enabling PDO, but the mysql class.

**Comment by mikauskas** [comment]
> @mikauskas the error message `"Prepared statement needs to be re-prepared"` can be solved by either changing the database server configuration or by setting this `pdo_emulate_prepares` value. it may not happen all the time, especially on systems where many different applications and customers are using the same database, tjhis can also be time depending.
> 
> The PHP extensions have nothing to do with this issue - except possibly not enabling PDO, but the mysql class.

`pdo_emulate_prepares` didn't help until I enabled PHP extensions. Yes, PDO was one of them.
