### ISSUE TITLE
Friendica\Model\PermissionSet record uninitialized is back

### ISSUE THREAD

**Issue by Quix0r** [friendica/friendica#9516]
With some older posts (`/display/xxx` is called) this error comes back as already shown in #9491 :

````
#0 /var/www/src/BaseModel.php(119): Friendica\BaseModel->checkValid()
#1 [internal function]: Friendica\BaseModel->__get('id')
#2 /var/www/src/BaseCollection.php(91): array_column(Array, 'id', NULL)
#3 /var/www/src/Model/PermissionSet.php(76): Friendica\BaseCollection->column('id')
#4 /var/www/src/Model/Item.php(3457): Friendica\Model\PermissionSet::get(0, 2)
#5 /var/www/mod/display.php(300): Friendica\Model\Item::getPermissionsSQLByUserId(0)
#6 /var/www/src/LegacyModule.php(90): display_content(Object(Friendica\App))
#7 /var/www/src/LegacyModule.php(64): Friendica\LegacyModule::runModuleFunction('content', Array)
#8 [internal function]: Friendica\LegacyModule::content(Array)
#9 /var/www/src/App/Page.php(331): call_user_func(Array, Array)
#10 /var/www/src/App/Page.php(387): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#11 /var/www/src/App.php(559): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Core\Config\PreloadConfig), Object(Friendica\Core\PConfig\PreloadPConfig))
#12 /var/www/index.php(42): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\PreloadPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page))
#13 {main}
````
I have latest `develop` code + a fix in `src/Database/PostUpdate.php` due to missing array element `$max_item_delivery_data['iid']`.

**Comment by MrPetovan** [comment]
> ```
> #4 /var/www/src/Model/Item.php(3457): Friendica\Model\PermissionSet::get(0, 2)
> ```

There is no `PermissionSet::get` call on line 3457 of `src/Model/Item.php` in the current `develop` branch, are you sure you updated your files recently?

**Comment by Quix0r** [comment]
I cannot seem to reproduce it with latest code 490ce976c11a6b6353d74740edab3b934b0da59a is my code rebased on.
