### ISSUE TITLE
No processing of GIF by imagick

### ISSUE THREAD

**Issue by utzer** [friendica/friendica#9570]
### Is the feature request related to a problem? 
Gifs are processed by ImageMagick, this entails problems, first the processing uses resources like CPU and RAM. There is no need to process the gif, it is most of the times just a few MB in size, it just has to be fetched/uploaded and stored. 

### Describe the feature you'd like
Don't process Gifs at all. Fetch a remote gif and proxy it locally if needed and when uploaded to the gallery just bypass the image processing and store the gif, the most processing to be done should be if the file is a gif. 

### Describe alternatives you've considered

Implemt webm or similar video handling, these would need the same non processed handling. Upload and embed only, no need to handle them.

**Comment by MrPetovan** [comment]
A place we want to process GIF images is in profile pictures. We use several standard sizes depending on the context (profile page, contact list, post header, reshare information) and we currently generate separate copies for each size.

Apart for there, I don't think we are processing GIF images present in post body content?

**Comment by AlfredSK** [comment]
I think we must somehow do process and store animated gifs in several sizes **when uploading** an image. It is possible to reproduce the issue by uploading a normal size animated gif of say... 1000x1000 pixel, 5 MB.
PHP process is using imagick/ImageMagick to process the gif. The process produces a lot of load - pretty normal I guess. But ImageMagick is using tons of RAM (up to 15 GB) and remarkable amounts of temporary files in /tmp eating up disk space.

I'm not sure if we resize imported remote gifs as well.

**Comment by MrPetovan** [comment]
Ha, I forgot about uploading them. I only thought about receiving remote posts with GIF images linked in the body 😅

**Comment by utzer** [comment]
Incoming posts gifs don't work without imagick, I would guess we process them as well.

Also we could just not process the gifs in all this places and just load the same size gif in all cases, just show them scaled. That would just be bad for data transfer, which might not be a problem.

Also keep in mind this is also a solution to a bug that curently imagick does not work with Friendica, it will produce out of memory and out of storage situation regularly.

**Comment by SpcCw** [comment]
There is some heavy processing involved with remote gifs as well. I never upload gifs myself but it took some tweaking to get larger incoming ones displaying properly and when I view one there is a spike in resource usage. With smaller systems it can be felt. Run out of disk space due to imagick glitch a couple times as well.

I made an issue about it a while ago: https://github.com/friendica/friendica/issues/8524

It would be great if these GIFs were just proxified directly without this sort of processing which takes a lot of resource and sometimes breaks them. E.g. Diaspora has this approach - it just proxies, doesn't even cache anything.

**Comment by utzer** [comment]
> It would be great if these GIFs were just proxified directly without this sort of processing which takes a lot of resource and sometimes breaks them. E.g. Diaspora has this approach - it just proxies, doesn't even cache anything.

Yes, that would be great.

**Comment by Casuallynoted** [comment]
I'm not sure if this is related, but I'm finding that on my instance user profile pics that are gifs (say from Mastodon instances for instance) are broken and don't display the image. When following the image URL, I see this error:

Internal Server Error
Invalid photo with id 8.
```
#0 [internal function]: Friendica\Module\Photo::rawContent(Array)
#1 /Volumes/Docker/tmp/Friendica/src/App/Module.php(289): call_user_func(Array, Array)
#2 /Volumes/Docker/tmp/Friendica/src/App.php(557): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\StreamLogger), Object(Friendica\Util\Profiler), Array, Array)
#3 /Volumes/Docker/tmp/Friendica/index.php(44): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\Security\Authentication), Object(Friendica\App\Page), 1609527503.6452)
#4 {main}
```

**Comment by SpcCw** [comment]
@Casuallynoted - you can check that by downloading some of these problematic avatars and making some posts with them embedded (better to do it not on your server but make testing account somewhere else and add it to contacts). Then see if they show up correctly in your timeline when the test post arrives.

If they appear glitchy or not at all perhaps you will have to tune your imagemagic, check out the issue linked by me two comments above, it contains some sample configs.

I have had some problems with animated avatars myself.

**Comment by Casuallynoted** [comment]
So interestingly enough, it shows up as a video when I embed it into the test instance's post and check my Friendica timeline. What should I do if that's the case?

Edit: Looks like if I post the same photo to my Friendica instance it has the same issue. Odd.

**Comment by utzer** [comment]
What was your test instance, I think Mastodon converts to Webm or so, hence it will be a video and not a gif anymore?

**Comment by Casuallynoted** [comment]
> What was your test instance, I think Mastodon converts to Webm or so, hence it will be a video and not a gif anymore?

Oof it was via mastodon. I'll try posting using another instance!
