### ISSUE TITLE
web installer unable to create local.config.php

### ISSUE THREAD

**Issue by mikauskas** [friendica/friendica#9957]
Git Install on VPS, latest stable. Carefully followed each step [https://github.com/friendica/friendica/blob/develop/doc/Install.md](url) 
`a2enmod rewrite`
```
/etc/apache2/sites-available/domain1.com-le-ssl.conf
	  <Directory /var/www/domain1>
                Require all granted
                Options ALL
                AllowOverride ALL
        </Directory>
```

Using web installer everything green except. `The web installer needs to be able to create a file called "local.config.php" in the "config" folder of your web server but is unable to do so.... `

To work around 
```
sudo chown www-data: config
cd ..
chmod 777 mywebsite
```

Instaled without problems, then

```
chmod 755 mywebsite
sudo chown newusername: mywebsite/config
chmod o-r mywebsite/config/local.config.php
```

I don't think it supposed to be done this way. Why I had that error? What permissions for these directories and files must be at the end?

**Comment by AlfredSK** [comment]
The permissions you get when you clone the repo are correct.  Don't change them. But I guess the owner of the files and folders were wrong. For example when you clone as `root` everything is owned by `root`. But the files and folders must be readable and writable by the user the web server is running with (e.g. `www-data` on Ubuntu).

**Comment by mikauskas** [comment]
Previously I installed as root, but still had the same problem. This time made myself owner mywebsite directory to avoid using composer as root. In my understanding having all files and folders readable and writable by www-data a huge security risk. Especially having world readable `local.config.php` where my database user name and password are stored unencrypted.

**Comment by MrPetovan** [comment]
`www-data` likely is the user your web server is running as, so it absolutely needs to be able to read all the files in the Friendica directory. It also need write access in several specific places, like `config/` during install, `view/smarty/cache` and `proxy/`.

**Comment by mikauskas** [comment]
As I remember I granted `www-data` ownership of `config/ ` and 770 permissions, but nothing helped until I gave 777  to the parent directory.
Does `local.config.php` really need world read permission?
What about this error
 ```
 PHP Warning:  Directory /var/www/quality/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 in /var/www/quality/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297,
 ```

**Comment by AlfredSK** [comment]
Again, `if` your system user who is running the web server is `www-data` change the owner of ALL files and folders to that user. And leave the permissions (rwx) on default.

For example when /var/www/html is your document root of Friendica:

`chown -R www-data:www-data /var/www/html`

**Comment by MrPetovan** [comment]
Giving 777 is the nuclear option, it will work but it doesn't mean it needs that much to work. Depending on which user owned `/var/www/quality`, it could have prevented `www-data` from traversing the folder to write in `config/`.

`config/local.config.php` doesn't need world read permission.

**Comment by mikauskas** [comment]
Yes, 777 is really nuclear. Perhaps `chown www-data: /var/www/quality` would be enough? Will try next time.
Apparently `config/local.config.php` need worlds read permission, otherwise you will get problem like that:
```
cd /var/www/quality/ ; /usr/bin/php bin/worker.php
PHP Warning:  include(/var/www/quality/config/local.config.php): failed to open stream: Permission denied in /var/www/quality/src/Util/ConfigFileLoader.php on line 370
PHP Warning:  include(): Failed opening '/var/www/quality/config/local.config.php' for inclusion (include_path='.:/usr/share/php') in /var/www/quality/src/Util/ConfigFileLoader.php on line 370
PHP Fatal error:  Uncaught Exception: Error loading config file /var/www/quality/config/local.config.php in /var/www/quality/src/Util/ConfigFileLoader.php:373
Stack trace:
#0 /var/www/quality/src/Util/ConfigFileLoader.php(168): Friendica\Util\ConfigFileLoader->loadConfigFile()
#1 /var/www/quality/src/Util/ConfigFileLoader.php(116): Friendica\Util\ConfigFileLoader->loadCoreConfig()
#2 /var/www/quality/src/Factory/ConfigFactory.php(43): Friendica\Util\ConfigFileLoader->setupCache()
#3 /var/www/quality/vendor/level-2/dice/Dice.php(150): Friendica\Factory\ConfigFactory->createCache()
#4 /var/www/quality/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#5 /var/www/quality/vendor/level-2/dice/Dice.php(240): Dice\Dice->create()
#6 /var/www/quality/vendor/level-2/dice/Dice.php(132): Dice\Dice->Dice\{closure}()
#7 /var/www/quality/vendor/level-2/dice/Dice.php(96): Dice\Dice->Dice\{closure}()
#8 /var/www/quality/vendor/level-2/dice/Dice.php(240): Dice\Dice->create()
#9 /var/www/quality/vendor/level-2/dice/Dice.php(132): Dic in /var/www/quality/src/Util/ConfigFileLoader.php on line 373
```
Another storm is coming  :-1:

**Comment by MrPetovan** [comment]
What user is your cronjob running as? It should be `www-data` as well.

**Comment by mikauskas** [comment]
yes, it was me, should be OK when gets started by cron.

**Comment by MrPetovan** [comment]
I'm not sure what you mean by "should be OK".

**Comment by mikauskas** [comment]
`view/smarty/cache` and `proxy/` do not exist at all :(

**Comment by MrPetovan** [comment]
What about `view/smarty3/cache` ?

**Comment by mikauskas** [comment]
Previously you wrote ` It also need write access in several specific places, like config/ during install, view/smarty/cache and proxy/.`

What to do with error:
```
PHP Warning:  Directory /var/www/quality/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer not writable, please chmod to 777 in /var/www/quality/vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer.php on line 297,
```
I did `sudo chown www-data: -R vendor` instead 777 should be OK?

**Comment by MrPetovan** [comment]
Yes it should.
